### ISSUE TITLE
[BUG] [javascript] Unable to generate javascript code with error - Could not generate model

### ISSUE THREAD

**Issue by puneetugru** [OpenAPITools/openapi-generator#10006]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue? Yes
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))? Yes
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs? Yes
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

While trying to generate javascript code for the openapi specification, error is seen and code generation is not done.

##### openapi-generator version

5.2.0

##### OpenAPI declaration file content or url

https://gist.github.com/puneetugru/a58091831597a84beaa7b7019c374267

##### Generation Details

Below output was seen while trying for generation,

``` terminal
openapi-generator generate -i testMinimumMaximum.json -g javascript 
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - No .openapi-generator-ignore file found.
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: javascript (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'javascript' is considered stable.
[main] INFO  o.o.c.l.JavascriptClientCodegen - Using JS ES6 templates
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'inline_response_200'
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:544)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:875)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.RuntimeException: Target files must be generated within the output directory; absoluteTarget=/Users/puneet/OAS_Minimum_Maximum/JavaScript_Client/src/model/InlineResponse200.js outDir=/Users/puneet/OAS_Minimum_Maximum/JavaScript_Client/.
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1015)
        at org.openapitools.codegen.DefaultGenerator.generateModel(DefaultGenerator.java:382)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:535)
        ... 4 more
```

##### Steps to reproduce

Run the command - **openapi-generator generate -i testMinimumMaximum.json -g javascript**

##### Related issues/PRs

None

##### Suggest a fix

None

**Comment by code1x1** [comment]
did you try the latest release 5.3.0

it just works for me

```bash
openapi-generator-cli generate -g javascript -i ../spec/testMinimumMaximum.json -o ../spec/testMinimumMaximum
```

```bash
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - No .openapi-generator-ignore file found.
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: javascript (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'javascript' is considered stable.
[main] INFO  o.o.c.l.JavascriptClientCodegen - Using JS ES6 templates
[main] INFO  o.o.c.l.JavascriptClientCodegen - Environment variable JS_POST_PROCESS_FILE not defined so the JS code may not be properly formatted. To define it, try 'export JS_POST_PROCESS_FILE="/usr/local/bin/js-beautify -r -f"' (Linux/Mac)
[main] INFO  o.o.c.l.JavascriptClientCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/src/model/InlineResponse200.js
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/test/model/InlineResponse200.spec.js
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/docs/InlineResponse200.md
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/src/model/Values.js
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/test/model/Values.spec.js
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/docs/Values.md
[main] WARN  o.o.codegen.DefaultCodegen - Empty operationId found for path: get /testMinMax. Renamed to auto-generated operationId: testMinMaxGet
[main] WARN  o.o.codegen.DefaultCodegen - Empty operationId found for path: post /testMinMax/{value}. Renamed to auto-generated operationId: testMinMaxValuePost
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/src/api/DefaultApi.js
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/test/api/DefaultApi.spec.js
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/docs/DefaultApi.md
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/package.json
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/git_push.sh
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/README.md
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/mocha.opts
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/.travis.yml
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/.babelrc
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/.gitignore
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/src/index.js
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/src/ApiClient.js
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/.openapi-generator-ignore
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/.openapi-generator/VERSION
[main] INFO  o.o.codegen.TemplateManager - writing file /home/xxxx/Development/git/java/eclipse-workspace/spec/testMinimumMaximum/.openapi-generator/FILES
################################################################################
# Thanks for using OpenAPI Generator.                                          #
# Please consider donation to help us maintain this project 🙏                 #
# https://opencollective.com/openapi_generator/donate                          #
################################################################################
```

```bash
java/eclipse-workspace/spec 
➜ ls testMinimumMaximum     
docs  git_push.sh  mocha.opts  package.json  README.md  src  test

java/eclipse-workspace/spec 
➜ ls                   
api.yaml  testMinimumMaximum  testMinimumMaximum.json

java/eclipse-workspace/spec 
➜ 
```

**Comment by code1x1** [comment]
did you see this exception message
`Caused by: java.lang.RuntimeException: Target files must be generated within the output directory; absoluteTarget=/Users/puneet/OAS_Minimum_Maximum/JavaScript_Client/src/model/InlineResponse200.js outDir=/Users/puneet/OAS_Minimum_Maximum/JavaScript_Client/.
`

**Comment by puneetugru** [comment]
> openapi-generator generate -i testMinimumMaximum.json -g javascript

Apologies for the delay in response.

Yes, I'm seeing the above exception message.

``` console

openapi-generator version
5.4.0

openapi-generator generate -i testMinimumMaximum.json -g javascript
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - Legacy support: '.swagger-codegen-ignore' file renamed to '.openapi-generator-ignore'.
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: javascript (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'javascript' is considered stable.
[main] INFO  o.o.c.l.JavascriptClientCodegen - Using JS ES6 templates
[main] INFO  o.o.c.l.JavascriptClientCodegen - Environment variable JS_POST_PROCESS_FILE not defined so the JS code may not be properly formatted. To define it, try 'export JS_POST_PROCESS_FILE="/usr/local/bin/js-beautify -r -f"' (Linux/Mac)
[main] INFO  o.o.c.l.JavascriptClientCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'inline_response_200'
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:532)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:888)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.RuntimeException: Target files must be generated within the output directory; absoluteTarget=/Users/puneet/Clones/HvacR/Controller/test/OAS_RAML_Files/OAS_Minimum_Maximum/JavaScript_Client/src/model/InlineResponse200.js outDir=/Users/puneet/Clones/HvacR/Controller/test/OAS_RAML_Files/OAS_Minimum_Maximum/JavaScript_Client/.
	at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1032)
	at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1021)
	at org.openapitools.codegen.DefaultGenerator.generateModel(DefaultGenerator.java:388)
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:523)
	... 4 more
```

**Comment by pamikola** [comment]
I have the same issue, using version 6.2.1 of generator via npx.

> did you see the exception message `Caused by: java.lang.RuntimeException: Target files must be generated within the output directory; absoluteTarget=/Users/puneet/OAS_Minimum_Maximum/JavaScript_Client/src/model/InlineResponse200.js outDir=/Users/puneet/OAS_Minimum_Maximum/JavaScript_Client/. `

Maybe I'm missing something, but the message is not helpful because the `absoluteTarget` file in the error message is in fact within the `outDir` already, so it's not clear what exactly the problem is.

Anybody figured this one out yet?

**Comment by pamikola** [comment]
OK, the problem appears to be the `.` at the end of the `outDir` which makes [this condition](https://github.com/OpenAPITools/openapi-generator/blob/1f7824c0830f7caf68ba8b1ed91f2fdf5096a878/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java#L1055) fail and causes this error.

One possible workaround is to explicitly specify the output directory (and make it something other than ".") via `-o` or `--output` CLI options or via `outputDir` in the generator configuration file.
