### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by maliky** [OpenAPITools/openapi-generator#10282]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Why do I have the error
`ModuleNotFoundError: No module named 'openapi_server.models.one_ofintegernumber'`

when running the python-flask generated stub ?
I was expecting it to lauch a http server like it does for the petstore exemple.

##### openapi-generator version

I'm using the version 5.3.0-SNAPSHOT (after trying with latest stable)

##### OpenAPI declaration file content or url

I use the yaml from https://docs.kraken.com/rest/ that I validated with https://apidevtools.org/swagger-parser/online/

https://gist.github.com/maliky/03de5e2a1664ec8df5a665c517d0d151

##### Generation Details
Here are the command I run

```
java -jar openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g python-flask -i swagger-kraken-validated.json -o Og-latest-kraken -p legacyDiscriminatorBehavior=false 
```

then in a virtual env with the requirements installed I run
```
cd Og-latest_kraken
python -m openapi_server
```

```
Traceback (most recent call last):
  File "/home/mlk/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mlk/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mlk/Prog/Python/Crypto/API/Swagger-OpenAPI/Og-latest-kraken/openapi_server/__main__.py", line 5, in <module>
    from openapi_server import encoder
  File "/home/mlk/Prog/Python/Crypto/API/Swagger-OpenAPI/Og-latest-kraken/openapi_server/encoder.py", line 4, in <module>
    from openapi_server.models.base_model_ import Model
  File "/home/mlk/Prog/Python/Crypto/API/Swagger-OpenAPI/Og-latest-kraken/openapi_server/models/__init__.py", line 8, in <module>
    from openapi_server.models.asset_pair import AssetPair
  File "/home/mlk/Prog/Python/Crypto/API/Swagger-OpenAPI/Og-latest-kraken/openapi_server/models/asset_pair.py", line 9, in <module>
    from openapi_server.models.one_ofintegernumber import OneOfintegernumber
ModuleNotFoundError: No module named 'openapi_server.models.one_ofintegernumber'
```

##### Steps to reproduce
Try to generate server python-flask stub from the given json file.

##### Related issues/PRs

Did not find any
##### Suggest a fix
Looks like some typing hint not working as expected ?

**Comment by wing328** [comment]
> ModuleNotFoundError: No module named 'openapi_server.models.one_ofintegernumber'

I don't think python-flask generates support oneOf models at the moment. We welcome contributions on that.

You can also try the `python` client generator to see if you like the oneOf implementation and potentially plot it to the python-flask generator.

**Comment by maliky** [comment]
@wing328  I'm very new to openAPI and don't get what are `oneOf models`.  Is there an option to ignore this at generation time, or do I have to mingle the json file?

**Comment by wing328** [comment]
In the spec, look for `oneOf` and replace it with something else such as string as a workaround.

**Comment by maliky** [comment]
Got it working as you suggested.  Thank you.  I'm sorry I could not be of any help implementing the oneof feature in python-flask.

**Comment by wing328** [comment]
No problem. Let's see if someone else from the community has the cycle to make the contribution.

We hope you found openapi-generator useful in your work and personal projects.
