### ISSUE TITLE
[BUG] NullPointerException in parser when referencing invalid schema

### ISSUE THREAD

**Issue by mildsunrise** [OpenAPITools/openapi-generator#10321]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Minor bug report, you can close it if you like.
It would be nice if the validation error was reported correctly (like usual) instead of NPE.

##### openapi-generator version

tested with 5.0.0, 5.2.1, 6.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

`test.yaml`:

~~~ yaml
openapi: 3.0.0
info:
  description: test
  version: test
  title: test
paths:
  /test:
    $ref: 'other.yaml#/test'
~~~

`other.yaml`:

~~~ yaml
test:
  get:
    responses:
      '200':
        description: test
        content:
          application/json:
            schema:
              type: object
              properties:
                prop1:
                  type: array
                prop2:
                  type: date
~~~

##### Steps to reproduce

then, `java -jar openapi-generator-cli.jar generate -i test.yaml -g java` gives an NPE when trying to access `items`:

~~~
[main] WARN  io.swagger.v3.parser.OpenAPIV3Parser - Exception while resolving:
java.lang.NullPointerException: null
        at io.swagger.v3.parser.processors.SchemaProcessor.processArraySchema(SchemaProcessor.java:196)
        at io.swagger.v3.parser.processors.SchemaProcessor.processSchemaType(SchemaProcessor.java:47)
        at io.swagger.v3.parser.processors.SchemaProcessor.processPropertySchema(SchemaProcessor.java:117)
        at io.swagger.v3.parser.processors.SchemaProcessor.processSchemaType(SchemaProcessor.java:54)
        at io.swagger.v3.parser.processors.SchemaProcessor.processSchema(SchemaProcessor.java:39)
        at io.swagger.v3.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:52)
        at io.swagger.v3.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:67)
        at io.swagger.v3.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:84)
        at io.swagger.v3.parser.OpenAPIResolver.resolve(OpenAPIResolver.java:49)
        at io.swagger.v3.parser.OpenAPIV3Parser.resolve(OpenAPIV3Parser.java:175)
        at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:154)
        at io.swagger.v3.parser.OpenAPIV3Parser.readLocation(OpenAPIV3Parser.java:89)
        at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:523)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:573)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:433)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Exception in thread "main" java.lang.NullPointerException
        at org.openapitools.codegen.utils.ModelUtils.lambda$getUnusedSchemas$1(ModelUtils.java:180)
        at org.openapitools.codegen.utils.ModelUtils.visitSchema(ModelUtils.java:325)
        at org.openapitools.codegen.utils.ModelUtils.visitSchema(ModelUtils.java:372)
        at org.openapitools.codegen.utils.ModelUtils.visitContent(ModelUtils.java:306)
        at org.openapitools.codegen.utils.ModelUtils.visitPathItem(ModelUtils.java:254)
        at org.openapitools.codegen.utils.ModelUtils.visitOpenAPI(ModelUtils.java:231)
        at org.openapitools.codegen.utils.ModelUtils.getUnusedSchemas(ModelUtils.java:179)
        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:537)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:573)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:433)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
~~~

Putting it in a single schema produces the correct output, indicating that there's a validation error and where.

**Comment by mildsunrise** [comment]
Removing `prop2` gives a slightly better output:

~~~
[main] WARN  io.swagger.v3.parser.OpenAPIV3Parser - Exception while resolving:
java.lang.NullPointerException: null
        at io.swagger.v3.parser.processors.SchemaProcessor.processArraySchema(SchemaProcessor.java:196)
        at io.swagger.v3.parser.processors.SchemaProcessor.processSchemaType(SchemaProcessor.java:47)
        at io.swagger.v3.parser.processors.SchemaProcessor.processPropertySchema(SchemaProcessor.java:117)
        at io.swagger.v3.parser.processors.SchemaProcessor.processSchemaType(SchemaProcessor.java:54)
        at io.swagger.v3.parser.processors.SchemaProcessor.processSchema(SchemaProcessor.java:39)
        at io.swagger.v3.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:52)
        at io.swagger.v3.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:67)
        at io.swagger.v3.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:84)
        at io.swagger.v3.parser.OpenAPIResolver.resolve(OpenAPIResolver.java:49)
        at io.swagger.v3.parser.OpenAPIV3Parser.resolve(OpenAPIV3Parser.java:175)
        at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:154)
        at io.swagger.v3.parser.OpenAPIV3Parser.readLocation(OpenAPIV3Parser.java:89)
        at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:523)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:573)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:433)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 0
Errors: 
        -null

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:546)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:573)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:433)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
~~~

**Comment by zhuangheihei** [comment]
Hi,

I am able to reproduce the issue, I can apply some change so it throws a more meaningful exception instead of a general NPE.
