### ISSUE TITLE
[BUG]  OpenAPIV3Parser fails on Windows for schemas with relative $refs

### ISSUE THREAD

**Issue by gbaah** [OpenAPITools/openapi-generator#10394]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
When trying to load a yaml file using the OpenAPIParser 
   ```OpenAPI openAPI = new OpenAPIV3Parser().read("paths.yaml")```
a StringIndexOutOfBoundsException is thrown, which prevents the OpenAPI object from being constructed correctly.

##### openapi-generator version
5.2.1
swagger-parser: 2.0.26

##### OpenAPI declaration file content or url
```yaml
paths.yaml
----------------
openapi: 3.0.1
info:
  title: 'Reproduce Error'
  version: test
paths:
  /example:
    get:
      tags:
        - Error
      operationId: reproduceError
      description: 'Reproduce Error'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'schema1.yaml#/components/schemas/NestedSomeObjects'

schema1.yaml
----------------
components:
  schemas:
    NestedSomeObjects:
      type: object
      properties:
        prop1:
          $ref: '#/components/schemas/SomeObject1'
    SomeObject1:
      $ref: '#/components/schemas/SomeObject2'
    SomeObject2:
      type: object
      properties:
        prop:
          type: number
```
##### Steps to reproduce
To reproduce just call
 ```OpenAPI openAPI = new OpenAPIV3Parser().read("paths.yaml")```
and provide the paths.yaml file.

##### Related issues/PRs
No, this is different.

##### Stack Trace
Here is the stack trace and the line number may be off on your machine.
```
[main] WARN io.swagger.v3.parser.OpenAPIV3Parser - Exception while resolving:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefToExternalSchema(ExternalRefProcessor.java:128)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefSchema(ExternalRefProcessor.java:936)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processSchema(ExternalRefProcessor.java:215)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processProperties(ExternalRefProcessor.java:238)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processProperties(ExternalRefProcessor.java:245)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefToExternalSchema(ExternalRefProcessor.java:173)
	at io.swagger.v3.parser.processors.SchemaProcessor.processReferenceSchema(SchemaProcessor.java:213)
	at io.swagger.v3.parser.processors.SchemaProcessor.processSchema(SchemaProcessor.java:37)
	at io.swagger.v3.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:52)
	at io.swagger.v3.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:67)
	at io.swagger.v3.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:84)
	at io.swagger.v3.parser.OpenAPIResolver.resolve(OpenAPIResolver.java:49)
	at io.swagger.v3.parser.OpenAPIV3Parser.resolve(OpenAPIV3Parser.java:175)
	at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:154)
	at io.swagger.v3.parser.OpenAPIV3Parser.readLocation(OpenAPIV3Parser.java:89)
	at io.swagger.v3.parser.OpenAPIV3Parser.read(OpenAPIV3Parser.java:116)
	at io.swagger.v3.parser.OpenAPIV3Parser.read(OpenAPIV3Parser.java:105)
```
##### Suggest a fix
The bug is located in ```ExternalRefProcessor#processRefToExternalSchema``` in the swagger parser at line 128.
```                    
126 if (!ref.equals(RefFormat.URL)) {
127    String schemaFullRef = schema.get$ref();
128     String parent = file.substring(0, file.lastIndexOf(File.separatorChar));
129     if (!parent.isEmpty()) {
130        schemaFullRef = Paths.get(parent, schemaFullRef).normalize().toString();
131     }
132     schema.set$ref(processRefToExternalSchema(schemaFullRef, ref));
133 }
```
 
In openapi forward slashes are used in the $ref paths and on Windows the File.separatorChar is a back slash hence the substring call fails. I haven't tested this fix and but the schemaFullRef is always computed on line 127. My suggestion will be to remove lines 128 through 131 and if for some reason those lines of code are needed (I still don't know why) then change File.separatorChar to "/".

**Comment by gbaah** [comment]
This bug has been fixed in swagger-parser v2.0.27 so I will close this issue.
