### ISSUE TITLE
[BUG] [PYTHON-LEGACY] Configuration.access_token not set in constructor

### ISSUE THREAD

**Issue by johnthagen** [OpenAPITools/openapi-generator#10688]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Using the generated `python-legacy` client targeting an OpenAPI 3 schema that supports both basicAuth, cookieAuth, and jwtAuth, the `access_token` attribute is not set in the constructor or a value to be passed in. As a result, when using basicAuth, the following stack trace is generated:

```
Traceback (most recent call last):
  File "/openapi_client/api/api_api.py", line 3297, in api_import_partial_update
    return self.api_import_with_http_info(id, **kwargs)  # noqa: E501
  File "/openapi_client/api/api_api.py", line 3398, in api_import_partial_update_with_http_info
    return self.api_client.call_api(
  File "/openapi_client/api_client.py", line 397, in call_api
    return self.__call_api(
  File "/openapi_client/api_client.py", line 176, in __call_api
    self.update_params_for_auth(
  File "/openapi_client/api_client.py", line 619, in update_params_for_auth
    auth_setting = self.configuration.auth_settings().get(auth)
  File "/openapi_client/configuration.py", line 435, in auth_settings
    if self.access_token is not None:
AttributeError: 'Configuration' object has no attribute 'access_token'
```

In the generated `openapi_client_README.md` it says that the `access_token` can be passed in:

```py
# Configure Bearer authorization (JWT): jwtAuth
configuration = openapi_client.Configuration(
    access_token = 'YOUR_BEARER_TOKEN'
)
```

But it is not present in the generated `Configuration` constructor:

```py
    def __init__(
        self,
        host=None,
        api_key=None,
        api_key_prefix=None,
        username=None,
        password=None,
        discard_unknown_keys=False,
        disabled_client_side_validations="",
        server_index=None,
        server_variables=None,
        server_operation_index=None,
        server_operation_variables=None,
        ssl_ca_cert=None,
    ):
```

Because of this, the generated `auth_settings()` method accesses `self.access_token` which is never set to `None` or a user supplied value in the constructor:

```py
    def auth_settings(self):
        """Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        auth = {}
        if self.username is not None and self.password is not None:
            auth["basicAuth"] = {
                "type": "basic",
                "in": "header",
                "key": "Authorization",
                "value": self.get_basic_auth_token(),
            }
        if "cookieAuth" in self.api_key:
            auth["cookieAuth"] = {
                "type": "api_key",
                "in": "cookie",
                "key": "sessionid",
                "value": self.get_api_key_with_prefix(
                    "cookieAuth",
                ),
            }
        if self.access_token is not None:
            auth["jwtAuth"] = {
                "type": "bearer",
                "in": "header",
                "format": "JWT",
                "key": "Authorization",
                "value": "Bearer " + self.access_token,
            }
        return auth
```

##### openapi-generator version

5.3.0 (also exists in 5.2.1)

##### Generation Details

```
npx @openapitools/openapi-generator-cli generate \
  --input-spec http://localhost:8000/openapi \
  --generator-name python-legacy --output . \
  --additional-properties=generateSourceCodeOnly=true
```

##### Suggest a fix

When a `Configuration` object is created that uses `access_token`, add the following optional argumenet:

```py
def __init__(
    ...
    access_token=None,
):
    ...
    self.access_token = access_token
```

**Comment by spacether** [comment]
@johnthagen it would be a simple fix.
All you need to do is update the template to 
- add the access_token as an input parameter with a None default
- use self.access_token = access_token in init
