### ISSUE TITLE
[BUG][Python] model template __copy__ refers to new_cls (undefined)

### ISSUE THREAD

**Issue by tuanchien** [OpenAPITools/openapi-generator#10856]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The Python generator template's `__copy__` function refers to `new_cls`, which is not defined in the function.

See: https://github.com/OpenAPITools/openapi-generator/blob/9464999d9c799ff9eb723886206ea98b7222032d/modules/openapi-generator/src/main/resources/python/model_templates/methods_shared.mustache#L22

This propagates into the generated `model_utils.py` file. It will result in failed operations if you try to `copy()` an `OpenApiModel` object. 

##### openapi-generator version

This is present in the master branch but also 5.3.0

##### OpenAPI declaration file content or url

This is reproducible using the petstore sample already present in the repo.

##### Generation Details

None. Use petstore sample.

##### Steps to reproduce

From the `openapi-generator/samples/client/petstore/python` directory, launch Python and run
```python
import petstore_api
from petstore_api.model.class_model import ClassModel
import copy

a = ClassModel()
b = copy.deepcopy(a)  # OK
c = copy.copy(a)  # Raises an error
```

It produces an error like:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/copy.py", line 84, in copy
    return copier(x)
  File "/home/user/openapi-generator/samples/client/petstore/python/petstore_api/model_utils.py", line 195, in __copy__
    return new_cls.__new__(cls, **self.__dict__)
NameError: name 'new_cls' is not defined
```

##### Suggest a fix

Change
 https://github.com/OpenAPITools/openapi-generator/blob/9464999d9c799ff9eb723886206ea98b7222032d/modules/openapi-generator/src/main/resources/python/model_templates/methods_shared.mustache#L22
to
```python
            return cls.__new__(cls, **self.__dict__)
```

**Comment by tuanchien** [comment]
Fixed by PR  #11792
