### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by martin5233** [OpenAPITools/openapi-generator#11090]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I have an OpenAPI specification for which I want to generate code. No matter, which backend I use, the generator always complains about validation errors as follows:

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 4, Warning count: 0
Errors: 
	-attribute paths.'/resources/v1/modeler/documents/CheckoutTicket'(put).responses.200.content.'application/json'.schema.#/components/x-schemas/MultiFileResultDownloadTicket is missing
	-attribute paths.'/resources/v1/modeler/documents/CheckoutTicket'(put).responses.200.content.'application/json'.schema.#/components/x-definitions/RESULTS-DownloadTicket is missing
	-attribute paths.'/resources/v1/modeler/documents/CheckoutTicket'(put).requestBody.content.'application/json'.schema.#/components/x-schemas/downloadticketinput is missing
	-attribute paths.'/resources/v1/modeler/documents/CheckoutTicket'(put).requestBody.content.'application/json'.schema.#/components/x-schemas/multifiledownloadticketinput is missing

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:554)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:581)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:433)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

```
The document validates with the above-mentioned validator at apidevtools without problems.

##### openapi-generator version

docker latest version corresponding to commit c94d2b2

##### OpenAPI declaration file content or url

```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "Document REST Services",
    "description": "REST Services for managing the Document modeler.",
    "version": "1.1.3",
    "x-ds-service": [
      "3DSpace"
    ]
  },
  "servers": [
    {
      "url": "{3DSpace}",
      "variables": {
        "3DSpace": {
          "default": "https://3dspace.mydomain:443/3DSpace"
        }
      }
    }
  ],
  "paths": {
    "/resources/v1/modeler/documents/CheckoutTicket": {
      "put": {
        "description": "",
        "summary": "Lock and get the checkout tickets for the given documents",
        "tags": [
          "FCS"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": "Request will be passed with oneOf mask available in the Schema Tab.",
                "oneOf": [
                  {
                    "$ref": "#/components/x-schemas/downloadticketinput"
                  },
                  {
                    "$ref": "#/components/x-schemas/multifiledownloadticketinput"
                  }
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "A JSON object containing Checkout information",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Response will be returned with oneOf mask available in the Schema Tab.",
                  "oneOf": [
                    {
                      "$ref": "#/components/x-definitions/RESULTS-DownloadTicket"
                    },
                    {
                      "$ref": "#/components/x-schemas/MultiFileResultDownloadTicket"
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "401": {
            "$ref": "#/components/responses/401"
          },
          "403": {
            "$ref": "#/components/responses/403"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        },
        "parameters": [
          {
            "$ref": "#/components/parameters/SecurityContext"
          },
          {
            "$ref": "#/components/parameters/Accept-Language"
          },
          {
            "$ref": "#/components/parameters/ENO_CSRF_TOKEN"
          },
          {
            "$ref": "#/components/parameters/zipFiles"
          }
        ]
      }
    }
  },
  "components": {
    "x-schemas": {
      "ownerInfo": {
        "allOf": [
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "example": "184182566B5300005FFD3FF400074CFC"
              },
              "type": {
                "type": "string",
                "example": "Person"
              },
              "cestamp": {
                "type": "string",
                "example": "18418256A75C000060FFED41001627C4"
              },
              "dataelements": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "VPLMAdminUser1"
                  },
                  "firstname": {
                    "default": "Unknown",
                    "type": "string",
                    "example": "AdminUser1"
                  },
                  "lastname": {
                    "default": "Unknown",
                    "type": "string",
                    "example": "VPLM"
                  },
                  "email": {
                    "default": "Unknown",
                    "x-IncludedByDefault:": "no",
                    "type": "string"
                  }
                }
              }
            }
          }
        ]
      },
      "originatorInfo": {
        "allOf": [
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "example": "184182566B5300005FFD3FF400074CFC"
              },
              "type": {
                "type": "string",
                "example": "Person"
              },
              "cestamp": {
                "type": "string",
                "example": "18418256A75C000060FFED41001627C4"
              },
              "dataelements": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "VPLMAdminUser"
                  },
                  "firstname": {
                    "type": "string",
                    "example": "AdminUser"
                  },
                  "lastname": {
                    "type": "string",
                    "example": "VPLM"
                  },
                  "email": {
                    "x-IncludedByDefault:": "no",
                    "type": "string"
                  }
                }
              }
            }
          }
        ]
      },
      "parentId": {
        "allOf": [
          {
            "$ref": "#/components/x-definitions/BASICS"
          }
        ]
      },
      "parents": {
        "allOf": [
          {
            "$ref": "#/components/x-definitions/BASICS"
          },
          {
            "type": "object",
            "properties": {
              "dataelements": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "revision": {
                    "type": "string"
                  },
                  "title": {
                    "type": "string"
                  },
                  "synopsis": {
                    "x-IncludedByDefault:": "no",
                    "type": "string"
                  },
                  "firstname": {
                    "description": "the person's first name - only applies when the object is a Person",
                    "default": "Unknown",
                    "type": "string"
                  },
                  "lastname": {
                    "description": "the person's last name - only applies when the object is a Person",
                    "default": "Unknown",
                    "type": "string"
                  },
                  "fullname": {
                    "description": "the person's full name - only applies when the object is a Person",
                    "default": "Unknown",
                    "type": "string"
                  },
                  "objectId": {
                    "x-IncludedByDefault:": "no",
                    "type": "string"
                  },
                  "policy": {
                    "description": "required to support state NLS",
                    "type": "string"
                  },
                  "stateNLS": {
                    "type": "string"
                  },
                  "typeNLS": {
                    "type": "string"
                  },
                  "collabSpace": {
                    "x-IncludedByDefault:": "no",
                    "type": "string"
                  },
                  "ownerFullname": {
                    "x-IncludedByDefault:": "no",
                    "type": "string"
                  },
                  "hasfiles": {
                    "description": "determines whether the object has a file checked in any format",
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "fileExtension": {
                    "description": "the extension of the file.",
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          {
            "type": "object",
            "properties": {
              "relelements": {
                "type": "object",
                "properties": {
                  "originated": {
                    "x-IncludedByDefault:": "no",
                    "type": "string"
                  }
                }
              }
            }
          },
          {
            "type": "object",
            "properties": {
              "relateddata": {
                "type": "object",
                "properties": {
                  "relOwnerInfo": {
                    "x-IncludedByDefault:": "no",
                    "type": "array",
                    "items": {
                      "$ref": "#/components/x-schemas/relOwnerInfo"
                    }
                  }
                }
              }
            }
          }
        ]
      },
      "relOwnerInfo": {
        "allOf": [
          {
            "$ref": "#/components/x-definitions/BASICS"
          },
          {
            "type": "object",
            "properties": {
              "dataelements": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "firstname": {
                    "default": "Unknown",
                    "type": "string"
                  },
                  "lastname": {
                    "default": "Unknown",
                    "type": "string"
                  },
                  "email": {
                    "default": "Unknown",
                    "x-IncludedByDefault:": "no",
                    "type": "string"
                  }
                }
              }
            }
          }
        ]
      },
      "DownloadTicket": {
        "allOf": [
          {
            "$ref": "#/components/x-definitions/DOWNLOAD-BASICS"
          },
          {
            "type": "object",
            "properties": {
              "dataelements": {
                "type": "object",
                "properties": {
                  "ticketURL": {
                    "description": "The URL to retrieve the file from the FCS server.",
                    "example": "https://3dspace.mydomain:453/fcs/servlet/fcs/checkout?__fcs__jobTicket=QEBlbnZlbG9wQEBmY3NrZXlfM2ZkYTAxZTBhNDhmMDE1OEBAdGFyZ2V0QEBmY3NrZXlfM2ZkYTAxZTBhNDhmMDE1OEBAc291cmNlQ"
                  },
                  "fileName": {
                    "description": "If single file is being downloaded then this field will appear.",
                    "example": "Filename.docx"
                  }
                }
              }
            }
          }
        ]
      },
      "MultiFileResultDownloadTicket": {
        "allOf": [
          {
            "$ref": "#/components/x-definitions/success"
          },
          {
            "type": "object",
            "properties": {
              "dataelements": {
                "type": "object",
                "properties": {
                  "csrf": {
                    "$ref": "#/components/x-definitions/csrf"
                  },
                  "ticketURL": {
                    "description": "The URL to retrieve the file from the FCS server.",
                    "example": "https://3dspace.mydomain:453/fcs/servlet/fcs/checkout?__fcs__jobTicket=QEBlbnZlbG9wQEBmY3NrZXlfM2ZkYTAxZTBhNDhmMDE1OEBAdGFyZ2V0QEBmY3NrZXlfM2ZkYTAxZTBhNDhmMDE1OEBAc291cmNlQ"
                  },
                  "fileNames": {
                    "description": "If multiple files are being downloaded then this field will appear.",
                    "type": "array",
                    "items": {
                      "type": "string",
                      "example": "[FileName.docx, FileName.xlsx]"
                    }
                  }
                }
              }
            }
          }
        ]
      },
      "CheckoutTicket": {
        "allOf": [
          {
            "$ref": "#/components/x-definitions/DOWNLOAD-BASICS"
          },
          {
            "type": "object",
            "properties": {
              "dataelements": {
                "type": "object",
                "properties": {
                  "ticketURL": {
                    "description": "The URL to retrieve the file from the FCS server.",
                    "example": "https://3dspace.mydomain:453/fcs/servlet/fcs/checkout?__fcs__jobTicket=QEBlbnZlbG9wQEBmY3NrZXlfM2ZkYTAxZTBhNDhmMDE1OEBAdGFyZ2V0QEBmY3NrZXlfM2ZkYTAxZTBhNDhmMDE1OEBAc291cmNlQ"
                  },
                  "fileName": {
                    "type": "object",
                    "description": "If single file is being checked out then this field will appear.",
                    "example": "Filename.docx"
                  }
                }
              }
            }
          }
        ]
      },
      "downloadticketinput": {
        "type": "object",
        "required": [
          "csrf",
          "data"
        ],
        "properties": {
          "csrf": {
            "$ref": "#/components/x-definitions/csrf"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "example": "{id: 86818256F97100006110D1A7001E2FCA}"
                }
              }
            }
          }
        }
      },
      "multifiledownloadticketinput": {
        "type": "object",
        "required": [
          "csrf",
          "data"
        ],
        "properties": {
          "csrf": {
            "$ref": "#/components/x-definitions/csrf"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "example": "{id:86818256F97100006110D1A7001E2FCA},{id:86818256F97100006110D1B8000CF3F0}"
                }
              }
            }
          }
        }
      },
      "versions": {
        "allOf": [
          {
            "$ref": "#/components/x-definitions/BASICS"
          },
          {
            "type": "object",
            "properties": {
              "dataelements": {
                "type": "object",
                "properties": {
                  "title": {
                    "description": "the file name.",
                    "type": "string",
                    "x-ApplicableOperations": "Create (Required), Read (Yes), Modify (No)"
                  },
                  "name": {
                    "description": "The name of the file object.",
                    "type": "string",
                    "x-ApplicableOperations": "Create (Yes), Read (Yes), Modify (No)"
                  },
                  "comments": {
                    "description": "the comments associated with the file checkin operation.",
                    "type": "string"
                  },
                  "locker": {
                    "description": "The locker user name if the file is locked.",
                    "type": "string",
                    "readOnly": true
                  },
                  "fileType": {
                    "default": " ",
                    "type": "string"
                  },
                  "dimension": {
                    "type": "string"
                  },
                  "length": {
                    "type": "string",
                    "example": "10.0"
                  },
                  "revision": {
                    "description": "The revision of the document object.",
                    "type": "string",
                    "x-ApplicableOperations": "Create (Yes), Read (Yes), Modify (No)",
                    "example": "1"
                  },
                  "originated": {
                    "description": "the originated date of the file.",
                    "type": "string",
                    "readOnly": true,
                    "example": "2021-08-09T06:44:07.000Z"
                  },
                  "modified": {
                    "description": "the last modified date of the file.",
                    "type": "string",
                    "readOnly": true,
                    "example": "2021-08-09T13:12:46.000Z"
                  },
                  "receipt": {
                    "description": "The FCS receipt for supporting the file operation; takes precedence over the one provided with the document.",
                    "type": "string",
                    "x-ApplicableOperations": "Create (Yes), Read (No), Modify (No)"
                  },
                  "keepLocked": {
                    "description": "Keeps the file locked after a checkin process.",
                    "type": "string",
                    "x-ApplicableOperations": "Create (Yes), Read (No), Modify (No)"
                  },
                  "format": {
                    "description": "Override the default format for the checkin process",
                    "type": "string",
                    "x-ApplicableOperations": "Create (Yes), Read (No), Modify (No)"
                  },
                  "store": {
                    "description": "Override the default store for the checkin process",
                    "type": "string",
                    "x-ApplicableOperations": "Create (Yes), Read (No), Modify (No)"
                  },
                  "fileObjectId": {
                    "description": "The file object id.",
                    "x-IncludedByDefault:": "no",
                    "type": "string",
                    "readOnly": true
                  },
                  "fileSize": {
                    "description": "The file size in bytes.",
                    "type": "string",
                    "example": 1210
                  }
                },
                "required": [
                  "title"
                ]
              }
            },
            "required": [
              "title"
            ]
          },
          {
            "type": "object",
            "properties": {
              "relateddata": {
                "type": "object",
                "properties": {
                  "ownerInfo": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/x-schemas/ownerInfo"
                    }
                  }
                }
              }
            }
          }
        ]
      },
      "sovaccess": {
        "allOf": [
          {
            "$ref": "#/components/x-definitions/BASICS"
          },
          {
            "type": "object",
            "properties": {
              "dataelements": {
                "type": "object",
                "properties": {
                  "orgnization": {
                    "type": "string"
                  },
                  "project": {
                    "type": "string"
                  },
                  "person": {
                    "type": "string"
                  },
                  "access": {
                    "type": "string"
                  },
                  "comment": {
                    "type": "string"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "x-definitions": {
      "RESULTS-DownloadTicket": {
        "allOf": [
          {
            "$ref": "#/components/x-definitions/success"
          },
          {
            "type": "object",
            "properties": {
              "csrf": {
                "$ref": "#/components/x-definitions/csrf"
              },
              "data": {
                "type": "array",
                "items": {
                  "$ref": "#/components/x-schemas/DownloadTicket"
                }
              }
            }
          }
        ]
      },
      "RESULTS-EMPTY": {
        "allOf": [
          {
            "$ref": "#/components/x-definitions/success"
          },
          {
            "type": "object",
            "properties": {
              "csrf": {
                "$ref": "#/components/x-definitions/csrf"
              }
            }
          }
        ]
      },
      "BASICS": {
        "type": "object",
        "properties": {
          "id": {
            "description": "The unique object identifier.",
            "type": "string",
            "example": "18418256E7550000612343A300129F6C"
          },
          "type": {
            "description": "The object type.",
            "type": "string",
            "example": "Document"
          },
          "identifier": {
            "description": "The unique object identifier when an object is represented by a Public URI.",
            "type": "string",
            "example": "18418256495900006102323D0004A2F4"
          },
          "source": {
            "description": "The object server URL when an object is represented by a Public URI.",
            "example": "https://3dspace.mydomain:443/3dspace",
            "type": "string"
          },
          "relativePath": {
            "description": "The object resource path when an object is represented by a Public Resource URI.",
            "example": "/resources/v1/modeler/documents/18418256793A000060F6D26900140DB8",
            "type": "string"
          }
        }
      },
      "DOWNLOAD-BASICS": {
        "type": "object",
        "properties": {
          "id": {
            "description": "The unique object identifier.",
            "example": "86818256F97100006110D1A7001E2FCA",
            "type": "string"
          }
        }
      },
      "csrf": {
        "description": "CSRF object is required to be sent back for update operations and typically provided with read operations.",
        "type": "object",
        "properties": {
          "name": {
            "description": "The CSRF token name.",
            "example": "ENO_CSRF_TOKEN",
            "type": "string"
          },
          "value": {
            "description": "The CSRF token value.",
            "example": "EXAM-PLEW-R1CD-BNF7-G8UC-KT52-MGUA-UBE1",
            "type": "string"
          }
        }
      },
      "success": {
        "description": "The response data when the request succeeds with 200 status code.",
        "type": "object",
        "properties": {
          "success": {
            "description": "Reflects true to indicate successful request.",
            "example": true,
            "type": "boolean"
          },
          "statusCode": {
            "description": "The HTTP response code.",
            "example": 200,
            "type": "integer"
          }
        }
      },
      "error-400": {
        "description": "The response data when the request fails with 400 or 500 error. The request could not be understood by the server due to malformed syntax/invalid data",
        "type": "object",
        "properties": {
          "success": {
            "description": "Reflects false to indicate failure.",
            "example": false,
            "type": "boolean"
          },
          "statusCode": {
            "description": "The HTTP response code.",
            "example": 400,
            "type": "integer"
          },
          "error": {
            "description": "An NLS error message.  In the case of a 400 error, the message is precise.  In the case of 500 error, the message is generic.",
            "example": "Error: Invalid Business Object Specified"
          },
          "internalError": {
            "description": "The technical reason of the failure - usually associated with a 500 error; this is not an NLS message and reflects the MQL or runtime exception.",
            "example": "Message:Business Object Does Not Exist Severity:2 ErrorCode:4000036"
          }
        }
      },
      "error-401": {
        "description": "The request requires user authentication.",
        "type": "object",
        "properties": {
          "success": {
            "description": "Reflects false to indicate failure.",
            "example": false,
            "type": "boolean"
          },
          "statusCode": {
            "description": "The HTTP response code.",
            "example": 401,
            "type": "integer"
          },
          "error": {
            "description": "An NLS error message.  In the case of a 400 error, the message is precise.  In the case of 500 error, the message is generic.",
            "type": "string"
          },
          "internalError": {
            "description": "The technical reason of the failure - usually associated with a 500 error; this is not an NLS message and reflects the MQL or runtime exception.",
            "type": "string"
          }
        }
      },
      "error-403": {
        "description": "The response data when the request fails with 400 or 500 error.",
        "type": "object",
        "properties": {
          "success": {
            "description": "Reflects false to indicate failure.",
            "example": false,
            "type": "boolean"
          },
          "statusCode": {
            "description": "The HTTP response code.",
            "example": 403,
            "type": "integer"
          },
          "error": {
            "description": "An NLS error message.  In the case of a 400 error, the message is precise.  In the case of 500 error, the message is generic.",
            "example": "Unauthorized Access Error"
          },
          "csrf": {
            "type": "object",
            "properties": {
              "name": {
                "example": "ENO_CSRF_TOKEN"
              },
              "value": {
                "example": "3OUI-DWWJ-IUYC-3FSD-T235-NUCP-38WK-AYT7"
              }
            }
          }
        }
      },
      "error-500": {
        "description": "A generic error message, given when an unexpected condition was encountered and no more specific message is suitable.",
        "type": "object",
        "properties": {
          "success": {
            "description": "Reflects false to indicate failure.",
            "example": false,
            "type": "boolean"
          },
          "statusCode": {
            "description": "The HTTP response code.",
            "example": 500,
            "type": "integer"
          },
          "error": {
            "description": "An NLS error message.  In the case of a 400 error, the message is precise.  In the case of 500 error, the message is generic.",
            "type": "string"
          },
          "internalError": {
            "description": "The technical reason of the failure - usually associated with a 500 error; this is not an NLS message and reflects the MQL or runtime exception.",
            "type": "string"
          }
        }
      }
    },
    "responses": {
      "200": {
        "description": "Success",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/x-definitions/RESULTS-EMPTY"
            }
          }
        }
      },
      "400": {
        "description": "Bad Request.",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/x-definitions/error-400"
            }
          }
        }
      },
      "401": {
        "description": "Authentication Issue",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/x-definitions/error-401"
            }
          }
        }
      },
      "403": {
        "description": "CSRF Issue",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/x-definitions/error-403"
            }
          }
        }
      },
      "500": {
        "description": "Internal Server Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/x-definitions/error-500"
            }
          }
        }
      }
    },
    "parameters": {
      "SecurityContext": {
        "name": "SecurityContext",
        "description": "Role.Organization.CollabSpace value e.g.VPLMProjectLeader.MyCompany.Default",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string"
        }
      },
      "Accept-Language": {
        "name": "Accept-Language",
        "description": "Identifies the locale for the web request.",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string"
        }
      },
      "ENO_CSRF_TOKEN": {
        "name": "ENO_CSRF_TOKEN",
        "description": "CSRF token that required for update operations. You can get it from 3DSpace/resources/v1/application/CSRF",
        "in": "header",
        "required": true,
        "schema": {
          "type": "string"
        }
      },
      "include": {
        "name": "$include",
        "description": "Identify sub-resources that should be returned by the web request.",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string"
        }
      },
      "fields": {
        "name": "$fields",
        "description": "Identify resource and sub-resource fields that should be returned by the web request.",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string"
        }
      },
      "zipFiles": {
        "name": "zipFiles",
        "description": "To download more than one selected file in .zip format.",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string"
        },
        "example": false
      },
      "top": {
        "name": "$top",
        "description": "Represents the total number of items returned from the search, accepts a maximum value of 1000. The default value is 50.",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string"
        }
      },
      "skip": {
        "name": "$skip",
        "description": "Represents the number of items to skip (to be used along with $top query parameter).",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string"
        }
      }
    }
  }
}

```

##### Generation Details

docker run --rm -v ~/local:/local openapitools/openapi-generator-cli generate -i /local/bookmarks.openapi.json -g cpp-qt-client -o /local/out

The actual generator doesn't matter.

##### Steps to reproduce

Invoke above command on a Linux shell.

**Comment by wing328** [comment]
Please try the `--skip-validate-spec` flag to skip the spec validation if you're sure the spec is correct.

**Comment by martin5233** [comment]
@wing328: Thanks for you response. I ran the generator with the `--skip-validate-spec` flag, which results in the following output:

```
 Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 4, Warning count: 0
Errors:
        -attribute paths.'/resources/v1/modeler/documents/CheckoutTicket'(put).responses.200.content.'application/json'.schema.#/components/x-schemas/MultiFileResultDownloadTicket is missing
        -attribute paths.'/resources/v1/modeler/documents/CheckoutTicket'(put).responses.200.content.'application/json'.schema.#/components/x-definitions/RESULTS-DownloadTicket is missing
        -attribute paths.'/resources/v1/modeler/documents/CheckoutTicket'(put).requestBody.content.'application/json'.schema.#/components/x-schemas/downloadticketinput is missing
        -attribute paths.'/resources/v1/modeler/documents/CheckoutTicket'(put).requestBody.content.'application/json'.schema.#/components/x-schemas/multifiledownloadticketinput is missing

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:554)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:581)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:433)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
mal1@dell1254cem [~/local] > docker run --rm -v ~/local:/local openapitools/openapi-generator-cli generate -i /local/test.api -g cpp-qt-client -o /local/out --skip-validate-spec
[main] WARN  o.o.c.config.CodegenConfigurator - There were issues with the specification, but validation has been explicitly disabled.
Errors:
        -attribute paths.'/resources/v1/modeler/documents/CheckoutTicket'(put).responses.200.content.'application/json'.schema.#/components/x-schemas/MultiFileResultDownloadTicket is missing
        -attribute paths.'/resources/v1/modeler/documents/CheckoutTicket'(put).responses.200.content.'application/json'.schema.#/components/x-definitions/RESULTS-DownloadTicket is missing
        -attribute paths.'/resources/v1/modeler/documents/CheckoutTicket'(put).requestBody.content.'application/json'.schema.#/components/x-schemas/downloadticketinput is missing
        -attribute paths.'/resources/v1/modeler/documents/CheckoutTicket'(put).requestBody.content.'application/json'.schema.#/components/x-schemas/multifiledownloadticketinput is missing

[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: cpp-qt-client (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'cpp-qt-client' is considered stable.
[main] INFO  o.o.c.languages.AbstractCppCodegen - Environment variable CPP_POST_PROCESS_FILE not defined so the C++ code may not be properly formatted. To define it, try 'export CPP_POST_PROCESS_FILE="/usr/local/bin/clang-format -i"' (Linux/Mac)
[main] INFO  o.o.c.languages.AbstractCppCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to 'true' (--enable-post-process-file for CLI).
[main] WARN  o.o.codegen.DefaultCodegen - Empty operationId found for path: put /resources/v1/modeler/documents/CheckoutTicket. Renamed to auto-generated operationId: resourcesV1ModelerDocumentsCheckoutTicketPut
[main] WARN  o.o.codegen.DefaultCodegen - The following schema has undefined (null) baseType. It could be due to form parameter defined in OpenAPI v2 spec with incorrect consumes. A correct 'consumes' for form parameters should be 'application/x-www-form-urlencoded' or 'multipart/?'
[main] WARN  o.o.codegen.DefaultCodegen - schema: class ComposedSchema {
    class Schema {
        type: null
        format: null
        $ref: null
        description: null
        title: null
        multipleOf: null
        maximum: null
        exclusiveMaximum: null
        minimum: null
        exclusiveMinimum: null
        maxLength: null
        minLength: null
        pattern: null
        maxItems: null
        minItems: null
        uniqueItems: null
        maxProperties: null
        minProperties: null
        required: null
        not: null
        properties: null
        additionalProperties: null
        nullable: null
        readOnly: null
        writeOnly: null
        example: Request will be passed with oneOf mask available in the Schema Tab.
        externalDocs: null
        deprecated: null
        discriminator: null
        xml: null
    }
    allOf: null
    anyOf: null
    oneOf: [class Schema {
        type: null
        format: null
        $ref: #/components/x-schemas/downloadticketinput
        description: null
        title: null
        multipleOf: null
        maximum: null
        exclusiveMaximum: null
        minimum: null
        exclusiveMinimum: null
        maxLength: null
        minLength: null
        pattern: null
        maxItems: null
        minItems: null
        uniqueItems: null
        maxProperties: null
        minProperties: null
        required: null
        not: null
        properties: null
        additionalProperties: null
        nullable: null
        readOnly: null
        writeOnly: null
        example: null
        externalDocs: null
        deprecated: null
        discriminator: null
        xml: null
    }, class Schema {
        type: null
        format: null
        $ref: #/components/x-schemas/multifiledownloadticketinput
        description: null
        title: null
        multipleOf: null
        maximum: null
        exclusiveMaximum: null
        minimum: null
        exclusiveMinimum: null
        maxLength: null
        minLength: null
        pattern: null
        maxItems: null
        minItems: null
        uniqueItems: null
        maxProperties: null
        minProperties: null
        required: null
        not: null
        properties: null
        additionalProperties: null
        nullable: null
        readOnly: null
        writeOnly: null
        example: null
        externalDocs: null
        deprecated: null
        discriminator: null
        xml: null
    }]
}
[main] WARN  o.o.codegen.DefaultCodegen - codegenModel is null. Default to UNKNOWN_BASE_TYPE
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/client/OAIFCSApi.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/client/OAIFCSApi.h
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/client/OAIHelpers.h
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/client/OAIHelpers.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/client/OAIHttpRequest.h
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/client/OAIHttpRequest.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/client/OAIHttpFileElement.h
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/client/OAIHttpFileElement.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/client/OAIObject.h
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/client/OAIEnum.h
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/client/OAIServerConfiguration.h
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/client/OAIServerVariable.h
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/client/OAIOauth.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/client/OAIOauth.h
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/README.md
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/client/CMakeLists.txt
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/client/client.pri
[main] INFO  o.o.codegen.TemplateManager - Skipped /local/out/.openapi-generator-ignore (Skipped by supportingFiles options supplied by user.)
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/.openapi-generator/VERSION
[main] INFO  o.o.codegen.TemplateManager - writing file /local/out/.openapi-generator/FILES
################################################################################
# Thanks for using OpenAPI Generator.                                          #
# Please consider donation to help us maintain this project 🙏                #
# https://opencollective.com/openapi_generator/donate                          #
################################################################################
```

I then tried to compile the generated code. First it failed, because the generated code references QDesktopServices, but the CMakeLists.txt does not contain a reference to the containing Qt5Gui library. After adding this library, the code still does not compile with the following error message (generated for multiple files):

```
In file included from /home/home_dev/MAL1/local/out/client/OAIFCSApi.cpp:12:
/home/home_dev/MAL1/local/out/client/OAIFCSApi.h:20:10: fatal error: OAIError_400.h: No such file or directory
 #include "OAIError_400.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
```

The referenced include file does not exist. Is there anything else I can check?

**Comment by wing328** [comment]
About the following
```
[main] WARN  o.o.codegen.DefaultCodegen - The following schema has undefined (null) baseType. It could be due to form parameter defined in OpenAPI v2 spec with incorrect consumes. A correct 'consumes' for form parameters should be 'application/x-www-form-urlencoded' or 'multipart/?'
[main] WARN  o.o.codegen.DefaultCodegen - schema: class ComposedSchema {
```

Please give it another try with v6.0.0 or the latest master as we've made a lot of improvements to the inline schema handling, which should have fixed the issue.

**Comment by madukan** [comment]
I am trying with version 6.0.1, and finding the same issue

**Comment by fiddyschmitt** [comment]
Hi @martin5233,

What URL did you use to retrieve `bookmarks.openapi.json` from the server?

Was it something like:
https://3dspace-server/3dspace/resources/v1/bookmarks.openapi.json

Thanks,
Fidel

**Comment by martin5233** [comment]
Hi @fiddyschmitt,

I downloaded the JSON file from an internal documentation site, not from the server offering the service itself. But I don't understand, why this makes a difference.

Thanks,

Martin

**Comment by fiddyschmitt** [comment]
Thanks @martin5233,

I'm trying to connect to a similar service, but I can't seem to find a URL for the swagger/open-api definition file. Your post is the only one I found which mentions what I'm after. You're right - it doesn't make a difference for your reported bug :sweat_smile:

Thanks for you help though.
Fidel
