### ISSUE TITLE
[BUG] Using $ref under components/schema results in spec validation failure 

### ISSUE THREAD

**Issue by dmitri-d** [OpenAPITools/openapi-generator#11151]
A spec like this:

```
openapi: 3.0.3
info:
  title: api spec
  version: 1.0.0
servers:
  - url: /v3
components:
  schemas:
    $ref: './definitions/_index.yaml'
...
```
Results in validation error(s):
```
xception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 2, Warning count: 0
Errors: 
	-attribute components.schemas.$ref is not of type `object`
	-attribute components.schemas.Schema name $ref doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:544)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:571)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:433)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

This is using docker.io/openapitools/openapi-generator-cli:latest (image id: e718a88b4de4). The spec with the `schemas` changed as below passes the validation:

```
openapi: 3.0.3
info:
  title: api spec
  version: 1.0.0
servers:
  - url: /v3
components:
  schemas:
    UnauthorizedError:
      $ref: "./definitions/unauthorized_error.yaml"
    NotFoundError:
      $ref: "./definitions/not_found_error.yaml"
...
```

According to 3.0 docs a `$ref` element should be valid immediately under `schema`.

**Comment by wolkenschieber** [comment]
Have been hit by same issue. I'm currently working around this by completely dereferencing  the specification through [swagger-cli](https://github.com/APIDevTools/swagger-cli):
```
swagger-cli.js bundle --outfile "${OPENAPI_SPEC_DEREF}" --dereference --type yaml "${OPENAPI_SPEC}"
```

**Comment by ShauniArima** [comment]
Same problem here. Using @wolkenschieber solution solve partially the problem.

Using [bundle](https://redoc.ly/docs/cli/commands/bundle) command of redocly does not work at all :cry:

**Comment by greglearns** [comment]
@wolkenschieber solution worked for me, but with this tweak:
```
swagger-cli bundle --outfile "${OPENAPI_SPEC_THAT_WILL_BE_USED_EVERYWHERE}" --dereference --type yaml "${OPENAPI_SPEC_THAT_NEEDS_TO_BE_DEREFERENCED}"
```

**Comment by ShauniArima** [comment]
Does someone have an idea of what to do to resolve this issue?

**Comment by zhuxubin01** [comment]
how about this bug? what time will fix this bug?

**Comment by lasconic** [comment]
I just submitted an issue on the OpenAPI specification in the hope that they could make it clear in the next version that the syntax is correct.
In the meantime, it could be fixed in https://github.com/swagger-api/swagger-parser/blob/065fa61ee74d42cbe62ebd53d1c7fedbfb6edf1e/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java#L823 
Assuming this is the library used by openapi-generator

**Comment by pontus-eliason** [comment]
Any update here?

**Comment by gaurao29** [comment]
Saw the same issue any updates here?

**Comment by nschlechter** [comment]
Issue still exists in openapi 3.1.0, any update?

**Comment by NXML** [comment]
Same issue here ,
the only way i can manage to use external refs for shemas in py open api spec (with type resolution in openapi-generator) is to use a tool like swagger-cli to bundle all in one file and then use the new bundled file to generate classes
