### ISSUE TITLE
[BUG][Go] Parameter with free-form object type throws NullPointerException

### ISSUE THREAD

**Issue by jrauen** [OpenAPITools/openapi-generator#11283]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version
5.3.1

##### OpenAPI declaration file content or url

If you post the code inline, please wrap it with
```json
"/settings/integration": {
  "put": {
    "description": "Create or update an instance of an integration",
    "summary": "Create/update an integration instance",
    "operationId": "createUpdateIntegrationInstance",
    "parameters": [
      {
        "name": "CreateIntegrationRequest",
        "in": "body",
        "schema": {
          "type": "object"
        }
      }
    ],
    "responses": {
      "200": {
        "description": "IntegrationWrapper",
        "schema": {
          "$ref": "#/definitions/IntegrationWrapper"
        }
      }
    }
  }
}
```

##### Generation Details
```
Exception in thread "main" java.lang.RuntimeException: Could not generate api file for 'Default'
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:682)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:907)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException
	at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:541)
	at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:492)
	at org.openapitools.codegen.languages.GoClientCodegen.postProcessOperationsWithModels(GoClientCodegen.java:460)
	at org.openapitools.codegen.DefaultGenerator.processOperations(DefaultGenerator.java:1224)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:585)
```

**Comment by jrauen** [comment]
I think this is a regression but I don't know the version that worked previously as it's been a while. The free-form objects used to create functions that would accept `map[string]interface{}`, but now it's generating an empty struct.

Old:
```go
type ApiCreateUpdateIntegrationInstanceRequest struct {
	ctx _context.Context
	ApiService *DefaultApiService
	createIntegrationRequest *map[string]interface{}
}
```
New:
```go
type ApiCreateUpdateIntegrationInstanceRequest struct {
	ctx _context.Context
	ApiService *DefaultApiService
	createIntegrationRequest *CreateIntegrationRequest
}
type CreateIntegrationRequest struct {}
```
