### ISSUE TITLE
[BUG][angular typescript] latest docker image not reading configuration file

### ISSUE THREAD

**Issue by LPCmedia** [OpenAPITools/openapi-generator#11287]
##### Description

we are using the latest docker image in our code generation for typescript angular. As we updated yesterday, the generator now errors out whenever we pass in a configuration file: 

```[bash]
docker pull openapitools/openapi-generator-cli:latest

docker run --rm -v ${PWD}:/local -v $(pwd)/codegen_scripts/:/tmp/cfg openapitools/openapi-generator-cli:latest generate \
    -i http://ourpath-to-openapi.json \
    -g typescript-angular \
    **-c /tmp/cfg/config.json \** 
    -o /local/typescript-angular
```

where we have in codegen_scripts/config.json

```[json]
{
  "additionalProperties": {
    "useHttpClient": true,
    "useNgPackagr": true,
    "basePath": "",
    "enumPropertyNaming": "UPPERCASE",
    "stringEnums": true
  },
  "ngVersion": "13.1.1",
  "npmName": "@activia/cm-api",
  "npmVersion": "52.4.5",
  "npmRepository": "https://ourepo/repository/npm-internal/",
  "supportsES6": true
}
```

##### openapi-generator version

openapitools/openapi-generator-cli@sha256:5cf9a2bd60dbd7a517ff462824fb8792168c074fe13e8dd4708718127f819939

##### Steps to reproduce

run the bash above against a valid openapi.json
-> expected: works and generates

-> actual: 

```
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.lang.String.concat(Unknown Source)
        at org.openapitools.codegen.CodegenConfigLoader.forName(CodegenConfigLoader.java:48)
        at org.openapitools.codegen.config.CodegenConfigurator.fromFile(CodegenConfigurator.java:94)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:272)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

removing the -c option works but generated httpclient.delete calls contain an extra parameter, we lost package.json info. As well using the latest-release image has the same extra parameter in the delete as well and thus the generated code won't compile.

**Comment by LPCmedia** [comment]
similar to https://github.com/OpenAPITools/openapi-generator/issues/11276
