### ISSUE TITLE
[BUG][Go] NullPointerException for free-form request objects

### ISSUE THREAD

**Issue by childish-sambino** [OpenAPITools/openapi-generator#11470]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Go client generator doesn't support free-form request objects.

##### openapi-generator version

5.3.1

##### OpenAPI declaration file content or url

If you post the code inline, please wrap it with
```yaml
info:
  description: Test
  title: Test
  version: 1.0.0
openapi: 3.0.1
paths:
  /test:
    get:
      operationId: Test
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                TestObject:
                  description: Description
                  type: object
              title: Body
              type: object
      responses:
        '200':
          description: Response description
```

##### Generation Details

```
docker run --rm -it -v "$(pwd)"/api.yaml:/specs/api.yaml openapitools/openapi-generator-cli:v5.3.1 generate -i /specs/api.yaml -g go
```

##### Steps to reproduce

1. store example in api.yaml
1. run example from "generation details"
1. see exception

```
Exception in thread "main" java.lang.RuntimeException: Could not generate api file for 'Default'
        at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:682)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:907)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:541)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:492)
        at org.openapitools.codegen.languages.GoClientCodegen.postProcessOperationsWithModels(GoClientCodegen.java:460)
        at org.openapitools.codegen.DefaultGenerator.processOperations(DefaultGenerator.java:1224)
        at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:585)
        ... 4 more
```

##### Suggest a fix

Verify the parameter has items before attempting to generate the the example.

**Comment by wing328** [comment]
tested with the latest master and no longer got NPE.
