### ISSUE TITLE
[BUG][python] ApiException reason is always empty

### ISSUE THREAD

**Issue by davidnewcomb** [OpenAPITools/openapi-generator#11771]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] N/A Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] N/A [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178)).

##### Description

`ApiException.reason` is always empty

##### openapi-generator version
```
openapi-generator-cli 5.3.1
  commit : 6269a98
  built  : 2021-12-21T10:47:20Z
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/
```

##### OpenAPI declaration file content or url

Any code that throws ApiException

##### Generation Details

Normal

##### Steps to reproduce

From the (more or less) vanilla generated code for auth in the 'python' client:
```
with openapi_client.ApiClient(configuration) as api_client:
    # Create an instance of the API class
    api_instance = auth_api.AuthApi(api_client)
    auth_body = AuthRequestDTOAuthenticationRequest(
        user_name = 'user',
        password = 'pass'
    ) # AuthRequestDTOAuthenticationRequest | Credentials for authentication request

    try:
        # login with username and password
        api_response = api_instance.auth_using_post(auth_body)
        # pprint(api_response)
        return {'ok': True, 'token': api_response.token}
    except openapi_client.ApiException as e:
        # print("Exception when calling AuthApi->auth_using_post: %s\n" % e)
        return {'ok': False, 'reason': e.reason}
```

If one dumps the exception `e` you get:
```
[
('__cause__', None),
('__class__', <class 'openapi_client.exceptions.ApiException'>),
('__context__', None),
('__delattr__', <method-wrapper '__delattr__' of ApiException object at 0x10cde7fa0>),
('__dict__', {
	'body': '{"status":"BAD_REQUEST","message":"Invalid credentials!"}',
	'headers': HTTPHeaderDict(
			{'Access-Control-Allow-Origin': '*',
			'Access-Control-Allow-Methods': 'GET, POST, DELETE, PUT, PATCH, HEAD, OPTIONS',
			'Access-Control-Allow-Headers': 'Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, auth-token',
			'Access-Control-Expose-Headers': 'Access-Control-Allow-Origin, Access-Control-Allow-Credentials',
			'Access-Control-Allow-Credentials': 'true',
			'Access-Control-Max-Age': '10',
			'Content-Type': 'application/json;charset=UTF-8',
			'Transfer-Encoding': 'chunked',
			'Date': 'Wed, 02 Mar 2022 11:07:37 GMT',
			'Connection': 'close'}),
	'reason': '',
	'status': 400}),
('args', ()),
('body', '{"status":"BAD_REQUEST","message":"Invalid credentials!"}'),
('headers', HTTPHeaderDict({'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, PUT, PATCH, HEAD, OPTIONS', 'Access-Control-Allow-Headers': 'Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, auth-token', 'Access-Control-Expose-Headers': 'Access-Control-Allow-Origin, Access-Control-Allow-Credentials', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Max-Age': '10', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Date': 'Wed, 02 Mar 2022 11:07:37 GMT', 'Connection': 'close'})),
('reason', ''),
('status', 400),
('with_traceback', <built-in method with_traceback of ApiException object at 0x10cde7fa0>),
('__module__',        'openapi_client.exceptions'),
('__doc__',           None),
('__suppress_context__', False),
('__init__',          <bound method ApiException.__init__ of ApiException()>),
('__init_subclass__', <built-in method __init_subclass__ of type object at 0x7fbeab153d70>),
('__dir__',           <built-in method __dir__ of ApiException object at 0x10cde7fa0>),
('__format__',        <built-in method __format__ of ApiException object at 0x10cde7fa0>),
('__new__',           <built-in method __new__ of type object at 0x10c2d3ef0>),
('__reduce__',        <built-in method __reduce__ of ApiException object at 0x10cde7fa0>),
('__reduce_ex__',     <built-in method __reduce_ex__ of ApiException object at 0x10cde7fa0>),
('__eq__',            <method-wrapper '__eq__' of ApiException object at 0x10cde7fa0>),
('__ge__',            <method-wrapper '__ge__' of ApiException object at 0x10cde7fa0>),
('__getattribute__',  <method-wrapper '__getattribute__' of ApiException object at 0x10cde7fa0>),
('__gt__',            <method-wrapper '__gt__' of ApiException object at 0x10cde7fa0>),
('__hash__',          <method-wrapper '__hash__' of ApiException object at 0x10cde7fa0>),
('__le__',            <method-wrapper '__le__' of ApiException object at 0x10cde7fa0>),
('__lt__',            <method-wrapper '__lt__' of ApiException object at 0x10cde7fa0>),
('__ne__',            <method-wrapper '__ne__' of ApiException object at 0x10cde7fa0>),
('__repr__',          <method-wrapper '__repr__' of ApiException object at 0x10cde7fa0>),
('__setattr__',       <method-wrapper '__setattr__' of ApiException object at 0x10cde7fa0>),
('__setstate__',      <built-in method __setstate__ of ApiException object at 0x10cde7fa0>),
('__sizeof__',        <built-in method __sizeof__ of ApiException object at 0x10cde7fa0>),
('__str__',           <bound method ApiException.__str__ of ApiException()>),
('__subclasshook__',  <built-in method __subclasshook__ of type object at 0x7fbeab153d70>),
('__traceback__', <traceback object at 0x10cd3fdc0>),
('__weakref__', None)
]
```

As you can see `reason` is empty and if you look carefully you can see that the body is a string and not an object:
```
('__dict__', {
	'body': '{"status":"BAD_REQUEST","message":"Invalid credentials!"}',
```

This might be the cause.

##### Related issues/PRs

Couldn't find anything related

##### Suggest a fix

Make `body` a proper object.
To get the reason, I have to get the body, convert it to an object then read it! This can't be right.

**Comment by wing328** [comment]
> openapi-generator-cli 5.3.1

Please try v5.4.0 or the latest master instead.

There's also a new python-experimental generator that you may want give it a try to see if the same issue occurs.

**Comment by davidnewcomb** [comment]
Same results with 5.4.0.
The python-experimental didn't even make it past the generate stage. This is going to take a lot longer to figure out which bit of this is broken.

```
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - Output directory (/Users/davidnewcomb/GOOGLE/gitlab/30_Tools/spool/python-client/openapi_client) does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: python-experimental (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'python-experimental' is considered experimental.
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] INFO  o.o.c.l.AbstractPythonCodegen - Environment variable PYTHON_POST_PROCESS_FILE not defined so the Python code may not be properly formatted. To define it, try 'export PYTHON_POST_PROCESS_FILE="/usr/local/bin/yapf -i"' (Linux/Mac)
[main] INFO  o.o.c.l.AbstractPythonCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - Output directory (/Users/davidnewcomb/GOOGLE/gitlab/30_Tools/spool/python-client/openapi_client) does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.c.l.PythonExperimentalClientCodegen - Environment variable PYTHON_POST_PROCESS_FILE not defined so the Python code may not be properly formatted. To define it, try 'export PYTHON_POST_PROCESS_FILE="/usr/local/bin/yapf -i"' (Linux/Mac)
[main] INFO  o.o.c.l.PythonExperimentalClientCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.c.l.PythonExperimentalClientCodegen - generateAliasAsModel is hard coded to true in this generator. Alias models will only be generated if they contain validations or enums
[main] WARN  o.o.codegen.utils.URLPathUtils - 'scheme' not defined in the spec (2.0). Default to [http] for server URL [http://localhost:8091/]
[main] WARN  o.o.codegen.utils.URLPathUtils - 'scheme' not defined in the spec (2.0). Default to [http] for server URL [http://localhost:8091/]
[main] WARN  o.o.c.l.AbstractPythonCodegen - Type null not handled properly in toExampleValue
[main] WARN  o.o.c.l.AbstractPythonCodegen - Type null not handled properly in toExampleValue
.... lots of these!
[main] WARN  o.o.c.l.AbstractPythonCodegen - Type null not handled properly in toExampleValue
[main] WARN  o.o.c.l.AbstractPythonCodegen - Type null not handled properly in toExampleValue
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'API_ERROR'
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:532)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:888)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: com.github.jknack.handlebars.HandlebarsException: model.handlebars:3:3: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.HashMap$Node[] java.util.HashMap.table accessible: module java.base does not "opens java.util" to unnamed module @4d937939
    model.handlebars:3:3
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.github.jknack.handlebars.context.FieldValueResolver$FieldMember.setAccessible(FieldValueResolver.java:150)
	at com.github.jknack.handlebars.context.MemberValueResolver.cache(MemberValueResolver.java:82)
	at com.github.jknack.handlebars.context.MemberValueResolver.resolve(MemberValueResolver.java:54)
	at com.github.jknack.handlebars.Context$CompositeValueResolver.resolve(Context.java:199)
	at com.github.jknack.handlebars.internal.path.PropertyPath.eval(PropertyPath.java:52)
	at com.github.jknack.handlebars.Context$PathExpressionChain.next(Context.java:361)
	at com.github.jknack.handlebars.Context$PathExpressionChain.eval(Context.java:381)
	at com.github.jknack.handlebars.Context.get(Context.java:618)
	at com.github.jknack.handlebars.internal.Partial.override(Partial.java:253)
	at com.github.jknack.handlebars.internal.Partial.merge(Partial.java:226)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:125)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:125)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:113)
	at org.openapitools.codegen.templating.HandlebarsEngineAdapter.compileTemplate(HandlebarsEngineAdapter.java:92)
	at org.openapitools.codegen.TemplateManager.write(TemplateManager.java:163)
	at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1034)
	at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1021)
	at org.openapitools.codegen.DefaultGenerator.generateModel(DefaultGenerator.java:388)
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:523)
	... 4 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.HashMap$Node[] java.util.HashMap.table accessible: module java.base does not "opens java.util" to unnamed module @4d937939
	... 28 more
```

Given a choice of 2 broken things, I'll take the one I've got a hack for:
```
def api_response_failure_reason(e):
    try:
        b = e.body
        o = json.loads(b)
        return o['message']
    except Exception as e:
        return 'unknown'
```

...but it'd be nice if this was made right.

I appreciate that the body (in some error conditions) may not be a proper json object but this is an application/json request/response and so the client should seek to ensure this. If it is a json object it should be deserialised before being handed back to the client and throw if it can't with a deserialisation error.

**Comment by spacether** [comment]
In the python client in version 6.2.0 and onward, this issue is resolved because the api response always contains the raw urllib3 response.
One can see this here:
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/petstore_api/paths/fake/post.py#L439
