### ISSUE TITLE
[BUG] python/python-experimental generator got NPE when handle object schema in query parameters

### ISSUE THREAD

**Issue by chanjarster** [OpenAPITools/openapi-generator#11946]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

5.4.0

6.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.2
info:
  title: foo api
  version: v1
  description: 'bar'

paths:
  '/users':
    get:
      summary: user list
      operationId: userList
      parameters:
        - name: mapBean
          in: query
          required: false
          description: mapBean
          style: deepObject
          explode: true
          schema:
            type: object
            properties:
              keyword:
                title: keyword
                type: string
      responses:
        '200':
          description: ok
```

##### Generation Details

config:

```yaml
projectName: foo-api
packageName: foo_api
```

##### Steps to reproduce

```bash
openapi-generator-cli generate \
  --generator-name python \
  --config foo-api-gen-config.yaml \
  --output foo-api \
  --input-spec foo-api.yaml
```

got error:

```
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: python (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'python' is considered stable.
[main] INFO  o.o.c.languages.PythonClientCodegen - generateAliasAsModel is hard coded to true in this generator. Alias models will only be generated if they contain validations or enums
[main] INFO  o.o.codegen.utils.URLPathUtils - 'host' (OAS 2.0) or 'servers' (OAS 3.0) not defined in the spec. Default to [http://localhost] for server URL [http://localhost/]
[main] INFO  o.o.codegen.utils.URLPathUtils - 'host' (OAS 2.0) or 'servers' (OAS 3.0) not defined in the spec. Default to [http://localhost] for server URL [http://localhost/]
[main] INFO  o.o.codegen.TemplateManager - writing file /Users/qianjia/tmp/oas-gen/foo-api/foo_api/model/map_bean.py
[main] INFO  o.o.codegen.TemplateManager - Skipped /Users/qianjia/tmp/oas-gen/foo-api/test/test_map_bean.py (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - writing file /Users/qianjia/tmp/oas-gen/foo-api/docs/MapBean.md
[main] ERROR o.o.codegen.DefaultCodegen - Undefined property/schema for `map_bean`. Default to type:string.
[main] ERROR o.o.codegen.DefaultCodegen - Undefined property/schema for `map_bean`. Default to type:string.
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: class Tag {
    name: default
    description: null
    externalDocs: null
}
  Operation: userList
  Resource: get /users
  Schemas: {mapBean=class ObjectSchema {
    class Schema {
        type: object
        format: null
        $ref: null
        description: null
        title: null
        multipleOf: null
        maximum: null
        exclusiveMaximum: null
        minimum: null
        exclusiveMinimum: null
        maxLength: null
        minLength: null
        pattern: null
        maxItems: null
        minItems: null
        uniqueItems: null
        maxProperties: null
        minProperties: null
        required: null
        not: null
        properties: {keyword=class StringSchema {
            class Schema {
                type: string
                format: null
                $ref: null
                description: null
                title: keyword
                multipleOf: null
                maximum: null
                exclusiveMaximum: null
                minimum: null
                exclusiveMinimum: null
                maxLength: null
                minLength: null
                pattern: null
                maxItems: null
                minItems: null
                uniqueItems: null
                maxProperties: null
                minProperties: null
                required: null
                not: null
                properties: null
                additionalProperties: null
                nullable: null
                readOnly: null
                writeOnly: null
                example: null
                externalDocs: null
                deprecated: null
                discriminator: null
                xml: null
            }
        }}
        additionalProperties: null
        nullable: null
        readOnly: null
        writeOnly: null
        example: null
        externalDocs: null
        deprecated: null
        discriminator: null
        xml: null
    }
}}
  Exception: null
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1163)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1054)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:549)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:891)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException
	at org.openapitools.codegen.languages.PythonClientCodegen.fromProperty(PythonClientCodegen.java:440)
	at org.openapitools.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:4752)
	at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:4113)
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1131)
	... 6 more
```

##### Suggest a fix

`PythonClientCodegen#fromProperty` and `PythonExperimentalClientCodegen#fromProperty` doesn't handle the situation that super.fromProperty may return null.

**Comment by spacether** [comment]
This is happening because the inlineModelResolver extracts this model with the name `mapBean` and getParameterDataType returns it as `MapBean`

**Comment by spacether** [comment]
Are you up for adding the deepObject deserialization method like this comment mentions?
https://github.com/OpenAPITools/openapi-generator/issues/9603#issuecomment-1020675741

**Comment by chanjarster** [comment]
Nope, not familiar with python, i'm a java guy, maybe sometime.

**Comment by nloding** [comment]
@spacether - I am facing this issue with the python generator. I have a very simple deepObject parameter and it's throwing the same error reported above. I haven't found much good information on the lifecycle or differences between the python and python-experimental generators. Do changes move down from experimental at all? I hesitate to use anything not considered stable, but at the same time the python generator is completely broken for us. Any recommendations?

**Comment by spacether** [comment]
@nloding the model construction is similar between those generators. In python-experimental, spec case is used for all model property names though. Changes have not been moving from python-experimental into python because the python-experimental generator was re-written to more robustly handle schema validation.
What is the definition fo your object schema parameter?
The style DeepObject is not yet supported in python-experimental.

Your options are:
1. Try using python-experimental. and peg it to a specific version of openapi-generator. Then you will not get breaking changes unless you rev-roll.
2. Submit a PR fixing this feature in the python generator
3. Submit a PR adding deepObject serialization to python-experimental
4. Modify your client/server to send this data in the request body rather than a parameter

**Comment by nloding** [comment]
@spacether this is the parameter definition:
```
          {
            "name": "metadata",
            "in": "query",
            "schema": {
              "type": "object",
              "additionalProperties": {
                "type": "string",
                "nullable": true
              }
            },
            "style": "deepObject",
            "expand": true
          },
```

This seems to work in other generators, only python appears broken. I haven't looked at how this code is generated at all, but I'll look to see what I can find in the generator to fix it!
