### ISSUE TITLE
[BUG][angular-typescript] can't generate client, throws java.nio.file.NoSuchFileException

### ISSUE THREAD

**Issue by marcellkiss** [OpenAPITools/openapi-generator#12191]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

I'm trying to generate an angular client with typescript-angular, and I'm getting the following error:
```
➜  ng-openapi-gen-test git:(main) ✗ npm run openapi-generator

> ng-openapi-gen-test@1.0.0 openapi-generator
> openapi-generator-cli generate -i openapi.yaml -g typescript-angular -o /output-openapi-generator

[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - Output directory (/output-openapi-generator) does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: typescript-angular (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'typescript-angular' is considered stable.
[main] INFO  o.o.c.l.AbstractTypeScriptClientCodegen - Hint: Environment variable 'TS_POST_PROCESS_FILE' (optional) not defined. E.g. to format the source code, please try 'export TS_POST_PROCESS_FILE="/usr/local/bin/prettier --write"' (Linux/Mac)
[main] INFO  o.o.c.l.AbstractTypeScriptClientCodegen - Note: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.c.l.TypeScriptAngularClientCodegen - generating code for Angular 13.0.1 ...
[main] INFO  o.o.c.l.TypeScriptAngularClientCodegen -   (you can select the angular version by setting the additionalProperty ngVersion)
[main] INFO  o.o.codegen.TemplateManager - writing file /output-openapi-generator/model/./post.ts
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'Post'
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:532)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:888)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.nio.file.NoSuchFileException: /output-openapi-generator/model/./post.ts
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
        at java.nio.file.Files.newOutputStream(Files.java:216)
        at java.nio.file.Files.write(Files.java:3292)
        at org.openapitools.codegen.TemplateManager.writeToFileRaw(TemplateManager.java:255)
        at org.openapitools.codegen.TemplateManager.writeToFile(TemplateManager.java:237)
        at org.openapitools.codegen.TemplateManager.writeToFile(TemplateManager.java:198)
        at org.openapitools.codegen.TemplateManager.write(TemplateManager.java:164)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1034)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1021)
        at org.openapitools.codegen.DefaultGenerator.generateModel(DefaultGenerator.java:388)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:523)
        ... 4 more
```

##### openapi-generator version

`^2.4.26`

##### OpenAPI declaration file content or url

[Link](https://github.com/marcellkiss/ng-openapi-gen-debug/blob/main/openapi.yaml)

##### Generation Details

`openapi-generator-cli generate -i openapi.yaml -g typescript-angular -o /output-openapi-generator`

##### Steps to reproduce

Clone this repo and run `npm run openapi-generator`
https://github.com/marcellkiss/ng-openapi-gen-debug

##### Related issues/PRs

-

##### Suggest a fix

No idea, I tried it with two different openapi files (openapi.json and openapi.yaml in the repo) and both lead to the same result.

**Comment by glebmachine** [comment]
same

**Comment by NikitaIT** [comment]
Same error. It works for my project:
```diff
openapi-generator-cli generate -i 
- openapi.yaml 
+ ./openapi.yaml 
-g typescript-angular -o 
- /output-openapi-generator
+ ./output-openapi-generator
```

**Comment by bnheise** [comment]
Same issue with the rust client generator.

**Comment by thejeff77** [comment]
Glad to see these issues are getting triaged and responded to. Same issue here.

**Comment by mluogh** [comment]
Hi folks, I think the issue is that the path you are providing starts with an /

> openapi-generator-cli generate -i openapi.yaml -g typescript-angular -o /output-openapi-generator

I believe if you change from `-o /output-openapi-generator` to `-o output-openapi-generator` and maybe try `mkdir output-openapi-generator` first, it should work.

At least it did for me.

**Comment by bas-kirill** [comment]
Same error with typescipr-axios, used a parameters from that video:  [YouTube: William Cheng, Using OpenAPI Generator With Docker](https://www.youtube.com/watch?v=9MuEP01h1XU), so everything works well 🙂

**Comment by bas-kirill** [comment]
Also pulling image can help: `docker pull openapitools/openapi-generator-cli:v7.8.0`
