### ISSUE TITLE
Query Parameters of type integer in format int64 seem to create a broken spring API

### ISSUE THREAD

**Issue by jbumueller** [OpenAPITools/openapi-generator#1226]
##### Description

Created a API Spec with a query parameter of type integer, with format int64 which results to Long in Java. Leads to a broken spring Api with thr following signature:

```
    default ResponseEntity<NotificationSummary> notifications(@ApiParam(value = "The maximum number of Records in the Result", defaultValue = "10l") @Valid @RequestParam(value = "maxResults", required = false, defaultValue="10l") Long maxResults) {
```

10l should be 10 instead, otherwise a numberFormatException occurs.

##### openapi-generator version

On the Master (3.3.0)

##### Command line used for generation

```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \ 
-i .../basicspec.yml  \
-l spring --library spring-mvc \ 
o .../
```

##### Steps to reproduce

- create a spec with the postet yaml
- run the posted command
- take a look to the generated code in org/openapitools/api/NotificationsApi.java

##### Suggest a fix/enhancement
Generate 
```
    default ResponseEntity<NotificationSummary> notifications(@ApiParam(value = "The maximum number of Records in the Result", defaultValue = "10") @Valid @RequestParam(value = "maxResults", required = false, defaultValue="10") Long maxResults) {
```

instead of

```
    default ResponseEntity<NotificationSummary> notifications(@ApiParam(value = "The maximum number of Records in the Result", defaultValue = "10l") @Valid @RequestParam(value = "maxResults", required = false, defaultValue="10l") Long maxResults) {
```

**Comment by wing328** [comment]
@jbumueller is it correct to say that the defaultValue must be a string? In other words, the following is still incorrect:
```
defaultValue =10l
```

**Comment by jbumueller** [comment]
Well the default value can be a String but it must be parsable for `parseInt`/`parseLong` that is if it contains only digits. Therefore 10l is still wrong but 10 would be correct as it can be parsed by `Long.parseLong(10)`.

**Comment by stephanpelikan** [comment]
I experienced the same behaviour and viewing my API in swagger-ui gives my this exception:

`2018-12-06 12:01:13.339  WARN 12096 --- [nio-8400-exec-2] i.s.m.p.AbstractSerializableParameter    : Illegal DefaultValue -1l for parameter type integer

java.lang.NumberFormatException: For input string: "-1l"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at io.swagger.models.parameters.AbstractSerializableParameter.getDefault(AbstractSerializableParameter.java:322)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:687)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:718)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:639)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3905)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3219)
	at springfox.documentation.spring.web.json.JsonSerializer.toJson(JsonSerializer.java:38)
	at springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(Swagger2Controller.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)`

I asked myself why the are any suffixes defined at

https://github.com/OpenAPITools/openapi-generator/blob/92d60b684a7270cb36f25c111ddc82b68b5b2307/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L779-L796

I do not see in https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md whether this is required (and specified).

Can we remove those suffixes safely? Or (in my case) should be swagger adopted to be able to parse default values using those suffixes?

**Comment by jan-berger** [comment]
Is there any workaround for this issue?
