### ISSUE TITLE
[REQ] Feature Request Description

### ISSUE THREAD

**Issue by ehartford** [OpenAPITools/openapi-generator#12415]
### Is your feature request related to a problem? Please describe.

Please print line numbers when there is an error 

## Describe the solution you'd like

I am trying to generate nestjs from swagger, using this command:

    openapi-generator-cli generate -i clean_oapi.json -g typescript-nestjs -o ../gen/

and I get an error like this:
    
    -attribute paths.For path parameter id the required value should be true

I would like to know the line number of the swagger where the error is located, so i can fix it.

## Describe alternatives you've considered

the best way is to have the line number

**Comment by oravecz** [comment]
Seems like a big oversight if true. My error is somewhere in several files and 1000's of lines

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 1
Errors: 
        -attribute components.schemas.AuthenticationFailed.required is not of type `array`
Warnings: 
        -attribute components.schemas.AuthenticationFailed.required is not of type `array`

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:604)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:631)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:457)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

Looks like I'm going to start deleting large swaths to narrow in on it

**Comment by Jaygee-jargon** [comment]
seriously? this isn't being treated as important?

**Comment by npajkovsky** [comment]
This is mega lol.

How can I find what causes this without line numbers?
```
        - The 'type' attribute must be one of 'null', 'boolean', 'object', 'array', 'number',
          'string', or 'integer'.
```
