### ISSUE TITLE
[BUG][csharp][aspnetcore] Generator fails with exception when using 6.0.0 instead of 5.4.0

### ISSUE THREAD

**Issue by mparge** [OpenAPITools/openapi-generator#12527]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output? 
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Generation code from a yaml spec (see example yaml) fails when using generator 6.0.0 instead of 5.4.0 with this output:

Exception: Cannot read field "dataType" because "p.items" is null
        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1167)
        at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1058)
        at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:553)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:895)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:449)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException: Cannot read field "dataType" because "p.items" is null
        at org.openapitools.codegen.languages.AbstractCSharpCodegen.setParameterExampleValue(AbstractCSharpCodegen.java:1414)
        at org.openapitools.codegen.DefaultCodegen.setParameterExampleValue(DefaultCodegen.java:1901)
        at org.openapitools.codegen.DefaultCodegen.finishUpdatingParameter(DefaultCodegen.java:4528)
        at org.openapitools.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:4847)
        at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:4162)
        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1135)

##### openapi-generator version

Works with 5.4.0
Fails with 6.0.0

##### OpenAPI declaration file content or url

```yaml
openapi: "3.0.0"
info:
  version: 0.1.0
  title:  API
servers:
  - url: http://api/
paths:
  /FunctionControl/ChannelEnable:
    get:
      operationId: GetChannelEnable
      tags: 
        - configuration
      parameters:
        - name: data
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/ChannelEnable"        
      responses:
        '200':
          description: description
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ChannelEnable"
 
components:
  schemas:
    ChannelEnable:
      type: object
      properties:
        Index:
          type: integer
          format: int32
          minimum: 1
          maximum: 5
        Channel:
          type: integer
          format: int32
          minimum: 1
          maximum: 4
        Status:
          type: boolean
```

##### Steps to reproduce

Take the yaml spec and try to generate, 5.4.0 will succeed, 6.0.0 will fail with an exception

java -jar "..\generator\openapi-generator-cli-5.4.0.jar" generate -g aspnetcore  -i .\..\api\api.yml  -o ..\api\generated\aspnetcore 
java -jar "..\generator\openapi-generator-cli-6.0.0.jar" generate -g aspnetcore  -i .\..\api\api.yml  -o ..\api\generated\aspnetcore 

##### Suggest a fix

https://github.com/OpenAPITools/openapi-generator/pull/11355 might have introduces the bug,

**Comment by wing328** [comment]
@mparge thanks for reporting the issue, which has been fixed by #12538
