### ISSUE TITLE
[BUG] Type cast error of string to int using the dart-dio generator

### ISSUE THREAD

**Issue by TobiasHintiLotzApp** [OpenAPITools/openapi-generator#12570]
#### I've searched alot to find a solution to this error but haven't found something which could help me.

I'm getting the following error when the generated code is trying to parse my ID attribute from string to int:

```
Exception has occurred.
DioError (DioError [DioErrorType.other]: Deserializing '[{ID: 10, artikel: 2, name: artikeltttttttttttttttttttttttt adsfasdfasdf asdf...' to 'BuiltList<Stock>' failed due to: Deserializing '[ID, 10, artikel, 2, name, artikeltttttttttttttttttttttttt adsfasdfasdf asdfa...' to 'Stock' failed due to: Deserializing '10' to 'int' failed due to: type 'String' is not a subtype of type 'int' in type cast
#0      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:178:11)
#1      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:124:18)
#2      StockApi.findStocks (package:openapi/src/api/stock_api.dart:157:36)
<asynchronous suspension>
#3      StockRepository.fetchStocks (package:demo_stocks/repo/stock_repository.dart:18:9)
<asynchronous suspension>
#4      new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:247:17)
<asynchronous suspension>

Source stack:
#0      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:178:11)
#1      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:124:18)
#2      StockApi.findStocks (package:openapi/src/api/stock_api.dart:157:36)
<asynchronous suspension>
#3      StockRepository.fetchStocks (package:demo_stocks/repo/stock_repository.dart:18:9)
<asynchronous suspension>
#4      new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:247:17)
<asynchronous suspension>
)
```

#### Yaml file I use for creating my openapi:

```
swagger: "2.0"
info:
  description: "LotzApp V1"
  version: "1.0.0"
  title: "LotzApp V1"
  contact:
    email: "office@lotzapp.org"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "www.lotzapp.org"
basePath: "/api"
tags:
- name: "stock"
  description: "Everything about stocks"
- name: "client"
  description: "Everything about clients"
schemes:
- "https"
paths:
  /{clientId}/we:
    post:
      tags:
      - "stock"
      summary: "Add a new stock to the LotzApp system"
      description: ""
      operationId: "addStock"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "clientId"
        type: "integer"
        required: true
        description: Numeric ID of the assingned client
      - in: "body"
        name: "body"
        description: "Stock object that needs to be added to the LotzApp system"
        required: true
        schema:
          $ref: "#/definitions/Stock"
      responses:
        "200":
          description: "OK"
        "401":
          description: "Not authorized to add a new stock"
        "403":
          description: "No permission to access data of this client"
      security:
        - basicAuth: []
    get:
      tags:
      - "stock"
      summary: "Finds stocks"
      description: ""
      operationId: "findStocks"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "clientId"
        type: "integer"
        required: true
        description: Numeric ID of the assingned client
      - name: "typ"
        in: "query"
        description: "Type value that needs to be considered for filter"
        required: false
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Stock"
        "401":
          description: "Not authorized to load stocks"
        "403":
          description: "No permission to access data of this client"
      security:
        - basicAuth: []
securityDefinitions:
  basicAuth:
    type: basic
definitions:
  Stock:
    type: "object"
    properties:
      ID:
        type: "integer"
        format: "int64"
      artikel:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      menge:
        type: "number"
        format: "double"
      typ:
        type: "integer"
        format: "int64"
      tabID:
        type: "integer"
        format: "int64"
      lager:
        type: "integer"
        format: "int64"
      createtime:
        type: "string"
        format: "date-time"
    required:
      - "artikel"
      - "menge"
      - "typ"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
```

### What I use for generating:

jar file: openapi-generator-cli-5.3.0.jar

command for generating the openapi: 
`java -jar ..\openapi-generator-cli-5.3.0.jar generate -g dart-dio-next -i ..\swagger_stock.yaml -o ./stocks_api`

After I open the generated folder in vscode I use the two following commands to get rid of all errors:

`flutter pub get`

`flutter pub run build_runner build`

### Question
Because this error is happening in the generated code I just want to know if I used the wrong steps to generate the openapi or if it's really a bug in the generator.

**Thanks in advance for providing any clues for fixing my error!**

**Comment by Nukesor** [comment]
It seems like you're using version 5.3.0

Didi you try using the new v6.0 version? There have been quite a few new versions out since then.

**Comment by TobiasHintiLotzApp** [comment]
Thanks for the answer. I've just tried it with the v6.0 generator and I get the same error. Do you have a working example you could share with me?

**Comment by TobiasHintiLotzApp** [comment]
The error was caused be the json response which only consisted of string values. The reason I didn't think about that was because I assumed it wouldn't matter for the parser. Can somebody confirm that my json was the cause of the error?

**Comment by Nukesor** [comment]
Your stacktrace indeed mirrors the behavior you have described.
Your JSON seem to contain a string when a `int` is expected.

In case your bug is fixed, please close the issue :)
