### ISSUE TITLE
 openapi-generator-cli attempting to parse json as yaml

### ISSUE THREAD

**Issue by yringler** [OpenAPITools/openapi-generator#1266]
##### Description
The cli is parsing JSON as yaml, and of course failing.

##### openapi-generator version
3.3.1

##### OpenAPI declaration file content or url
https://gist.github.com/yringler/700aaa11f4155ddc6644a43ca6ca5de1

##### Command line used for generation

java -jar openapi-generator-cli-3.3.1.jar generate -i "virtual-path.openapi.json" -g cwiki

Java version:
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
##### Steps to reproduce

Run the command?
The bug occured two days ago, it worked yesterday, and today it doesn't work again...
This might be a [heisenbug](https://en.wikipedia.org/wiki/Heisenbug)

**Comment by wing328** [comment]
@yringler what about using the URL instead of opening a local file? e.g.
```
java -jar "./modules/openapi-generator-cli/target/openapi-generator-cli.jar" generate -i https://gist.githubusercontent.com/yringler/700aaa11f4155ddc6644a43ca6ca5de1/raw/e596fd74261ee6f2c01143b8f8f6a470be8e8985/virtual-path.openapi.json  -g go -o /tmp/go
```
That works for me without error.

**Comment by yringler** [comment]
Strange.
When I use the gist, it works , and when I use my local file, it throws a yaml error (that tabs are invalid).
Can you confirm that it works for you using a local file, using a command such as I posted previously?
( I also tried specifying the full local path, but that didn't work either.)

**Comment by dkvollmar** [comment]
I can reproduce this locally with a json spec. This succeeds: 

java -jar $OAG_HOME/modules/openapi-generator-cli/target/openapi-generator-cli.jar validate -i <local path to my json spec>

while this fails:
java -jar $OAG_HOME/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
   -i <local path to my json spec>
   -g html2 \
   -o <local path to my output dir>

since it appears to be assuming to read YML:
[main] WARN  io.swagger.v3.parser.OpenAPIV3Parser - Exception while reading:
org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 1, column 3:
      "openapi": "3.0.0",
      ^
expected <block end>, but found FlowEntry
 in 'string', line 1, column 21:
      "openapi": "3.0.0",
                        ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)

**Comment by dkvollmar** [comment]
I figured out that my problem was that a referenced file was missing the starting "{".
I guess the error message should be better.
