### ISSUE TITLE
NullPointerException with command line interface and command help

### ISSUE THREAD

**Issue by ndjensen** [OpenAPITools/openapi-generator#1278]
##### Description
If you run the command line generator with one option of help, it throws a NullPointerException when it can't find the second option.
`java -jar openapi-generator-cli.jar help`
Ideally it would return a list of options that help will work with, such as generate.  (I have no idea what other options you can provide the help command, hence a list would be nice).

```java
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Objects.firstNonNull(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
	at io.airlift.airline.GlobalUsageSummary$2.apply(GlobalUsageSummary.java:100)
	at io.airlift.airline.GlobalUsageSummary$2.apply(GlobalUsageSummary.java:97)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:785)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at io.airlift.airline.UsagePrinter.appendTable(UsagePrinter.java:57)
	at io.airlift.airline.GlobalUsageSummary.usage(GlobalUsageSummary.java:96)
	at io.airlift.airline.GlobalUsageSummary.usage(GlobalUsageSummary.java:52)
	at io.airlift.airline.Help.help(Help.java:57)
	at io.airlift.airline.Help.help(Help.java:50)
	at io.airlift.airline.Help.run(Help.java:25)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:62)
```

##### openapi-generator version
3.3.1

##### OpenAPI declaration file content or url
N/A

##### Command line used for generation
`java -jar openapi-generator-cli.jar help`

##### Steps to reproduce
Run `java -jar openapi-generator-cli.jar help` in a terminal.

##### Related issues/PRs
Couldn't find one.

##### Suggest a fix/enhancement
See exception stacktrace.  If `help` is the first argument, verify there is a second argument, otherwise return a list of commands help works with.

**Comment by ackintosh** [comment]
Thanks for reporting the issue! I'm working on this.

**Comment by wing328** [comment]
Thanks for the quick fix by @ackintosh 

@ndjensen please give it another try using SNAPSHOT version or docker images and let us know if you still encounter the issue.

**Comment by ndjensen** [comment]
Tested and confirmed it's fixed.
