### ISSUE TITLE
[BUG][JAVA]  Error On Template getting

### ISSUE THREAD

**Issue by pindaroli** [OpenAPITools/openapi-generator#13042]
executing in a command line

>  openapi-generator-cli author template -g jaxrs-spec 

I obtain the following error: 
Exception in thread "main" java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at org.openapitools.codegen.cmd.AuthorTemplate.execute(AuthorTemplate.java:54)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

WINDOWS 10: Oracle jdk 1.8

the error is common in npm cli both jar version

**Comment by pindaroli** [comment]
CLI and jar version 6.0.1
