### ISSUE TITLE
[BUG] python-experimental stackOverflow when using self-referencing data structures like GeoJson

### ISSUE THREAD

**Issue by fbl100** [OpenAPITools/openapi-generator#13043]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Issue 8052 fixed a bug with example values for models with circular references.  The test case provided was a minimal representation of GeoJSON.  While it is unclear what has changed, a full representation of the GeoJson Specification now causes an infinite recursion in python-experimental.  The full GeoJson Specification "works" in the legacy generator, in that it doesn't get into an infinite loop. 

##### openapi-generator version
6.0.1+

##### OpenAPI declaration file content or url

The GeoJsonGeometry used in the prior test was not exactly right and may have masked the true nature of this bug.  This spec is not the full GeoJson, but it is sufficient to cause the bug.  Essentially a GeoJsonGeometry is either a Point, or a GeometryCollection, and a GeometryCollection can have more GeoJsonGeometry objects.  The full spec includes lines, polygons, and a few more types, but this is the minimal subset that causes the issue.
```yaml
openapi: 3.0.0
info:
  version: 01.01.00
  title: APITest API documentation.
  termsOfService: http://api.apitest.com/party/tos/
servers:
  - url: https://api.apitest.com/v1
paths:
  /geojson:
    post:
      summary: Add a GeoJson Object
      operationId: post-geojson
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
                description: GeoJson ID
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeoJsonGeometry'
      parameters: []
components:
  schemas:
    GeoJsonGeometry:
      title: GeoJsonGeometry
      description: GeoJSON geometry
      oneOf:
        - $ref: '#/components/schemas/Point'
        - $ref: '#/components/schemas/GeometryCollection'
      discriminator:
        propertyName: type
        mapping:
          Point: '#/components/schemas/Point'
          GeometryCollection: '#/components/schemas/GeometryCollection'
      externalDocs:
        url: http://geojson.org/geojson-spec.html#geometry-objects
    Point:
      title: Point
      type: object
      description: GeoJSON geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id2
      properties:
        coordinates:
          title: Point3D
          type: array
          description: Point in 3D space
          externalDocs:
            url: http://geojson.org/geojson-spec.html#id2
          minItems: 2
          maxItems: 3
          items:
            type: number
            format: double
        type:
          type: string
          default: Point
      required:
        - type
    GeometryCollection:
      title: GeometryCollection
      type: object
      description: GeoJSon geometry collection
      required:
        - type
        - geometries
      externalDocs:
        url: http://geojson.org/geojson-spec.html#geometrycollection
      properties:
        type:
          type: string
          default: GeometryCollection
        geometries:
          type: array
          items:
            $ref: '#/components/schemas/GeoJsonGeometry'

```

##### Steps to reproduce

This test (if placed into PythonExperimentalClientTest) will recreate the bug.  Note that in my testing environment, I added the GeoJson spec (above) to the prior yaml.

```java
    @Test(description = "tests RecursiveToExample")
    public void testRecursiveToExample() throws IOException {
        final OpenAPI openAPI = TestUtils.parseFlattenSpec("src/test/resources/3_0/issue_8052_recursive_model.yaml");
        final PythonExperimentalClientCodegen codegen = new PythonExperimentalClientCodegen();
        codegen.setOpenAPI(openAPI);

        final Operation operation = openAPI.getPaths().get("/geojson").getPost();
        Schema schema = ModelUtils.getSchemaFromRequestBody(operation.getRequestBody());
        String exampleValue = codegen.toExampleValue(schema, null);

        // you never get here

    }
```

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/8052

##### Suggest a fix

I would be happy to attempt to fix it, but I could use a little guidance from @spacether.  It looks like the new generator is attempting to detect cycles, and it's unclear what about the full GeoJson specification is causing the issue.  Hopefully the provided yaml and test case will shed some light on this.

**Comment by spacether** [comment]
Do you have your intelij set up so you can debug the generator? What is the stack trace? Want to sync up this week?

**Comment by fbl100** [comment]
I’ll get you the stack trace today.  Happy to connect anytime.  What time zone are you in?  I’m US/East Coast.

-Frank
(sent via my iPhone, so pardon any spelling errors)

**Comment by fbl100** [comment]
This is the output from the test case I posted.  I'm on commit 79c5091de49

```
java.lang.StackOverflowError
	at java.base/java.util.ArrayList.hashCode(ArrayList.java:582)
	at java.base/java.util.Collections$UnmodifiableList.hashCode(Collections.java:1319)
	at java.base/java.util.Arrays.hashCode(Arrays.java:4498)
	at java.base/java.util.Objects.hash(Objects.java:133)
	at org.openapitools.codegen.DefaultCodegen$SanitizeNameOptions.hashCode(DefaultCodegen.java:7450)
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2344)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at org.openapitools.codegen.DefaultCodegen.sanitizeName(DefaultCodegen.java:5938)
	at org.openapitools.codegen.DefaultCodegen.sanitizeName(DefaultCodegen.java:5907)
	at org.openapitools.codegen.DefaultCodegen.sanitizeName(DefaultCodegen.java:5886)
	at org.openapitools.codegen.languages.AbstractPythonCodegen.toVarName(AbstractPythonCodegen.java:187)
	at org.openapitools.codegen.DefaultCodegen.createDiscriminator(DefaultCodegen.java:3313)
	at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.toExampleValueRecursive(PythonExperimentalClientCodegen.java:1594)
	at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.toExampleValueRecursive(PythonExperimentalClientCodegen.java:1582)
	at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.toExampleValueRecursive(PythonExperimentalClientCodegen.java:1764)
	at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.exampleForObjectModel(PythonExperimentalClientCodegen.java:1881)
	at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.toExampleValueRecursive(PythonExperimentalClientCodegen.java:1641)
	at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.toExampleValueRecursive(PythonExperimentalClientCodegen.java:1582)
	at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.toExampleValueRecursive(PythonExperimentalClientCodegen.java:1764)
	at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.exampleForObjectModel(PythonExperimentalClientCodegen.java:1881)
	at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.toExampleValueRecursive(PythonExperimentalClientCodegen.java:1641)
	at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.toExampleValueRecursive(PythonExperimentalClientCodegen.java:1582)
	at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.toExampleValueRecursive(PythonExperimentalClientCodegen.java:1764)
	at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.exampleForObjectModel(PythonExperimentalClientCodegen.java:1881)
	at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.toExampleValueRecursive(PythonExperimentalClientCodegen.java:1641)
	at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.toExampleValueRecursive(PythonExperimentalClientCodegen.java:1582)
	at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.toExampleValueRecursive(PythonExperimentalClientCodegen.java:1764)
	at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.exampleForObjectModel(PythonExperimentalClientCodegen.java:1881)
```

**Comment by spacether** [comment]
So it is infinitely looping in the Java layer when trying to generate an example value.

**Comment by fbl100** [comment]
Correct.  Sorry, should have put that part into the ticket.  Linked issue was all about the example too.

-Frank
(sent via my iPhone, so pardon any spelling errors)

**Comment by spacether** [comment]
Related PR: https://github.com/OpenAPITools/openapi-generator/pull/13109
