### ISSUE TITLE
Generated Node Express Server Wont Handle mutlipart/form-data 

### ISSUE THREAD

**Issue by davesargrad** [OpenAPITools/openapi-generator#13523]
Though I've used the generator for several API's this is the first time I've tried adding a route to support file upload. 

I've effectively followed this documented process:
https://swagger.io/docs/specification/describing-request-body/file-upload/

However I have tried several variants, none of which have worked.

The path:
```
"/upload_video":{
      "post": {
        "description": "Upload a video or series of videos ",
        "operationId": "uploadFiles",
        "requestBody": {
          "description": "Videos to upload",
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/UploadVideo"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "successful operation",
            "content": { }
          },
          "400": {
            "description": "Invalid bucket",
            "content": {}
          },
          "403": {
            "description": "Forbidden directory is not writeable or file exists but not overwritten ",
            "content": {}
          }
        },
        "deprecated": false,
        "security": [
          {
            "api_key": []
          }
        ],
        "summary": "Upload video to provided video_category.",
        "tags": [ "video_category" ]
      }
    },    
```

I've tried with a schema using a reference (as shown above) and also inline (rather than use a reference).

I've generated both a node express service stub using:

`npx ./node_modules/.bin/openapi-generator-cli generate -i InterfaceSpecification.json  -g nodejs-express-server -o test_srvr_stubs`

and a javascript client:
`npx ./node_modules/.bin/openapi-generator-cli generate -i InterfaceSpecification.json  -g javascript -o test_lib_javascript`

The client library is used in a react application, and it can generate the request to the service..

However the service returns a 500 code.
![image](https://user-images.githubusercontent.com/48793689/192281514-0e5f02c4-1cb5-481f-9162-bb081f5af79f.png)
 I've dug into the service and found where it is crashing.

The error can be seen in the following print of the error:
```
ddd TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Function.collectRequestParams (/home/dsargrad/dev/vm_api_svc/srvr/controllers/Controller.js:86:16)
    at Function.handleRequest (/home/dsargrad/dev/vm_api_svc/srvr/controllers/Controller.js:114:59)
    at uploadFiles (/home/dsargrad/dev/vm_api_svc/srvr/controllers/VideoCategoryController.js:25:20)
    at Layer.handle [as handle_request] (/home/dsargrad/dev/vm_api_svc/srvr/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dsargrad/dev/vm_api_svc/srvr/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/dsargrad/dev/vm_api_svc/srvr/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/dsargrad/dev/vm_api_svc/srvr/node_modules/express/lib/router/layer.js:95:5)
    at /home/dsargrad/dev/vm_api_svc/srvr/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/dsargrad/dev/vm_api_svc/srvr/node_modules/express/lib/router/index.js:346:12)

```

The generated code includes controllers/Controller.js

That file includes the following static method:
```
static collectRequestParams(request) {
    const requestParams = {};
    if (request.openapi.schema.requestBody !== undefined) {
      const { content } = request.openapi.schema.requestBody;
      if (content['application/json'] !== undefined) {
        const requestBodyName = camelCase(this.getRequestBodyName(request));
        requestParams[requestBodyName] = request.body;
      } else if (content['multipart/form-data'] !== undefined) {
        Object.keys(content['multipart/form-data'].schema.properties).forEach(
          (property) => {
            const propertyObject = content['multipart/form-data'].schema.properties[property];
            if (propertyObject.format !== undefined && propertyObject.format === 'binary') {
              requestParams[property] = this.collectFile(request, property);
            } else {
              requestParams[property] = request.body[property];
            }
          },
        );
      }
    }

    request.openapi.schema.parameters.forEach((param) => {
      if (param.in === 'path') {
        requestParams[param.name] = request.openapi.pathParams[param.name];
      } else if (param.in === 'query') {
        requestParams[param.name] = request.query[param.name];
      } else if (param.in === 'header') {
        requestParams[param.name] = request.headers[param.name];
      }
    });
    return requestParams;
  }

```
Notice that in the else if for multipart/form-data, it performs a forEach on 
`Object.keys(content['multipart/form-data'].schema.properties).forEach(`

However the referenced "schema.properties" is undefined:
![image](https://user-images.githubusercontent.com/48793689/192282218-25b97bc7-4c51-4fde-9512-c8e4e7713c28.png)

The schema includes a reference to the model:
![image](https://user-images.githubusercontent.com/48793689/192282545-9eebe75a-8485-4854-b31d-752f6907db2e.png)

This is true even if the initial model parameters was included inline (the generator generates openapi.yaml, and automatically creates a model and then references it).

I've struggled with this for a day, and would appreciate guidance.

**Comment by davesargrad** [comment]
The essence of the problem is that the npx generated service creates a file (openapi.yaml) that uses a reference $ref. The generated service code does not deal properly with this reference.

**Comment by davesargrad** [comment]
This seems like it is truly a bug in the generated node express service code. Anyone able to pick this issue up?
