### ISSUE TITLE
[BUG] dart-dio generator has basic deserialization issues

### ISSUE THREAD

**Issue by ffpetrovic** [OpenAPITools/openapi-generator#13568]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

As far as I can tell, the description of the `/users/latest` endpoint 200 response is correct, it's just the `User` model... and the generator can't deserialize it because it's basically trying to cast a `Map` into an `Iterable`

`DioError [DioErrorType.other]: Deserializing '{id: ba2be130-dece-4a5c-ac94-771fe70f9f7e, firstName: test, lastName: test, i...' to 'User' failed due to: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Iterable<Object?>' in type cast
#0      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:178:11)
#1      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:124:18)`

##### openapi-generator version

6.2.0

##### OpenAPI declaration file content or url

```
{"openapi":"3.0.0","paths":{"/users/latest":{"get":{"operationId":"UserController_getLatestUser","summary":"","description":"","parameters":[],"responses":{"200":{"description":"","content":{"application/json":{"schema":{"$ref":"#/components/schemas/User"}}}}},"tags":["Users"],"security":[{"bearer":[]}]}},"/users":{"post":{"operationId":"UserController_createUser","summary":"","description":"","parameters":[],"responses":{"201":{"description":""}},"tags":["Users"],"security":[{"bearer":[]}]}}},"info":{"title":"api","description":"","version":"0.0.1","contact":{}},"tags":[],"servers":[],"components":{"schemas":{"User":{"type":"object","properties":{"id":{"type":"string"},"firstName":{"type":"string"},"lastName":{"type":"string"},"isActive":{"type":"boolean"}},"required":["id","firstName","lastName","isActive"]}}}}
```

##### Steps to reproduce

openapi-generator generate -g dart-dio -i http://localhost:3000/swagger-ui-json -o generated

**Comment by caniko** [comment]
We have the same [issue](https://github.com/OpenAPITools/openapi-generator/issues/13818)
