### ISSUE TITLE
[BUG] [Spring] Upgrading api generator from 4.3.1 to 6.1.0 fails to parse "tags" descriptions

### ISSUE THREAD

**Issue by ymasha** [OpenAPITools/openapi-generator#13579]
##### Description

After upgrading  API generator from 4.3.1 to 6.1.0 fails to parse "tags" long tags descriptions.

##### openapi-generator version

6.1.0

##### OpenAPI declaration file content or url

```
tags:
  - name: pets
    description: |
     # Everything about your Pets
        Some very long description 
```

##### Steps to reproduce

run the spring build, there will be an compilation error

```
Error snake-parsing yaml content 
at io.swagger.v3.parser.util.DeseralizationUtils$CustomSnakeYamlConstructor.getSinglrData(DeseralizationUtils.java:417)
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491)
```

**Comment by DeaneOC** [comment]
I was unable to recreate the issue, could you add more details of your configuration perhaps?

**Comment by Karbust** [comment]
I'm also getting the same error with Cloudflare's OpenAPI schema: https://github.com/cloudflare/api-schemas. With JSON I can get a bit farther but still doesn't finish without errors...

I tried multiple typescript (I want typescript-axios) all have the same issue, I also tried java (the one mentioned on the blog post of CF https://blog.cloudflare.com/open-api-transition/ ), same issue.
