### ISSUE TITLE
[BUG][Elm] Generation crashes with Exception: 

### ISSUE THREAD

**Issue by Erudition** [OpenAPITools/openapi-generator#13571]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue? 
- > Using the full [Stripe API spec](https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json).
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))? 
- >I used the CLI with `validate` and it found no issues.
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists? 
- > Not yet, but I see no related changes to the Elm generator since 6.2.0 (the current latest release)
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

The elm generator produces partial output and broken code before failing with this error:

```
  Exception: Property type is missing from getVars
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1187)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1078)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:580)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:915)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:465)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.RuntimeException: Property type is missing from getVars
	at org.openapitools.codegen.DefaultCodegen.addRequiredVarsMap(DefaultCodegen.java:7319)
	at org.openapitools.codegen.DefaultCodegen.addVarsRequiredVarsAdditionalProps(DefaultCodegen.java:7354)
	at org.openapitools.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:4972)
	at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:4394)
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1155)
	... 6 more
```

##### openapi-generator version

6.2.0 (latest via npm)

##### OpenAPI declaration file content or url
https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json

##### Steps to reproduce

1. `generate -i "https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json" -g elm -o elmStripeAPI`

**Comment by cyangle** [comment]
I got the same error when generating crystal client for stripe api.
It seems like 2 get operations are interfering each other with required params.

Here's a minimal spec file that reproduces this error with latest master branch generating crystal client. The same spec works with v6.0.1.

It seems like this bug was introduced by #13117. @spacether

```yaml
openapi: 3.0.0
info:
  description: >-
    This spec is mainly for testing Petstore server and contains fake endpoints,
    models. Please do not use this for any other purpose. Special characters: "
    \
  version: 1.0.0
  title: OpenAPI Petstore
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: fake
paths:
  /fake:
    get:
      tags:
        - fake
      operationId: fake
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
          style: form
        - name: scope
          in: query
          required: true
          style: deepObject
          explode: true
          schema:
            $ref: "#/components/schemas/scope_param"
      responses:
        "200":
          description: The instance started successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties: string
  /fake2:
    get:
      tags:
        - fake
      operationId: fake2
      parameters:
        - name: scope
          in: query
          required: true
          style: deepObject
          explode: true
          schema:
            $ref: "#/components/schemas/scope_param"
      responses:
        "200":
          description: The instance started successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties: string
servers:
  - url: https://localhost:8080/{version}
    description: The local server
    variables:
      version:
        enum:
          - "v1"
          - "v2"
        default: "v2"
  - url: https://127.0.0.1/no_variable
    description: The local server without variables
components:
  schemas:
    scope_param:
      type: object
      title: scope_param
      properties:
        type:
          enum: ["account", "user"]
          type: "string"
        user:
          maxLength: 5000,
          type: "string"
      required: ["type"]

```

And the error I got is this:

```
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: class Tag {
    name: fake
    description: null
    externalDocs: null
}
  Operation: fake2
  Resource: get /fake2
  Schemas: {scope_param=class ObjectSchema {
    class Schema {
        type: object
        format: null
        $ref: null
        description: null
        title: scope_param
        multipleOf: null
        maximum: null
        exclusiveMaximum: null
        minimum: null
        exclusiveMinimum: null
        maxLength: null
        minLength: null
        pattern: null
        maxItems: null
        minItems: null
        uniqueItems: null
        maxProperties: null
        minProperties: null
        required: [type]
        not: null
        properties: {type=class StringSchema {
            class Schema {
                type: string
                format: null
                $ref: null
                description: null
                title: null
                multipleOf: null
                maximum: null
                exclusiveMaximum: null
                minimum: null
                exclusiveMinimum: null
                maxLength: null
                minLength: null
                pattern: null
                maxItems: null
                minItems: null
                uniqueItems: null
                maxProperties: null
                minProperties: null
                required: null
                not: null
                properties: null
                additionalProperties: null
                nullable: null
                readOnly: null
                writeOnly: null
                example: null
                externalDocs: null
                deprecated: null
                discriminator: null
                xml: null
            }
        }, user=class StringSchema {
            class Schema {
                type: string
                format: null
                $ref: null
                description: null
                title: null
                multipleOf: null
                maximum: null
                exclusiveMaximum: null
                minimum: null
                exclusiveMinimum: null
                maxLength: null
                minLength: null
                pattern: null
                maxItems: null
                minItems: null
                uniqueItems: null
                maxProperties: null
                minProperties: null
                required: null
                not: null
                properties: null
                additionalProperties: null
                nullable: null
                readOnly: null
                writeOnly: null
                example: null
                externalDocs: null
                deprecated: null
                discriminator: null
                xml: null
            }
        }}
        additionalProperties: null
        nullable: null
        readOnly: null
        writeOnly: null
        example: null
        externalDocs: null
        deprecated: null
        discriminator: null
        xml: null
    }
}}
  Exception: Property type is missing from getVars
        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1187)
        at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1078)
        at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:580)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:915)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:465)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.RuntimeException: Property type is missing from getVars
        at org.openapitools.codegen.DefaultCodegen.addRequiredVarsMap(DefaultCodegen.java:7319)
        at org.openapitools.codegen.DefaultCodegen.addVarsRequiredVarsAdditionalProps(DefaultCodegen.java:7354)
        at org.openapitools.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:4972)
        at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:4394)
        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1155)
        ... 6 more
```

**Comment by spacether** [comment]
Thank you for reporting this bug @Erudition and @cyangle
this is happening because DefaultCodegen is modifying the codegenProperty.baseName which isued used to store the schema property name.
This line: https://github.com/OpenAPITools/openapi-generator/blame/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L5080
is mutating the baseName so that the properties.vars have the names:
- scope[type]
- scope[user]
@wing328 why did you add that change in https://github.com/OpenAPITools/openapi-generator/pull/12369?
If the baseName is not modified, these specs will run as-is.

**Comment by cyangle** [comment]
The implementation in #8563 probably doesn't work with nested json objects.

I think a model flattener is better than the current implementation.

**Comment by Erudition** [comment]
Just tried @cyangle 's workaround, it builds now!
Alas, my generated code still has a thousand compile errors :(

**Comment by jawad-r3** [comment]
Guys, Is there any workaround to this? I need to generate some Apex clients for Stripe API.

**Comment by jawad-r3** [comment]
Even when I remove the basename change from Default Codegen, I am unable to generate any client code for Stripe API Docs. Its now error out at 'Map of form parameters not supported'

**Comment by Erudition** [comment]
> Guys, Is there any workaround to this? I need to generate some Apex clients for Stripe API.

See the messages before yours and you will see that yes, there is a workaround, and yes, I tried it and it works.

But alas, we're still a long way from a usable Stripe API it seems. The generated code doesn't compile, and it's not trivial to fix, due to many remaining bugs in the Elm generator. 

I fixed hundreds of errors and gave up - they just keep coming. Distinct items named exactly the same, lists not closed, parameters missing altogether because their type is unsupported... the generator may be good as-is for simple APIs, but the Stripe API is too complex and uses too many OpenAPI features that are still broken in the Elm generator...

**Comment by recryptoonline** [comment]
reproduced here as well
