### ISSUE TITLE
[BUG][JAVA] Implement adapter for java.time.LocalDateTime in client code

### ISSUE THREAD

**Issue by jo2** [OpenAPITools/openapi-generator#13889]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
In the Java generator there is no adapter for `java.time.LocalDateTime` parsing in the client code generator. Adapters for `OffsetDateTime` and `LocalDate` exist, though. When Receiving a LocalDateTime over the API, the generated client tries to parse an object like this: 
```json
{
    "year" : 2010,
    "month" : "JANUARY",
    "dayOfMonth" : 1,
    "dayOfWeek" : "FRIDAY",
    "dayOfYear" : 1,
    "monthValue" : 1,
    "hour" : 2,
    "minute" : 2,
    "second" : 0,
    "nano" : 0,
    "chronology" : {
      "id" : "ISO",
      "calendarType" : "iso8601"
}
```
Because it receives a ISO string in this format `2010-01-01T02:02:00` it can't be parsed so an IllegalArgumentException like this is thrown:
```
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $.letzteAenderung
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:163)
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:88)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:214)
	... 51 more
```

With a corresponding adapter for `LocalDateTime` parsing, I would expect to be able to parse a valid ISO_LOCAL_DATE_TIME string into a `LocalDateTime` object. 

##### openapi-generator version
6.2.1, but it seems to be the case in earlier versions, too

##### OpenAPI declaration file content or url

Minimized excerpt from pet store example:
```yml
openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: ''
  version: 0.0.1
tags:
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: store
    description: Access to Petstore orders
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
  - name: user
    description: Operations about user
paths:
  /store/order/{orderId}:
    get:
      tags:
        - store
      summary: Find purchase order by ID
      description: For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
      operationId: getOrderById
      parameters:
        - name: orderId
          in: path
          description: ID of order that needs to be fetched
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        petId:
          type: integer
          format: int64
          example: 198772
        quantity:
          type: integer
          format: int32
          example: 7
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          example: approved
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean
      xml:
        name: order

```

##### Generation Details

Maven plugin configuration:
```xml
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>6.2.1</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.basedir}/target/${project.artifactId}/openapi.yaml</inputSpec>
                <output>${project.build.directory}/generated-sources/openapi</output>
                <generatorName>java</generatorName>
                <groupId>${project.groupId}</groupId>
                <artifactId>${project.artifactId}</artifactId>
                <artifactVersion>${project.version}</artifactVersion>
                <additionalProperties>
                    serializableModel=true,dateLibrary=java8,java8=true,useTags=true,groupId=de.persona.dal,hideGenerationTimestamp=true
                </additionalProperties>
                <configOptions>
                    <sourceFolder>src/main/java</sourceFolder>
                </configOptions>
                <typeMappings>
                    <typeMapping>OffsetDateTime=LocalDateTime</typeMapping>
                </typeMappings>
                <importMappings>
                    <importMapping>java.time.OffsetDateTime=java.time.LocalDateTime</importMapping>
                </importMappings>
                <generateModelTests>false</generateModelTests>
                <generateApiTests>false</generateApiTests>
            </configuration>
        </execution>
    </executions>
</plugin>
```

##### Suggest a fix

A fix could be to add a parser in eihter [https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/JSON.mustache#L365](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/JSON.mustache#L365) or [https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/JSON.mustache#L365](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/JSON.mustache#L365):

```
    /**
     * Gson TypeAdapter for JSR310 LocalDateTime type
     */
    public static class LocalDateTimeTypeAdapter extends TypeAdapter<LocalDateTime> {
        private DateTimeFormatter formatter;
        public LocalDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE_TIME);
        }

        public LocalDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDateTime.parse(date, formatter);
            }
        }
    }
```

**Comment by jo2** [comment]
if you can tell me which of both files is the ccorect one, I can submit a PR fixing this.

**Comment by XvikX** [comment]
Hello I encounter this bug aswell.

**Comment by jo2** [comment]
This is a quick solution for some, but sadly I am running the job in a pipeline so I can't edit the files manually.

**Comment by GabOzbek** [comment]
Hi,

Is there any progress on this issue?

**Comment by dstango** [comment]
> This is a quick solution for some, but sadly I am running the job in a pipeline so I can't edit the files manually.

I encountered the same troubles, and managed to figure out a way that even works in a pipeline: adding the localDateTimeTypeAdapter in my code that uses the ApiClient:

```java
	private void configureGsonLocalDateTimeHandling(ApiClient client) {
		GsonBuilder gsonBuilder = client.getJSON().getGson().newBuilder();
		gsonBuilder.registerTypeAdapter(LocalDateTime.class, localDateTimeTypeAdapter);
		client.getJSON().setGson(gsonBuilder.create());
	}
```

this can be added to your client implementation and modifies the configuration of the gson-Object that manages the serialization. 

It's working fine for me with the default library okhttp-gson, I didn't test it with other libraries.

**Comment by shailers89** [comment]
Hey, i'm having  the same issue.  anyone has a good workaround this? 
i'm using Kotlin btw .

**Comment by havardthom** [comment]
> Hey, i'm having the same issue. anyone has a good workaround for this? i'm using Kotlin btw .

We were able to configure openapi-generator-maven-plugin to use `LocalDateTime` instead of `OffsetDatetime` for string date-time fields in openapi spec by adding the following typeMapping:

```
<typeMappings>
    <typeMapping>string+date-time=LocalDateTime</typeMapping>
</typeMappings>
```

This is with kotlin and openapi-generator-maven-plugin v7.2.0

**Comment by leccyril** [comment]
> > Hey, i'm having the same issue. anyone has a good workaround for this? i'm using Kotlin btw .
> 
> We were able to configure openapi-generator-maven-plugin to use `LocalDateTime` instead of `OffsetDatetime` for string date-time fields in openapi spec by adding the following typeMapping:
> 
> ```
> <typeMappings>
>     <typeMapping>string+date-time=LocalDateTime</typeMapping>
> </typeMappings>
> ```
> 
> This is with kotlin and openapi-generator-maven-plugin v7.2.0

hi, thank you , but you need then to import localDatetime instead of Joda how to do ? 
```

<importMappings>
								<importMapping>string+date-time=java.time.LocalDateTime</importMapping>
							</importMappings>
							<typeMappings>
								<typeMapping>string+date-time=LocalDateTime</typeMapping>
							</typeMappings>
```
i tried this but could not import java.time.LocalDateTime

**Comment by leccyril** [comment]
> > > Hey, i'm having the same issue. anyone has a good workaround for this? i'm using Kotlin btw .
> > 
> > 
> > We were able to configure openapi-generator-maven-plugin to use `LocalDateTime` instead of `OffsetDatetime` for string date-time fields in openapi spec by adding the following typeMapping:
> > ```
> > <typeMappings>
> >     <typeMapping>string+date-time=LocalDateTime</typeMapping>
> > </typeMappings>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is with kotlin and openapi-generator-maven-plugin v7.2.0
> 
> hi, thank you , but you need then to import localDatetime instead of Joda how to do ?
> 
> ```
> 
> <importMappings>
> 								<importMapping>string+date-time=java.time.LocalDateTime</importMapping>
> 							</importMappings>
> 							<typeMappings>
> 								<typeMapping>string+date-time=LocalDateTime</typeMapping>
> 							</typeMappings>
> ```
> 
> i tried this but could not import java.time.LocalDateTime

Finally i managed to dot it by setting this configuration in <executions> , not in <configOptions> 👍🏼 

```
<typeMappings>
								<typeMapping>OffsetDateTime=LocalDateTime</typeMapping>
							</typeMappings>
							<importMappings>
								<importMapping>java.time.OffsetDateTime=java.time.LocalDateTime</importMapping>
							</importMappings>
```
