### ISSUE TITLE
[BUG] [Python] Handling objects as dictionnaries not working in 6.2.1

### ISSUE THREAD

**Issue by OmarBouslama** [OpenAPITools/openapi-generator#13997]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

We have an Event model in OpenAPI that contains these fields:
```
    Event:
      type: object
      x-examples:
        example-1:
          name: watched_trailer
          occuredAt: '2013-07-16T19:20:30+1:00'
          properties: {}
      properties:
        name:
          type: string
        occuredAt:
          type: string
        properties:
          type: object
      required:
        - name
        - occuredAt
```

Using generator version 5.x.x, I was able to init the model this way in Python:
`event = Event(name="xxx", occuredAt="2020-06-01", properties={"prop1": "value1"})
`

However, using the 6.2.1 version
we have this stack trace now

nothing has changed except using a new open API generator version

```
  File "/usr/local/lib/python3.10/site-packages/crm_client/model/update_customer_v1_request.py", line 318, in __new__
    return super().__new__(
  File "/usr/local/lib/python3.10/site-packages/crm_client/schemas.py", line 2990, in __new__
    return super().__new__(cls, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/crm_client/schemas.py", line 621, in __new__
    return __new_cls._get_new_instance_without_conversion_oapg(
  File "/usr/local/lib/python3.10/site-packages/crm_client/schemas.py", line 490, in _get_new_instance_without_conversion_oapg
    properties = cls._get_properties_oapg(arg, path_to_item, path_to_schemas)
  File "/usr/local/lib/python3.10/site-packages/crm_client/schemas.py", line 2133, in _get_properties_oapg
    new_value = property_cls._get_new_instance_without_conversion_oapg(
  File "/usr/local/lib/python3.10/site-packages/crm_client/schemas.py", line 493, in _get_new_instance_without_conversion_oapg
    items = cls._get_items_oapg(arg, path_to_item, path_to_schemas)
  File "/usr/local/lib/python3.10/site-packages/crm_client/schemas.py", line 1822, in _get_items_oapg
    new_value = item_cls._get_new_instance_without_conversion_oapg(
  File "/usr/local/lib/python3.10/site-packages/crm_client/schemas.py", line 490, in _get_new_instance_without_conversion_oapg
    properties = cls._get_properties_oapg(arg, path_to_item, path_to_schemas)
  File "/usr/local/lib/python3.10/site-packages/crm_client/schemas.py", line 2133, in _get_properties_oapg
    new_value = property_cls._get_new_instance_without_conversion_oapg(
  File "/usr/local/lib/python3.10/site-packages/crm_client/schemas.py", line 490, in _get_new_instance_without_conversion_oapg
    properties = cls._get_properties_oapg(arg, path_to_item, path_to_schemas)
  File "/usr/local/lib/python3.10/site-packages/crm_client/schemas.py", line 2133, in _get_properties_oapg
    new_value = property_cls._get_new_instance_without_conversion_oapg(
AttributeError: type object 'DynamicSchema' has no attribute '_get_new_instance_without_conversion_oapg'
```

##### openapi-generator version

6.2.1

##### Steps to reproduce

Add a model with that contains an object, generate the code and try to init the model by passing a dictionary to the object property
`AnyModel(some_field="value", object_property={"toto": "tata"})

**Comment by spacether** [comment]
Hi there. I am unable to replicate your issue.
Here are the steps that I followed:
Using this spec:
```
openapi: 3.0.0
info:
  version: 1.0.0
  title: issue 13141 spec
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers: []
tags: []
paths: {}
components:
  schemas:
    Event:
      type: object
      x-examples:
        example-1:
          name: watched_trailer
          occuredAt: '2013-07-16T19:20:30+1:00'
          properties: {}
      properties:
        name:
          type: string
        occuredAt:
          type: string
        properties:
          type: object
      required:
        - name
        - occuredAt
```
I generated a 6.2.1 client:
`docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.2.1 generate -i /local/issue_13997.yaml -g python -o /local/python_out/`

Then I created a python 3 (3.7.12) virtual environment and installed the library into it.
Then I ran this sample successfuly
```
from openapi_client.model import event
inst = event.Event(name="xxx", occuredAt="2020-06-01", properties={"prop1": "value1"})
```
Then I successfully repeated the same steps with python 3.10.1
So unfortunately I can't replicate your issue.

Can you provide your detailed steps to demonstrate the problem?

**Comment by Linux13524** [comment]
Hi @spacether. I can reproduce the issue with the following spec:

```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: issue 13997 spec
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers: []
tags: []
paths: {}
components:
  schemas:
    EventRequest:
      type: object
      required:
        - event
      properties:
        event:
          $ref: '#/components/schemas/Event'
    Event:
      type: object
      properties:
        name:
          type: string
        occuredAt:
          type: string
        properties:
          type: object
```

I generated the client then similar how you did:

```
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.2.1 generate -i /local/openapi-test.yaml -g python -o /local/python_out/
```

Running the following does work:

```python
>>> from openapi_client.model.event import Event
>>> from openapi_client.model.event_request import EventRequest
EventRequest(event=Event(name="test", properties={}))
```

But running this does not:

```python
>>> from openapi_client.model.event import Event
>>> from openapi_client.model.event_request import EventRequest
>>> EventRequest(config=Event(name="test", properties={"name": "test"}))
```

Resulting in a similar error that @OmarBouslama reported:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/openapi/python_out/openapi_client/model/event_request.py", line 80, in __new__
    return super().__new__(
  File "/home/user/openapi/python_out/openapi_client/schemas.py", line 2439, in __new__
    return super().__new__(cls, *args, **kwargs)
  File "/home/user/openapi/python_out/openapi_client/schemas.py", line 532, in __new__
    return __new_cls._get_new_instance_without_conversion_oapg(
  File "/home/user/openapi/python_out/openapi_client/schemas.py", line 436, in _get_new_instance_without_conversion_oapg
    properties = cls._get_properties_oapg(arg, path_to_item, path_to_schemas)
  File "/home/user/openapi/python_out/openapi_client/schemas.py", line 1707, in _get_properties_oapg
    new_value = property_cls._get_new_instance_without_conversion_oapg(
  File "/home/user/openapi/python_out/openapi_client/schemas.py", line 436, in _get_new_instance_without_conversion_oapg
    properties = cls._get_properties_oapg(arg, path_to_item, path_to_schemas)
  File "/home/user/openapi/python_out/openapi_client/schemas.py", line 1707, in _get_properties_oapg
    new_value = property_cls._get_new_instance_without_conversion_oapg(
  File "/home/user/openapi/python_out/openapi_client/schemas.py", line 436, in _get_new_instance_without_conversion_oapg
    properties = cls._get_properties_oapg(arg, path_to_item, path_to_schemas)
  File "/home/user/openapi/python_out/openapi_client/schemas.py", line 1707, in _get_properties_oapg
    new_value = property_cls._get_new_instance_without_conversion_oapg(
AttributeError: type object 'DynamicSchema' has no attribute '_get_new_instance_without_conversion_oapg'
```

**Comment by spacether** [comment]
A work around for your issue for now is to not pass in model instances into `__new__` or `from_openapi_data`
```
from openapi_client.model.event import Event
from openapi_client.model.event_request import EventRequest
EventRequest(config={name="test", properties={"name": "test"}})
```

**Comment by spacether** [comment]
All fixed :)
