### ISSUE TITLE
[BUG] Issue with defining inputSpec of openapi generator gradle plugin on Windows

### ISSUE THREAD

**Issue by rainer198** [OpenAPITools/openapi-generator#14075]
##### Description

In a gradle project on a Windows machine, I'd like to generate Java code from an openapi spec. However, I can't figure out how to specify the inputSpec parameter. For simplicity I describe the `validate` task since the issue occurrs there as well.

    plugins {
        ...
        id "org.openapi.generator" version "6.2.1"
        ...
    }
    
    openApiValidate {
        inputSpec = "src/main/resources/api/openapi.yaml"
    }

leads to `Caused by: java.lang.RuntimeException: Could not find src/main/resources/api/openapi.yaml on the classpath`

Expecting that I could have mispelled the path, I tried to include a typo intentionally

    inputSpec = "src/main/resources/api/openapi.WRONG"

But this leads to a different exception

    A problem was found with the configuration of task ':publisher-service:openApiValidate' (type 'ValidateTask').
    > File 'C:\dev\myProject\src\main\resources\api\openapi.WRONG' specified for property 'inputSpec' does not exist.

If using 

    inputSpec = "$projectDir/src/main/resources/api/openapi.yaml"

instead, it says `java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\dev\myProject/src/main/resources/api/openapi.yaml`

Next trial with an absolute path: 

    inputSpec = "/c/dev/myProject/src/main/resources/api/openapi.yaml"

Again, it fails with something different:

    > File 'C:\dev\myProject\c\dev\myProject\src\main\resources\api\openapi.yaml' specified for property 'inputSpec' does not exist. 

Notice that some path parts are duplicated there.

I tried running gradle (gradlew to be precise) in a git bash and from within Intellij with no difference.

Any idea how to solve this?

##### openapi-generator version

6.2.1

Older versions seem to work. I've tried 6.1.0 which does not have this issue. Instead I have another problem with spec validation `com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')`

**Comment by rainer198** [comment]
I don't know, after switching between different versions, it works with 6.2.1 as well, at least when defining the `inputSpec` like

    inputSpec.set((new File("${projectDir}/src/main/resources/api/openapi.yml")).toString());

**Comment by rainer198** [comment]
In another project which uses another gradle version (7.5.1) even the described workaround did not work.

**Comment by martin-mfg** [comment]
It works fine for me using:
- Windows 10
- org.openapi.generator 6.2.1
- gradlew with gradle 8.0
- git bash to run the command `./gradlew openApiValidate`
- input path "C:/Users/MY_USER_NAME/Desktop/webhook-example.yaml"

The important part is probably that even when using git bash you should still specify the input path using "C:/...".

Hope this helps!

**Comment by mdastronaut** [comment]
Gradle 7.6.1
```
inputSpec = (file("<path-to-spec>")).toString()
```

**Comment by mtrakal** [comment]
it's broken with: openapi: 3.**1**.0
when change to: openapi: 3.0.x it generate.

Windows 11 + openapi: 3.1.0

problem is path which it try to use: D:**\\** instead of /

```
 -Illegal character in opaque part at index 2: D:\Projects\project\module\api/api.yaml

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:717)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:744)
        at org.openapitools.generator.gradle.plugin.tasks.GenerateTask.doWork(GenerateTask.kt:937)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
```

**Comment by mtrakal** [comment]
Simple workaround:
```
openApiGenerate {
    // add .replace("\\","/") behind yaml file path :)
    inputSpec = "$projectDir/specification.yaml".replace("\\","/")
```

**Comment by desertratx** [comment]
the workaround does unfortunatly not work in maven with <inputSpecRootDirectory>
        <inputSpecRootDirectory>${good.basedir}/src/main/resources</inputSpecRootDirectory>

Reading spec: .........../src/main/resources**\**models.yaml

**Comment by koscejev** [comment]
Encountered the same issue. Here's a workaround that uses a newer Gradle approach (.kts version):
```kotlin
inputSpec = layout.buildDirectory.file("resources/main/openapi.yaml").map { it.asFile.toURI().toString() }
```

**Comment by andradf** [comment]
In case anyone else falls down the wrong rabbit hole like I did and ends up here. My problem which yielded this exact exception was from trying to generate a client from a 3.1.0 spec with version 7.14.0.  An update to 7.25.0 fixed it.
