### ISSUE TITLE
python generator can't handle 'application/json; charset=UTF-8'

### ISSUE THREAD

**Issue by bayeslearner** [OpenAPITools/openapi-generator#14147]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?

##### openapi-generator version

openapi-generator-cli 6.2.1
  commit : b0ce532
  built  : 2022-11-01T09:40:00Z
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/

##### OpenAPI declaration file content or url
https://admin.splunk.com/service/info/specs/v2/openapi.json

##### Generation Details
openapi-generator generate  -g python -o out -i https://admin.splunk.com/service/info/specs/v2/openapi.json --package-name splunkacs --skip-validate-spec

The API call for the following program goes through and in fact fetches the desired json, but the content-type check fails and exception is thrown instead. 

 

##### Steps to reproduce

Traceback (most recent call last):
  File "splunk_cloud_acs_test.py", line 33, in <module>
    api_response = api_instance.list_indexes(
  File "/Users/xxx/.local/lib/python3.10/site-packages/splunkacs-1.0.0-py3.10.egg/splunkacs/paths/stack_adminconfig_v2_indexes/get.py", line 408, in list_indexes
  File "/Users/xxx/.local/lib/python3.10/site-packages/splunkacs-1.0.0-py3.10.egg/splunkacs/paths/stack_adminconfig_v2_indexes/get.py", line 342, in _list_indexes_oapg
  File "/Users/xx/.local/lib/python3.10/site-packages/splunkacs-1.0.0-py3.10.egg/splunkacs/api_client.py", line 929, in deserialize
splunkacs.exceptions.ApiValueError: Invalid content_type returned. Content_type='application/json; charset=UTF-8' was returned when only {'application/json'} are defined for status_code=200

```
import splunkacs
from splunkacs.apis.tags import indexes_api
from splunkacs.model.error import Error
from splunkacs.model.index_response import IndexResponse
from pprint import pprint
# Defining the host is optional and defaults to http://localhost
# See configuration.py for a list of all supported configuration parameters.
configuration = splunkacs.Configuration(
    host = "https://admin.splunk.com"
)

# The client must configure the authentication and authorization parameters
# in accordance with the API server security policy.
# Examples for each auth method are provided below, use the example that
# satisfies your auth use case.

# Configure Bearer authorization (JWT): bearerAuth
configuration.access_token = '<private token>'


# Enter a context with an instance of the API client
with splunkacs.ApiClient(configuration) as api_client:
    # Create an instance of the API class
    api_instance = indexes_api.IndexesApi(api_client)

    # example passing only required values which don't have defaults set
    path_params = {
        'stack': "michmed",
    }
    query_params = {
    }
    try:
        api_response = api_instance.list_indexes(
            path_params=path_params,
            query_params=query_params,
        )
        pprint(api_response)
    except splunkacs.ApiException as e:
        print("Exception when calling IndexesApi->list_indexes: %s\n" % e)
 
```
Traceback (most recent call last):
  File ".../splunkacstest/splunk_cloud_acs_test.py", line 33, in <module>
    api_response = api_instance.list_indexes(
  File "/Users/yyy/.local/lib/python3.10/site-packages/splunkacs-1.0.0-py3.10.egg/splunkacs/paths/stack_adminconfig_v2_indexes/get.py", line 408, in list_indexes
  File "/Users/yyy/.local/lib/python3.10/site-packages/splunkacs-1.0.0-py3.10.egg/splunkacs/paths/stack_adminconfig_v2_indexes/get.py", line 342, in _list_indexes_oapg
  File "/Users/yyy/.local/lib/python3.10/site-packages/splunkacs-1.0.0-py3.10.egg/splunkacs/api_client.py", line 929, in deserialize
splunkacs.exceptions.ApiValueError: Invalid content_type returned. Content_type='application/json; charset=UTF-8' was returned when only {'application/json'} are defined for status_code=200

##### Suggest a fix
Not sure whether the spec json is flawed or openapi-generator needs to relax the checking.

**Comment by spacether** [comment]
It does work
Please see this PR
https://github.com/OpenAPITools/openapi-generator/pull/12114/files

You need to add the charset to the spec.
If you want to add general charset handling to the generator where it knows that application/json includes certain charsets feel free to write a PR.

**Comment by bayeslearner** [comment]
Sorry, I have little knowledge of the inner workings of python client tool,  the PR you mentioned seems to have already been merged?  I dig into the generated code and it seems to have a json detection class that claims to handle charset UTF-8.  

What modifications do I need to provide when invoking the api in the client code, or do you mean the master branch still needs to be patched?

**Comment by spacether** [comment]
Note: this issue is a duplicate of: https://github.com/OpenAPITools/openapi-generator/issues/13467

> method 1. the spec json needs to be modified, correct?
Correct

> method 2. modify the generator to spit out code that allows additional charset. The PR seems to have already added additional json content-type detection? Why didn't it work?
Because the code only allows in content types strictly defined in the spec.
It is not making it past that check. If it did make it pass that check, the content can be correctly deserialized into model instances.
