### ISSUE TITLE
[BUG] [python-nextgen] (De)serialization of enums fails due to missing conversion methods

### ISSUE THREAD

**Issue by TimoGuenther** [OpenAPITools/openapi-generator#14524]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The `python-nextgen` generator assumes the existence of `(from|to)_(dict|json)` methods on generated enums, which causes enum (de)serialization to fail with an exception.

Affected:

- singular `allOf`: The parent expects `(from|to)_dict` from the enum.
- `anyOf`, `oneOf`, plural `allOf`: The composite model expects `(from|to)_(dict|json)` from the wrapped enum(s).

Impact:

- That is how [DRF Spectacular](https://pypi.org/project/drf-spectacular/) generates enums, for example.

##### openapi-generator version

6.3.0-20230125.125049-89

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: ""
  version: ""
paths: {}
components:
  schemas:
    Parent:
      type: object
      properties:
        number:
          allOf:
          - $ref: '#/components/schemas/Number'
    Number:
      enum:
      - one
      - two
      - three
      type: string
```

##### Generation Details

```shell
java -jar openapi-generator-cli-6.3.0-20230125.125049-89.jar generate -i openapi-schema.yaml -g python-nextgen
```

##### Steps to reproduce

Assuming the import problem described in #14523 is fixed:

```py
>>> from openapi_client import Parent, Number
>>> Parent.from_dict(dict(number="one"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "openapi_client/models/parent.py", line 73, in from_dict
    "number": Number.from_dict(obj.get("number")) if obj.get("number") is not None else None
AttributeError: type object 'Number' has no attribute 'from_dict'
>>> Parent(number=Number.ONE).to_dict()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "openapi_client/models/parent.py", line 60, in to_dict
    _dict['number'] = self.number.to_dict()
AttributeError: 'Number' object has no attribute 'to_dict'
```

##### Related issues/PRs

- #14523

##### Suggest a fix

Manually replacing the `from_dict` call with an enum value lookup (by calling the enum class directly) and removing the block that calls `to_dict` on the enum from `parent.py` fixes (de)serialization for singular `allOf`:

```py
>>> from openapi_client import Parent, Number
>>> Parent.from_dict(dict(number="one"))
Parent(number=<Number.ONE: 'one'>)
>>> Parent(number=Number.ONE).to_dict()
{'number': <Number.ONE: 'one'>}
```

This must be automated.

The fix for composite models seems more involved (e.g., checking for existence of the required methods on the wrapped value).

Alternatively, the enums could feature trivial implementations of the required methods.

**Comment by spacether** [comment]
If you are open to using the `python` generator, we have verified CI tests of enums at:
- https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/3_0_3_unit_test/python/test/test_models/test_enum_with0_does_not_match_false.py#L25
- https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/3_0_3_unit_test/python/test/test_models/test_enum_with1_does_not_match_true.py
- https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/3_0_3_unit_test/python/test/test_models/test_enum_with_escaped_characters.py
- https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/3_0_3_unit_test/python/test/test_models/test_enum_with_false_does_not_match0.py
- https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/3_0_3_unit_test/python/test/test_models/test_enum_with_true_does_not_match1.py
- https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/3_0_3_unit_test/python/test/test_models/test_enums_in_properties.py
- https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/tests_manual/test_boolean_enum.py#L28
- https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/tests_manual/test_integer_enum_one_value.py#L52
- https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/tests_manual/test_string_enum.py

**Comment by wing328** [comment]
I think this has been resolved in the latest master as we now have better support to handle the following:
```
        number:
          allOf:
          - $ref: '#/components/schemas/Number'
```
please give the latest master a try and happy to reopen this if needed.

**Comment by matt7aylor** [comment]
Does this fix the other affected cases from the issue description e.g. `anyOf`. I am hitting what looks like the same issue `has no attribute 'from_json'` in latest snapshot with a schema using `anyOf`.
e.g. as above but
```
        number:
          anyOf:
          - $ref: '#/components/schemas/Number'
```

**Comment by wing328** [comment]
For anyOf/oneOf, please enable `SIMPLIFY_ONEOF_ANYOF` in the openapi normalizer: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#openapi-normalizer

**Comment by wing328** [comment]
@TimoGuenther I tested with the latest master and here is what I got:
```
➜  py python
Python 3.7.13 (default, Oct  5 2022, 10:45:58) 
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from openapi_client import Parent, Number
>>> Parent.from_dict(dict(number="one"))
Parent(number=<Number.ONE: 'one'>)
>>> Parent(number=Number.ONE).to_dict()
{'number': <Number.ONE: 'one'>}
```

Can you please PM me via Slack so that I can help you out on this?

https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

**Comment by matt7aylor** [comment]
Hi @wing328, I get a different error when I generate with that option. Using `java -jar ~/bin/openapitools/openapi-generator-cli-6.6.0-20230411.095613-12.jar generate -i openapi-schema.yaml -g python-nextgen -o test_simplify_anyOf --openapi-normalizer SIMPLIFY_ONEOF_ANYOF=true`

```python
Python 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from openapi_client import Parent, Number
>>> Parent.from_dict(dict(number="one"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/openapi/test_simplify_anyOf/openapi_client/models/parent.py", line 75, in from_dict
    "number": AnyOf.from_dict(obj.get("number")) if obj.get("number") is not None else None
NameError: name 'AnyOf' is not defined
```

without the option I get the same errors as above, i.e. using `java -jar ~/bin/openapitools/openapi-generator-cli-6.6.0-20230411.095613-12.jar generate -i openapi-schema.yaml -g python-nextgen -o test_normal`

```python
Python 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from openapi_client import Parent, Number
>>> Parent.from_dict(dict(number="one"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/openapi/test_normal/openapi_client/models/parent.py", line 71, in from_dict
    "number": ParentNumber.from_dict(obj.get("number")) if obj.get("number") is not None else None
  File "/tmp/openapi/test_normal/openapi_client/models/parent_number.py", line 60, in from_dict
    return cls.from_json(json.dumps(obj))
  File "/tmp/openapi/test_normal/openapi_client/models/parent_number.py", line 69, in from_json
    instance.actual_instance = Number.from_json(json_str)
AttributeError: type object 'Number' has no attribute 'from_json'
>>> 
```

The schema is:
```yaml
openapi: 3.0.3
info:
  title: ""
  version: ""
paths: {}
components:
  schemas:
    Parent:
      type: object
      properties:
        number:
          anyOf:
          - $ref: '#/components/schemas/Number'
    Number:
      enum:
      - one
      - two
      - three
      type: string
```

**Comment by wing328** [comment]
@matt7aylor I've merged https://github.com/OpenAPITools/openapi-generator/pull/15225 to fix the issue. Please give it another with the latest master (latest snapshot version can be found in the readme)

**Comment by wing328** [comment]
We've merged some fixes (which include more tests). Can you please give it another try with the latest master?

SNAPSHOT version can be found in https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/6.6.0-SNAPSHOT/

**Comment by wing328** [comment]
@TimoGuenther thanks for the test result. Will try to fix these tomorrow.

```
components:
  schemas:
    Parent:
      type: object
      properties:
        number:
          allOf:
          - $ref: '#/components/schemas/Number'
          - $ref: '#/components/schemas/Number'
    Number:
      enum:
      - one
      - two
      - three
      type: string
```

Just want to clarify the definition of the above.

Is it intentional to have duplicate/identical sub-schemas in the `allOf` ?

**Comment by wing328** [comment]
let's consider this:
```
openapi: 3.0.3
info:
  title: ""
  version: ""
paths: {}
components:
  schemas:
    Parent:
      type: object
      properties:
        character:
          allOf:
          - $ref: '#/components/schemas/Number'
          - $ref: '#/components/schemas/Letter'
    Number:
      enum:
      - one
      - two
      - three
      type: string
    Letter:
      enum:
      - A
      - B
      - C
      type: string
```
(replaced oneOf with allOf baed on your example)

syntax-wise, it's valid but the definition (allOf enum strings) won't make sense if I understand it correctly.

allOf needs to ensure all sub-schemas are valid with respect to the payload. I cannot find a single example of payload that can match the following schemas at the same time:
```
    Number:
      enum:
      - one
      - two
      - three
      type: string
    Letter:
      enum:
      - A
      - B
      - C
      type: string
```

I suggest we step back try to understand about the requirement/use case and see if allOf enum strings (or primitive types) are the best way to describe the data

(python-nextgen supports allOf models but not allOf primitive types)

**Comment by wing328** [comment]
```
>>> from openapi_client import Parent, Number
>>> Parent.from_dict(dict(character="one"))
Parent(character=ParentCharacter(oneof_schema_1_validator=None, oneof_schema_2_validator=None, actual_instance=<Number.ONE: 'one'>, one_of_schemas=['Letter', 'Number']))
>>> Parent(character=Number.ONE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Parent
character
  value is not a valid dict (type=type_error.dict)
```

Please use the following as a workaround for the time being:
```
>>> from openapi_client import Parent, Number, ParentCharacter, Number, Letter
>>> Parent(character=ParentCharacter(Number.ONE))
Parent(character=ParentCharacter(oneof_schema_1_validator=None, oneof_schema_2_validator=None, actual_instance=<Number.ONE: 'one'>, one_of_schemas=['Letter', 'Number']))
>>> 
```

We'll update the oneOf type to include oneOf sub-schemas so that users can assign the value directly without creating the oneOf class. (same for anyOf)
