### ISSUE TITLE
(`value1` and `value2`) in parameters:description leads to error in Confluence

### ISSUE THREAD

**Issue by dusiema** [OpenAPITools/openapi-generator#1460]
##### Description

I have a value of 
```yaml  
(`value1` and `value2`)  
```
in one of my descriptions in a parameter. Copying the resulting confluence markup into Confluence (Version 6.8.2) leads to a server error. 

In Confluence wiki it results to: 
```
(&#x60;spVon&#x60; und &#x60;spBis&#x60;)
```

It works if I put a space after and before the parenthesis. Or if I escape the parenthesis.

##### openapi-generator version

3.3.2
##### OpenAPI declaration file content or url

generate -g cwiki -i <file.yaml> -o <outputFolder>

**Comment by wing328** [comment]
I'm no expert in Confluence. If the description is simply `(something here)`, do we need to insert space after and before the parenthesis?

**Comment by dusiema** [comment]
I looked up the log on the confluence server and this is the exception:  

`java.lang.RuntimeException: com.atlassian.confluence.content.render.xhtml.XhtmlParsingException: The XML content could not be parsed. There is a problem at line 1, column 363. Parser message: Unexpected character &#39;&lt;&#39; (code 60); expected a hex digit (0-9a-fA-F).`

it goes on with: 

`Caused by: com.atlassian.confluence.content.render.xhtml.XhtmlParsingException: The XML content could not be parsed. There is a problem at line 1, column 363. Parser message: Unexpected character &#39;&lt;&#39; (code 60); expected a hex digit (0-9a-fA-F).
 at [row,col {unknown-source}]: [1,363]
	at com.atlassian.confluence.content.render.xhtml.StaxUtils.convertToXhtmlException(StaxUtils.java:433)`

and

`Caused by: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '<' (code 60); expected a hex digit (0-9a-fA-F).
 at [row,col {unknown-source}]: [1,363]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedChar(StreamScanner.java:648)`

**Comment by dusiema** [comment]
Maybe there is some hidden conversion somewhere. 
Anyways, I just removed the parenthesis in my OpenAPI description. 

We could close this issue if you want to. It might just happen to be a problem in the parser that confluence uses. Or something else.
