### ISSUE TITLE
#14574 Causes issues with big / random objects

### ISSUE THREAD

**Issue by jenspopp** [OpenAPITools/openapi-generator#14655]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

#14574 causes "random" timeouts and errors if big objects are transferred. I have a special test case creating a random String with 100MB converting it to byte[] and byte[] to String to test encoding issues. Besides a very bad performance penalty (Test takes 3-5 min instead of 2) I get random errors:

com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input: was expecting closing quote for a string value
in ApiClient.deserialize(ApiClient.java:745)

And on server side:

Failed to handle request: java.io.IOException: java.io.IOException: Failed to write
at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.write(ResteasyReactiveOutputStream.java:225)
at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2171)
at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegment2(UTF8JsonGenerator.java:1485)
at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegment(UTF8JsonGenerator.java:1432)
at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegments(UTF8JsonGenerator.java:1315)
at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:511)
at com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:41)

I assume that if the "wrong" random String is generated it will cause the Scanner to fail. I hit the issue about ever 2nd to 3rd run with scanner, have never had it without. Additionally the small buffer size in scanner seems to make it slow in the large stream use case.

##### openapi-generator version

6.3.0 (did not happen before in 6.2.1) Apache http client

##### Steps to reproduce
Client code:

```
		int leftLimit = 48;
		int rightLimit = 122;
		int targetStringLength = 100 * 1024 * 1024;

		String big = random.ints(leftLimit, rightLimit + 1).limit(targetStringLength)
				.collect(StringBuilder::new, StringBuilder::appendCodePoint, StringBuilder::append).toString();
		ByteArrayHolderDTO holder = new ByteArrayHolderDTO().value(big.getBytes(StandardCharsets.UTF_8));
		StringHolderDTO str = new StringHolderDTO().value(big);
		try {
			assertEquals(big, getApi().convertToString(holder).getValue());
			assertArrayEquals(holder.getValue(),
					getApi().convertToByteViaBody(str).getValue());
		} catch (Exception e) {
			fail("Create should not throw an exception", e);
		}

```
Server code:

```
	@Override
	public ByteArrayHolderDTO convertToByteViaBody(@Valid StringHolderDTO body) {
		String in = body.getValue();
		log.infof("convertToByteViaBody received %s", in.length() > 200 ? in.substring(0, 200) + "..." : in);
		return new ByteArrayHolderDTO().value(in.getBytes(StandardCharsets.UTF_8));
	}

	@Override
	public StringHolderDTO convertToString(@Valid ByteArrayHolderDTO body) {
		String in = new String(body.getValue(), StandardCharsets.UTF_8);
		log.infof("convertToString returns %s", in.length() > 200 ? in.substring(0, 200) + "..." : in);
		return new StringHolderDTO().value(in);
	}

	@Override
	public ByteArrayHolderDTO convertToByte(String stringin) {
		log.infof("convertToByte received %s", stringin);
		return new ByteArrayHolderDTO().value(stringin.getBytes(StandardCharsets.UTF_8));
	}

```

##### Related issues/PRs

Caused by #14574

##### Suggest a fix

Do not use Scanner in ApiClient

**Comment by jenspopp** [comment]
Relevant Openapi parts:

  /api/specialchars/:
    get:
      tags:
        - Special Tests
      parameters:
        - in: query
          name: stringin
          schema:
            type: string
      operationId: "convertToByte"
      summary: Convert the given string to byte
      responses:
        200:
          description: converted string to byte array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ByteArrayHolderDTO'
    post:
      tags:
        - Special Tests
      operationId: "convertToString"
      summary: Convert the given byte array to string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ByteArrayHolderDTO'
      responses:
        200:
          description: converted byte array to string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringHolderDTO'
    put:
      tags:
        - Special Tests
      operationId: "convertToByteViaBody"
      summary: Convert the given string in method body to string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StringHolderDTO'
      responses:
        200:
          description: converted byte array from string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ByteArrayHolderDTO'

components:
  securitySchemes:
    basicAuth:  
      type: http
      scheme: basic
  schemas:
    StringHolderDTO:
      type: object
      required:
        - value
      properties:
        value:
          type: string  
    ByteArrayHolderDTO:
      type: object
      required:
        - value
      properties:
        value:
          type: string
          format: byte

**Comment by jenspopp** [comment]
The issue can only be recreated with Java 11. The code hangs at s.next(), it seems stream copy is extremly slow.
With Java 17 s.next() takes about 5 sec to run.

**Comment by jenspopp** [comment]
Possible solutions discussed in PR #14574 

Just remove scanner from template and use BAOS
