### ISSUE TITLE
[BUG][Java][RestTemplate][WebClient] Java client generator doesn't support deepObject in query

### ISSUE THREAD

**Issue by jorgerod** [OpenAPITools/openapi-generator#14691]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Java RestTemplate and Java Webclient generator don't support deepObject in query

##### openapi-generator version

5.4.0, 6.3.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0

info:
  title: Example
  description: Example of deepObject failure.
  version: 1.0.0

paths:
  /test:
    get:
      operationId: test
      parameters:
        - name: filter
          in: query
          style: deepObject
          explode: true
          schema:
            type: object
            properties:
              search:
                description: Filter.
                type: string
      responses:
        '200':
          description: Response.
```

##### Generation Details

java -jar openapi-generator-cli.jar generate -g java -i openapi-rest.yml -o openapi --library resttemplate
java -jar openapi-generator-cli.jar generate -g java -i openapi-rest.yml -o openapi --library webclient

##### Related issues/PRs

- https://github.com/OpenAPITools/openapi-generator/pull/13662
- https://github.com/OpenAPITools/openapi-generator/issues/10806

**Comment by wing328** [comment]
can you try the `native` or `apache-httpclient` library, which has better support for deep object query paramters?

**Comment by jorgerod** [comment]
Hello

With `apache-httpclient` it didn't work for me. it generates a url like this:

```
/api/team?query=class%20TeamCriteriaDTODTO%20%7B%0A%20%20%20%20teamIdList%3A%20%5B%5D%0A%20%20%20%20teamKeyList%3A%20%5B%5D%0A%20%20%20%20key%3A%20kkk%0A%20%20%20%20name%3A%20null%0A%20%20%20%20description%3A%20dddd%0A%20%20%20%20typeIdList%3A%20%5B%5D%0A%20%20%20%20managerLogin%3A%20null%0A%20%20%20%20department%3A%20d%0A%20%20%20%20includeTeamMembers%3A%20true%0A%20%20%20%20includeTeamProfiles%3A%20true%0A%20%20%20%20includeTeamProjects%3A%20true%0A%20%20%20%20includeTeamResources%3A%20false%0A%20%20%20%20includeTeamAchievements%3A%20false%0A%7D
```


 With `native` the generated code doesn't even compile.

**Comment by jorgerod** [comment]
I have expanded this issue with more bug cases in this other issue:
- https://github.com/OpenAPITools/openapi-generator/issues/14790

**Comment by stephenmontgomery** [comment]
Copy of https://github.com/OpenAPITools/openapi-generator/issues/4808#issuecomment-1491766707

Doesn't work with Spring Weblient generation in openapi-generator-maven-plugin:6.40. Generates same error as https://github.com/OpenAPITools/openapi-generator/issues/4808#issuecomment-1383980884 ie `?pageable=class%20Pageable%20%7B%0A%20%20%20%20page%3A%200%0A%20%20%20%20size%3A%20100%0A%20%20%20%20sort%3A%20%5Bname%5D%0A%7D` 

In Swagger UI it creates the expected `?page=0&size=20&sort=name` 

```
Caused by: org.springframework.core.codec.DecodingException: JSON decoding error: Cannot deserialize value of type `com.contrastsecurity.authz.client.model.SortObject` from Array value (token `JsonToken.START_ARRAY`); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `com.contrastsecurity.authz.client.model.SortObject` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 426] (through reference chain: com.contrastsecurity.authz.client.model.PageUserAccessGroupResponse["pageable"]->com.contrastsecurity.authz.client.model.PageableObject["sort"])
	at org.springframework.http.codec.json.AbstractJackson2Decoder.processException(AbstractJackson2Decoder.java:242)
	Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Body from GET http://localhost:10005/organizations/f4546458-72ae-4784-a7e2-a440761fb92e/user-access-groups/user/388f1310-7dfd-44f6-82ad-be7e8997c08c?pageable=class%20Pageable%20%7B%0A%20%20%20%20page%3A%200%0A%20%20%20%20size%3A%20100%0A%20%20%20%20sort%3A%20%5Bname%5D%0A%7D [DefaultClientResponse]
Original Stack Trace:
		at org.springframework.http.codec.json.AbstractJackson2Decoder.processException(AbstractJackson2Decoder.java:242)
		at org.springframework.http.codec.json.AbstractJackson2Decoder.decode(AbstractJackson2Decoder.java:198)
		at org.springframework.http.codec.json.AbstractJackson2Decoder.lambda$decodeToMono$1(AbstractJackson2Decoder.java:179)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299)
		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
		at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160)
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
		at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
		at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:424)
		at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:478)
		at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:712)
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:139)
		at reactor.core.publisher.Mono.block(Mono.java:1766)
```

**Comment by motograter** [comment]
yep, same problem ts-axios :={

**Comment by stephenmontgomery** [comment]
Any word on this?

**Comment by GregDThomas** [comment]
This bug ticket explicitly mentions the Java RestTemplate in the title. 

I believe this was fixed in https://github.com/OpenAPITools/openapi-generator/pull/14825 released in 7.0.0

**Comment by nefarian-gaming** [comment]
The bug still exist in 7.0.1 for webclient. Any ideas for a workaround?

**Comment by GregDThomas** [comment]
This ticket is talking about sending a query string in the request. Looks like your problem is in parsing a response, so a different issue.

**Comment by stephenmontgomery** [comment]
Prob time @GregDThomas to open an epic and just get 1 OneAPI Java client working with Spring Data Paging. This ticket is still open and related (long-running) https://github.com/OpenAPITools/openapi-generator/issues/4808 re-opened. I'm not sure you get any points if just the request works...

**Comment by jorgerod** [comment]
@GregDThomas RestTemplate problem continues in version 7.3.0

**Comment by jorgerod** [comment]
Closed in favor of https://github.com/OpenAPITools/openapi-generator/issues/14790
