### ISSUE TITLE
NullPointerException when generating Bungie.net OpenAPI spec

### ISSUE THREAD

**Issue by Yogarine** [OpenAPITools/openapi-generator#1480]
##### Description

When trying to generate clients for the Bungie.net OpenAPI spec, I get a NullPointerException:
```
Exception in thread "main" java.lang.NullPointerException
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:939)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:910)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:488)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:868)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:349)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:62)
```
(I'll add a full `--verbose` log in a comment.)

##### openapi-generator version

3.3.4-SNAPSHOT (master @ c656194f22f9624ee861abe57964758ae7e7bd39)

##### OpenAPI declaration file content or url

[https://raw.githubusercontent.com/Bungie-net/api/master/openapi.json](https://raw.githubusercontent.com/Bungie-net/api/master/openapi.json)

##### Command line used for generation

```bash
java -jar openapi-generator-cli.jar generate
      --generator-name php
      --config         /local/openapi-config.php.json
      --input-spec     https://raw.githubusercontent.com/Bungie-net/api/master/openapi.json
      --output         /local/bungie-sdk-php
      -DapiTests=false
      -DmodelTests=false
      --verbose
```

openapi-config.php.json:
```json
{
  "packageName": "bungie-sdk-php",
  "composerVendorName": "yogarine",
  "composerProjectName": "bungie-sdk-php",
  "artifactVersion": "2.3.2",
  "invokerPackage" : "Bungie",
  "modelPackage": "Model",
  "apiPackage": "API",
  "variableNamingConvention": "camelCase",
  "srcBasePath": "src",
  "gitUserId": "Yogarine",
  "gitRepoId": "bungie-sdk-php",
  "validateSpec": false
}
```

##### Steps to reproduce

Build with the above command.

**Comment by Yogarine** [comment]
Found the issue. There is a tag at the end with an empty 'name' field:
```json
{
"name": "",
"description": "core"
}
```

Should we just want to ignore the empty name?
