### ISSUE TITLE
[BUG] Schema mappings in configuration file do not work

### ISSUE THREAD

**Issue by ventsyv** [OpenAPITools/openapi-generator#14926]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I'm getting an error when I try to generate a model with a schema mappings defined in a config file.

##### openapi-generator version

6.4.0

##### Generation Details

Generating with --schema-mappings argument on the command line works:
```openapi-generator-cli generate -i common_components.yaml -g cpp-pistache-server --schema-mapping Arm=org.openapitools.server.model.Arm ```

##### Steps to reproduce

If I try to move the schema mapping to a config file, I get an error:

`openapi-generator-cli generate -i common_components.yaml -g cpp-pistache-server --config config.yaml`

Config.yaml looks like this:

` schemaMappings: "Arm=org.openapitools.server.model.Arm" `

Results in the following error:

```
[main] ERROR o.o.c.config.CodegenConfigurator - Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('Arm=org.openapitools.server.model.Arm')
 at [Source: (File); line: 2, column: 1] (through reference chain: org.openapitools.codegen.config.GeneratorSettings["schemaMappings"])
[main] ERROR o.o.c.config.CodegenConfigurator - Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('Arm=org.openapitools.server.model.Arm')
 at [Source: (File); line: 2, column: 1] (through reference chain: org.openapitools.codegen.config.GeneratorSettings["schemaMappings"])
Exception in thread "main" java.lang.RuntimeException: Unable to deserialize config file: config.yaml
	at org.openapitools.codegen.config.CodegenConfigurator.readDynamicSettings(CodegenConfigurator.java:171)
	at org.openapitools.codegen.config.CodegenConfigurator.fromFile(CodegenConfigurator.java:90)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:314)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

```

**Comment by ventsyv** [comment]
I was able to figure it out. The expected format is as follows:
```
---
schemaMappings: 
  <Class>: [<namespace.ClassName>]
  <Class>: [<namespace.ClassName>]
```

Can the format be documented somewhere?
