### ISSUE TITLE
Error when running docker command to generate from Make file.

### ISSUE THREAD

**Issue by khayargoli** [OpenAPITools/openapi-generator#14940]
I am using docker to generate and this runs fine if I manually paste this command into powershell and run it. Now if I create a Make file and try to run the make file, it fails (error is below)

**docker run --rm -v ":/local" openapitools/openapi-generator-cli:v6.1.0 generate -i /local/openapi.spec.yaml -c /local/openapi.config.yaml -g dart-dio -o /local/dart-dio-client**

Error:
[main] ERROR o.o.c.config.CodegenConfigurator - /local/openapi.config.yaml (No such file or directory)
[main] ERROR o.o.c.config.CodegenConfigurator - /local/openapi.config.yaml (No such file or directory)
Exception in thread "main" java.lang.RuntimeException: Unable to deserialize config file: /local/openapi.config.yaml
        at org.openapitools.codegen.config.CodegenConfigurator.readDynamicSettings(CodegenConfigurator.java:167)
        at org.openapitools.codegen.config.CodegenConfigurator.fromFile(CodegenConfigurator.java:89)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:293)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
make: *** [Makefile:17: generate-client-win] Error 1

**Comment by ahmednfwela** [comment]
@jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08)

**Comment by kuhnroyal** [comment]
The file is either not in your container, or there is a different file. You probably need to expand your working directory.
See https://stackoverflow.com/questions/41485217/mount-current-directory-as-a-volume-in-docker-on-windows-10
This question is not really related to the openapi generator as it works outside of docker.

@wing328 Please close, thanks!
