### ISSUE TITLE
[BUG] Typescript Fetch Client Code Fails

### ISSUE THREAD

**Issue by wakaztahir** [OpenAPITools/openapi-generator#14975]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

There are couple of issues with the generated code on `Windows` , The typescript code contains errors 

##### 1 - ERROR IN export and import , I pasted the whole folder with `tsconfig.json` , since generated tsconfig.json is being used , there shouldn't be this error

```
ERROR in src/api/index.ts:5:10
TS1205: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
    3 | export * from "./models/all";
    4 | export { createConfiguration } from "./configuration"
  > 5 | export { Configuration } from "./configuration"
      |          ^^^^^^^^^^^^^
    6 | export * from "./apis/exception";
    7 | export * from "./servers";
    8 | export { RequiredError } from "./apis/baseapi";

ERROR in src/api/index.ts:10:10
TS1205: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
     8 | export { RequiredError } from "./apis/baseapi";
     9 |
  > 10 | export { PromiseMiddleware as Middleware } from './middleware';
       |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    11 | export { PromiseDefaultApi as DefaultApi } from './types/PromiseAPI';
    12 |
    13 |
```

##### 2 - Error with Backslashes

I don't know if backslashes inside imports work on other operating systems , but they don't work in windows , the backslash is escaping the character and I'm getting an error in IDE

```typescript
import { Member } from '..\models\Member';
import { ProjectBugsInner } from '..\models\ProjectBugsInner';
import { User } from '..\models\User';
```

##### 3 - Error with running the Code

The first error is with the URL , The URL cannot be constructed , the URL object , it gives error because the URL fed to it is empty , I checked this by console logging and an exception occurs when you try to make a request with the client

After fixing everything , changing the imports and exports backslahes to forward slashes , fixing the export imports of the modules , You'd get this error

```typescript
TypeError: Failed to construct 'URL': Invalid URL
    at new RequestContext (http.ts:51:1)
    at ServerConfiguration.makeRequestContext (servers.ts:49:1)
    at DefaultApiRequestFactory.getAllProjects (DefaultApi.ts:311:1)
    at ObservableDefaultApi.getAllProjects (ObservableAPI.ts:205:1)
    at PromiseDefaultApi.getAllProjects (PromiseAPI.ts:100:1)
    at Object.getAllProjects (Controller.ts:13:1)
    at ProjectList.tsx:22:1
    at ProjectList.tsx:34:1
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
```

###### 4- How to download the latest master using npm or easily

as I'm using 6.4.0 , which is the latest stable version , If these issues have been fixed in the latest master , I'd like to use that instead but listing the npm version there's no snapshot version there , How can I easily download the latest version

Also the linode server latest uses the older 5.2.0 version which also doesn't work

##### openapi-generator version 

6.4.0

##### OpenAPI declaration file content or url

any code generated

##### Generation Details

language : typescript-fetch

##### Steps to reproduce

1 - Generate code using typescript-fetch

**Comment by wakaztahir** [comment]
plus opening the generated code in web storm reveals a lot of non critical problems with it , These quick fixes should be integrated into generated code

1 - unused imports
2 - un-shortened imports
3 - two-equal sign comparisons , in typescript 3 equal sign  comparison is preferred as the IDE suggests , basically these IDE suggestions should already be present in the generated code
3 - useless code that is meant to be shared in typescript generated libraries / too many abstractions because of library generated code sharing

**Comment by wakaztahir** [comment]
I have two suggestions for this project

1 - Move to Kotlin , Kotlin is now multiplatform , which means you could run the generator everywhere , plus Kotlin is also very null type safe , this means finally the generator could run in the browser , on the client machine , This would require some effort but would be very fruitful in the end and can be done slowly
2 -  Use Kotlin Gradle Kts
