### ISSUE TITLE
[BUG][JAVA (potentially all langs)] StackOverflowException with combination of allOf oneOf without explicit declaration of discriminator property in "properties"

### ISSUE THREAD

**Issue by bear43** [OpenAPITools/openapi-generator#15298]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Previously related issue #8468 is actually fixed since version 6.0.0 but only if discriminator property is defined in "properties" explicitly. If the discriminator property definition is provided only in "discriminator"."propertyName" without any other information in "properties" then it leads to StackOverflowException during schemas introspection. The information should contain values of discriminator property or, at least, just an explicit declaration of the property. An example YAML in #8468 is completely covered the correct case without StackOverflowException.

But YAML without values of a discriminator property or even without declaration of discriminator property in "properties"  is a valid OpenAPI specification (according to https://apitools.dev/swagger-parser/online/).

StackTrace without values of discriminator property or without declaration of discriminator property:
```
java.lang.StackOverflowError
	at java.util.regex.Pattern.error(Pattern.java:1969)
	at java.util.regex.Pattern.<init>(Pattern.java:1354)
	at java.util.regex.Pattern.compile(Pattern.java:1054)
	at java.lang.String.replace(String.java:2239)
	at org.openapitools.codegen.utils.ModelUtils.getSimpleRef(ModelUtils.java:401)
	at org.openapitools.codegen.utils.ModelUtils.getReferencedSchema(ModelUtils.java:802)
	at org.openapitools.codegen.DefaultCodegen.discriminatorFound(DefaultCodegen.java:3173)
	at org.openapitools.codegen.DefaultCodegen.discriminatorFound(DefaultCodegen.java:3206)
	at org.openapitools.codegen.DefaultCodegen.discriminatorFound(DefaultCodegen.java:3195)
	at org.openapitools.codegen.DefaultCodegen.discriminatorFound(DefaultCodegen.java:3206)
	at org.openapitools.codegen.DefaultCodegen.discriminatorFound(DefaultCodegen.java:3195)
	at org.openapitools.codegen.DefaultCodegen.discriminatorFound(DefaultCodegen.java:3206)
	at org.openapitools.codegen.DefaultCodegen.discriminatorFound(DefaultCodegen.java:3195)
```

##### openapi-generator version

Using generator versions from 6.0.0 to 6.5.0. Also the master branch version.

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.2
info:
  title: Polymorphism Java Example
  version: 1.0.0
  contact:
    name: polydectes
    email: 12345@sharklasers.com
servers:
  - url: 'https://localhost'
tags:
  - name: Example
paths:
  '/animal':
    post:
      tags:
        - Example
      operationId: createAnAnimal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Animal'
      responses:
        '200':
          $ref: '#/components/responses/200-OK'
        '400':
          $ref: '#/components/responses/400-BadRequest'
components:
  responses:
    200-OK:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Animal'
    400-BadRequest:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    Animal:
      type: object
      oneOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'
      discriminator:
        propertyName: animalType
    Cat:
      type: object
      allOf:
        - $ref: '#/components/schemas/Animal'
      properties:
        acceptableAsHousepet:
          type: boolean
    Dog:
      type: object
      allOf:
        - $ref: '#/components/schemas/Animal'
      properties:
        canBeTrained:
          type: string
    OkResponse:
      type: object
      properties:
        id:
          type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
```

##### Generation Details

```
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>6.5.0</version>
                <executions>
                    <execution>
                        <id>generate-poly-api</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/specs/issue_spring_codegen_polymorphism.yaml
                            </inputSpec>
                            <modelPackage>poly.model</modelPackage>
                            <apiPackage>poly.api</apiPackage>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <generatorName>spring</generatorName>
                            <library>spring-cloud</library>
                            <configOptions>
                                <dateLibrary>java8-localdatetime</dateLibrary>
                                <serializableModel>true</serializableModel>
                                <interfaceOnly>true</interfaceOnly>
                                <useOneOfInterfaces>false</useOneOfInterfaces>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <useTags>true</useTags>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

##### Steps to reproduce

calling "mvn clean compile" will cause the generation failure.

##### Related issues/PRs

Bug issue #8468 

##### Suggest a fix

  
Either remember visited schemas in disciminatorFound recursive method or add the demand of declaration discriminator property in "properties" with error log level.
 
 ```java
private CodegenProperty discriminatorFound(String composedSchemaName, Schema sc, String discPropName, OpenAPI openAPI, Set<Schema> visitedSchemas) {...}
 ```

**Comment by wing328** [comment]
tested with the latest master and no longer seeing the exception:

```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g spring --library spring-cloud -i /tmp/aa.yaml -o /tmp/go234 --openapi-normalizer REFACTOR_ALLOF_WITH_PROPERTIES_ONLY=true
```

happy to reopen the issue if needed
