### ISSUE TITLE
Issue loading template from custom generator due to classloader used

### ISSUE THREAD

**Issue by dpweberza** [OpenAPITools/openapi-generator#1530]
##### Description
I am running into an issue whereby the generator cannot load my custom generator's template when using the gradle plugin.

I believe the issue is due to the fact that the custom generator is loaded via a class-loader different to the one used below:

https://github.com/OpenAPITools/openapi-generator/blob/5aa1da7c2edb5d0a9552b95fd0f2598a538ea3f6/modules/openapi-generator/src/main/java/org/openapitools/codegen/AbstractGenerator.java#L73

Exception:
```
11:54:17.672 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
11:54:17.673 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildClient'.
11:54:17.673 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
11:54:17.673 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
11:54:17.673 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
11:54:17.674 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
11:54:17.674 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
11:54:17.674 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
11:54:17.674 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
11:54:17.674 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
11:54:17.675 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
11:54:17.675 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
11:54:17.675 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
11:54:17.675 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
11:54:17.675 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
11:54:17.675 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
11:54:17.675 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
11:54:17.675 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
11:54:17.675 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
11:54:17.675 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
11:54:17.676 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
11:54:17.676 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
11:54:17.676 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
11:54:17.676 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:262)
11:54:17.676 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:246)
11:54:17.677 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:136)
11:54:17.677 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
11:54:17.677 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.execute(DefaultTaskPlanExecutor.java:201)
11:54:17.677 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.executeWithTask(DefaultTaskPlanExecutor.java:192)
11:54:17.677 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
11:54:17.677 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
11:54:17.677 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
11:54:17.677 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
11:54:17.678 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
11:54:17.678 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
11:54:17.678 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.lang.Thread.run(Thread.java:748)
11:54:17.678 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.api.GradleException: Code generation failed.
11:54:17.678 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.openapitools.generator.gradle.plugin.tasks.GenerateTask.doWork(GenerateTask.kt:541)
11:54:17.678 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:54:17.678 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:54:17.678 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:54:17.678 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.lang.reflect.Method.invoke(Method.java:498)
11:54:17.678 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
11:54:17.678 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
11:54:17.679 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
11:54:17.679 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
11:54:17.679 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
11:54:17.679 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
11:54:17.679 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
11:54:17.679 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
11:54:17.679 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
11:54:17.679 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
11:54:17.679 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
11:54:17.679 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
11:54:17.679 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
11:54:17.679 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
11:54:17.679 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 33 more
11:54:17.680 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.RuntimeException: Could not generate supporting file 'SupportingFile:
11:54:17.680 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	templateFile: api.mustache
11:54:17.680 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	folder: 
11:54:17.680 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	destinationFilename: api.ts
11:54:17.680 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] '
11:54:17.680 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.openapitools.codegen.DefaultGenerator.generateSupportingFiles(DefaultGenerator.java:673)
11:54:17.680 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:820)
11:54:17.680 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.openapitools.generator.gradle.plugin.tasks.GenerateTask.doWork(GenerateTask.kt:537)
11:54:17.680 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 51 more
11:54:17.680 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.RuntimeException: can't load template typescript-client/api.mustache
11:54:17.680 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.openapitools.codegen.AbstractGenerator.readTemplate(AbstractGenerator.java:68)
11:54:17.680 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.openapitools.codegen.DefaultGenerator.generateSupportingFiles(DefaultGenerator.java:640)
11:54:17.680 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 53 more
```

##### openapi-generator version

3.2.3

##### OpenAPI declaration file content or url

Not relevant

##### Command line used for generation

Gradle

```
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath "com.demo:my-custom-generator:0.0.1"
        classpath "org.openapitools:openapi-generator-gradle-plugin:3.2.3"
    }
}
```

```
task buildClient(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    delete clientDistDir
    generatorName = "typescript-client"
    inputSpec = "$rootDir/src/openapi.yaml".toString()
    outputDir = clientDistDir
    additionalProperties = [
        npmVersion: "0.0.1",
        npmName   : "typescript-client"
    ]
}
```

##### Steps to reproduce

Run the generator via gradle with a custom generator & template from a buildscript dependency

##### Suggest a fix/enhancement

Fallback to using the custom generator config's class-loader

```
if (is == null) {
                is = ((DefaultGenerator) this).config.getClass().getResourceAsStream("/" + getCPResourcePath(name));
            }
```

**Comment by jimschubert** [comment]
@dpweberza I've tried to reproduce the issue, and I was unable to repro on the current release (3.3.3), although classloaders don't seem to have changed.

I have my example here: https://github.com/jimschubert/custom-generator-example

Can you check the example repro and see if it also occurs for you? If so, can you provide the gradle version you've tested on so I can also check if it's a gradle issue?

**Comment by dpweberza** [comment]
Hey @jimschubert 
Thanks for your example, it helped me narrow down the issue.
Your repo worked as is and with my generator artifact.

Seems the issue was in my consumer where I still had a buildSrc for a different generator.
As soon as I deleted that buildSrc dir everything worked as is.

Not sure exactly what issue that was causing for the classloader to fail to find my mustache templates yet succeed in loading the generator, but happy this is resolved.

**Comment by jimschubert** [comment]
Do you have a minimal example of what you were doing in buildSrc? I can see if I can track down exactly what caused it.
