### ISSUE TITLE
[BUG] Unable to generate SDK for Unity using OpenAPI Generator CLI with UnityWebRequest

### ISSUE THREAD

**Issue by Natashkinsasha** [OpenAPITools/openapi-generator#15385]
I'm trying to generate an SDK for Unity using OpenAPI Generator CLI with the UnityWebRequest library. I've executed the following script:
```
npx @openapitools/openapi-generator-cli generate -i swagger.json -g csharp-netcore --library unityWebRequest -o sdk-unity/ --skip-validate-spec --global-property modelTests=false --global-property apiTests=false --global-property modelDocs=false --global-property apiDocs=false --additional-properties packageName=BX
```
However, I'm encountering the following error:
```
Exception in thread "main" java.lang.RuntimeException: Unknown option: library
        at org.openapitools.codegen.CliOptionParser.parse(CliOptionParser.java:56)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:353)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:33)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```
It seems like the library option is not recognized, and I'm unable to generate the SDK with the UnityWebRequest library. Can you please help me with this issue?

Thank you.

**Comment by Natashkinsasha** [comment]
switched in 6.5.0 and now work
```
openapi-generator-cli version-manager set 6.5.0
```
