### ISSUE TITLE
[BUG] Generating SDK for Unity using OpenAPI Generator CLI results in RestSharp library instead of UnityWebRequest

### ISSUE THREAD

**Issue by Natashkinsasha** [OpenAPITools/openapi-generator#15383]
I'm trying to generate an SDK for Unity using OpenAPI Generator CLI. I've executed the following script:

```
npx @openapitools/openapi-generator-cli generate -i swagger.json -g csharp-netcore -o sdk-unity/ --skip-validate-spec --global-property modelTests=false --global-property apiTests=false --global-property modelDocs=false --global-property apiDocs=false --additional-properties packageName=BX --additional-properties library=unityWebRequest
```

I was expecting to get the SDK generated with the UnityWebRequest library, but instead, the generated SDK is using the RestSharp library. I have checked the OpenAPI Generator documentation and it says that the unityWebRequest option is available for C# .NET Core generator.

Can you please help me with this issue? How can I generate an SDK for Unity using the UnityWebRequest library instead of RestSharp?

Thank you.

**Comment by wing328** [comment]
`library` is a general (top level) option so please do `--library unityWebRequest` instead.

**Comment by Natashkinsasha** [comment]
Thank, but now another problem. Run this script.
```
npx @openapitools/openapi-generator-cli generate -i swagger.json -g csharp-netcore --library unityWebRequest -o sdk-unity/ --skip-validate-spec --global-property modelTests=false --global-property apiTests=false --global-property modelDocs=false --global-property apiDocs=false --additional-properties packageName=BX"
```
And get error:
```
Exception in thread "main" java.lang.RuntimeException: Unknown library: unityWebRequest
Available libraries:
  generichost
  httpclient
  restsharp
        at org.openapitools.codegen.DefaultCodegen.setLibrary(DefaultCodegen.java:5943)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:656)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:479)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

```
