### ISSUE TITLE
[REQ] Instructions to debug opaque error message

### ISSUE THREAD

**Issue by jzabroski** [OpenAPITools/openapi-generator#15431]
### Is your feature request related to a problem? Please describe.

I'm trying to compare .NET's NSwag code generator for C# to OpenAPI-Generator and evaluate which one is better.  OpenAPI's native support for RestSharp on the surface would seem like a clear winner.

When I run openapi-generator, I get an opaque error message that does not provide context.

I can't find "SwaggerConverter" in this project's code.  I think this library is internally using this third party API code: https://github.com/swagger-api/swagger-parser/blob/e5a23e8813df1462b9f90f9e535e8da80088bfb1/modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java#L1034 - it would be helpful to know if this is the case.

The error message is:

PS D:\Users\John.Zabroski\source\openapitools> java -jar .\openapi-generator-cli.jar generate -g csharp -i bundleGroupService.json -o BundleGroupClient.cs -v
[main] INFO  o.o.c.config.CodegenConfigurator -
VERBOSE MODE: ON. Additional debug options are injected
 - [debugOpenAPI] prints the OpenAPI specification as interpreted by the codegen
 - [debugModels] prints models passed to the template engine
 - [debugOperations] prints operations passed to the template engine
 - [debugSupportingFiles] prints additional data passed to the template engine
Exception in thread "main" java.lang.NumberFormatException: For input string: "true"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:1134)
        at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:608)
        at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:539)
        at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:250)
        at io.swagger.v3.parser.converter.SwaggerConverter.readResult(SwaggerConverter.java:104)
        at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:85)
        at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:589)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:647)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:479)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

## Describe the solution you'd like

Pointers in how to skip support and debug this problem myself.

## Describe alternatives you've considered

1. File a bug report. Bug the .json file is proprietary and behind an NDA, and it has 43,000 lines of JSON.
2. Reach out to third party vendor with the swagger.json service causing the problem. I'd like to provide more context before doing this.

**Comment by jzabroski** [comment]
I believe my immediate bad error message is due to the following rest parameter:

```
        {
          "name" : "_knitColumnMeta",
          "in" : "query",
          "description" : "Optional. maximum number of results that the request should return.",
          "required" : false,
          "type" : "integer",
          "enum" : [ "true", "false" ],
          "x-is-special-param" : true,
          "x-@CLASS" : "java.lang.String"
        }
```

I am guessing that the parser dislikes the combination of `"type" : "integer"` and `"enum" : [ "true", "false" ]`

**Comment by wing328** [comment]
right, if you remove `"enum" : [ "true", "false" ]`, that should workaround the problem before the vendor fixes the spec.

(also worth mentioning that csharp-netcore client generators support other HTTP libraries such as httpclient, generichost, `unityWebRequest` (e.g. via the --library option in the CLI)
