### ISSUE TITLE
[BUG] openapi-generator-cli with openapi-normalizer

### ISSUE THREAD

**Issue by srofin** [OpenAPITools/openapi-generator#15939]
##### Description

When trying to generate a Spring Boot Rest API Server with openapi-generator-cli with the openapi-normalizer option, the generation fails with 
```
Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
	at java.base/java.util.ArrayList.grow(ArrayList.java:238)
	at java.base/java.util.ArrayList.grow(ArrayList.java:243)
	at java.base/java.util.ArrayList.add(ArrayList.java:486)
	at java.base/java.util.ArrayList.add(ArrayList.java:499)
	at org.openapitools.codegen.DefaultCodegen.updateAllModels(DefaultCodegen.java:633)
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:529)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:921)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:487)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```
The input yaml file is valid according to https://editor.swagger.io
Generation without the open-normalizer option works fine (but produces unwanted ...AllOf model classes.

##### openapi-generator version

6.6.0 / 6.4.0

##### OpenAPI declaration file content or url

I cannot disclose the OpenAPI Spec (yaml).
Its openapi v 3.0.2 and rather large (21000+ lines)

##### Steps to reproduce

`java -jar openapi-generator-cli-6.6.0.jar generate -g spring -i openapi-v3.yaml -o spring --openapi-normalizer REF_AS_PARENT_IN_ALLOF=true`

or 

`java -Xmx16g -jar openapi-generator-cli-6.6.0.jar generate -g spring -i openapi-v3.yaml -o spring --openapi-normalizer REF_AS_PARENT_IN_ALLOF=true`

**Comment by rishyrane** [comment]
I am also getting this error. My json file is 2000 lines and I cannot share it. How were you able to fix this error?

**Comment by wing328** [comment]
hard to troubleshoot without a spec to reproduce the issue.

**Comment by rishyrane** [comment]
I believe the issue could have come from grandparent inheritance,


Or parameters called through allOf being named the same as a different class definition.

For e.g.

Class 1: {
     properties: {
      allOf: [{
        action : {
        
        $ref: /#/components/schema/actionResponse
       
      }]
     }
}


and then Class 2: {
     properties: {
      allOf: [{
        action : {
        
        $ref: /#/components/schema/actionsResponse
       
      }]
     }
}
