### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by MAKOMO** [OpenAPITools/openapi-generator#16071]
#### Bug Report Checklist

- [ x] Have you provided a full/minimal spec to reproduce the issue?
- [ x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x ] Have you searched for related issues/PRs?
- [x ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The python generator produces stubs which fail with an AttributeError on a query parameter of type string restricted by an enum.

##### openapi-generator version

I tested this on the current v7.0.0-beta as well as with todays trunk using the python (was python-nextgen) generator. This worked with the python and python-experimental generators of v6.0.

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: ""
  version: ""
paths:
  /items:
    get:
      operationId: getHidden
      summary: Get all hidden
      description: Returns all hidden entries
      parameters:
        - $ref: "#/components/parameters/hidden"
      responses:
        200:
            description: OK
components:
  parameters:
    hidden:
      name: hidden
      in: query
      schema:
        type: string
        enum:
          - only
          - 'true'
```

##### Generation Details

```
# java -jar openapi-generator-7.0.0-beta/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i openapi-schema.yaml -g python

# java -jar openapi-generator-master-2023-07-11/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i openapi-schema.yaml -g python
```

##### Steps to reproduce

```python
import time
import os
import openapi_client
from openapi_client.rest import ApiException
from pprint import pprint

configuration = openapi_client.Configuration(
    host = "http://localhost"
)

with openapi_client.ApiClient(configuration) as api_client:
    api_instance = openapi_client.DefaultApi(api_client)
    api_instance.get_hidden(hidden='only')
```

results in

```
... 
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
  File "/Users/luther/Documents/Projects/Artisan+/Repositories/artisanplusapi/Bugs/enum-string-no-attribute-value/openapi_client/api/default_api.py", line 74, in get_hidden
    return self.get_hidden_with_http_info(hidden, **kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
  File "/Users/luther/Documents/Projects/Artisan+/Repositories/artisanplusapi/Bugs/enum-string-no-attribute-value/openapi_client/api/default_api.py", line 149, in get_hidden_with_http_info
    _query_params.append(('hidden', _params['hidden'].value))
                                    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'value'
```
##### Related issues/PRs

Possible related to Issue #14524

##### Suggest a fix

Sorry

**Comment by mofr** [comment]
Faced the same problem. The type hint for parameter is StrictStr, but the code inside tries to access `value` attribute. I would expect the type hint to be a enum.

**Comment by RynoM** [comment]
Experiencing same issue here, any workaround to adjust the spec? Simply passing an enum value works, and the type hint is Any. Even though the docstring says type: <MyEnum>... Ideally the type hint would contain that too
