### ISSUE TITLE
[typescript-angular] Bug generating client library with ngVersion=7 

### ISSUE THREAD

**Issue by pkainz** [OpenAPITools/openapi-generator#1612]
##### Description

Generator `typescript-angular` delivers incompatible versions for Angular 7.x in `package.json`. This causes `npm install` to fail and blocks packaging the library using `npm run build`.

New dependencies in Angular 7 (according to the [release notes](https://github.com/angular/angular/blob/master/CHANGELOG.md#dependency-updates)) also should be upgraded to `rxjs 6.3.0+` and `typescript 3.1+`. 

##### openapi-generator version

v3.3.4 / master / latest

##### OpenAPI declaration file content or url

Example: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml

##### Command line used for generation

```bash
openapi-generator generate -i petstore.yaml -g typescript-angular -o petstore --additional-properties="npmName=petstore,npmVersion=0.9.0,withInterfaces=true,providedInRoot=true,ngVersion=7.1.1"
```

##### Steps to reproduce

1. Run the command to generate the output (see above)
2. Install the dependencies `npm install`, which creates these warnings:
```log
...
npm WARN @angular/core@7.1.1 requires a peer of zone.js@~0.8.26 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler-cli@7.1.1 requires a peer of typescript@>=3.1.1 <3.2 but none is installed. You must install peer dependencies yourself.
npm WARN ng-packagr@2.4.5 requires a peer of @angular/compiler@^5.0.0 || ^6.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-packagr@2.4.5 requires a peer of @angular/compiler-cli@^5.0.0 || ^6.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-packagr@2.4.5 requires a peer of tsickle@>=0.25.5 but none is installed. You must install peer dependencies yourself.
...
```
3. Ignore the warnings and move on to `npm run build`, as suggested in the `README.md`
```bash
$ npm run build

> petstore@0.9.0 build /builds/petstore
> ng-packagr -p ng-package.json

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'tsickle/src/tsickle'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/builds/kmlvision/ikosa/portal/portal-api/typescript-angular/portal-api-client/node_modules/ng-packagr/lib/ngc/create-emit-callback.js:15:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ikosa/portal-api-client@0.9.0-alpha build: `ng-packagr -p ng-package.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ikosa/portal-api-client@0.9.0-alpha build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-04T16_01_26_875Z-debug.log
ERROR: Job failed: exit code 1
 ```

I tracked the issue to the generated `package.json`, which uses a hard-coded version  of `ng-packagr` (`^2.4.1`), which actually installs `2.4.5`. This now requires an additional dependency `tsickle` in a compatible version and seems to be the cause for being incompatible with the new/current Angular 7.x stack.

```json
{
  "name": "petstore",
  "version": "0.9.0",
  "description": "OpenAPI client for petstore",
  "author": "OpenAPI-Generator Contributors",
  "keywords": [
    "openapi-client",
    "openapi-generator"
  ],
  "license": "Unlicense",
  "scripts": {
    "build": "ng-packagr -p ng-package.json"
  },
  "peerDependencies": {
    "@angular/core": "^7.1.1",
    "@angular/http": "^7.1.1",
    "@angular/common": "^7.1.1",
    "@angular/compiler": "^7.1.1",
    "core-js": "^2.4.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^6.1.0"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^7.1.1",
    "@angular/core": "^7.1.1",
    "@angular/http": "^7.1.1",
    "@angular/common": "^7.1.1",
    "@angular/compiler": "^7.1.1",
    "@angular/platform-browser": "^7.1.1",
    "ng-packagr": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^6.1.0",
    "zone.js": "^0.7.6 || ^0.8.26",
    "typescript": ">=2.1.5 <2.8"
  }
}
```

##### Related issues/PRs

https://github.com/ng-packagr/ng-packagr/issues/605

##### Suggest a fix/enhancement

- Change the way the typescript-angular template is parameterized due to the Angular / Typescript / RxJS / ZoneJS / ng-packagr compatibility issues. 
- Suggest package versions that are known to be compatible to the Angular 2-7 versions

**Comment by misaelito76** [comment]
ng update --all --force

ng update is not working full so you add force and it will work
