### ISSUE TITLE
[BUG][C#]Additional logging to debug OOM exception

### ISSUE THREAD

**Issue by PeterVaccaITR** [OpenAPITools/openapi-generator#16347]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

2.7.0

##### OpenAPI declaration file content or url
https://gist.github.com/PeterVaccaITR/04c4d1875096acdca665b49edfa72c76.js
##### Generation Details
` "swagger:gen:lp-api:mac": "set JAVA_OPTS=\"%JAVA_OPTS% -Dlog.level=debug -Dio.swagger.parser.util.RemoteUrl.trustAll=true -Dio.swagger.v3.parser.util.RemoteUrl.trustAll=true\" && npx @openapitools/openapi-generator-cli generate -i https://localhost:7176/v3/apis/il-inview/swagger/swagger.json --additional-properties=withInterfaces=true,modelPropertyNaming=original,withSeparateModelsAndApi=true,legacyDiscriminatorBehavior=false --skip-validate-spec --api-package lp-offering-api --model-package models -g typescript-axios -o ./src/swagger/lp-offering-api",`

##### Steps to reproduce

Running the above results in a OOM heap space exception. I don't see any additional logging with the `-Dlog.level=debug `

`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOfRange(Arrays.java:3822)
	at java.base/java.lang.String.<init>(String.java:4531)
	at java.base/java.lang.String.<init>(String.java:1487)
	at java.base/java.lang.StringBuilder.toString(StringBuilder.java:453)
	at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:465)
	at com.fasterxml.jackson.core.io.SegmentedStringWriter.getAndClear(SegmentedStringWriter.java:85)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1146)
	at io.swagger.v3.core.util.Json.pretty(Json.java:24)
	at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:2982)
	at org.openapitools.codegen.DefaultCodegen.handleMethodResponse(DefaultCodegen.java:4271)
	at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:4435)
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1189)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1115)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:586)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:949)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:487)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)`

**Comment by PeterVaccaITR** [comment]
As an additional note, commenting out the Search method from BulkDownloadController makes the following changes and allows for the swagger generation to complete.
`--- swagger_bad.json	2023-08-18 13:49:07
+++ swagger_good.json	2023-08-18 13:46:27
@@ -2017,116 +2017,6 @@
         }
       }
     },
-    "/v3/apis/il-inview/bulkdownload/search": {
-      "get": {
-        "tags": [
-          "BulkDownload"
-        ],
-        "summary": "Search BulkDownload using available filters.",
-        "parameters": [
-          {
-            "name": "IncludeActive",
-            "in": "query",
-            "schema": {
-              "type": "boolean"
-            }
-          },
-          {
-            "name": "Offset",
-            "in": "query",
-            "schema": {
-              "type": "integer",
-              "format": "int32",
-              "default": 0
-            }
-          },
-          {
-            "name": "Limit",
-            "in": "query",
-            "schema": {
-              "type": "integer",
-              "format": "int32",
-              "default": 20
-            }
-          },
-          {
-            "name": "Sort.Field",
-            "in": "query",
-            "schema": {
-              "type": "string",
-              "default": "name"
-            }
-          },
-          {
-            "name": "Sort.SortOrder",
-            "in": "query",
-            "schema": {
-              "$ref": "#/components/schemas/SortOrder"
-            }
-          },
-          {
-            "name": "Fields",
-            "in": "query",
-            "schema": {
-              "uniqueItems": true,
-              "type": "array",
-              "items": {
-                "type": "string"
-              }
-            }
-          },
-          {
-            "name": "Filter",
-            "in": "query",
-            "schema": {
-              "type": "string"
-            }
-          },
-          {
-            "name": "Portal-Id",
-            "in": "header",
-            "description": "Header to set Portal Id for all CRUD requests",
-            "required": true,
-            "schema": {
-              "type": "string"
-            },
-            "example": "b8d36f60-f86c-11ec-b939-0242ac120002"
-          }
-        ],
-        "responses": {
-          "500": {
-            "description": "Server Error",
-            "content": {
-              "application/json": {
-                "schema": {
-                  "$ref": "#/components/schemas/Result"
-                }
-              }
-            }
-          },
-          "400": {
-            "description": "Bad Request",
-            "content": {
-              "application/json": {
-                "schema": {
-                  "$ref": "#/components/schemas/Result"
-                }
-              }
-            }
-          },
-          "200": {
-            "description": "Success",
-            "content": {
-              "application/json": {
-                "schema": {
-                  "$ref": "#/components/schemas/BulkDownloadPaginatedResult"
-                }
-              }
-            }
-          }
-        }
-      }
-    },
     "/v3/apis/il-inview/bulkdownload/{id}": {
       "get": {
         "tags": [
\ No newline at end of file
@@ -16061,25 +15951,6 @@
         },
         "additionalProperties": false
       },
-      "BulkDownloadPaginatedResult": {
-        "type": "object",
-        "properties": {
-          "_meta": {
-            "$ref": "#/components/schemas/ResultMetadata"
-          },
-          "_status": {
-            "$ref": "#/components/schemas/ResultPageStatus"
-          },
-          "data": {
-            "type": "array",
-            "items": {
-              "$ref": "#/components/schemas/BulkDownload"
-            },
-            "nullable": true
-          }
-        },
-        "additionalProperties": false
-      },
       "BulkDownloadResult": {
         "type": "object",
         "properties": {
\ No newline at end of file
`

the above is the only difference in the spec file.

**Comment by devhl-labs** [comment]
Why is c# in the description when the config says typescript?
