### ISSUE TITLE
[BUG][JAVA] Integers as array default type cause ClassCastException in code generation

### ISSUE THREAD

**Issue by simon-spinner** [OpenAPITools/openapi-generator#16426]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

If an external path item is included from a separate spec file and this path item contains a parameter of type array of integers and has a default value specified, the code generation (in this case jaxrs-spec) fails with a ClassCastException:

```
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
        at org.openapitools.codegen.languages.AbstractJavaCodegen.toArrayDefaultValue(AbstractJavaCodegen.java:991)
        at org.openapitools.codegen.languages.AbstractJavaCodegen.toDefaultValue(AbstractJavaCodegen.java:1063)
        at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:4129)
        at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:3841)
        at org.openapitools.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:5116)
        at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:4636)
        at org.openapitools.codegen.languages.AbstractJavaCodegen.fromOperation(AbstractJavaCodegen.java:1751)
        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1193)
```

If the path item is not in a separate file, code generation is successful.

##### openapi-generator version

7.0.0

**Regression:** Same specification works in 6.6.0

##### OpenAPI declaration file content or url
openapi-spec.yaml:
```yaml
openapi: 3.0.2
info:
  title: 'Repro'
  version: 1.0.0
paths:
  '/repro':
    $ref: './test.yaml#/paths/repro'
```
test.yaml
```yaml
openapi: 3.0.2
info:
  title: 'Repro'
  version: 1.0.0
paths:
  'repro':
    get:
      parameters:
        - name: array
          in: query
          schema:
            type: array
            items:
              type: integer
            default:
              - 1
      responses:
        '200':
          description: OK
```

##### Generation Details

jaxrs-spec

**Comment by wing328** [comment]
thanks for reporting the issue, which has been fixed via #16434
