### ISSUE TITLE
[BUG] OpenAPI Generator CLI does not recognize Spec v3.0 output created by TSOA

### ISSUE THREAD

**Issue by vandadnp** [OpenAPITools/openapi-generator#16486]
##### Description

The OpenAPI Generator CLI does not recognize Spec v3.0 output created by TSOA

##### openapi-generator version

```bash
npx openapi-generator-cli version  
7.0.0
```

##### Steps to reproduce

1. Clone this repository => https://github.com/vandadnp/testingswagger
2. CD into root folder of the cloned repo
3. `npm install`
4. `npm run build`
5. `npm run dev`

Now that the server is up and running go into another folder in Terminal and:

1. `npm install @openapitools/openapi-generator-cli`
2. `curl http://localhost:5555/swagger.json --output swagger.json`
3. `npx openapi-generator-cli generate -i swagger.json -g dart-dio -o ./api/`

And you will get the following results:

```bash
npx openapi-generator-cli generate -i swagger.json -g dart-dio -o ./api/
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 0
Errors:
	-attribute default is unexpected

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:668)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:695)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:503)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

**Comment by wing328** [comment]
> 	-attribute default is unexpected

looks like the spec is invalid.

> The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).

You can workaround it for the time being

**Comment by vandadnp** [comment]
Thank you for your response

I noticed that in my app.ts I was serving the tsoa.json (swagger.json) as a module, instead of a raw file. I changed it to `res.sendFile()` and it fixed the issue.

Thank you again
