### ISSUE TITLE
[BUG] [csharp] System.NotImplementedException exception in ApiClient.cs with OAuth2

### ISSUE THREAD

**Issue by graemevwilson** [OpenAPITools/openapi-generator#16660]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using a client generated for an API that is secured using OAuth2 the following exception occurs for all requests to the API:
```
Unhandled Exception: System.NotImplementedException: Set the RestClientOptions.Authenticator property instead
   at RestSharp.RestClientExtensions.UseAuthenticator(RestClient client, IAuthenticator authenticator)
   at MyProj.OAuthService.Client.ApiClient.Exec[T](RestRequest request, RequestOptions options, IReadableConfiguration configuration) in C:\Source\OAuthSolution\src\MyProj.OAuthService\Client\ApiClient.cs:line 466
   at MyProj.OAuthService.Client.ApiClient.Get[T](String path, RequestOptions options, IReadableConfiguration configuration) in C:\Source\OAuthSolution\src\MyProj.OAuthService\Client\ApiClient.cs:line 773
   at MyProj.OAuthService.Api.UsersApi.ListUsersWithHttpInfo(String organizationRef, String search, String userName, String email, String firstName, String lastName, Nullable`1 enabled, Nullable`1 requireEmailVerification, Nullable`1 requireMFA, Nullable`1 requirePasswordReset, Nullable`1 limit, String cursor, Int32 operationIndex) in C:\Source\OAuthSolution\src\MyProj.OAuthService\Api\UsersApi.cs:line 2681
   at MyProj.OAuthService.Api.UsersApi.ListUsers(String organizationRef, String search, String userName, String email, String firstName, String lastName, Nullable`1 enabled, Nullable`1 requireEmailVerification, Nullable`1 requireMFA, Nullable`1 requirePasswordReset, Nullable`1 limit, String cursor, Int32 operationIndex) in C:\Source\OAuthSolution\src\MyProj.OAuthService\Api\UsersApi.cs:line 2560
   at IdentityService.Console.NETFW.DisableUser.Main(String[] args) in C:\Source\OAuthSolution\src\MyProj.OAuthConsole\DisableUser.cs:line 28
```

I think this defect has appeared since the RestSharp dependency got updated from v108 to v110.

##### openapi-generator version

Version 7.0.1

##### Generation Details

java -jar openapi-generator-cli.jar generate -i service.json -g csharp -o ./ --additional-properties=targetFramework=netstandard2.0

##### Steps to reproduce

Generate the client code for an API using a securityScheme of oauth2 with the client credential flow.
Call any API operation that is secured with OAuth2.

##### Related issues/PRs

None Found

##### Suggest a fix

I can prepare a PR for this.

**Comment by graemevwilson** [comment]
Suggested fix: https://github.com/OpenAPITools/openapi-generator/pull/16661
