### ISSUE TITLE
[BUG][CSHARP] Mixing object/array/primitive types in anyOf/oneOf for csharp generators generates client code that fails to deserialize.

### ISSUE THREAD

**Issue by ForgeRubenAguilar** [OpenAPITools/openapi-generator#16686]
#### Bug Report Checklist

- [ x ] Have you provided a full/minimal spec to reproduce the issue?
- [ x ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ x ] Have you searched for related issues/PRs?
- [ x ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Mixing object/array/primitive types in anyOf/oneOf for csharp generators generates client code that fails to deserialize.

Expect object to deserialize to C# typed object properly. Currently throws:

```
Unhandled exception. Pets.Client.ApiException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Boolean. Path 'content', line 2, position 17.
   at Pets.Client.CustomJsonCodec.Deserialize(HttpResponseMessage response, Type type) in /Users/rubenaguilar/repo/openapi/openapi-generator/project/generated/csharp/src/Pets/Client/ApiClient.cs:line 151
   at Pets.Client.CustomJsonCodec.Deserialize[T](HttpResponseMessage response) in /Users/rubenaguilar/repo/openapi/openapi-generator/project/generated/csharp/src/Pets/Client/ApiClient.cs:line 86
   at Pets.Client.ApiClient.ExecAsync[T](HttpRequestMessage req, IReadableConfiguration configuration, CancellationToken cancellationToken)
   at Pets.Api.PetTagApi.GetPetAnyOfByIdWithHttpInfoAsync(Int64 petId, CancellationToken cancellationToken) in /Users/rubenaguilar/repo/openapi/openapi-generator/project/generated/csharp/src/Pets/Api/PetTagApi.cs:line 436
   at Pets.Api.PetTagApi.GetPetAnyOfByIdAsync(Int64 petId, CancellationToken cancellationToken) in /Users/rubenaguilar/repo/openapi/openapi-generator/project/generated/csharp/src/Pets/Api/PetTagApi.cs:line 400
```

##### openapi-generator version

Using 7.0.1 of the jar. 

##### OpenAPI declaration file content or url

I tacked on a small repro dotnet [console app on my fork](https://github.com/ForgeRubenAguilar/openapi-generator/tree/csharp/issue-console-app/project) with run scripts for the broken and fixed template scenarios.

Generating a client with [this OpenApi Spec](https://github.com/ForgeRubenAguilar/openapi-generator/blob/csharp/issue-console-app/project/OpenApi/openapi_spec.yml) then triggering a deserialization of [this Json data](https://github.com/ForgeRubenAguilar/openapi-generator/blob/csharp/issue-console-app/project/Data/Pets-string.json) will cause deserialization to fail.

##### Generation Details

[This script](https://github.com/ForgeRubenAguilar/openapi-generator/blob/csharp/issue-console-app/project/run-broken.sh) runs against [this config.](https://github.com/ForgeRubenAguilar/openapi-generator/blob/csharp/issue-console-app/project/OpenApi/config-csharp-broken.json)

##### Steps to reproduce

Running [run-broken.sh](https://github.com/ForgeRubenAguilar/openapi-generator/tree/csharp/issue-console-app/project) to run the dotnet console app with yarn and dotnet 6.0+ installed will reproduce the exception.

##### Related issues/PRs

I didn't see any for csharp specifically.

##### Suggest a fix

I have the current fixed templates we're using as a workaround on a branch on my fork. [Diffs here.](https://github.com/OpenAPITools/openapi-generator/compare/master...ForgeRubenAguilar:csharp/anyof-oneof-mixed-primitive-object-parse-error?expand=1) I'm not entirely sure how this would be tested within this project.

**Comment by wing328** [comment]
can you please file a PR to start wth?
