### ISSUE TITLE
[BUG] Generator breaks on empty properties fields in components.

### ISSUE THREAD

**Issue by davegarred** [OpenAPITools/openapi-generator#17172]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

Generator breaks on empty properties fields in components.

##### openapi-generator version

7.2.0-SNAPSHOT
commit: 0d2a01611c8350b596a2b883964da2589e7baa93

##### OpenAPI declaration file content or url

The [Discord API](https://github.com/discord/discord-api-spec/blob/main/specs/openapi.json) contains multiple empty properties which break in this tool but are valid. I've pushed up a [simpler version taken](https://raw.githubusercontent.com/davegarred/openapi-generator/test_empty_property/openapi.json) taken from that.

##### Generation Details

Attempt to generate a client from a spec that includes a schema with property that is empty.
E.g.,
```json
"components": {
  "schemas": {
    "GithubWebhook": {
      "type": "object",
      "properties": {
        "pull_request": {}
      }
    }
  }
}
```

A `NullPointerException` is produced.
```
Exception: null
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1269)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1163)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:609)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:994)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:519)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException
	at org.openapitools.codegen.examples.ExampleGenerator.resolvePropertyToExample(ExampleGenerator.java:228)
	at org.openapitools.codegen.examples.ExampleGenerator.resolveModelToExample(ExampleGenerator.java:352)
	at org.openapitools.codegen.examples.ExampleGenerator.resolvePropertyToExample(ExampleGenerator.java:311)
	at org.openapitools.codegen.examples.ExampleGenerator.resolveModelToExample(ExampleGenerator.java:352)
	at org.openapitools.codegen.examples.ExampleGenerator.generate(ExampleGenerator.java:159)
	at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:4673)
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1237)
	... 6 more
```
##### Steps to reproduce
Generate using the cli tool (any language).
```
docker run --rm -v ./:/local \
  openapitools/openapi-generator-cli \
  generate \
  -g rust \
  -o /local/output_directory \
  -i /local/openapi.json
```
##### Related issues/PRs

None found yet.

##### Suggest a fix

_Edit: https://github.com/OpenAPITools/openapi-generator/pull/17173/files_

**Comment by wing328** [comment]
thanks for reporting the issue.

I've filed https://github.com/OpenAPITools/openapi-generator/issues/17172 to address the NPE in example generator.

Will file another PR later to better support any type in 3.1 spec.

**Comment by wing328** [comment]
merged the fix to the master. please pull the latest master to give it a try.
