### ISSUE TITLE
[BUG] Using $ref for schema definition for server sent event (SEE) though spring-boot generator raise null pointer exception

### ISSUE THREAD

**Issue by axel7083** [OpenAPITools/openapi-generator#17271]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

We are using gradle plugin version 7.1.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  description: apis
  version: 1.0.0
  title: debug-apis

paths:
  /stream:
    get:
      summary: Get the notifications stream
      operationId: getNotificationsStream
      responses:
        "200":
          $ref: "#/components/responses/NotificationStream"

components:
  schemas:
    Notification:
      type: object
      properties:
        message:
          type: string

    NotificationArray:
      type: array
      format: event-stream
      items:
        $ref: '#/components/schemas/Notification'

  responses:
    NotificationStream:
      description: notification stream
      content:
        text/event-stream:
          schema:
            $ref: '#/components/schemas/NotificationArray'
```

##### Generation Details

The configuration file used, you can make the generation work by changing `serverSentEvents` from `true` to `false`.
```json
{
  "library": "spring-boot",
  "apiPackage": "com.example.api",
  "invokerPackage": "com.example.invoker",
  "modelPackage": "com.example.model",
  "hideGenerationTimestamp": "true",
  "generatePom": "false",
  "title": "debug-title",
  "interfaceOnly": "true",
  "serverSentEvents": "true",
  "delegatePattern": "true",
  "reactive": "true",
  "unhandledException": "true",
  "dateLibrary": "java8",
  "useSpringBoot3": "true"
}

```

##### Steps to reproduce

See https://github.com/OpenAPITools/openapi-generator/pull/17273 for test use case failing

##### Schemas leading to issue

The schema above produces

>   Exception: element cannot be mapped to a null key
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1269)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1160)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:609)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:994)
	at org.openapitools.generator.gradle.plugin.tasks.GenerateTask.doWork(GenerateTask.kt:925)
	... 122 more
Caused by: java.lang.NullPointerException: element cannot be mapped to a null key
	at org.openapitools.codegen.languages.SpringCodegen.fromOperation(SpringCodegen.java:1288)
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1237)
	... 126 more
##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/16543

##### Suggest a fix

If we place the schema definition directly in the response it works.

```yaml
....
  responses:
    NotificationStream:
      description: notification stream
      content:
        text/event-stream:
          schema:
            type: array
            format: event-stream
            items:
              $ref: '#/components/schemas/Notification'
```

**Comment by axel7083** [comment]
CC @krasv @wing328
