### ISSUE TITLE
[BUG] [Python] NullPointerException when no type is defined for value

### ISSUE THREAD

**Issue by waterfallwhitebread** [OpenAPITools/openapi-generator#17302]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I am generating my openapi (3.1) specs via fastapi (Python). Using typing.Any generates a spec where the "type" attribute of a value is missing. The openapi-generator for Python seems unable to use this spec as it aborts with a NullPointerException. If I modify typing to: `"type": ["number","string","boolean","object","array", "null"]` the generation of the client works as expected. To my understanding a missing type should be equivalent to all types are valid (see also https://github.com/OAI/OpenAPI-Specification/issues/1388#issuecomment-339061316), online OpenAPI validator accepts the spec as valid.

Exception:

```
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: class Tag {
    name: My Configurations
    description: null
    externalDocs: null
}
  Operation: get_config_value_config_get_config_value_post
  Resource: post /config/get_config_value
  Schemas: {MyConfigValue=class JsonSchema {
    class Schema {
        type: [object]
        format: null
        $ref: null
        description: Some description.
        title: MyConfigValue
        multipleOf: null
        maximum: null
        exclusiveMaximum: null
        minimum: null
        exclusiveMinimum: null
        maxLength: null
        minLength: null
        pattern: null
        maxItems: null
        minItems: null
        uniqueItems: null
        maxProperties: null
        minProperties: null
        required: [value]
        not: null
        properties: {value=null}
        additionalProperties: null
        nullable: null
        readOnly: null
        writeOnly: null
        example: null
        externalDocs: null
        deprecated: null
        discriminator: null
        xml: null
        patternProperties: null
        contains: null
        $id: null
        $anchor: null
        $schema: null
        $vocabulary: null
        $dynamicAnchor: null
        const: null
        contentEncoding: null
        contentMediaType: null
        contentSchema: null
        propertyNames: null
        unevaluatedProperties: null
        maxContains: null
        minContains: null
        additionalItems: null
        unevaluatedItems: null
        _if: null
        _else: null
        then: null
        dependentRequired: null
        dependentSchemas: null
        $comment: null
        prefixItems: null
    }
}, GetMyConfigValueRequest=class JsonSchema {
    class Schema {
        type: [object]
        format: null
        $ref: null
        description: Request to get a nested value from a config.
        title: GetMyConfigValueRequest
        multipleOf: null
        maximum: null
        exclusiveMaximum: null
        minimum: null
        exclusiveMinimum: null
        maxLength: null
        minLength: null
        pattern: null
        maxItems: null
        minItems: null
        uniqueItems: null
        maxProperties: null
        minProperties: null
        required: [config_path, file_in_config, nested_keys]
        not: null
        properties: {config_path=class JsonSchema {
            class Schema {
                type: [string]
                format: null
                $ref: null
                description: null
                title: Config Path
                multipleOf: null
                maximum: null
                exclusiveMaximum: null
                minimum: null
                exclusiveMinimum: null
                maxLength: null
                minLength: null
                pattern: null
                maxItems: null
                minItems: null
                uniqueItems: null
                maxProperties: null
                minProperties: null
                required: null
                not: null
                properties: null
                additionalProperties: null
                nullable: null
                readOnly: null
                writeOnly: null
                example: null
                externalDocs: null
                deprecated: null
                discriminator: null
                xml: null
                patternProperties: null
                contains: null
                $id: null
                $anchor: null
                $schema: null
                $vocabulary: null
                $dynamicAnchor: null
                const: null
                contentEncoding: null
                contentMediaType: null
                contentSchema: null
                propertyNames: null
                unevaluatedProperties: null
                maxContains: null
                minContains: null
                additionalItems: null
                unevaluatedItems: null
                _if: null
                _else: null
                then: null
                dependentRequired: null
                dependentSchemas: null
                $comment: null
                prefixItems: null
            }
        }, file_in_config=class JsonSchema {
            class Schema {
                type: [string]
                format: null
                $ref: null
                description: null
                title: File In Config
                multipleOf: null
                maximum: null
                exclusiveMaximum: null
                minimum: null
                exclusiveMinimum: null
                maxLength: null
                minLength: null
                pattern: null
                maxItems: null
                minItems: null
                uniqueItems: null
                maxProperties: null
                minProperties: null
                required: null
                not: null
                properties: null
                additionalProperties: null
                nullable: null
                readOnly: null
                writeOnly: null
                example: null
                externalDocs: null
                deprecated: null
                discriminator: null
                xml: null
                patternProperties: null
                contains: null
                $id: null
                $anchor: null
                $schema: null
                $vocabulary: null
                $dynamicAnchor: null
                const: null
                contentEncoding: null
                contentMediaType: null
                contentSchema: null
                propertyNames: null
                unevaluatedProperties: null
                maxContains: null
                minContains: null
                additionalItems: null
                unevaluatedItems: null
                _if: null
                _else: null
                then: null
                dependentRequired: null
                dependentSchemas: null
                $comment: null
                prefixItems: null
            }
        }, nested_keys=class ArraySchema {
            class Schema {
                type: array
                format: null
                $ref: null
                description: null
                title: null
                multipleOf: null
                maximum: null
                exclusiveMaximum: null
                minimum: null
                exclusiveMinimum: null
                maxLength: null
                minLength: null
                pattern: null
                maxItems: null
                minItems: null
                uniqueItems: null
                maxProperties: null
                minProperties: null
                required: null
                not: null
                properties: null
                additionalProperties: null
                nullable: null
                readOnly: null
                writeOnly: null
                example: null
                externalDocs: null
                deprecated: null
                discriminator: null
                xml: null
            }
        }}
        additionalProperties: null
        nullable: null
        readOnly: null
        writeOnly: null
        example: null
        externalDocs: null
        deprecated: null
        discriminator: null
        xml: null
        patternProperties: null
        contains: null
        $id: null
        $anchor: null
        $schema: null
        $vocabulary: null
        $dynamicAnchor: null
        const: null
        contentEncoding: null
        contentMediaType: null
        contentSchema: null
        propertyNames: null
        unevaluatedProperties: null
        maxContains: null
        minContains: null
        additionalItems: null
        unevaluatedItems: null
        _if: null
        _else: null
        then: null
        dependentRequired: null
        dependentSchemas: null
        $comment: null
        prefixItems: null
    }
}}
  Exception: null
        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1269)
        at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1163)
        at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:609)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:994)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:519)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException
        at org.openapitools.codegen.examples.ExampleGenerator.resolvePropertyToExample(ExampleGenerator.java:228)
        at org.openapitools.codegen.examples.ExampleGenerator.resolveModelToExample(ExampleGenerator.java:352)
        at org.openapitools.codegen.examples.ExampleGenerator.generate(ExampleGenerator.java:159)
        at org.openapitools.codegen.examples.ExampleGenerator.generateFromResponseSchema(ExampleGenerator.java:95)
        at org.openapitools.codegen.examples.ExampleGenerator.generateFromResponseSchema(ExampleGenerator.java:60)
        at org.openapitools.codegen.DefaultCodegen.handleMethodResponse(DefaultCodegen.java:4426)
        at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:4603)
        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1237)
        ... 6 more

```

##### openapi-generator version

7.1.0 (also tried snapshot of 7.2.0 on 01.12.2023)

##### OpenAPI declaration file content or url

```json
{
    "openapi": "3.1.0",
    "info": {
        "title": "MY.FANCY.API",
        "version": "0.1.0"
    },
    "servers": [{
            "url": "/",
            "description": "Local"
        }
    ],
    "paths": {
        "/config/get_config_value": {
            "post": {
                "tags": ["My Configurations"],
                "summary": "Get Config Value",
                "description": "Some description.",
                "operationId": "get_config_value_config_get_config_value_post",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/GetMyConfigValueRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/MyConfigValue"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "MyConfigValue": {
                "properties": {
                    "value": {
                        "title": "Value"
                    }
                },
                "type": "object",
                "required": ["value"],
                "title": "MyConfigValue",
                "description": "Some description."
            },
			"GetMyConfigValueRequest": {
                "properties": {
                    "config_path": {
                        "type": "string",
                        "title": "Config Path"
                    },
                    "file_in_config": {
                        "type": "string",
                        "title": "File In Config"
                    },
                    "nested_keys": {
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "title": "Nested Keys"
                    }
                },
                "type": "object",
                "required": ["config_path", "file_in_config", "nested_keys"],
                "title": "GetMyConfigValueRequest",
                "description": "Request to get a nested value from a config."
            }
        }
    }
}
```

##### Generation Details

npx @openapitools/openapi-generator-cli generate -i 'C:\xxx\my_api_openapi.json' -g python -o 'C:\xxx\python\dev\my_client' -p library=asyncio -p packageName=communication.my_rest_client --skip-validate-spec

##### Steps to reproduce

Just call the generator with provided spec

##### Related issues/PRs

Did not find any

##### Suggest a fix

-

**Comment by wing328** [comment]
tested with the latest master and couldn't repeat the issue

please give it a try with the latest master

happy to reopen the issue if needed
