### ISSUE TITLE
Return value of "io.swagger.v3.oas.models.media.Schema.getTypes()" is null with v7.2.0

### ISSUE THREAD

**Issue by stanislav-georgiev-tt** [OpenAPITools/openapi-generator#17524]
##### Description

Even though I am able to build successfully during the build process I get the following error: 
An exception occurred in OpenAPI Normalizer
java.lang.NullPointerException: Cannot invoke "java.util.Set.contains(Object)" because the return value of "io.swagger.v3.oas.models.media.Schema.getTypes()" is null
With the same input *json file and using generator 7.1.0 I was unable to generate code due to: java.lang.NullPointerException: [1;31mCannot invoke "io.swagger.v3.oas.models.media.Schema.getExample()" because "property" is null
##### openapi-generator version

7.2.0

##### OpenAPI declaration file content or url

```json
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "anyOf": [
                                        {
                                            "$ref": "#/components/schemas/Request-Output"
                                        },
                                        {
                                            "type": "null"
                                        }
                                    ],
                                    "title": "Response Set Session Param Ai V0 Setsessionparam  Post"
                                }
                            }
                        }
                    },

```
The issue is assumably in any of these lines of code since when I delete them, the error is gone.
##### Command line used for generation

mvn clean install

**Comment by wing328** [comment]
can you please share the full spec to reproduce the issue?

**Comment by samidarko** [comment]
Got the same issue. Not happening with 7.1.0. Unfortunately I can't share the spec.

**Comment by stanislav-georgiev-tt** [comment]
Hello, I can't share it either.

**Comment by wing328** [comment]
> An exception occurred in OpenAPI Normalizer

Can you provide the full stack trace?

Also what about disabling all normalizer rules? e.g. `--openapi-normalizer DISABLE_ALL=true`

**Comment by stanislav-georgiev-tt** [comment]
Here is the complete trace: 
`[[1;34mINFO[m] [1m--- [0;32mopenapi-generator:7.2.0:generate[m [1m(generate-client)[m @ [36m[0;1m ---[m
[[1;33mWARNING[m] Generation using 3.1.0 specs is in development and is not officially supported yet. If you would like to expedite development, please consider woking on the open issues in the 3.1.0 project: https://github.com/orgs/OpenAPITools/projects/4/views/1 and reach out to our team on Slack at https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g
[[1;34mINFO[m] Generating with dryRun=false
[[1;34mINFO[m] No .openapi-generator-ignore file found.
[[1;34mINFO[m] OpenAPI Generator: java (client)
[[1;34mINFO[m] Generator 'java' is considered stable.
[[1;34mINFO[m] Environment variable JAVA_POST_PROCESS_FILE not defined so the Java code may not be properly formatted. To define it, try 'export JAVA_POST_PROCESS_FILE="/usr/local/bin/clang-format -i"' (Linux/Mac)
[[1;34mINFO[m] NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[[1;34mINFO[m] Invoker Package Name, originally not set, is now derived from api package name: tech.turbulence.biovet/client
[[1;33mWARNING[m] Invalid openapi-normalizer rule name: 
[[1;31mERROR[m] An exception occurred in OpenAPI Normalizer. Please report the issue via https://github.com/openapitools/openapi-generator/issues/new/: 
java.lang.NullPointerException: Cannot invoke "java.util.Set.contains(Object)" because the return value of "io.swagger.v3.oas.models.media.Schema.getTypes()" is null
	at org.openapitools.codegen.OpenAPINormalizer.processNormalize31Spec(OpenAPINormalizer.java:937)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeSimpleSchema(OpenAPINormalizer.java:461)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeSchema(OpenAPINormalizer.java:452)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeProperties(OpenAPINormalizer.java:478)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeSchema(OpenAPINormalizer.java:446)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeComponentsSchemas(OpenAPINormalizer.java:375)
	at org.openapitools.codegen.OpenAPINormalizer.normalize(OpenAPINormalizer.java:196)
	at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:274)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:1221)
	at org.openapitools.codegen.plugin.CodeGenMojo.execute(CodeGenMojo.java:936)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
[[1;34mINFO[m] Inline schema created as Response_Ai_Entry_Point_Ai__Post. To have complete control of the model name, set the `title` field or use the modelNameMapping option (e.g. --model-name-mappings Response_Ai_Entry_Point_Ai__Post=NewModel,ModelA=NewModelA in CLI) or inlineSchemaNameMapping option (--inline-schema-name-mappings Response_Ai_Entry_Point_Ai__Post=NewModel,ModelA=NewModelA in CLI).
[[1;34mINFO[m] Inline schema created as ValidationError_loc_inner. To have complete control of the model name, set the `title` field or use the modelNameMapping option (e.g. --model-name-mappings ValidationError_loc_inner=NewModel,ModelA=NewModelA in CLI) or inlineSchemaNameMapping option (--inline-schema-name-mappings ValidationError_loc_inner=NewModel,ModelA=NewModelA in CLI).
[[1;34mINFO[m] Processing operation root__get
[[1;34mINFO[m] Processing operation ai_entry_point_AI__post
[[1;34mINFO[m] Processing operation get_api_version_AI_v0_getApiVersion__post
[[1;34mINFO[m] Processing operation open_session_AI_v0_openSession__post
[[1;34mINFO[m] Processing operation close_session_AI_v0_closeSession__post
[[1;34mINFO[m] Processing operation set_session_param_AI_v0_setSessionParam__post
[[1;34mINFO[m] Processing operation predict_process_AI_v0_predictProcess__post
[[1;33mWARNING[m] Generation using 3.1.0 specs is in development and is not officially supported yet. If you would like to expedite development, please consider woking on the open issues in the 3.1.0 project: https://github.com/orgs/OpenAPITools/projects/4/views/1 and reach out to our team on Slack at https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g
[[1;34mINFO[m] 'host' (OAS 2.0) or 'servers' (OAS 3.0) not defined in the spec. Default to [http://localhost] for server URL [http://localhost/]
[[1;34mINFO[m] 'host' (OAS 2.0) or 'servers' (OAS 3.0) not defined in the spec. Default to [http://localhost] for server URL [http://localhost/]`

Adding this inside my pom file doesn't fix the issue:
<openapiNormalizer>
<DISABLE_ALL>true</DISABLE_ALL>
</openapiNormalizer>

**Comment by wing328** [comment]
should be fixed via https://github.com/OpenAPITools/openapi-generator/commit/c6efe8810df39ba04b89f9c4886eb5e808848bd6

please pull the latest master to give it a try
