### ISSUE TITLE
[BUG] NullPointerException: Cannot invoke "java.util.Set.contains(Object)" because the return value of "io.swagger.v3.oas.models.media.Schema.getTypes()" is null

### ISSUE THREAD

**Issue by Trolldemorted** [OpenAPITools/openapi-generator#17601]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists? **[we tested with the :latest docker image]**
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Since 7.2.0, openapi-generator-cli is printing a stacktrace and incorrectly typing typescript interfaces (everything becomes `any`):
```
[main] WARN  o.o.codegen.DefaultCodegen - Generation using 3.1.0 specs is in development and is not officially supported yet. If you would like to expedite development, please consider woking on the open issues in the 3.1.0 project: https://github.com/orgs/OpenAPITools/projects/4/views/1 and reach out to our team on Slack at https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: typescript-fetch (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'typescript-fetch' is considered stable.
[main] INFO  o.o.c.l.AbstractTypeScriptClientCodegen - Hint: Environment variable 'TS_POST_PROCESS_FILE' (optional) not defined. E.g. to format the source code, please try 'export TS_POST_PROCESS_FILE="/usr/local/bin/prettier --write"' (Linux/Mac)
[main] INFO  o.o.c.l.AbstractTypeScriptClientCodegen - Note: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] WARN  o.o.codegen.DefaultCodegen - The value (generator's option) must be either boolean or string. Default to `false`.
[main] ERROR o.o.codegen.DefaultGenerator - An exception occurred in OpenAPI Normalizer. Please report the issue via https://github.com/openapitools/openapi-generator/issues/new/: 
[main] ERROR o.o.codegen.DefaultGenerator - An exception occurred in OpenAPI Normalizer. Please report the issue via https://github.com/openapitools/openapi-generator/issues/new/: 
java.lang.NullPointerException: Cannot invoke "java.util.Set.contains(Object)" because the return value of "io.swagger.v3.oas.models.media.Schema.getTypes()" is null
        at org.openapitools.codegen.OpenAPINormalizer.processNormalize31Spec(OpenAPINormalizer.java:937)
        at org.openapitools.codegen.OpenAPINormalizer.normalizeSimpleSchema(OpenAPINormalizer.java:461)
        at org.openapitools.codegen.OpenAPINormalizer.normalizeSchema(OpenAPINormalizer.java:452)
        at org.openapitools.codegen.OpenAPINormalizer.normalizeContent(OpenAPINormalizer.java:266)
        at org.openapitools.codegen.OpenAPINormalizer.normalizeResponses(OpenAPINormalizer.java:337)
        at org.openapitools.codegen.OpenAPINormalizer.normalizePaths(OpenAPINormalizer.java:231)
        at org.openapitools.codegen.OpenAPINormalizer.normalize(OpenAPINormalizer.java:195)
        at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:274)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:1221)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:527)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
[main] WARN  o.o.codegen.DefaultCodegen - Generation using 3.1.0 specs is in development and is not officially supported yet. If you would like to expedite development, please consider woking on the open issues in the 3.1.0 project: https://github.com/orgs/OpenAPITools/projects/4/views/1 and reach out to our team on Slack at https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g
[main] INFO  o.o.codegen.utils.URLPathUtils - 'host' (OAS 2.0) or 'servers' (OAS 3.0) not defined in the spec. Default to [http://localhost] for server URL [http://localhost/]
[main] INFO  o.o.codegen.utils.URLPathUtils - 'host' (OAS 2.0) or 'servers' (OAS 3.0) not defined in the spec. Default to [http://localhost] for server URL [http://localhost/]
[main] INFO  o.o.codegen.utils.URLPathUtils - 'host' (OAS 2.0) or 'servers' (OAS 3.0) not defined in the spec. Default to [http://localhost] for server URL [http://localhost/]
[main] INFO  o.o.codegen.TemplateManager - writing file /local/frontend/src/generated-sources/apis/DefaultApi.ts
[main] INFO  o.o.codegen.utils.URLPathUtils - 'host' (OAS 2.0) or 'servers' (OAS 3.0) not defined in the spec. Default to [http://localhost] for server URL [http://localhost/]
[main] INFO  o.o.codegen.TemplateManager - writing file /local/frontend/src/generated-sources/index.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /local/frontend/src/generated-sources/runtime.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /local/frontend/src/generated-sources/apis/index.ts
[main] INFO  o.o.codegen.TemplateManager - Skipped /local/frontend/src/generated-sources/.openapi-generator-ignore (Skipped by supportingFiles options supplied by user.)
[main] INFO  o.o.codegen.TemplateManager - writing file /local/frontend/src/generated-sources/.openapi-generator/VERSION
[main] INFO  o.o.codegen.TemplateManager - writing file /local/frontend/src/generated-sources/.openapi-generator/FILES
################################################################################
# Thanks for using OpenAPI Generator.                                          #
# Please consider donation to help us maintain this project 🙏                 #
# https://opencollective.com/openapi_generator/donate                          #
################################################################################
```

##### openapi-generator version
7.2.0 is broken, 7.1.0 is ok

##### OpenAPI declaration file content or url
This is a (rather) minimal example that triggers the stacktrace: https://gist.github.com/Trolldemorted/f0b5155f4d1a0d46ea18196d1c2a8574

##### Generation Details
```
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v7.2.0 generate -i /local/backend/openapi.json -o /local/frontend/src/generated-sources -g typescript-fetch
```

##### Steps to reproduce
- Use the given openapi.json and run the generator

##### Related issues/PRs
Might be related to https://github.com/OpenAPITools/openapi-generator/issues/17524, but that one does not have enough information to be sure

**Comment by wing328** [comment]
should be fixed via https://github.com/OpenAPITools/openapi-generator/commit/c6efe8810df39ba04b89f9c4886eb5e808848bd6

please pull the latest master to give it a try

**Comment by Trolldemorted** [comment]
`openapitools/openapi-generator-cli:latest` works like a charm, thanks a lot!
