### ISSUE TITLE
[BUG] Issue with `bin/utils/export_docs_generators.sh`

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#1774]
##### Description

Run `./bin/utils/export_docs_generators.sh`, which shows the following issues (partial result):

```
# START SCRIPT: ./bin/utils/export_generator.sh erlang-proper
java.io.FileNotFoundException: docs/generators/erlang-proper.md (Is a directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.openapitools.codegen.cmd.ConfigHelp.run(ConfigHelp.java:72)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:62)
./bin/utils/export_generator.sh: line 19: docs/generators/erlang-proper.md: Is a directory
# START SCRIPT: ./bin/utils/export_generator.sh erlang-server
# START SCRIPT: ./bin/utils/export_generator.sh flash
# START SCRIPT: ./bin/utils/export_generator.sh scala-finch
# START SCRIPT: ./bin/utils/export_generator.sh go
# START SCRIPT: ./bin/utils/export_generator.sh go-server
# START SCRIPT: ./bin/utils/export_generator.sh go-gin-server
# START SCRIPT: ./bin/utils/export_generator.sh graphql-schema
java.io.FileNotFoundException: docs/generators/graphql-schema.md (Is a directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.openapitools.codegen.cmd.ConfigHelp.run(ConfigHelp.java:72)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:62)
./bin/utils/export_generator.sh: line 19: docs/generators/graphql-schema.md: Is a directory
# START SCRIPT: ./bin/utils/export_generator.sh graphql-server
java.io.FileNotFoundException: docs/generators/graphql-server.md (Is a directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.openapitools.codegen.cmd.ConfigHelp.run(ConfigHelp.java:72)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:62)
./bin/utils/export_generator.sh: line 19: docs/generators/graphql-server.md: Is a directory
```

##### openapi-generator version

latest master

##### Suggest a fix

If anyone wants to help with this issue, please reply to let us know.

**Comment by karismann** [comment]
Hello @wing328   is this issue has been solved ?  I don't actually have the problem with this script on updated master branch
