### ISSUE TITLE
[BUG] [main] Exception in thread "main" java.lang.StackOverflowError

### ISSUE THREAD

**Issue by wqvv** [OpenAPITools/openapi-generator#17902]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
i want to use openapi-generator to generate go client code, but when i use the version 7.3.0 ,i got some errors
i have no idea how to solve this 

##### openapi-generator version

v7.3.0

##### OpenAPI declaration file content or url

here is our spec file
[openapi.yaml.zip](https://github.com/OpenAPITools/openapi-generator/files/14340621/openapi.yaml.zip)

##### Generation Details

[main] ERROR o.o.codegen.DefaultCodegen - Required var abs_estimate_fee not in properties
[main] ERROR o.o.codegen.DefaultCodegen - Required var balance not in properties
[main] ERROR o.o.codegen.DefaultCodegen - Required var balance not in properties
[main] ERROR o.o.codegen.DefaultCodegen - Required var chain not in properties
[main] ERROR o.o.codegen.DefaultCodegen - Required var chain not in properties
[main] ERROR o.o.codegen.DefaultCodegen - Required var coin not in properties
[main] ERROR o.o.codegen.DefaultCodegen - Required var coin not in properties
[main] ERROR o.o.codegen.DefaultCodegen - Required var transferable_balance not in properties
[main] ERROR o.o.codegen.DefaultCodegen - Required var transferable_balance not in properties
[main] ERROR o.o.codegen.DefaultCodegen - Required var apikey not in properties
[main] ERROR o.o.codegen.DefaultCodegen - Required var apikey not in properties
[main] ERROR o.o.codegen.DefaultCodegen - Required var exchange not in properties
[main] ERROR o.o.codegen.DefaultCodegen - Required var exchange not in properties
[main] ERROR o.o.codegen.DefaultCodegen - Required var secret not in properties
**[main] ERROR o.o.codegen.DefaultCodegen - Required var secret not in properties
Exception in thread "main" java.lang.StackOverflowError
        at java.base/java.util.TreeSet.size(TreeSet.java:207)
        at java.base/java.util.AbstractCollection.toArray(AbstractCollection.java:139)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:723)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:728)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:728)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:728)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:728)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:728)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:728)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:728)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:728)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:728)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:728)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:728)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:728)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:728)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:728)
        at org.openapitools.codegen.languages.GoClientCodegen.constructExampleCode(GoClientCodegen.java:728)**

##### Steps to reproduce

openapi-generator generate --additional-properties=packageName=CoboPortal -i openapi.yaml -g go -o portal_go_sdk --git-repo-id cobo-portal-go-api --git-user-id CoboGlobal --global-property debugOpenAPI>> output.txt

**Comment by fmmajd** [comment]
hi. any resolutions for this? anybody found the fix or the problem?

**Comment by fmmajd** [comment]
I can't as I' 've solved mine. my problem was, that one of the schemas was referencing itself, so there was a loop and I got a StackOverflow exception. In case it could help anyone else. I paid attention to the logs before the error happened(marked as [info]) and there was indeed a message saying an anomaly was seen

**Comment by kbakk** [comment]
I also saw this issue, which I resolved by removing the circular dependency.

I.e. remove `components.schemas.JToken.items`: 

```
...
  "components": {
    "schemas": {
      "JToken": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/JToken"
        }
```

Using "[The Doctor](https://pb33f.io/doctor/)" to report OAS errors helped narrow down the schema issue for me (the `circular-references` rule).

**Comment by sp6370** [comment]
@kbakk Ran into the same issue with JToken! Thanks for the info.

Here's a public openAPI spec to replicate the issue: 
https://api.mews.com/Swagger/connector/swagger.yaml

JToken is defined on line 29786.

**Comment by wing328** [comment]
UPDATE: add logic in normalizer to auto correct self referencing schemas via https://github.com/OpenAPITools/openapi-generator/commit/d1ca82cb8b71b8a08111463712bf53549dad2a91

Tested with https://api.mews.com/Swagger/connector/swagger.yaml and no longer seeing the same issue
