### ISSUE TITLE
[BUG] [python] generator version > 7.0.0-beta generate broken code for youtrack.

### ISSUE THREAD

**Issue by caiiiycuk** [OpenAPITools/openapi-generator#17910]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists? **(I tested on latest docker image)**
- [X] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I trying to generate python client library for youtrack. I am using docker image, and python generator. The command that i use to generate client is following:

```
docker run --rm -v $PWD:/local openapitools/openapi-generator-cli:v<version> generate -i https://<host>/api/openapi.json -g python -o /local/oclient
```

Then I install the client using:
```
sudo python3 setup.py install
```

Then I try to use it:
```
python3
import openapi_client
```

both for python and python-pedantic-v1 generators, I have following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/__init__.py", line 20, in <module>
  File "/usr/local/lib/python3.10/dist-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/api/__init__.py", line 4, in <module>
  File "/usr/local/lib/python3.10/dist-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/api/default_api.py", line 28, in <module>
  File "/usr/local/lib/python3.10/dist-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/models/__init__.py", line 18, in <module>
  File "/usr/local/lib/python3.10/dist-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/models/activity_cursor_page.py", line 23, in <module>
  File "/usr/local/lib/python3.10/dist-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/models/activity_item.py", line 24, in <module>
  File "/usr/local/lib/python3.10/dist-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/models/filter_field.py", line 96, in <module>
  File "/usr/local/lib/python3.10/dist-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/models/custom_filter_field.py", line 23, in <module>
  File "/usr/local/lib/python3.10/dist-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/models/custom_field.py", line 113, in <module>
  File "/usr/local/lib/python3.10/dist-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/models/custom_field_defaults.py", line 104, in <module>
  File "/usr/local/lib/python3.10/dist-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/models/build_bundle_custom_field_defaults.py", line 23, in <module>
  File "/usr/local/lib/python3.10/dist-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/models/build_bundle.py", line 23, in <module>
  File "/usr/local/lib/python3.10/dist-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/models/base_bundle.py", line 23, in <module>
  File "/usr/local/lib/python3.10/dist-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/models/bundle.py", line 99, in <module>
ImportError: cannot import name 'BaseBundle' from partially initialized module 'openapi_client.models.base_bundle' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/models/base_bundle.py)
>>> 
```

Then I start downgrade generator and find that v6.5, v7.0.0-beta works fine.

##### openapi-generator version

Bug exists in: > v7.0.0-beta 

##### OpenAPI declaration file content or url

[openapi.json](https://github.com/OpenAPITools/openapi-generator/files/14350952/openapi.json)

##### Steps to reproduce

Just generate python client code, and import it.

**Comment by wing328** [comment]
> ImportError: cannot import name 'BaseBundle' from partially initialized module 'openapi_client.models.base_bundle' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/openapi_client-1.0.0-py3.10.egg/openapi_client/models/base_bundle.py)

can you please try the latest master as we recently merge a fix for circular import?

the snapshot version can be found in the project's readme.

**Comment by caiiiycuk** [comment]
@wing328, I am really sorry; I lost my inspiration to use openapi-generator. Even though v6.5 generates the Python client just fine, it does not work. The access_token that I pass in the config is just ignored. #13686 is not implemented correctly. I patched the client, and it started working, but then it broke again on some API methods. So, I threw it out. The idea is great, but the implementation is not that great for now.

**Comment by chylek-qr** [comment]
Tried 7.11.0, got a "partially initialized module" error but in a different place. 6.x breaks at runtime. Even tried to generate Java instead, and got a bunch of compile errors that were already reported in #19537. After over 3 hours of trying to find any way to use the generator for YouTrack, I've also given up.
