### ISSUE TITLE
OpenAPI 3.1 normalization fails with schema specifying only prefixItems in array

### ISSUE THREAD

**Issue by doctorpangloss** [OpenAPITools/openapi-generator#17923]
##### Description

Observe this schema is valid for 3.1 but does not have `items`:
```yaml
    QueueTuple:
      type: array
      description: |
        An item that was added to the queue.
      minItems: 3
      maxItems: 5
      prefixItems:
        - type: number
          description: Queue priority.
        - type: string
          description: The hash id of the prompt object. This should be the the prompt ID.
        - $ref: "#/components/schemas/Prompt"
        - $ref: "#/components/schemas/ExtraData"
        - type: array
          description: A list of "good output" node IDs in the prompt.
          items:
            type: string
```

This causes the exception in generation:
```
[main] ERROR o.o.codegen.DefaultGenerator - An exception occurred in OpenAPI Normalizer. Please report the issue via https://github.com/openapitools/openapi-generator/issues/new/: 
java.lang.NullPointerException
	at org.openapitools.codegen.OpenAPINormalizer.processNormalize31Spec(OpenAPINormalizer.java:1040)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeSimpleSchema(OpenAPINormalizer.java:502)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeSchema(OpenAPINormalizer.java:493)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeOneOf(OpenAPINormalizer.java:561)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeSchema(OpenAPINormalizer.java:452)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeSchema(OpenAPINormalizer.java:450)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeProperties(OpenAPINormalizer.java:519)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeSchema(OpenAPINormalizer.java:487)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeComponentsSchemas(OpenAPINormalizer.java:419)
	at org.openapitools.codegen.OpenAPINormalizer.normalize(OpenAPINormalizer.java:222)
	at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:274)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:1212)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:535)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

The referenced line is here, which causes the exception because items doesn't exist.
https://github.com/OpenAPITools/openapi-generator/blob/f1919042974ec17821d66a5529e4a8df5d3b3ac7/modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java#L1040C1-L1040C75

See reproduction in Google Colab with latest master at:
https://colab.research.google.com/drive/18sXET4mnQLMrsxru2vumN7iuk1fVJEVr?usp=sharing

##### openapi-generator version

`master`

##### OpenAPI declaration file content or url

```yaml
    QueueTuple:
      type: array
      description: |
        An item that was added to the queue.
      minItems: 3
      maxItems: 5
      prefixItems:
        - type: number
          description: Queue priority.
        - type: string
          description: The hash id of the prompt object. This should be the the prompt ID.
        - $ref: "#/components/schemas/Prompt"
        - $ref: "#/components/schemas/ExtraData"
        - type: array
          description: A list of "good output" node IDs in the prompt.
          items:
            type: string
```

##### Command line used for generation
```
java --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -jar ../openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate --input-spec ./comfy/api/openapi.yaml --global-property models --config ./comfy/api/openapi_python_config.yaml
```

##### Steps to reproduce

[unambiguous set of steps to reproduce the bug.](https://colab.research.google.com/drive/18sXET4mnQLMrsxru2vumN7iuk1fVJEVr?usp=sharing)

##### Related issues/PRs

#17755 

##### Suggest a fix/enhancement

Not sure, the referenced snippet needs to deal with no items and only prefixItems correctly.

**Comment by wing328** [comment]
thanks for reporting the issue. i've filed #17955 to fix the issue
