### ISSUE TITLE
Declared path parameter functionId needs to be defined as a path parameter in path or operation level

### ISSUE THREAD

**Issue by raimondsL** [OpenAPITools/openapi-generator#18339]
```
PS D:\DEV\talq> docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate -i /local/talq-api-cms-2-6-0-online.json -g html2 -o /local/talq-api-cms-html2
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 2, Warning count: 0
Errors:
        -paths.'/devices/{deviceAddress}/{functionId}/{attributeName}'. Declared path parameter functionId needs to be defined as a path parameter in path or operation level
        -paths.'/devices/{deviceAddress}/{functionId}/{attributeName}'. Declared path parameter attributeName needs to be defined as a path parameter in path or operation level

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:717)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:744)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:527)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
PS D:\DEV\talq> 
```

**Comment by raimondsL** [comment]
```
PS D:\DEV\talq> docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli --version
openapi-generator-cli 7.5.0-SNAPSHOT
  commit : b2a7f43
  built  : -999999999-01-01T00:00:00+18:00
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/

PS D:\DEV\talq> 
```

**Comment by wing328** [comment]
looks like your spec in invalid

have you tried another openapi validator to see if it reports similar issues for your spec?

**Comment by raimondsL** [comment]
Good question. Maybe TALQ 2.6 json is incorrect?
https://github.com/TALQ-consortium/TALQ_specification/blob/main/oas/talq-data-model-2-6-0-online.json
