### ISSUE TITLE
[BUG] Spring Generator wrong Path parsing

### ISSUE THREAD

**Issue by john-dev** [OpenAPITools/openapi-generator#1834]
##### Description

When generating for spring, having a "." (dot) in the username does replace the path's with a "/" (slash) on MacOS.
For example "/Users/foo.bar/" will end up being "/Users/foo/bar/".

##### openapi-generator version

4.0.0-beta (maven)

##### Command line used for generation

see maven plugin options

##### Steps to reproduce

simply generate with a username that has a "." (dot) in his username (or maybe somewere else in the path)

**Comment by john-dev** [comment]
Hello @jimschubert 

i am using openapi 4.0.0-beta to gernate a spring server using maven.
Attached, the configuration i use.

`<build>
		<sourceDirectory>src/main/java</sourceDirectory>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>add-source</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>${project.basedir}/target/generated/src/main/java</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>4.0.0-beta</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
							<generatorName>spring</generatorName>
							<output>target/generated</output>
							<validateSpec>false</validateSpec>
							<configOptions>
								<interfaceOnly>false</interfaceOnly>
								<sourceFolder>src/main/java</sourceFolder>
								<apiPackage>${project.groupId}.api</apiPackage>
								<modelPackage>${project.groupId}.model</modelPackage>
								<invokerPackage>${project.groupId}.invoker</invokerPackage>
							</configOptions>
							<ignoreFileOverride>${project.basedir}/.openapi-codegen-ignore</ignoreFileOverride>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>`

As you can see - i don't provide any absolute path's at all.
The Worspace-Folder in which i generate the soruces has the username with a ".".

I start to wonder if this is a problem of the org.codehaus.mojo.build-maven-helper plugin.

**Comment by jimschubert** [comment]
Thanks for this @john-dev. So to clarify… when you say "path" are you referring to the directory output location? I may have misread this as if you were generating an API with an endpoint called `/Users` where the path parameter was being converted.

**Comment by john-dev** [comment]
Yes i do.
Attached you will find the complete output..

As you can see, the path should be "/Users/**m.brown**/git/epartio-restserver/...."  but it is "Users/**m/brown**/git/epartio-restserver/..."

```
Marcus Brown, [11.01.2019, 14:35:33]:
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------< org.project.epartio:epartio-restserver >---------------
[INFO] Building epartio-restserver 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ epartio-restserver ---
[INFO] Deleting /Users/m.brown/git/epartio-restserver/target
[INFO] 
[INFO] --- build-helper-maven-plugin:3.0.0:add-source (add-source) @ epartio-restserver ---
[INFO] Source directory: /Users/m.brown/git/epartio-restserver/target/generated/src/main/java added.
[INFO] 
[INFO] --- jaxws-maven-plugin:2.5:wsimport (default) @ epartio-restserver ---
[INFO] Processing: file:/Users/m.brown/git/epartio-restserver/src/main/resources/wsdl/XsquareJobService_1.wsdl
[INFO] jaxws:wsimport args: [-keep, -s, '/Users/m.brown/git/epartio-restserver/target/generated/src/main/java', -d, '/Users/m.brown/git/epartio-restserver/target/classes', -encoding, UTF-8, -Xnocompile, "file:/Users/m.brown/git/epartio-restserver/src/main/resources/wsdl/XsquareJobService_1.wsdl"]
WSDL wird geparst ...



Code wird generiert ...

[INFO] Processing: file:/Users/m.brown/git/epartio-restserver/src/main/resources/wsdl/IPWS_1.wsdl
[INFO] jaxws:wsimport args: [-keep, -s, '/Users/m.brown/git/epartio-restserver/target/generated/src/main/java', -d, '/Users/m.brown/git/epartio-restserver/target/classes', -encoding, UTF-8, -Xnocompile, "file:/Users/m.brown/git/epartio-restserver/src/main/resources/wsdl/IPWS_1.wsdl"]
WSDL wird geparst ...



Code wird generiert ...

[INFO] 
[INFO] --- openapi-generator-maven-plugin:4.0.0-beta:generate (default) @ epartio-restserver ---
[WARNING] The 'language' option is deprecated and may reference language names only in the next major release (4.0). Please use 'generatorName' instead.
[INFO] ----------------------------------
[INFO] Set base package to invoker package (org.project.epartio.invoker)
[INFO] Environment variable JAVA_POST_PROCESS_FILE not defined so the Java code may not be properly formatted. To define it, try 'export JAVA_POST_PROCESS_FILE="/usr/local/bin/clang-format -i"' (Linux/Mac)
[INFO] NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to true (--enable-post-process-file for CLI).

[INFO] Processing operation getReport
[INFO] Processing operation getExternalMetadataSetNames
[INFO] Processing operation getClientMappings
[INFO] writing file /Users/m/braun/git/epartio-restserver/target/generated-sources/swagger/src/main/java/de/epartio/epartio/model/ErrormessageTO.java
[ERROR] /Users/m.brown/git/epartio-restserver/src/main/resources/api.yaml [0:0]: unexpected error in Open-API generation
java.lang.RuntimeException: Could not generate model 'ErrormessageTO'
 at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:501)
 at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:891)
 at org.openapitools.codegen.plugin.CodeGenMojo.execute(CodeGenMojo.java:630)
 at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
 at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
 at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
 at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
 at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
 at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
 at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
 at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
 at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
 at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
 at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
 at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.io.FileNotFoundException: /Users/m/braun/git/epartio-restserver/target/generated-sources/swagger/src/main/java/de/epartio/epartio/model/ErrormessageTO.java (No such file or directory)
 at java.io.FileOutputStream.open0(Native Method)
 at java.io.FileOutputStream.open(FileOutputStream.java:270)
 at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
 at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
 at org.openapitools.codegen.AbstractGenerator.writeToFile(AbstractGenerator.java:49)
 at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:925)
 at org.openapitools.codegen.DefaultGenerator.generateModel(DefaultGenerator.java:314)
 at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:490)
 ... 24 more
[ERROR] 
java.lang.RuntimeException: Could not generate model 'ErrormessageTO'
 at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:501)
 at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:891)
 at org.openapitools.codegen.plugin.CodeGenMojo.execute(CodeGenMojo.java:630)
 at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
 at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
 at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
 at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
 at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
 at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
 at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
 at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
 at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
 at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
 at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
 at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.io.FileNotFoundException: /Users/m/braun/git/epartio-restserver/target/generated-sources/swagger/src/main/java/de/epartio/epartio/model/ErrormessageTO.java (No such file or directory)
 at java.io.FileOutputStream.open0(Native Method)
 at java.io.FileOutputStream.open(FileOutputStream.java:270)
 at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
 at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
 at org.openapitools.codegen.AbstractGenerator.writeToFile(AbstractGenerator.java:49)
 at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:925)
 at org.openapitools.codegen.DefaultGenerator.generateModel(DefaultGenerator.java:314)
 at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:490)
 ... 24 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.868 s
[INFO] Finished at: 2019-01-11T14:35:13+01:00
[INFO] ------------------------------------------------------------------------
[ERROR

] Failed to execute goal org.openapitools:openapi-generator-maven-plugin:4.0.0-beta:generate (default) on project epartio-restserver: Code generation failed. See above for the full exception. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by john-dev** [comment]
Thanks for the quick support @jimschubert - we will try the new commit in the next days!
