### ISSUE TITLE
[BUG][JAVA] Error in serialization of object lists with polymorphism

### ISSUE THREAD

**Issue by jorgerod** [OpenAPITools/openapi-generator#18460]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

7.5.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0

info:
  version: 0.1.0
  title: My Service
  description: My Service
  contact:
    name: My Service
security:
  - BasicAuth: []
paths:
  /attribute:
    put:
      description: Upsert attribute
      summary: Upsert attribute
      operationId: upsertAttribute
      requestBody:
        description: Upsert attribute
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Parent"
        required: true
      responses:
        "200":
          description: Upserted attribute
  /attributes:
    put:
      description: Upsert attributes
      summary: Upsert attributes
      operationId: upsertAttributes
      requestBody:
        description: Version and attribute to upsert
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Parent"
        required: true
      responses:
        "200":
          description: Upserted attribute
components:
  schemas:
    Parent:
      type: object
      description: Input to upsert the attribute in a specific version
      discriminator:
        propertyName: type
        mapping:
          child1: "#/components/schemas/Child1"
          child2: "#/components/schemas/Child2"
      properties:
        type:
          type: string
      required:
        - type
    Child1:
      allOf:
        - $ref: '#/components/schemas/Parent'
        - type: object
      properties:
        prop1:
          type: string
    Child2:
      allOf:
        - $ref: '#/components/schemas/Parent'
        - type: object
      properties:
        prop2:
          type: string
```

##### Generation Details

```
java -jar openapi-generator-cli-7.5.0.jar generate -g java -i spec.yaml -o output --additional-properties library=resttemplate
```

`Parent.java`
```java
/*
 * My Service
 * My Service
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Input to upsert the attribute in a specific version
 */
@JsonPropertyOrder({
  ParentDTO.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "com.inditex.amigafwk.common.rest.client.codegen.AmigaJavaClientCodegen", date = "2024-04-22T18:36:41.291996684+02:00[Europe/Madrid]")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = Child1DTO.class, name = "child1"),
  @JsonSubTypes.Type(value = Child2DTO.class, name = "child2"),
})

public class ParentDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TYPE = "type";
  protected String type;

  public ParentDTO() {
  }

  public ParentDTO type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(String type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParentDTO parent = (ParentDTO) o;
    return Objects.equals(this.type, parent.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParentDTO {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

```
`Child1DTO.java`

```java
/*
 * My Service
 * My Service
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.inditex.pacmangrids.rest.dtos.ParentDTO;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Child1DTO
 */
@JsonPropertyOrder({
  Child1DTO.JSON_PROPERTY_PROP1
})
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class Child1DTO extends ParentDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_PROP1 = "prop1";
  private String prop1;

  public Child1DTO() {

  }

  public Child1DTO prop1(String prop1) {
    
    this.prop1 = prop1;
    return this;
  }

   /**
   * Get prop1
   * @return prop1
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROP1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProp1() {
    return prop1;
  }


  @JsonProperty(JSON_PROPERTY_PROP1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProp1(String prop1) {
    this.prop1 = prop1;
  }

  @Override
  public Child1DTO type(String type) {
    this.setType(type);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Child1DTO child1 = (Child1DTO) o;
    return Objects.equals(this.prop1, child1.prop1) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prop1, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Child1DTO {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    prop1: ").append(toIndentedString(prop1)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

```

##### Steps to reproduce
- Generate client application
- Build server application (with spring)

- Make a request from my generated client app to the endpoint `attribute`  with a single child -> Works OK
- Make a request from my generated client to the endpoint `attributes` with a list of children -> KO `Type` field is not sent

```java
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Could not resolve subtype of [simple type, class com.inditex.mynamespacerestserviceopenapi.dto.ParentDTO]: missing type id property 'type'
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:406)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:354)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:184)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:159)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:134)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122)

````

##### Related issues/PRs

- https://github.com/OpenAPITools/openapi-generator/issues/12777

**Comment by jorgerod** [comment]
@wing328 I have tried to activate the property legacyDiscriminatorBehaviour and I think it is not working correctly.
The Child does remove the annotations

```java
/**
 * Child1DTO
 */
@JsonPropertyOrder({
  Child1DTO.JSON_PROPERTY_PROP1
})
@JsonTypeName("Child1")
public class Child1DTO extends ParentDTO implements Serializable {
```

but not the parent:

```java
/**
 * Input to upsert the attribute in a specific version
 */
@JsonPropertyOrder({
  ParentDTO.JSON_PROPERTY_TYPE
})
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = Child1DTO.class, name = "child1"),
  @JsonSubTypes.Type(value = Child2DTO.class, name = "child2"),
})

public class ParentDTO implements Serializable {
````

**Comment by damzog** [comment]
Actually thinking again about the generated schema I found it was not correct. After playing around and regenerating it was generated (by fastapi) from
```python
class Address(BaseModel):
    street: str
    city: str


class User(BaseModel):
    name: str = None
    age: int = None
    relations: Dict[str, Address] = None
```
to 
```json
...
      "User": {
        "properties": {
          "name": {
            "type": "string",
            "title": "Name"
          },
          "age": {
            "type": "integer",
            "title": "Age"
          },
          "relations": {
            "additionalProperties": {
              "$ref": "#/components/schemas/Address"
            },
            "type": "object",
            "title": "Relations"
          }
        },
...
```
and now the generated code is also working

**Comment by jorgerod** [comment]
I have found a way to solve it based on this answer in [Jackson databind](https://github.com/FasterXML/jackson-databind/issues/699#issuecomment-73382972).

To do this, I enabled the **generateAliasAsModel** option and modified the API definition by adding the `Parents`.

```java
openapi: 3.0.0

info:
  version: 0.1.0
  title: My Service
  description: My Service
  contact:
    name: My Service
security:
  - BasicAuth: []
paths:
  /attribute:
    put:
      description: Upsert attribute
      summary: Upsert attribute
      operationId: upsertAttribute
      requestBody:
        description: Upsert attribute
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Parent"
        required: true
      responses:
        "200":
          description: Upserted attribute
  /attributes:
    put:
      description: Upsert attributes
      summary: Upsert attributes
      operationId: upsertAttributes
      requestBody:
        description: Version and attribute to upsert
        content:
          application/json:
            schema:
                $ref: "#/components/schemas/Parents"

        required: true
      responses:
        "200":
          description: Upserted attribute
components:
  schemas:
    Parents:
      type: array
      items:
        $ref: "#/components/schemas/Parent"
    Parent:
      type: object
      description: Input to upsert the attribute in a specific version
      discriminator:
        propertyName: type
        mapping:
          child1: "#/components/schemas/Child1"
          child2: "#/components/schemas/Child2"
      properties:
        type:
          type: string
      required:
        - type
    Child1:
      allOf:
        - $ref: '#/components/schemas/Parent'
        - type: object
      properties:
        prop1:
          type: string
    Child2:
      allOf:
        - $ref: '#/components/schemas/Parent'
        - type: object
      properties:
        prop2:
          type: string

```

New generated class:

```java
@JsonPropertyOrder({
})
@JsonTypeName("Parents")
public class ParentsDTO extends ArrayList<ParentDTO> implements Serializable {
  private static final long serialVersionUID = 1L;
// ...
```

Sample:
```java
    @Test
    void testWorkaround() {
        final RestTemplate restTemplate = new RestTemplate();

        Child1DTO child1DTO = new Child1DTO();

        ParentsDTO parentDTOS = new ParentsDTO();
        parentDTOS.add(child1DTO);

        final var responseEntity = restTemplate.postForEntity(this.getURIRequest("/list").build().encode().toUri(), parentDTOS, String.class);

        Assertions.assertThat(responseEntity.getBody()).isEqualTo("child1");
    }
```
