### ISSUE TITLE
[BUG][PHP-NEXTGEN] Exception in thread "main" java.lang.RuntimeException: Could not process model

### ISSUE THREAD

**Issue by robsonek** [OpenAPITools/openapi-generator#18499]
I'm trying to generate a library to handle the Allegro API with openapi-generator v7.5.0, using the php-nextgen generator (https://openapi-generator.tech/docs/generators/php-nextgen/).

Command: `openapi-generator generate -i https://developer.allegro.pl/swagger.yaml -g php-nextgen -o sdk`

Output:
`Exception in thread "main" java.lang.RuntimeException: Could not process model 'SaleProductOfferRequestV1'.Please make sure that your schema is correct!
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:542)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:1228)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:535)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException
	at org.openapitools.codegen.languages.PhpNextgenClientCodegen.toDefaultValue(PhpNextgenClientCodegen.java:204)
	at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:4262)
	at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:3937)
	at org.openapitools.codegen.DefaultCodegen.addVars(DefaultCodegen.java:6041)
	at org.openapitools.codegen.DefaultCodegen.addVarsRequiredVarsAdditionalProps(DefaultCodegen.java:7971)
	at org.openapitools.codegen.DefaultCodegen.updatePropertyForObject(DefaultCodegen.java:3851)
	at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:4187)
	at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:3937)
	at org.openapitools.codegen.DefaultCodegen.getComposedProperties(DefaultCodegen.java:8434)
	at org.openapitools.codegen.DefaultCodegen.getComposedSchemas(DefaultCodegen.java:8414)
	at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:3180)
	at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1683)
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:537)
	... 4 more`
	
The library generation using the default PHP generator (https://openapi-generator.tech/docs/generators/php/) is successful.

**Comment by wing328** [comment]
thanks for reporting the issue.

fixed via https://github.com/OpenAPITools/openapi-generator/commit/a5ccd7a77ee4326b7b9d491159e759e8b03a3f1f with a test

(sorry should have opened a PR instead)
