### ISSUE TITLE
Normalizer Function SIMPLIFY_ONEOF_ANYOF Broken In Version 7.5.0

### ISSUE THREAD

**Issue by geso02** [OpenAPITools/openapi-generator#18497]
##### Description

openapiNormalizer=SIMPLIFY_ONEOF_ANYOF=true is not working and crashes:

`[ERROR] An exception occurred in OpenAPI Normalizer. Please report the issue via https://github.com/openapitools/openapi-generator/issues/new/:
java.lang.NullPointerException: Cannot invoke "java.lang.Comparable.compareTo(Object)" because "k1" is null
        at java.base/java.util.TreeMap.compare(TreeMap.java:1569)
        at java.base/java.util.TreeMap.addEntryToEmptyMap(TreeMap.java:776)
        at java.base/java.util.TreeMap.put(TreeMap.java:785)
        at java.base/java.util.TreeMap.put(TreeMap.java:534)
        at java.base/java.util.TreeSet.add(TreeSet.java:255)
        at org.openapitools.codegen.OpenAPINormalizer.processSimplifyOneOf(OpenAPINormalizer.java:946)
        at org.openapitools.codegen.OpenAPINormalizer.normalizeOneOf(OpenAPINormalizer.java:644)
        at org.openapitools.codegen.OpenAPINormalizer.normalizeSchema(OpenAPINormalizer.java:520)
        at org.openapitools.codegen.OpenAPINormalizer.normalizeComponentsSchemas(OpenAPINormalizer.java:484)
        at org.openapitools.codegen.OpenAPINormalizer.normalize(OpenAPINormalizer.java:287)
        at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:274)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:1214)
        at org.openapitools.codegen.plugin.CodeGenMojo.execute(CodeGenMojo.java:996)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
        at com.soebes.maven.plugins.iterator.IteratorMojo.executeMojo(IteratorMojo.java:406)
        at com.soebes.maven.plugins.iterator.IteratorMojo.handlePluginExecution(IteratorMojo.java:305)
        at com.soebes.maven.plugins.iterator.IteratorMojo.execute(IteratorMojo.java:235)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
        at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
        at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
        at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)`

##### openapi-generator version

v7.5.0

##### OpenAPI declaration file content or url

```yaml
---
openapi: "3.0.3"
info:
  title: "Test"
  version: "V1"
components:
  schemas:
    Test:
      oneOf:
      - $ref: "#/components/schemas/A"
      - $ref: "#/components/schemas/B"
      - $ref: "#/components/schemas/C"
      - $ref: "#/components/schemas/D"
      - $ref: "#/components/schemas/E"
      - $ref: "#/components/schemas/F"
    A:
      type: "object"
      properties:
        modelType:
          type: string
          default: "A"
    B:
      type: "object"
      properties:
        modelType:
          type: string
          default: "B"
    C:
      type: "object"
      properties:
        modelType:
          type: string
          default: "C"
    D:
      type: "object"
      properties:
        modelType:
          type: string
          default: "D"
    E:
      type: "object"
      properties:
        modelType:
          type: string
          default: "E"
    F:
      type: "object"
      properties:
        modelType:
          type: string
          default: "F"
paths: {}
```

##### Command line used for generation

Executed from maven plugin (maven version: 3.9.6, java version: Java version: 17.0.10, Amazon Coretto )
``` xml
<goal>generate</goal>
  <plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
  </plugin>
  <configuration>
    <inputSpec>${openapi.output.path}</inputSpec>
      <output>${gensrc.output.folder}</output>
      <configurationFile>${project.basedir}/@item@/config.yaml</configurationFile>
      <templateResourcePath>${project.basedir}/templates</templateResourcePath>
  </configuration>
```
``` properties
openapi.generator.maven.plugin.generatorName=typescript-fetch
openapi.generator.maven.plugin.library=
openapi.generator.maven.plugin.skipOperationExample=true
openapi.generator.maven.plugin.generateApiTests=false
openapi.generator.maven.plugin.generateModelDocumentation=false
openapi.generator.maven.plugin.generateModelTests=false
openapi.generator.maven.plugin.generateApiDocumentation=false
openapi.generator.maven.plugin.generateModels=true
openapi.generator.maven.plugin.generateApis=false
openapi.generator.maven.plugin.generateSupportingFiles=true
# this is true per default openapi.generator.maven.plugin.openapiNormalizer=SIMPLIFY_ONEOF_ANYOF=true
``` 

##### Steps to reproduce

Use the given openapi file. I would expect that this does not only fail from maven

##### Suggest a fix/enhancement

Seems that the schema given here is null:
https://github.com/OpenAPITools/openapi-generator/blob/v7.5.0/modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java#L2137

This bug is new to version 7.5.0 . Version 7.4.0 works without an error

For now I will just disable the normalizer explicitely with SIMPLIFY_ONEOF_ANYOF=false in my project

**Comment by wing328** [comment]
thanks for reporting the issue. i'll take a look this weekend.

**Comment by wing328** [comment]
i've filed #18504. tested with your spec above and no longer seeing any error log

**Comment by wing328** [comment]
PR merged. Please give it another try with the latest master. snapshot version available in the project's readme.
