### ISSUE TITLE
Repeated `null` in "anyOf" selector throws exception

### ISSUE THREAD

**Issue by brent-statsig** [OpenAPITools/openapi-generator#18732]
##### Description
```
java.util.NoSuchElementException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:721)
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741)
	at org.openapitools.codegen.utils.ModelUtils.getType(ModelUtils.java:2142)
	at org.openapitools.codegen.OpenAPINormalizer.processSimplifyAnyOf(OpenAPINormalizer.java:1071)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeAnyOf(OpenAPINormalizer.java:663)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeSchema(OpenAPINormalizer.java:522)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeProperties(OpenAPINormalizer.java:599)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeSchema(OpenAPINormalizer.java:555)
	at org.openapitools.codegen.OpenAPINormalizer.processNormalize31Spec(OpenAPINormalizer.java:1254)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeArraySchema(OpenAPINormalizer.java:570)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeSchema(OpenAPINormalizer.java:513)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeProperties(OpenAPINormalizer.java:599)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeSchema(OpenAPINormalizer.java:555)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeComponentsSchemas(OpenAPINormalizer.java:484)
	at org.openapitools.codegen.OpenAPINormalizer.normalize(OpenAPINormalizer.java:287)
	at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:274)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:1214)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:535)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

##### openapi-generator version

openapi-generator-cli 7.5.0
commit : cce4139

##### OpenAPI declaration file content or url
Caused by this field with repeated types:

```
"targetValue": {
  "anyOf": [
    { "type": "array", "items": { "type": "string" } },
    { "type": "array", "items": { "type": "number" } },
    { "type": "string" },
    { "type": "number" },
    { "type": "null" },
    { "type": "null" }
  ]
},
```

**Comment by brent-statsig** [comment]
The broken API definition is being generated by https://github.com/asteasolutions/zod-to-openapi, which I'm creating an issue for as well - just figured I would flag since this seems like an unexpected behavior!

**Comment by wing328** [comment]
agreed with you that shouldn't throw an exception. i'll take a look later this week

as a workaround, please manually remove the duplicated `type: null` for the time being

**Comment by wing328** [comment]
i tried to repeat the issue using the latest master but couldn't 

can you please give it another try with the latest master or v7.6.0?

**Comment by newsgrep** [comment]
I was able to reproduce it on 7.6.0 and 7.7.0-20240520.095624-1.jar.

**Comment by wing328** [comment]
should be fixed via https://github.com/OpenAPITools/openapi-generator/pull/19014

please give it a try with the latest master (snapshot version mentioned in the project's readme will be published later as part of the travis ci workflow)
