### ISSUE TITLE
ERROR o.o.codegen.DefaultGenerator - java.lang.NullPointerException

### ISSUE THREAD

**Issue by cybernetchin** [OpenAPITools/openapi-generator#19166]
##### Description

Generating Code for yaml produces Nullpoint exception

##### openapi-generator version

@openapitools/openapi-generator-cli@2.7.0
@openapitools/openapi-generator-cli@2.13.4

##### OpenAPI declaration file content or url

[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: typescript-axios (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'typescript-axios' is considered stable.
[main] INFO  o.o.c.l.AbstractTypeScriptClientCodegen - Hint: Environment variable 'TS_POST_PROCESS_FILE' (optional) not defined. E.g. to format the source code, please try 'export TS_POST_PROCESS_FILE="/path/prettier --write"' (Linux/Mac)
[main] INFO  o.o.c.l.AbstractTypeScriptClientCodegen - Note: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] WARN  o.o.codegen.DefaultCodegen - The value (generator's option) must be either boolean or string. Default to `false`.
[main] ERROR o.o.codegen.DefaultGenerator - An exception occurred in OpenAPI Normalizer. Please report the issue via https://github.com/openapitools/openapi-generator/issues/new/: 
[main] ERROR o.o.codegen.DefaultGenerator - An exception occurred in OpenAPI Normalizer. Please report the issue via https://github.com/openapitools/openapi-generator/issues/new/: 
java.lang.NullPointerException
	at java.base/java.util.TreeMap.compare(TreeMap.java:1291)
	at java.base/java.util.TreeMap.put(TreeMap.java:536)
	at java.base/java.util.TreeSet.add(TreeSet.java:255)
	at org.openapitools.codegen.OpenAPINormalizer.processSimplifyOneOf(OpenAPINormalizer.java:946)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeOneOf(OpenAPINormalizer.java:644)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeSchema(OpenAPINormalizer.java:520)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeProperties(OpenAPINormalizer.java:599)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeSchema(OpenAPINormalizer.java:555)
	at org.openapitools.codegen.OpenAPINormalizer.normalizeComponentsSchemas(OpenAPINormalizer.java:484)
	at org.openapitools.codegen.OpenAPINormalizer.normalize(OpenAPINormalizer.java:287)
	at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:274)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:1214)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:535)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
[main] INFO  o.o.codegen.InlineModelResolver - Inline schema created as AUPetFieldDataDataV1_temperament. To have complete control of the model name, set the `title` field or use the modelNameMapping option (e.g. --model-name-mappings AUPetFieldDataDataV1_temperament=NewModel,ModelA=NewModelA in CLI) or inlineSchemaNameMapping option (--inline-schema-name-mappings AUPetFieldDataDataV1_temperament=NewModel,ModelA=NewModelA in CLI).
[main] INFO  o.o.codegen.InlineModelResolver - Inline schema created as AUPetFieldDataDataV1_temperament_input. To have complete control of the model name, set the `title` field or use the modelNameMapping option (e.g. --model-name-mappings AUPetFieldDataDataV1_temperament_input=NewModel,ModelA=NewModelA in CLI) or inlineSchemaNameMapping option (--inline-schema-name-mappings AUPetFieldDataDataV1_temperament_input=NewModel,ModelA=NewModelA in CLI).
[main] INFO  o.o.codegen.InlineModelResolver - Inline schema created as AUPetFieldDataV1_pet. To have complete control of the model name, set the `title` field or use the modelNameMapping option (e.g. --model-name-mappings AUPetFieldDataV1_pet=NewModel,ModelA=NewModelA in CLI) or inlineSchemaNameMapping option (--inline-schema-name-mappings AUPetFieldDataV1_pet=NewModel,ModelA=NewModelA in CLI).
[main] INFO  o.o.codegen.InlineModelResolver - Inline schema created as FormSubmitRequestBody_field_data. To have complete control of the model name, set the `title` field or use the modelNameMapping option (e.g. --model-name-mappings FormSubmitRequestBody_field_data=NewModel,ModelA=NewModelA in CLI) or inlineSchemaNameMapping option (--inline-schema-name-mappings FormSubmitRequestBody_field_data=NewModel,ModelA=NewModelA in CLI).
[main] INFO  o.o.codegen.DefaultGenerator - Model DocumentUploadRequestBody not generated since it's marked as unused (due to form parameters) and `skipFormModel` (global property) set to true (default)
[main] INFO  o.o.codegen.DefaultGenerator - Model FormFileUploadRequestBody not generated since it's marked as unused (due to form parameters) and `skipFormModel` (global property) set to true (default)
[main] INFO  o.o.codegen.TemplateManager - writing file /server-project-path/restful-api/api-client/index.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /server-project-path/restful-api/api-client/base.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /server-project-path/restful-api/api-client/common.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /server-project-path/restful-api/api-client/api.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /server-project-path/restful-api/api-client/configuration.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /server-project-path/restful-api/api-client/git_push.sh
[main] INFO  o.o.codegen.TemplateManager - writing file /server-project-pathe/restful-api/api-client/.gitignore
[main] INFO  o.o.codegen.TemplateManager - writing file /server-project-path/restful-api/api-client/.npmignore
[main] INFO  o.o.codegen.TemplateManager - Skipped /server-project-path/restful-api/api-client/.openapi-generator-ignore (Skipped by supportingFiles options supplied by user.)
[main] INFO  o.o.codegen.TemplateManager - writing file /server-project-path/restful-api/api-client/.openapi-generator/VERSION
[main] INFO  o.o.codegen.TemplateManager - writing file /server-project-path/restful-api/api-client/.openapi-generator/FILES
################################################################################
# Thanks for using OpenAPI Generator.                                          #
# Please consider donation to help us maintain this project 🙏                 #
# https://opencollective.com/openapi_generator/donate                          #
################################################################################

##### Command line used for generation

BASEDIR=/server-project-path/

npx @openapitools/openapi-generator-cli \
  generate \
  -i $BASEDIR/restful-api/specification/au-api.yml \
  -g typescript-axios \
  -p paramNaming=original \
  -p useSingleRequestParameter=true \
  -o $BASEDIR/restful-api/api-client

##### Steps to reproduce

As above

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/855

##### Suggest a fix/enhancement

Investigating o.o.codegen.DefaultGenerator with error of NullPointerException

**Comment by wing328** [comment]
can you please share your spec to reproduce the issue?

**Comment by wing328** [comment]
please also test the latest snapshot as i remember merging a PR to fix something similar to the error message reported above.

https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/7.8.0-SNAPSHOT/

**Comment by cybernetchin** [comment]
Please find here my spec:

```yaml
openapi: 3.1.0
info:
  description: |
    API specification.
  version: "1.0.0"
  title: API specification
  termsOfService: "Eula"
  contact:
    email: chin@jetpets.com.au
servers:
  - url: "https://test.test.net.au"
tags:
  - name: api-portal

paths:
  /index.php?rm=form-submit:
    post:
      tags:
        - au-customer-portal-scooby
      summary: Booking form step submit
      operationId: booking_form_step_submit
      security:
        - bearerAuth: []
      requestBody:
        $ref: "#/components/requestBodies/FormSubmitRequest"
      responses:
        "200":
          $ref: "#/components/responses/FormSubmitResponse"

components:
  schemas:
    ErrorData:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: number
        message:
          type: string

    DropDown:
      type: object
      required:
        - c1
        - c2
      properties:
        c1:
          type: string
        c2:
          type: string
        c3:
          type: string
        c4:
          type: string
        c5:
          type: string
        c6:
          type: string
        c7:
          type: string

    FieldData:
      type: object
      properties:
        b1:
          type: string
        b2:
          type: string
        b3:
          type: string
        b4:
          type: string
        b5:
          type: string
          nullable: true
        b6:
          type: string
        b7:
          type: string
        b8:
          type: string
        b9:
          type: string
        b10:
          type: string
          nullable: true
        b11:
          type: string
          nullable: true
        b12:
          type: string
          nullable: true
        b13:
          type: string
          nullable: true
        b14:
          type: string
        b15:
          type: string
          nullable: true
        b16:
          type: string
          nullable: true
        b17:
          type: string
          nullable: true
        b18:
          type: string
          nullable: true
        b19:
          type: string
          nullable: true
        b20:
          type: string
          nullable: true
        b21:
          type: string
          nullable: true
        b22:
          type: string
          nullable: true
        b23:
          type: string
          nullable: true
        b24:
          type: string
          nullable: true
        b25:
          type: string
          nullable: true
        b26:
          type: string
          nullable: true
        b27:
          type: string
          nullable: true
        b28:
          type: string
          nullable: true
        b29:
          type: string
          nullable: true
        b30:
          type: string
          nullable: true
        b31:
          type: string
          nullable: true
        b32:
          type: string
          nullable: true
        b33:
          type: string
          nullable: true
        b34:
          type: string
          nullable: true
        b35:
          type: string
          nullable: true
        b36:
          type: string
          nullable: true
        b37:
          type: string
          nullable: true
        b38:
          type: string
        b39:
          type: string
          nullable: true
        b40:
          type: string
        b41:
          type: object
          allOf:
            - $ref: "#/components/schemas/DropDown"
        b42:
          type: object
          allOf:
            - $ref: "#/components/schemas/DropDown"
        b43:
          type: object
          allOf:
            - $ref: "#/components/schemas/DropDown"
        b44:
          type: object
          allOf:
            - $ref: "#/components/schemas/DropDown"
        b45:
          type: object
          allOf:
            - $ref: "#/components/schemas/DropDown"
        b46:
          type: string
        b47:
          type: string
        b48:
          type: string
          nullable: true
        b49:
          type: string
          nullable: true
        b50:
          type: boolean
          nullable: true
        b51:
          type: boolean
          nullable: true
        b52:
          type: string
          nullable: true
        b53:
          type: string
          nullable: true
        b54:
          type: string
          nullable: true
        b55:
          type: string
          nullable: true
        b56:
          type: string
          nullable: true
        b57:
          type: string
          nullable: true
        b58:
          type: string
          nullable: true
        b59:
          type: string
          nullable: true
        b60:
          type: string
          nullable: true
        b61:
          type: string
          nullable: true
        b62:
          type: string
          nullable: true
        b63:
          type: string
          nullable: true
        b64:
          type: string
          nullable: true
        b65:
          type: string
          nullable: true
        b66:
          type: string
          nullable: true
        b67:
          type: string
          nullable: true
        b68:
          type: boolean
          nullable: true
        b69:
          type: string
          nullable: true
        b70:
          type: string
          nullable: true
        b71:
          type: boolean
          nullable: true
        b72:
          type: string
          nullable: true
        b73:
          type: string
          nullable: true
        b74:
          type: string
          nullable: true
        b75:
          type: string
          nullable: true
        b76:
          type: string
          nullable: true
        b77:
          type: string
          nullable: true
        b78:
          type: string
          nullable: true
        b79:
          type: string
          nullable: true
        b80:
          type: string
          nullable: true
        b81:
          type: string
          nullable: true
        b82:
          type: string
          nullable: true
        b83:
          type: string
          nullable: true
        b84:
          type: string
          nullable: true
        b85:
          type: string
          nullable: true
        b86:
          type: string
          nullable: true
        b87e:
          type: string
          nullable: true
        b88:
          type: string
          nullable: true
        b89:
          type: string
          nullable: true
        b90:
          type: string
          nullable: true
        b91:
          type: string
          nullable: true
        b92:
          type: string
          nullable: true
        b93:
          type: string
          nullable: true
        b94:
          type: string
        b95:
          type: array
          items:
            type: string
          example: ["passport_photo"]
        b96:
          type: string
          nullable: true
        b97:
          type: string
        b98:
          type: string
        b99:
          type: string
        b100:
          type: string

    AUContactDetailsV1:
      type: object
      required:
        - xx1
        - xx2
        - xx3
        - xx4
        - xx5
        - xx6
        - xx7
        - xx8
        - xx9
        - xx10
        - xx11
        - xx12
        - xx13
      properties:
        xx1:
          type: string
        xx2:
          type: string
        xx3:
          type: string
        xx4:
          type: string
        xx5:
          type: string
        xx6:
          type: string
        xx7:
          type: string
        xx8:
          type: string
        xx9:
          type: string
        xx10:
          type: string
        xx11:
          type: string
        xx12:
          type: string
        xx13:
          type: string

    AUYourDetailsFieldDataDataV1:
      type: object
      required:
        - x1
        - x2
        - x3
        - x4
        - x5
        - x6
        - x7
        - x8
        - x9
        - x10
        - x11
        - x12
        - x13
        - x14
        - x15
      properties:
        x1:
          type: string
        x2:
          type: string
        x3:
          type: string
        x4:
          type: string
        x5:
          type: string
        x6:
          type: string
        x7:
          type: string
        x8:
          type: string
        x9:
          type: string
        x10:
          type: string
        x11:
          type: string
        x12:
          type: string
        x13:
          type: string
        x14:
          type: string
        x15:
          type: object
          allOf:
            - $ref: "#/components/schemas/AUContactDetailsV1"

    AUYourDetailsFieldDataV1:
      type: object
      required:
        - d1
      properties:
        details:
          allOf:
            - $ref: "#/components/schemas/AUYourDetailsFieldDataDataV1"

    AUTemperamentV1:
      type: object
      required:
        - e1
      properties:
        id:
          type: string

    AUTemperamentInputV1:
      type: object
      required:
        - f1
        - f2
      properties:
        f1:
          type: string
        f2:
          type: string

    AUCrateSizeV1:
      type: object
      required:
        - aa1
        - aa2
        - aa3
      properties:
        aa1:
          type: string
        aa2:
          type: string
        aa3:
          type: string

    AUPetFieldDataDataV1:
      type: object
      required:
        - g1
        - g2_1
        - g3_1
        - g4
        - g5
        - g6
        - g7
        - g8
        - g9
        - g10
        - g11
        - g12
        - g13
        - g14
        - g15
        - g16
        - g17
        - g18
        - g19
        - g20
        - g21
        - g22
        - g23
        - g24
        - g25
        - g26
        - g27
        - g28
        - g29
        - g30
        - g31
        - g32
        - g33
      properties:
        g1:
          type: string
        "g2_1":
          type: string
        "g3_1":
          type: string
        g4:
          type: string
        g5:
          type: string
        g6:
          type: string
        g7:
          type: string
        g8:
          type: string
        g9:
          type: string
        g10:
          type: string
        g11:
          type: string
        g12:
          type: string
        g13:
          type: string
        g14:
          type: string
        g15:
          type: string
        g16:
          type: string
        g17:
          type: object
          additionalProperties: true
          properties:
            allOf:
              $ref: "#/components/schemas/AUTemperamentV1"
        g18:
          type: object
          additionalProperties: true
          properties:
            allOf:
              $ref: "#/components/schemas/AUTemperamentInputV1"
        g19:
          type: string
        g20:
          type: string
        g21:
          type: object
          allOf:
            - $ref: "#/components/schemas/AUCrateSizeV1"
        g22:
          type: string
        g23:
          type: string
        g24:
          type: string
        g25:
          type: string
        g26:
          type: string
        g27:
          type: string
        g28:
          type: string
        g29:
          type: string
        g30:
          type: string
        g31:
          type: string
        g32:
          type: string
        g33:
          type: string

    AUPetFieldDataV1:
      type: object
      required:
        - h1
      properties:
        h1:
          type: object
          additionalProperties: true
          properties:
            allOf:
              $ref: "#/components/schemas/AUPetFieldDataDataV1"

    AUDepartureFieldDataDataV1:
      type: object
      required:
        - i1
        - i2
        - i3
        - i4
        - i5
        - i6
        - i7
        - i8
        - i9
        - i10
        - i11
        - i12
        - i13
        - i14
        - i15
        - i16
        - i17
        - i18
        - i19
        - i20
        - i21
        - i22
        - i23
        - i24
        - i25
        - i26
        - i27
        - i28
        - i29
        - i30
        - i31
        - i32
        - i33
      properties:
        i1:
          type: string
        i2:
          type: number
        i3:
          type: number
          nullable: true
        i4:
          type: number
        i5:
          type: number
          nullable: true
        i6:
          type: string
        i7:
          type: number
        i8:
          type: number
        i9:
          type: string
        i10:
          type: string
        i11:
          type: string
        i12:
          type: string
        i13:
          type: string
        i14:
          type: string
        i15:
          type: string
        i16:
          type: string
        i17:
          type: string
        i18:
          type: string
        i19:
          type: string
        i20:
          type: string
        i21:
          type: string
        i22:
          type: string
        i23:
          type: string
        i24:
          type: string
        i25:
          type: string
        i26:
          type: string
        i27:
          type: string
        i28:
          type: string
        i29:
          type: string
        i30:
          type: string
        i31:
          type: string
        i32:
          type: string
        i33:
          type: string

    AUDepartureFieldDataV1:
      type: object
      required:
        - j1
      properties:
        j1:
          allOf:
            - $ref: "#/components/schemas/AUDepartureFieldDataDataV1"

    AUArrivalFieldDataDataV1:
      type: object
      required:
        - k1
        - k2
        - k3
        - k4
        - k5
        - k6
        - k7
        - k8
        - k9
        - k10
        - k11
        - k12
        - k13
        - k14
        - k15
        - k16
        - k17
        - k18
        - k19
        - k20
        - k21
        - k22
      properties:
        k1:
          type: string
        k2:
          type: string
        k3:
          type: string
        k4:
          type: string
        k5:
          type: string
        k6:
          type: string
        k7:
          type: string
        k8:
          type: string
        k9:
          type: string
        k10:
          type: string
        k11:
          type: string
        k12:
          type: string
        k13:
          type: string
        k14:
          type: string
        k15:
          type: string
        k16:
          type: string
        k17:
          type: string
        k18:
          type: string
        k19:
          type: string
        k20:
          type: string
        k21:
          type: string
        k22:
          type: string
        k23:
          type: string

    AUArrivalFieldDataV1:
      type: object
      required:
        - l1
      properties:
        l1:
          allOf:
            - $ref: "#/components/schemas/AUArrivalFieldDataDataV1"

    AUConfirmationFieldDataDataV1:
      type: object
      required:
        - m1
        - m2
        - m3
        - m4
        - m5
      properties:
        m1:
          type: string
        m2:
          type: string
        m3:
          type: string
        m4:
          type: string
        m5:
          type: string

    AUConfirmationFieldDataV1:
      type: object
      required:
        - n1
      properties:
        n1:
          allOf:
            - $ref: "#/components/schemas/AUConfirmationFieldDataDataV1"

    FormSubmitRequestBody:
      type: object
      required:
        - o1
        - o2
        - o3
      properties:
        o1:
          type: number
        o2:
          type: number
        o3:
          type: boolean
        o4:
          type: object
          oneOf:
            - $ref: "#/components/schemas/FieldData"
            - $ref: "#/components/schemas/AUYourDetailsFieldDataV1"
            - $ref: "#/components/schemas/AUPetFieldDataV1"
            - $ref: "#/components/schemas/AUDepartureFieldDataV1"
            - $ref: "#/components/schemas/AUArrivalFieldDataV1"
            - $ref: "#/components/schemas/AUConfirmationFieldDataV1"
        o5:
          type: string

    Progress:
      type: object
      required:
        - p1
        - p2
      properties:
        p1:
          type: number
          nullable: true
        p2:
          type: number
          nullable: true

    FormSubmitResponse:
      type: object
      required:
        - q1
        - q2
        - q3
      properties:
        q1:
          type: string
        q2:
          type: string
        q3:
          type: object
          allOf:
            - $ref: "#/components/schemas/Progress"
        error:
          type: object
          allOf:
            - $ref: "#/components/schemas/ErrorData"

  requestBodies:
    FormSubmitRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/FormSubmitRequestBody"
      required: true

  responses:
    FormSubmitResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/FormSubmitResponse"
```

**Comment by wing328** [comment]
tested with the latest master and no longer seeing the same error
```
$ java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java -i /tmp/a.yaml -o /tmp/aaa/
[main] WARN  o.o.codegen.DefaultCodegen - Generation using 3.1.0 specs is in development and is not officially supported yet. If you would like to expedite development, please consider woking on the open issues in the 3.1.0 project: https://github.com/orgs/OpenAPITools/projects/4/views/1 and reach out to our team on Slack at https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: java (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'java' is considered stable.
[main] INFO  o.o.c.languages.AbstractJavaCodegen - Environment variable JAVA_POST_PROCESS_FILE not defined so the Java code may not be properly formatted. To define it, try 'export JAVA_POST_PROCESS_FILE="/usr/local/bin/clang-format -i"' (Linux/Mac)
[main] INFO  o.o.c.languages.AbstractJavaCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.codegen.InlineModelResolver - Inline schema created as AUPetFieldDataDataV1_g17. To have complete control of the model name, set the `title` field or use the modelNameMapping option (e.g. --model-name-mappings AUPetFieldDataDataV1_g17=NewModel,ModelA=NewModelA in CLI) or inlineSchemaNameMapping option (--inline-schema-name-mappings AUPetFieldDataDataV1_g17=NewModel,ModelA=NewModelA in CLI).
[main] INFO  o.o.codegen.InlineModelResolver - Inline schema created as AUPetFieldDataDataV1_g18. To have complete control of the model name, set the `title` field or use the modelNameMapping option (e.g. --model-name-mappings AUPetFieldDataDataV1_g18=NewModel,ModelA=NewModelA in CLI) or inlineSchemaNameMapping option (--inline-schema-name-mappings AUPetFieldDataDataV1_g18=NewModel,ModelA=NewModelA in CLI).
[main] INFO  o.o.codegen.InlineModelResolver - Inline schema created as AUPetFieldDataV1_h1. To have complete control of the model name, set the `title` field or use the modelNameMapping option (e.g. --model-name-mappings AUPetFieldDataV1_h1=NewModel,ModelA=NewModelA in CLI) or inlineSchemaNameMapping option (--inline-schema-name-mappings AUPetFieldDataV1_h1=NewModel,ModelA=NewModelA in CLI).
[main] INFO  o.o.codegen.InlineModelResolver - Inline schema created as FormSubmitRequestBody_o4. To have complete control of the model name, set the `title` field or use the modelNameMapping option (e.g. --model-name-mappings FormSubmitRequestBody_o4=NewModel,ModelA=NewModelA in CLI) or inlineSchemaNameMapping option (--inline-schema-name-mappings FormSubmitRequestBody_o4=NewModel,ModelA=NewModelA in CLI).
[main] INFO  o.o.c.languages.AbstractJavaCodegen - Processing operation booking_form_step_submit
[main] WARN  o.o.codegen.DefaultCodegen - Generation using 3.1.0 specs is in development and is not officially supported yet. If you would like to expedite development, please consider woking on the open issues in the 3.1.0 project: https://github.com/orgs/OpenAPITools/projects/4/views/1 and reach out to our team on Slack at https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g
[main] INFO  o.o.codegen.TemplateManager - writing file C:\Users\wing3\AppData\Local\Temp\aaa\src\main\java\org\openapitools\client\model\AUArrivalFieldDataDataV1.java
[main] INFO  o.o.codegen.TemplateManager - Skipped C:\Users\wing3\AppData\Local\Temp\aaa\src\test\java\org\openapitools\client\model\AUArrivalFieldDataDataV1Test.java (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - writing file C:\Users\wing3\AppData\Local\Temp\aaa\docs\AUArrivalFieldDataDataV1.md
[main] INFO  o.o.codegen.TemplateManager - writing file C:\Users\wing3\AppData\Local\Temp\aaa\src\main\java\org\openapitools\client\model\AUArrivalFieldDataV1.java
[main] INFO  o.o.codegen.TemplateManager - Skipped C:\Users\wing3\AppData\Local\Temp\aaa\src\test\java\org\openapitools\client\model\AUArrivalFieldDataV1Test.java (Test files never overwrite an existing file of the same name.)

```

**Comment by cybernetchin** [comment]
Thank you wing328, when can this available and release for "npx @openapitools/openapi-generator-cli"?
