### ISSUE TITLE
[BUG][JAVA] OpenAPI Generate fails on Windows with Type-Mappings that contain generics

### ISSUE THREAD

**Issue by Glurz** [OpenAPITools/openapi-generator#19174]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using schema mappings that contain generics, the generator fails to run on Windows since it tries to construct a file path containing illegal characters (the generic brackets).

##### openapi-generator version

7.7.0
##### OpenAPI declaration file content or url

Not relevant.

##### Generation Details

```
openApiGenerate {
	generatorName = "spring"
	inputSpec = "my-openapi.yaml"
	outputDir = "${projectDir}/generated-src"
	apiPackage = "my.org.internal.infrastructure.resource"
	modelPackage = "my.org.internal.infrastructure.transfer"

	configOptions = mapOf(
		//"apiFirst" to "true",
		"interfaceOnly" to "true",
		"skipDefaultInterface" to "true",
		"useOptional" to "true",
		"useJakartaEe" to "true",
		"useTags" to "true",
		"useBeanValidation" to "true",
		"performBeanValidation" to "true",
		"useSpringBoot3" to "true",
		"useSpringController" to "true",
		"disallowAdditionalPropertiesIfNotPresent" to "false",
		"sourceFolder" to "", // With the default main/src/java in generated-src, the package name does not match
	)
	schemaMappings.set(
		mapOf(
			"UpdatePluginRequest" to "RequestDocument<Map<String, Object>>"
		)
	)
	importMappings.set(
		mapOf(
			"RequestDocument<Map<String, Object>>" to "my.org.RequestDocument"
		)
	)
}
```

##### Steps to reproduce

An above configuration with schema mappings that contain generics fails on Windows with the following stack trace:
**The relevant line is DefaultGenerator.java:481**

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':config-editor:openApiGenerate'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:130)
    at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:128)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:116)
    at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
    at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
    at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
    at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
    at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
    at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
...    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
    at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: org.gradle.api.GradleException: Code generation failed.
    at org.openapitools.generator.gradle.plugin.tasks.GenerateTask.doWork(GenerateTask.kt:957)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
    at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
    at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
    at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
    at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:244)
    at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
    at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
    at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
    at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
...
    at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
    at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
    at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
    at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
    at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
    at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
    at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
    at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
    at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
    at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: java.lang.RuntimeException: Could not process model 'UpdatePluginRequest'.Please make sure that your schema is correct!
    at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:530)
    at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:449)
    at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:1302)
    at org.openapitools.generator.gradle.plugin.tasks.GenerateTask.doWork(GenerateTask.kt:953)
    ... 123 more
Caused by: java.nio.file.InvalidPathException: Illegal char <<> at index 133: C:\Workspaces\git-repos\my-project\generated-src\my\org\internal\infrastructure\transfer\RequestDocument<Map<String, Object>>.java
    at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:481)
    ... 126 more
```

##### Suggest a fix

I only have a limited understanding of the generator logic. But it's not obvious, why a file path for the target type of the schema mapping is to be constructed in the model package.

**Comment by Xiphoseer** [comment]
I filed #19167 for this exact issue a day before this one :D

**Comment by Glurz** [comment]
@Xiphoseer: Thanks for the hint. I checked for already existing issues, but then got distracted and you were faster... ;)
I will close as duplicate.
