### ISSUE TITLE
[BUG] setup.py incorrect using python or python-pydantic-v1 generators when no paths are specified

### ISSUE THREAD

**Issue by loic-seguin** [OpenAPITools/openapi-generator#20090]
#### Bug Report Checklist

- [ x] Have you provided a full/minimal spec to reproduce the issue?
- [ x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I generate a python client based on my really simple openapi.yaml.
But the setup.py that is generated does not contain the setup() method.
So it is not possible to import this library with poetry or pip.

##### openapi-generator version

7.9.0 but it seems to have the same issue on 7.0.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: RepositoryActions
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    RepositoryActions:
      type: object
      properties:
        repository_url:
          type: string
        actions:
          type: array
          items:
            $ref: '#/components/schemas/CreateCommentAction'
    CreateCommentAction:
      type: object
      properties:
        text:
          type: string
```

##### Generation Details

openapi-generator-cli generate -i openapi.yaml -g python -o ./generated-python-client

##### Steps to reproduce

openapi-generator-cli generate -i openapi.yaml -g python -o ./generated-python-client

- Create a new folder testpoetry at the same level of the folder that has been generated
- Create a new file testpoetry/pyproject.toml with this content
```
[tool.poetry]
name = "poetrytest"
version = "0.1.0"
description = ""
authors = ["me"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openapi-client = {path="../generated-python-client/"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```
Run the command 'poetry install'

You will get this error 
```
poetry install
Updating dependencies
Resolving dependencies... (0.5s)

Package operations: 1 install, 0 updates, 0 removals

  - Installing openapi-client (1.0.0 /home/lseguin/Documents/github_describe_issue/generated-python-client): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  Traceback (most recent call last):
    File "/home/lseguin/.local/share/pypoetry/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
      main()
    File "/home/lseguin/.local/share/pypoetry/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
    File "/home/lseguin/.local/share/pypoetry/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 280, in build_wheel
      return _build_backend().build_wheel(
    File "/tmp/tmp8o7fzmxu/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 435, in build_wheel
      return _build(['bdist_wheel'])
    File "/tmp/tmp8o7fzmxu/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 426, in _build
      return self._build_with_temp_dir(
    File "/tmp/tmp8o7fzmxu/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 409, in _build_with_temp_dir
      result_basename = _file_with_extension(tmp_dist_dir, result_extension)
    File "/tmp/tmp8o7fzmxu/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 128, in _file_with_extension
      raise ValueError(
  ValueError: No distribution was found. Ensure that `setup.py` is not empty and that it calls `setup()`.
  

  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with openapi-client (1.0.0 /home/lseguin/Documents/github_describe_issue/generated-python-client) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "openapi-client @ file:///home/lseguin/Documents/github_describe_issue/generated-python-client"'.
```

##### Suggest a fix
The generation of the setup.py is incorrect, as it should call the setup method for me : 
```
from setuptools import setup, find_packages

NAME = "openapi-client"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">=3.7"
setup(name=NAME,version=VERSION,python_requires=PYTHON_REQUIRES)
```
This file does not seem to be used properly -> https://github.com/OpenAPITools/openapi-generator/blob/a95ea1f519c79ac23ca1315a796b5821b05800c8/modules/openapi-generator/src/main/resources/python/setup.mustache#L9

**Comment by loic-seguin** [comment]
I have found the problem I think, the paths property is not present in my openapi.yaml because I don't need any APIs for now. I just need the models to be generated. Trying to fix the problem in a PR.

**Comment by wing328** [comment]
thanks for providing the steps to reproduce the issue but I couldn't repeat it as `poetry install` works fine for me

i'm using Poetry (version 1.8.4).

**Comment by loic-seguin** [comment]
Could you print out your testpoetry/pyproject.toml please.
I don't see in your log thé dependency to your python client generated by openApi

**Comment by wing328** [comment]
```
wing328@MSI /tmp/python23 % cat testpoetry/pyproject.toml
[tool.poetry]
name = "poetrytest"
version = "0.1.0"
description = ""
authors = ["me"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openapi-client = {path="../generated-python-client/"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

**Comment by loic-seguin** [comment]
Could you show me your openapi.yaml
I will send you the version of my poetry install

**Comment by wing328** [comment]
i used the one you provided above:
```
openapi: 3.0.0
info:
  title: RepositoryActions
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    RepositoryActions:
      type: object
      properties:
        repository_url:
          type: string
        actions:
          type: array
          items:
            $ref: '#/components/schemas/CreateCommentAction'
    CreateCommentAction:
      type: object
      properties:
        text:
          type: string
```


did you test it in another machine or environment to see if the issue is caused by something else?

**Comment by loic-seguin** [comment]
Well, so I guess that the setup.py generated on your side contains the method setup right ?

**Comment by wing328** [comment]
that's what i got

```
wing328@MSI /tmp/python23 % cat setup.py
# coding: utf-8

"""
    RepositoryActions

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "openapi-client"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.8"
```

**Comment by loic-seguin** [comment]
Will try this on monday

**Comment by loic-seguin** [comment]
Just sent you the tar.gz of my test.

[issue_20090.tar.gz](https://github.com/user-attachments/files/17803173/issue_20090.tar.gz)

My poetry version is 1.8.4.

I did the following commands : 

```
tar -xzvf issue_20090.tar.gz
cd issue_20090/
wget https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/7.10.0-SNAPSHOT/openapi-generator-cli-7.10.0-20241118.101601-94.jar -O openapi-generator-cli.jar
java -jar openapi-generator-cli.jar generate -i openapi.yaml -g python -o ./generated-python-client
cd poetrytest
poetry install
```

I got the same log issue : 

```
Package operations: 8 installs, 0 updates, 0 removals

  - Installing typing-extensions (4.12.2)
  - Installing annotated-types (0.7.0)
  - Installing pydantic-core (2.23.4)
  - Installing six (1.16.0)
  - Installing pydantic (2.9.2)
  - Installing python-dateutil (2.9.0.post0)
  - Installing urllib3 (2.2.3)
  - Installing openapi-client (1.0.0 /home/lseguin/Documents/issue_20090/generated-python-client): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  Traceback (most recent call last):
    File "/home/lseguin/.local/share/pypoetry/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
      main()
    File "/home/lseguin/.local/share/pypoetry/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
    File "/home/lseguin/.local/share/pypoetry/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 280, in build_wheel
      return _build_backend().build_wheel(
    File "/tmp/tmpj8hl8kle/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 435, in build_wheel
      return _build(['bdist_wheel'])
    File "/tmp/tmpj8hl8kle/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 426, in _build
      return self._build_with_temp_dir(
    File "/tmp/tmpj8hl8kle/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 409, in _build_with_temp_dir
      result_basename = _file_with_extension(tmp_dist_dir, result_extension)
    File "/tmp/tmpj8hl8kle/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 128, in _file_with_extension
      raise ValueError(
  ValueError: No distribution was found. Ensure that `setup.py` is not empty and that it calls `setup()`.
  

  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with openapi-client (1.0.0 /home/lseguin/Documents/issue_20090/generated-python-client) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "openapi-client @ file:///home/lseguin/Documents/issue_20090/generated-python-client"'.
```

**Comment by wing328** [comment]
thanks for the info

did you test the fix (PR) locally (build the CLI JAR and test with the spec)?

**Comment by loic-seguin** [comment]
Nope will do it asap

**Comment by loic-seguin** [comment]
Ok done I have done these actions : 

```mvn clean install
   cp modules/openapi-generator-cli/target/openapi-generator-cli.jar ~/issue_20090
   cd ~/issue_20090
   java -jar openapi-generator-cli.jar generate -i openapi.yaml -g python -o ./generated-python-client
  cd poetrytest
  poetry install
```
I got
```
Creating virtualenv poetrytest in /home/lseguin/Downloads/issue_20090/poetrytest/.venv
Updating dependencies
Resolving dependencies... (1.7s)

Package operations: 8 installs, 0 updates, 0 removals

  - Installing typing-extensions (4.12.2)
  - Installing annotated-types (0.7.0)
  - Installing pydantic-core (2.27.1)
  - Installing six (1.16.0)
  - Installing pydantic (2.10.1)
  - Installing python-dateutil (2.9.0.post0)
  - Installing urllib3 (2.2.3)
  - Installing openapi-client (1.0.0 /home/lseguin/Downloads/issue_20090/generated-python-client)

Writing lock file

Installing the current project: poetrytest (0.1.0)

```
