### ISSUE TITLE
openapi schema 3.0 yaml warnings

### ISSUE THREAD

**Issue by ranjitkumar2k10** [OpenAPITools/openapi-generator#2030]
1) i created my yaml with openapi 3.0 specification 
2) generated the go server stub code  and getting below warnings.

1) WARN  - o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
2) WARN  o.o.codegen.DefaultCodegen - The following schema has undefined (null) baseType. It could be due to form parameter defined in OpenAPI v2 spec with incorrect consumes. A correct 'consumes' for form parameters should be 'application/x-www-form-urlencoded' or 'multipart/form-data'
[main] WARN  o.o.codegen.DefaultCodegen - schema: class ComposedSchema {
    class Schema {
        title: null
        multipleOf: null
        maximum: null
        exclusiveMaximum: null
        minimum: null
        exclusiveMinimum: null
        maxLength: null
        minLength: null
        pattern: null
        maxItems: null
        minItems: null
        uniqueItems: null
        maxProperties: null
        minProperties: null
        required: null
        type: null
        not: null
        properties: null
        additionalProperties: null
        description: null
        format: null
        $ref: null
        nullable: null
        readOnly: null
        writeOnly: null
        example: null
        externalDocs: null
        deprecated: null
        discriminator: null
        xml: null
    }
    allOf: null
    anyOf: null
    oneOf: [class Schema {
        title: null
        multipleOf: null
        maximum: null
        exclusiveMaximum: null
        minimum: null
        exclusiveMinimum: null
        maxLength: null
        minLength: null
        pattern: null
        maxItems: null
        minItems: null
        uniqueItems: null
        maxProperties: null
        minProperties: null
        required: null
        type: null
        not: null
        properties: null
        additionalProperties: null
        description: null
        format: null
        $ref: #/components/schemas/AppTerminationNotificationSubscription
        nullable: null
        readOnly: null
        writeOnly: null
        example: null
        externalDocs: null
        deprecated: null
        discriminator: null
        xml: null
    }, class Schema {
        title: null
        multipleOf: null
        maximum: null
        exclusiveMaximum: null
        minimum: null
        exclusiveMinimum: null
        maxLength: null
        minLength: null
        pattern: null
        maxItems: null
        minItems: null
        uniqueItems: null
        maxProperties: null
        minProperties: null
        required: null
        type: null
        not: null
        properties: null
        additionalProperties: null
        description: null
        format: null
        $ref: #/components/schemas/SerAvailabilityNotificationSubscription
        nullable: null
        readOnly: null
        writeOnly: null
        example: null
        externalDocs: null
        deprecated: null
        discriminator: null
        xml: null
    }]
}
3) WARN  o.o.codegen.DefaultCodegen - codegenModel is null. Default to UNKNOWN_BASE_TYPE

**Comment by wing328** [comment]
Which version are you using? If you're not using latest master, please give it a try.

**Comment by ranjitkumar2k10** [comment]
Even when I tried to generate with https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/4.0.0-SNAPSHOT/openapi-generator-cli-4.0.0-20190125.032857-237.jar

****i am getting below errors:** and core also not generating**
[root@steady-lab 3.0_withlatestjar]# java -jar openapi-generator-cli.jar  generate -i Mp1.yaml -t mustach_templates -g go-server -o .
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 11, Warning count: 0
Errors:
        -attribute paths.'/applications/{appInstanceId}/subscriptions/{subscriptionType}/{subscriptionId}'. Declared path parameter appInstanceId needs to be defined as a path parameter in path or operation level
        -attribute paths.'/applications/{appInstanceId}/subscriptions/{subscriptionType}/{subscriptionId}'. Declared path parameter subscriptionType needs to be defined as a path parameter in path or operation level
        -attribute paths.'/applications/{appInstanceId}/subscriptions/{subscriptionType}/{subscriptionId}'. Declared path parameter subscriptionId needs to be defined as a path parameter in path or operation level
        -attribute paths.'/applications/{appInstanceId}/dns_rules'. Declared path parameter appInstanceId needs to be defined as a path parameter in path or operation level
        -attribute paths.'/applications/{appInstanceId}/dns_rules/{dnsRuleId}'. Declared path parameter dnsRuleId needs to be defined as a path parameter in path or operation level
        -attribute paths.'/applications/{appInstanceId}/traffic_rules/{trafficRuleId}'. Declared path parameter trafficRuleId needs to be defined as a path parameter in path or operation level
        -attribute paths.'/applications/{appInstanceId}/traffic_rules'. Declared path parameter appInstanceId needs to be defined as a path parameter in path or operation level
        -attribute paths.'/applications/{appInstanceId}/subscriptions'. Declared path parameter appInstanceId needs to be defined as a path parameter in path or operation level
        -attribute paths.'/applications/{appInstanceId}/dns_rules/{dnsRuleId}'. Declared path parameter appInstanceId needs to be defined as a path parameter in path or operation level
        -attribute paths.'/services/{serviceId}'. Declared path parameter serviceId needs to be defined as a path parameter in path or operation level
        -attribute paths.'/applications/{appInstanceId}/traffic_rules/{trafficRuleId}'. Declared path parameter appInstanceId needs to be defined as a path parameter in path or operation level

        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:588)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:353)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)

**Comment by wing328** [comment]
There's a checklist when opening an issue. Please spend some time to go through that.

**Comment by ranjitkumar2k10** [comment]
Are these warnings are due to spec is properly aligned with 3.0 also
