### ISSUE TITLE
[BUG] javascript: unexpected token import

### ISSUE THREAD

**Issue by jacobweber** [OpenAPITools/openapi-generator#2126]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

I'm using a Swagger 2 spec, with the javascript generator, on Mac OS 10.14.2, with node v18.2.0 and npm 6.4.1. I can't get the example code to work, regardless of the spec.

After I build it, I make a `.tar.gz` of the code, so I can install it with npm:
```
tar czvf /path/to/swagger.tar.gz /path/to/output
```

Then in my project, I run:
```
npm install
npm install /path/to/swagger.tar.gz
```

The last command outputs:
```
npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers

> fsevents@1.2.7 install /path/to/project/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[fsevents] Success: "/path/to/project/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" is installed via remote
+ swagger_example@1.0.0
added 322 packages from 160 contributors and audited 1559 packages in 10.067s
found 0 vulnerabilities
```

Then when I try to use it, following the example:
```
var SwaggerExample = require('swagger_example');
```

I get an error:

```
/path/to/project/node_modules/swagger_example/src/index.js:15
import ApiClient from './ApiClient';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/project/src/index.js:2:29)
```

##### openapi-generator version

4.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

Works with any spec, e.g. https://gist.github.com/jacobweber/53422c873b34de07e9e715fdbb9cbc1d

##### Command line used for generation

```
java -jar /path/to/openapi-generator-cli.jar generate -i /path/to/spec.json -g javascript -o /path/to/output
```

##### Steps to reproduce

See above.

##### Related issues/PRs

This used to work with swagger-codegen.

##### Suggest a fix

None

**Comment by jacobweber** [comment]
Building with `-DuseES6=false` fixes this.

**Comment by wing328** [comment]
@jacobweber thanks for reporting the issue. I think we need to fix it as ES6 is now the default

**Comment by cliffano** [comment]
@jacobweber Just to confirm, do you mean node `v8.2.0` ? I'm guessing the `v18.2.0` is a typo?

@wing328 which node versions are the official ones that openapi-generator would like to support?

**Comment by jacobweber** [comment]
Sorry, I meant v8.12.0.

**Comment by wing328** [comment]
> @wing328 which node versions are the official ones that openapi-generator would like to support?

I don't think we've decided on that. What would you recommend?

**Comment by cliffano** [comment]
@wing328 I'd recommend to follow node's LTS schedule https://nodejs.org/en/about/releases/ .
Since v6 will be reaching EOL on April 1st, it's best to only support v8 and newer.
Having said that, I guess it will all depend on the team's capacity.

**Comment by wing328** [comment]
@cliffano From @jacobweber's reply, seems like it's an issue for both v6 and v8. Are you able to repeat the issue locally in your machine?

**Comment by jacobweber** [comment]
@wing328 I only tried 8.x (the 6.x was for npm). But I don't think Node supports ES6 modules (import/export) natively in any version....I think you have to use Babel to make them work.

**Comment by wing328** [comment]
> I think you have to use Babel to make them work.

@jacobweber thanks for sharing more. package.json does have babel included: https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/javascript-es6/package.json#L14

and there's a .babelrc file: https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/javascript-es6/.babelrc

**Comment by wing328** [comment]
Btw, I added some Petstore integration tests to JS ES6 client before ( https://github.com/OpenAPITools/openapi-generator/pull/2245), which seems to be working fine in my machine and the CI build server

@jacobweber when you've time, can you run these tests locally to see if you get any error?

**Comment by cliffano** [comment]
@jacobweber Can you share your swagger.tar.gz ? Or perhaps a simplified version of it that has an error.

@wing328 I can't yet reproduce the problem. However, I noticed that Petstore javascript-es6 example has both babel and babel-cli in package.json , not exactly sure why babel is needed considering it's deprecated and replaced by babel-cli.

**Comment by jacobweber** [comment]
@cliffano @wing328  If you got it working, I'm sure it's fine. I just didn't realize I had to run a Babel build....I was trying to run my JS file directly. Might be worth adding a note about that in the README.

(But aren't the settings in the generated package.json and .babelrc only used when building the client itself, rather than using it as a library in another app?)

**Comment by kvsm** [comment]
I ran into this, too, but fortunately recognised the issue as node not supporting es6 module format. The default generated package.json should probably include run/build script and npm package hook to make use of babel/babel-node.

**Comment by kvsm** [comment]
@jacobweber if you are using the client as a library in another app, you would typical run a babel build to convert es6 to es5 and publish the output as your library. I have it set up like this in package.json:
```
"scripts": {
    "build": "babel src -d dist",
    "prepack": "npm run build"
  },
"files": [ "dist" ]
}
```

This way only the es5 output in `dist` will be published.

**Comment by wing328** [comment]
> However, I noticed that Petstore javascript-es6 example has both babel and babel-cli in package.json , not exactly sure why babel is needed considering it's deprecated and replaced by babel-cli.

@cliffano I've no idea either. Maybe a good idea to clean it up and use babel-cli only?

**Comment by wing328** [comment]
Thanks for @kvsm PR, which has been merged into master.
