### ISSUE TITLE
[BUG] [PythonFlask] TypeError traceback (petshop.yaml)

### ISSUE THREAD

**Issue by instantlinux** [OpenAPITools/openapi-generator#2188]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

New installation will not create a working Flask container from the generated Dockerfile when I generate python-flask server from the demo modules/openapi-generator/src/test/resources/2_0/petstore.yaml in this repo. I get _TypeError: Failed to fetch_ within the v2/ui, and a different TypeError with stacktrace in the log.

##### openapi-generator version

Master or 3.3.4

##### OpenAPI declaration file content or url

The [petshop.yaml](https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml) contained in test directory of this repo.

##### Command line used for generation

generate -i openapi-generator/modules/openapi-generator/src/test/resources/3_0/petstore.yaml -g python-flask -o new

 or
run the openapi-generator-online image from dockerhub

##### Steps to reproduce
```
sudo apt install jq unzip
curl -o flask.zip \
  $(curl -s -X POST --header 'Content-Type: application/json' \
    --header 'Accept: application/json' \
    -d '{"openAPIUrl": "https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml"}' \
    http://openapi-generator.ci.net/api/gen/servers/python-flask \
    | jq -r .link)
unzip flask.zip
cd python-flask-server
sed -i -e "s/petstore.swagger.io/$(hostname -f):8080/" openapi_server/openapi/*.yaml
docker build . -t  petshop
docker run -p 8080:8080 --name=petshop -d petshop
```
Then try to invoke actions such as 
```
curl -X POST "http://$(hostname -f):8080/v2/user" -H "accept: */*" -H "Content-Type: application/json" -d "{\"email\":\"email@foo.com\",\"firstName\":\"firstName\",\"id\":0,\"lastName\":\"lastName\",\"password\":\"password\",\"phone\":\"phone\",\"userStatus\":6,\"username\":\"myname\"}"
```

On backend I see logs that look like:
```
192.168.2.44 - - [19/Feb/2019 06:54:17] "OPTIONS /v2/user HTTP/1.1" 200 -
[2019-02-19 06:54:31,738] ERROR in app: Exception on /v2/user [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 73, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 132, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 165, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 44, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
TypeError: create_user() missing 1 required positional argument: 'user'
```
I also tried the older resources/3_0/petstore.yaml and ran into _TypeError: cannot convert dictionary update sequence element #0_ instead of the positional-argument error.

##### Related issues/PRs

I cannot find one here or by googling the error messages, so that's why I'm here. Closest thing I can find is unresolved issue #1666.

##### Suggest a fix

I'm a newbie to this (though I do have some familiarity with swagger/flask/etc), and it looks to me like a getting-started.md with full examples (validated by the CI so they don't break) would help greatly.

**Comment by wing328** [comment]
@instantlinux thanks for reporting the issue. We do have CI setup to test python flask samples (py2, py3):

https://github.com/OpenAPITools/openapi-generator/blob/master/pom.xml#L1062-L1063

Can you please test those samples to see if it works in your environment?

**Comment by instantlinux** [comment]
I'd already tried those: here's more detail.
```
$ uname -a
Linux mckinley.ci.net 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ docker version
 ...
Server:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
$ git clone https://github.com/OpenAPITools/openapi-generator.git && git pull
$ cd /home/richb/openapi-generator/samples/server/petstore/python-flask
$ ls
Dockerfile   openapi_server  requirements.txt  test-requirements.txt
git_push.sh  pom.xml         setup.py          tox.ini
Makefile     README.md       test_python3.sh
$ docker build . -t petstore
Sending build context to Docker daemon  104.4kB
Step 1/9 : FROM python:3-alpine
 ---> 2d23e3e6584b
Step 2/9 : RUN mkdir -p /usr/src/app
 ---> Using cache
 ---> 5a88e0762fa0
Step 3/9 : WORKDIR /usr/src/app
 ---> Using cache
 ---> dacb2bbec703
Step 4/9 : COPY requirements.txt /usr/src/app/
 ---> Using cache
 ---> d73c300e81bb
Step 5/9 : RUN pip3 install --no-cache-dir -r requirements.txt
 ---> Using cache
 ---> a691f03a3353
Step 6/9 : COPY . /usr/src/app
 ---> 6338acd8f795
Step 7/9 : EXPOSE 8080
 ---> Running in 3263e162ea70
Removing intermediate container 3263e162ea70
 ---> 2359d31039e7
Step 8/9 : ENTRYPOINT ["python3"]
 ---> Running in 9c0ccd1fa40e
Removing intermediate container 9c0ccd1fa40e
 ---> ed3053e912ab
Step 9/9 : CMD ["-m", "openapi_server"]
 ---> Running in ffad3c6c2b43
Removing intermediate container ffad3c6c2b43
 ---> 5cca3276b0eb
Successfully built 5cca3276b0eb
Successfully tagged petstore:latest
$ docker run -p 8080:8080 -d  --name=petstore petstore
$ curl -X POST "http://$(hostname -f):8080/v2/user" -H "accept: */*" -H "Content-Type: application/json" -d "{\"email\":\"email@foo.com\",\"firstName\":\"firstName\",\"id\":0,\"lastName\":\"lastName\",\"password\":\"password\",\"phone\":\"phone\",\"userStatus\":6,\"username\":\"myname\"}"
{
  "detail": "The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.",
  "status": 500,
  "title": "Internal Server Error",
  "type": "about:blank"
}
```
On the container log from this instance (python3), this output is generated:
```
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
192.168.2.44 - - [21/Feb/2019 16:50:53] "GET /v2/ HTTP/1.1" 404 -
192.168.2.44 - - [21/Feb/2019 16:50:53] "GET /favicon.ico HTTP/1.1" 404 -
192.168.2.44 - - [21/Feb/2019 16:50:59] "GET / HTTP/1.1" 404 -
192.168.2.44 - - [21/Feb/2019 16:51:10] "GET /ui HTTP/1.1" 404 -
192.168.2.44 - - [21/Feb/2019 16:52:08] "GET /v2/ui/ HTTP/1.1" 200 -
192.168.2.44 - - [21/Feb/2019 16:52:08] "GET /v2/ui/swagger-ui.css HTTP/1.1" 304 -
192.168.2.44 - - [21/Feb/2019 16:52:08] "GET /v2/ui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
192.168.2.44 - - [21/Feb/2019 16:52:08] "GET /v2/ui/swagger-ui-bundle.js HTTP/1.1" 200 -
192.168.2.44 - - [21/Feb/2019 16:52:09] "GET /v2/openapi.json HTTP/1.1" 200 -
[2019-02-21 16:53:22,692] ERROR in app: Exception on /v2/user [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 73, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 132, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 172, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 44, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 108, in wrapper
    request.files, arguments, has_kwargs, sanitize)
  File "/usr/local/lib/python3.7/site-packages/connexion/operations/abstract.py", line 275, in get_arguments
    has_kwargs, sanitize))
  File "/usr/local/lib/python3.7/site-packages/connexion/operations/openapi.py", line 263, in _get_body_argument
    body_arg.update(body or {})
TypeError: cannot convert dictionary update sequence element #0 to a sequence
172.17.0.1 - - [21/Feb/2019 16:53:22] "POST /v2/user HTTP/1.1" 500 -
```
It's hard for me to believe that this Dockerfile is in CI and that all the endpoints are verified.

**Comment by instantlinux** [comment]
Moving on to the python2 image:
```
$ docker rm -f -v petstore
$ cd /home/richb/openapi-generator/samples/server/petstore/python-flask-python2
$ docker build . -t petstore-python2
Sending build context to Docker daemon  104.4kB
Step 1/9 : FROM python:2-alpine
 ---> 38c2c7254ad2
Step 2/9 : RUN mkdir -p /usr/src/app
 ---> Using cache
 ---> d7592c6bd4b6
Step 3/9 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 1470c99f05d4
Step 4/9 : COPY requirements.txt /usr/src/app/
 ---> 6dae81859a91
Step 5/9 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Running in 698fe5777b25
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting connexion==2.0.2 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/78/46/7a53cd1771e098d7d6b707a5667d93c8ce6028fe0a4544739eebe9b91303/connexion-2.0.2-py2.py3-none-any.whl (1.0MB)
Collecting swagger-ui-bundle==0.0.2 (from -r requirements.txt (line 2))
 ...
  Running setup.py install for PyYAML: started
    Running setup.py install for PyYAML: finished with status 'done'
Successfully installed Jinja2-2.10 MarkupSafe-1.1.0 PyYAML-3.13 Werkzeug-0.14.1 certifi-2018.11.29 chardet-3.0.4 click-7.0 clickclick-1.2.2 connexion-2.0.2 flask-1.0.2 functools32-3.2.3.post2 idna-2.8 inflection-0.3.1 itsdangerous-1.1.0 jsonschema-2.6.0 openapi-spec-validator-0.2.4 pathlib-1.0.1 python-dateutil-2.6.0 requests-2.21.0 six-1.12.0 swagger-ui-bundle-0.0.2 typing-3.5.2.2 urllib3-1.24.1
You are using pip version 19.0.2, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 698fe5777b25
 ---> dfa059ce54ef
Step 6/9 : COPY . /usr/src/app
 ---> cdf3646a0b9f
Step 7/9 : EXPOSE 8080
 ---> Running in b5963a90068f
Removing intermediate container b5963a90068f
 ---> 3aab74dd2dae
Step 8/9 : ENTRYPOINT ["python"]
 ---> Running in 08a0874d08e1
Removing intermediate container 08a0874d08e1
 ---> 40a2aac20a54
Step 9/9 : CMD ["-m", "openapi_server"]
 ---> Running in 95ad83552724
Removing intermediate container 95ad83552724
 ---> f902e30a7673
Successfully built f902e30a7673
Successfully tagged petstore-python2:latest
$ docker run -p 8080:8080 -d  --name=petstore petstore-python2
$ curl -X POST "http://$(hostname -f):8080/v2/user" -H "accept: */*" -H "Content-Type: application/json" -d "{\"email\":\"email@foo.com\",\"firstName\":\"firstName\",\"id\":0,\"lastName\":\"lastName\",\"password\":\"password\",\"phone\":\"phone\",\"userStatus\":6,\"username\":\"myname\"}"
{
  "detail": "The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.", 
  "status": 500, 
  "title": "Internal Server Error", 
  "type": "about:blank"
}
```
This one generates a slightly-different error:
```
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
192.168.2.44 - - [21/Feb/2019 16:50:53] "GET /v2/ HTTP/1.1" 404 -
192.168.2.44 - - [21/Feb/2019 16:50:53] "GET /favicon.ico HTTP/1.1" 404 -
192.168.2.44 - - [21/Feb/2019 16:50:59] "GET / HTTP/1.1" 404 -
192.168.2.44 - - [21/Feb/2019 16:51:10] "GET /ui HTTP/1.1" 404 -
192.168.2.44 - - [21/Feb/2019 16:52:08] "GET /v2/ui/ HTTP/1.1" 200 -
192.168.2.44 - - [21/Feb/2019 16:52:08] "GET /v2/ui/swagger-ui.css HTTP/1.1" 304 -
192.168.2.44 - - [21/Feb/2019 16:52:08] "GET /v2/ui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
192.168.2.44 - - [21/Feb/2019 16:52:08] "GET /v2/ui/swagger-ui-bundle.js HTTP/1.1" 200 -
192.168.2.44 - - [21/Feb/2019 16:52:09] "GET /v2/openapi.json HTTP/1.1" 200 -
[2019-02-21 16:53:22,692] ERROR in app: Exception on /v2/user [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 73, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 132, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 172, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 44, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 108, in wrapper
    request.files, arguments, has_kwargs, sanitize)
  File "/usr/local/lib/python3.7/site-packages/connexion/operations/abstract.py", line 275, in get_arguments
    has_kwargs, sanitize))
  File "/usr/local/lib/python3.7/site-packages/connexion/operations/openapi.py", line 263, in _get_body_argument
    body_arg.update(body or {})
TypeError: cannot convert dictionary update sequence element #0 to a sequence
172.17.0.1 - - [21/Feb/2019 16:53:22] "POST /v2/user HTTP/1.1" 500 -
```
This happens whether or not I specify the api-key header.

**Comment by instantlinux** [comment]
A coworker pointed me at a workaround that could lead to a fix for this, at least for the python3 image. If you run the generator against test/resources/3_0/petstore.yaml, and then hand-edit the generated openapi.yaml file at line 392 to add x-body-name directive, you can make it work (at least, it gets as far as the logic is implemented thus far):
{noformat}
  /user:
    post:
      description: This can only be done by the logged in user.
      operationId: create_user
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: user
              $ref: '#/components/schemas/User'
{noformat}
The problem is that the controller templates aren't specifying a parameter name that matches the yaml file.

Note that fixing this only delivers stub functions that output "do some magic!". I'd rather see these controller functions invoke a separate stub class with function names that match, so I don't have to hand-edit or toss out these generated controller functions. But it'll be an improvement if we just have a working Dockerfile that doesn't trigger error-500 in each of the sample directories.

**Comment by wangzhongchunongithub** [comment]
Refer to : https://connexion.readthedocs.io/en/latest/request.html

Warning
**Please note that when you have a parameter defined as not required at your endpoint and your Python view have a non-named argument, when you call this endpoint WITHOUT the parameter you will get an exception of missing positional argument.**

For my own generated flask-connexion-server code, I make such change .
from
```
def app_update_province_weather(province_id, weather_info):  # noqa: E501
    """app_update_province_weather

     # noqa: E501

    :param province_id: 
    :type province_id: int
    :param weather_info: 
    :type weather_info: dict | bytes

    :rtype: WeatherInfo
    """
    if connexion.request.is_json:
        weather_info = WeatherInfo.from_dict(connexion.request.get_json())  # noqa: E501
    return weather_info
```

to 
```
def app_update_province_weather(province_id, weather_info):  # noqa: E501
    """app_update_province_weather

     # noqa: E501

    :param province_id: 
    :type province_id: int
    :param weather_info: 
    :type weather_info: dict | bytes

    :rtype: WeatherInfo
    """
    if connexion.request.is_json:
        weather_info = WeatherInfo.from_dict(connexion.request.get_json())  # noqa: E501
    return weather_info
```

**Comment by cleborys** [comment]
I am not completely sure if this is the relevant in your context, but in addition to the `x-body-name` that @instantlinux mentioned above, I needed to including [this fix](https://github.com/zalando/connexion/pull/893/commits/518d1dd3d711782aa56eb406b7fb346443d94271) in my installation of `connexion`.

**Comment by OJFord** [comment]
> Note that fixing this only delivers stub functions that output "do some magic!". I'd rather see these controller functions invoke a separate stub class with function names that match, so I don't have to hand-edit or toss out these generated controller functions.

Absolutely this - I don't understand how this is supposed to be used in its current state?

Manually edit `return "do some magic!"` -> `real_impl.add_pet(pet)`, commit it, and then just discard that diff (in reverse) every time `generate` is run?

Not only is that annoying, but it also makes it impossible to use `generate` to check everything's up to date.
