### ISSUE TITLE
[BUG] Cannot generate server with invokePackage=Websupport\\InvoiceValidation

### ISSUE THREAD

**Issue by FilipBenco** [OpenAPITools/openapi-generator#2402]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used? 3.2 / 3.3 / 4.0
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

I cannot generate namespace: `Websupport\InvoiceValidation` for any php server version.

And I received error: 
##### OpenAPI declaration file content or url

OpanAPI file is in this bug irrelevant

##### Command line used for generation

```
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli:v4.0.0-beta2 generate -i /local/openapi.json -g php-slim -o /local --invoker-package Websupport\\InvoiceValidation
```

Output:
```
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'Health'
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:498)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:897)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:354)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 12
^Websupport\InvoiceValidation\\*(.+)
            ^
        at java.util.regex.Pattern.error(Pattern.java:1955)
        at java.util.regex.Pattern.escape(Pattern.java:2471)
        at java.util.regex.Pattern.atom(Pattern.java:2198)
        at java.util.regex.Pattern.sequence(Pattern.java:2130)
        at java.util.regex.Pattern.expr(Pattern.java:1996)
        at java.util.regex.Pattern.compile(Pattern.java:1696)
        at java.util.regex.Pattern.<init>(Pattern.java:1351)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at java.util.regex.Pattern.matches(Pattern.java:1133)
        at java.lang.String.matches(String.java:2121)
        at org.openapitools.codegen.languages.PhpSlimServerCodegen.modelFileFolder(PhpSlimServerCodegen.java:103)
        at org.openapitools.codegen.DefaultGenerator.generateModel(DefaultGenerator.java:306)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:487)
        ... 3 more

```

##### Steps to reproduce
Just type and use your own yaml or json openapi file.
```
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli:v4.0.0-beta2 generate -i /local/openapi.json -g php-slim -o /local --invoker-package Websupport\\InvoiceValidation
```

Expected output should be all classes under namespace: `Websupport\InvoiceValidation`

**Comment by ackintosh** [comment]
@FilipBenco  Thanks for this issue!

cc Technical Committee: @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ybelenko (2018/07), @renepardon (2018/12)

**Comment by ackintosh** [comment]
@vdelau Thanks for providing the example which reproduce the issue. I'm working on this issue. 💨

**Comment by ackintosh** [comment]
@FilipBenco @vdelau https://github.com/OpenAPITools/openapi-generator/pull/2604 has been merged into master! Please give it a try with the latest docker image.
