### ISSUE TITLE
[BUG]  ERROR! Not handling <code> as Body Parameter at the moment

### ISSUE THREAD

**Issue by adamdecaf** [OpenAPITools/openapi-generator#2580]
##### Description

I get the following error when trying to generate a Go client:

```
[main] ERROR o.o.codegen.DefaultCodegen - ERROR! Not handling  class Parameter {
    name: null
    in: null
    description: null
    required: null
    deprecated: null
    allowEmptyValue: null
    style: null
    explode: null
    allowReserved: null
    schema: null
    examples: null
    example: null
    content: null
    $ref: #/components/parameters/idempotencyKey
} as Body Parameter at the moment
```

This comes about when my `root.yaml` file contains a `paths` sub-object with a `$ref` to an external OpenAPI spec file for a path like:

```yaml
paths:
  /originators:
    post:
      tags:
        - Originators
      summary: Create a new Originator object
      operationId: addOriginator
      security:
        - bearerAuth: []
        - cookieAuth: []
      parameters:
        - $ref: '#/components/parameters/requestId'
        - $ref: '#/components/parameters/idempotencyKey'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOriginator'        

  parameters:
    idempotencyKey:
      in: header
      name: X-Idempotency-Key
      description: Idempotent key in the header which expires after 24 hours. These strings should contain enough entropy for to not collide with each other in your requests.
      example: a4f88150
      required: false
      schema:
        type: string
```

##### openapi-generator version

4.0.0-beta2

##### Steps to reproduce

```
OPENAPI_GENERATOR_VERSION=4.0.0-beta2 ./openapi-generator generate -i openapi.yaml -g go -o ./client
```

##### Suggest a fix

Looking at the [relevant source code](https://github.com/OpenAPITools/openapi-generator/blob/69ad9a9957fc0dca9dbd792cb9a6a3b6f5bf197c/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L2987) this path is simply commented out (and has been for quite some time), so I assume there's a refactor needed?

I'm willing to offer a patch which fixes this, but I'm unsure of the history or what all would need to be refactored. Any advice? I'll contribute a reproducible local test as part of the PR.

**Comment by wing328** [comment]
Thanks for reporting the issue and offering help to fix it.

Can you share the full spec via gist.github.com so that we can more easily reproduce the issue?

**Comment by adamdecaf** [comment]
Sure thing, here's the yaml files and output.

**issue-2580.yaml**:
```yaml
openapi: 3.0.2
info:
  version: v1
  title: Test API

tags:
  - name: Test
    description: TODO

paths:
  /v1/foo:
    $ref: './issue-2580-part2.yaml#/paths/~1foo'
```

**issue-2580-part2.yaml**:

```yaml
openapi: 3.0.2
info:
  version: v1
  title: Test API

tags:
  - name: Test
    description: TODO

paths:
  /foo:
    post:
      tags:
        - Test
      summary: Random endpoint
      operationId: foo
      parameters:
        - $ref: '#/components/parameters/XUserIdHeader'
      responses:
        '200':
          description: Service is running properly

components:
  parameters:
    XUserIdHeader:
      in: header
      name: X-User-Id
      description: Moov User ID header, required in all requests
      example: e3cdf999
      schema:
        type: string
      required: true
```

**Output:**
```
$ make 
OPENAPI_GENERATOR_VERSION=4.0.0-beta3 ./openapi-generator generate -i issue-2580.yaml -g go -o ./client
[main] WARN  o.o.c.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.c.languages.AbstractGoCodegen - Environment variable GO_POST_PROCESS_FILE not defined so Go code may not be properly formatted. To define it, try `export GO_POST_PROCESS_FILE="/usr/local/bin/gofmt -w"` (Linux/Mac)
[main] INFO  o.o.c.languages.AbstractGoCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] WARN  o.o.codegen.utils.URLPathUtils - 'host' (OAS 2.0) or 'servers' (OAS 3.0) not defined in the spec. Default to [http://localhost] for server URL [http://localhost/]
[main] WARN  o.o.codegen.utils.URLPathUtils - 'host' (OAS 2.0) or 'servers' (OAS 3.0) not defined in the spec. Default to [http://localhost] for server URL [http://localhost/]
[main] ERROR o.o.codegen.DefaultCodegen - ERROR! Not handling  class Parameter {
    name: null
    in: null
    description: null
    required: null
    deprecated: null
    allowEmptyValue: null
    style: null
    explode: null
    allowReserved: null
    schema: null
    examples: null
    example: null
    content: null
    $ref: #/components/parameters/XUserIdHeader
} as Body Parameter at the moment
[main] ERROR o.o.codegen.DefaultCodegen - ERROR! Not handling  class Parameter {
    name: null
    in: null
    description: null
    required: null
    deprecated: null
    allowEmptyValue: null
    style: null
    explode: null
    allowReserved: null
    schema: null
    examples: null
    example: null
    content: null
    $ref: #/components/parameters/XUserIdHeader
} as Body Parameter at the moment
[main] WARN  o.o.codegen.DefaultCodegen - Unknown parameter type: null
[main] WARN  o.o.codegen.DefaultCodegen - Parameter name not defined properly. Default to UNKNOWN_PARAMETER_NAME
[main] WARN  o.o.codegen.DefaultCodegen - Unknown parameter type null for null
Exception in thread "main" java.lang.RuntimeException: Could not generate api file for 'Test'
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:654)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:902)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:368)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:60)
Caused by: java.lang.NullPointerException
	at org.openapitools.codegen.languages.AbstractGoCodegen.postProcessOperationsWithModels(AbstractGoCodegen.java:402)
	at org.openapitools.codegen.DefaultGenerator.processOperations(DefaultGenerator.java:1116)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:540)
	... 3 more
make: *** [client] Error 1
```

**Comment by adamdecaf** [comment]
Is there any advice for how I should go about fixing this? I can try to work through the commented out code, but it seems pretty old. Thanks - cc @wing328

**Comment by adamdecaf** [comment]
If I move the `$ref` parameter inline with the spec everything generates fine. I'll do that to solve my build, but is there a way to let `$ref` work? 

```yaml
openapi: 3.0.2
info:
  version: v1
  title: Test API

servers:
  - url: https://api.moov.io
    description: Production server

tags:
  - name: Test
    description: TODO

paths:
  /v1/foo:
    $ref: './issue-2580-part2.yaml#/paths/~1foo'
```

```yaml
openapi: 3.0.2
info:
  version: v1
  title: Test API

tags:
  - name: Test
    description: TODO

paths:
  /foo:
    post:
      tags:
        - Test
      summary: Random endpoint
      operationId: foo
      parameters:
        - name: XUserIdHeader
          in: header
          name: X-User-Id
          description: Moov User ID header, required in all requests
          schema:
            type: string
            example: e3cdf999
          required: true
      responses:
        '200':
          description: Service is running properly
```

**Comment by agrizzli** [comment]
I had an error with same output like provided by adamdecaf and others, but only because of a typo in $ref path to parameter. I used only one file with components/parameters defined there in. So correct references get lost somewhere due to inclusion of other files, I guess. Maybe it helps some how.

**Comment by danielbartsch** [comment]
I have the same error with a much smaller `yaml`, and only within one file:

```
swagger: '2.0'
info:
  description: Description
  title: Title
paths:
  /:
    get:
      parameters:
        - $ref: '#/parameters/Language'
      responses:
        200:
          description: Description
          schema:
            type: file
parameters:
  Language:
    $ref: '#/definitions/LanguageEnum'
definitions:
  LanguageEnum:
    type: string
    enum:
      - de-DE
      - en-US
  Simple:
    type: object
    properties:
      language:
        $ref: '#/definitions/LanguageEnum'
```
running `validate` doesn't say anything bad (except unused models)
running `generate` then yields what's defined in the issue
(Twice for some reason)
```
[main] ERROR o.o.codegen.DefaultCodegen - ERROR! Not handling  class Parameter {
    name: null
    in: null
    description: null
    required: null
    deprecated: null
    allowEmptyValue: null
    style: null
    explode: null
    allowReserved: null
    schema: null
    examples: null
    example: null
    content: null
    $ref: #/definitions/LanguageEnum
} as Body Parameter at the moment
[main] ERROR o.o.codegen.DefaultCodegen - ERROR! Not handling  class Parameter {
    name: null
    in: null
    description: null
    required: null
    deprecated: null
    allowEmptyValue: null
    style: null
    explode: null
    allowReserved: null
    schema: null
    examples: null
    example: null
    content: null
    $ref: #/definitions/LanguageEnum
} as Body Parameter at the moment
```

**Comment by simPod** [comment]
I had the same issue and am running exactly the same command as @danielbartsch 

I validated my schema against https://editor.swagger.io/ and fixed errors it had shown (was missing `schema` for params in my case).

Fix those and you'll be fine.

`openapi-generator-cli validate` did not catch those.

**Comment by sankouski-dzmitry** [comment]
I faced similar issue when generating jira cloud api client. Generated code is broken, with `UNKNOWN_PARAM_NAME` instead of body. It's reproduced with `java` and `go` languages(maybe others too, but not tested). `swagger-codegen-cli` generates valid code.

Details:
- openapi generator version: 5.3.0
- [jira openapi spec file](https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json)
- generate command: `java -jar /opt/openapi/openapi-generator-cli-5.3.0.jar generate -i https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json --api-package com.atlassian.jira.rest.client.api --invoker-package com.atlassian.jira.rest.client.invoker --model-package com.atlassian.jira.rest.client.model --group-id com.atlassian.jira.rest --artifact-id jira-cloud-api -g go -o /tmp/jira_go`
- validate output:
```
Validating spec (https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json)
Warnings: 
        - Unused model: RichText
        - Unused model: AttachmentArchive
        - Unused model: PaginatedResponseComment
        - Unused model: IconBean

[info] Spec has 4 recommendation(s).```
- `grep -R UNKNOWN_PARAM_NAME /tmp/jira_go` output:
```
/tmp/jira_go/api_user_properties.go:    UNKNOWN_PARAM_NAME *
/tmp/jira_go/api_user_properties.go:func (r ApiSetUserPropertyRequest) UNKNOWN_PARAM_NAME(UNKNOWN_PARAM_NAME ) ApiSetUserPropertyRequest {
/tmp/jira_go/api_user_properties.go:    r.UNKNOWN_PARAM_NAME = &UNKNOWN_PARAM_NAME
/tmp/jira_go/api_user_properties.go:    if r.UNKNOWN_PARAM_NAME == nil {.........
```

**Comment by simllll** [comment]
Same for typescript-axios client.
```ts
editYoutubeId(companyId: string, UNKNOWN_PARAM_NAME: , options?: any): AxiosPromise<IAPICompany> {
            return localVarFp.editYoutubeId(companyId, UNKNOWN_PARAM_NAME, options).then((request) => request(axios, basePath));
        },
```

**Comment by equalspeterd** [comment]
FWIW, you can also reproduce this with the `openapi-yaml` generator. While the `go` label might be helpful, it really is an issue in the core default generator.

**Comment by Francoois** [comment]
> I had the same issue and am running exactly the same command as @danielbartsch
> 
> I validated my schema against https://editor.swagger.io/ and fixed errors it had shown (was missing `schema` for params in my case).
> 
> Fix those and you'll be fine.
> 
> `openapi-generator-cli validate` did not catch those.

Saved my day, thank you !

**Comment by ColeMurray** [comment]
Ran into the same error. In my case, I had invalid syntax in one of my objects

```
MyObject:
  type: object
  properties:
     val:
         type: string
         required: false
```

Where the required false is invalid syntax.

**Comment by rafael-as-martins** [comment]
How do we stand regarding this issue, is this a bug?

**Comment by miken32** [comment]
Just to confirm, this is still an issue...

**Comment by kino90** [comment]
Same problem, using `typescript-axios` generator

**Comment by vfouqueron** [comment]
I had the same issue, it is caused by $ref containing '{' character

I opened an issue on swagger-parser repository https://github.com/swagger-api/swagger-parser/issues/2033

**Comment by naviln** [comment]
> I had the same issue and am running exactly the same command as [@danielbartsch](https://github.com/danielbartsch)
> 
> I validated my schema against https://editor.swagger.io/ and fixed errors it had shown (was missing `schema` for params in my case).
> 
> Fix those and you'll be fine.
> 
> `openapi-generator-cli validate` did not catch those.

Couple years later and your comment helped me. Thanking you immensely. 👍😁

I'm using Nswag and just needed to know where and how to use schema:

```
    public class AddOptionalHeaderParameter : IOperationProcessor
    {
        public bool Process(OperationProcessorContext context)
        {
                context.OperationDescription.Operation.Parameters.Add(
                       new OpenApiParameter
                       {
                           Name = "Your Fantastic Header",
                           Description = "Description",
                           IsRequired = false,
                           Kind = OpenApiParameterKind.Header,
                           //Schema needs to be set like this!!!
                           Schema = new() { Type = NJsonSchema.JsonObjectType.String },
                       });
            }

            return true;
        }
    }
```
