### ISSUE TITLE
[BUG][All languages] NullPointerException on nested ComposedSchema

### ISSUE THREAD

**Issue by DonDi94** [OpenAPITools/openapi-generator#2610]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?

##### Description

I tried to generate code from a yaml with the latest commit of the generator, but I got the following exception:

*Exception in thread "main" java.lang.RuntimeException: Could not process model 'ComplexData'.Please make sure that your schema is correct!
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:458)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:899)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:368)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:60)
Caused by: java.lang.NullPointerException
	at org.openapitools.codegen.DefaultCodegen.addProperties(DefaultCodegen.java:1831)
	at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1737)
	at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1137)
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:453)
	... 3 more*

I tried to get into the source and it seems to be a problem with `ComposedSchema` handling. At line 1831 in `addProperties` the `allOf` is processed so that all of the properties defined in it are added to `required` and `properties` (lines 1852 and 1855). There is a check for the input variable `schema` to be an instance of `ComposedSchema`, but that is true for `oneOf`, `anyOf` and `allOf`, not just `allOf`. If we have a `allOf` all of its properties will be processed by the for loop recursively, if one of its properties is a `oneOf` it will be passed recursively to `addProperties`, the condition `schema instanceOf ComposedSchema` will be true and the procedure will continue to the for loop. As we are handling a `oneOf`, `schema.getAllOf()` will return `null` and create a NullPointerException.

##### openapi-generator version

4.0.0, commit b5ede4b
    
##### OpenAPI declaration file content or url

```yaml
openapi: '3.0.0'
info:
  version: 1.0.0
  title: ComplexTest
  description: A sample API that uses a complex schema
paths: 
  /test:    
    post:
      operationId: ComplexTest
      requestBody:
        content:
          'multipart/form-data+json':
            schema:
              $ref: '#/components/schemas/ComplexData'
      responses:
        default:
          $ref: '#/components/responses/DefaultResponse'
components:
  schemas:
    ComplexData:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
      allOf:
        - oneOf:
          - required: [ username ]
          - required: [ email ]
  responses:
    DefaultResponse:
      description: unexpected error
      content:       
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
```

##### Command line used for generation

`java -jar openapi-generator-cli.jar generate -i complexdata.yaml -g erlang-client -o client/`

`java -jar openapi-generator-cli.jar generate -i complexdata.yaml -g erlang-server -o client/`

##### Steps to reproduce

- Create a file `complexdata.yaml` with the given yaml specifications
- Generate the code in any language

##### Related issues/PRs

I haven't found related issues other than old `oneOf` issues.

**Comment by wing328** [comment]
```
  schemas:
    ComplexData:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
      allOf:
        - oneOf:
          - required: [ username ]
          - required: [ email ]
```

What does the payload look like?

I think we may be able to find a way to model the payload differently to workaround the issue.

**Comment by DonDi94** [comment]
I'm not sure whether I understand the question. By payload you mean the value that I would send to represent the schema `ComplexData`, right?

In that case, I haven't modeled this example from my own data. Instead, I found this issue while trying to generate code from the 3GPP 5G Core specifications. You can find this kind of nested composed schemas quite frequently, such as `ServiceAreaRestriction` in `TS29571_CommonData.yaml`. (http://www.3gpp.org/ftp/Specs/archive/29_series/29.571/)

```yaml
ServiceAreaRestriction:
  type: object
  properties:
	restrictionType:
	  $ref: '#/components/schemas/RestrictionType'
	areas:
	  type: array
	  items:
		$ref: '#/components/schemas/Area'
	maxNumOfTAs:
	  $ref: '#/components/schemas/Uinteger'
  allOf:
	- oneOf:
		- not:
			required:
			  - restrictionType
		- required:
			- areas
	- anyOf:
		- not:
			required:
			  - restrictionType
			properties:
			  restrictionType:
				type: string
				enum:
				  - NOT_ALLOWED_AREAS
		- not:
			required:
			  - maxNumOfTAs
```

As I was more interested into the parsed JSON rather than the mustache-ready processed value, I simply added a guard for the "getAllOf" and removed the exceptions. That was enough for what I was interested in doing (I am generating for erlang-server), but that limits the generation for erlang-client and probably all the other languages that would create models/data structures with it.

**Comment by shameerkc** [comment]
Thanks for opening this. I am also facing similar issues, especially while working with the 5G Core API's hosted at [https://github.com/jdegre/5GC_APIs](https://github.com/jdegre/5GC_APIs).

Tried multiple options including generating from [https://editor.swagger.io/](https://editor.swagger.io/)

`Exception in thread "Thread-1" java.lang.RuntimeException: Could not process model 'PatchOperation'.Please make sure that your schema is correct!
        at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:378)
        at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:756)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:342)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at io.swagger.codegen.v3.generators.util.OpenAPIUtil.getSimpleRef(OpenAPIUtil.java:32)
        at io.swagger.codegen.v3.generators.SchemaHandler.configureAnyOfModel(SchemaHandler.java:75)
        at io.swagger.codegen.v3.generators.DefaultCodegenConfig.fromModel(DefaultCodegenConfig.java:1374)
        at io.swagger.codegen.v3.generators.java.AbstractJavaCodegen.fromModel(AbstractJavaCodegen.java:895)
        at io.swagger.codegen.v3.DefaultGenerator.processModels(DefaultGenerator.java:988)
        at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:349)`

**Comment by amitinfo2k** [comment]
I am also facing the same  issue  with latest  https://github.com/jdegre/5GC_APIs.

`[main] INFO  o.o.c.l.CppPistacheServerCodegen - Using get/set-based model template
Exception in thread "main" java.lang.RuntimeException: Could not process model 'ServiceAreaRestriction'.Please make sure that your schema is correct!
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:472)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:923)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:416)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:60)
Caused by: java.lang.NullPointerException
        at org.openapitools.codegen.DefaultCodegen.addProperties(DefaultCodegen.java:2001)
        at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1888)
        at org.openapitools.codegen.languages.CppPistacheServerCodegen.fromModel(CppPistacheServerCodegen.java:183)
        at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1200)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:467)
        ... 3 more
`

**Comment by Bessonov** [comment]
Labels with Erlang are not correct, but title.

Run in the same issue with TypeScript. Use Case: Definition of some sort of MongoDB Query, which contains `$and` and `$or`.

**Comment by MiguelAraCo** [comment]
Getting the same error while trying to generate an HTML representation of the API.

**Comment by jpestima** [comment]
Same error as @DonDi94.

**Comment by eachirei** [comment]
Same error for typescript-angular

**Comment by simllll** [comment]
typescript-axios also affected, guess this is a general problem.

**Comment by doctau** [comment]
I can reproduce this, with a pretty simple example as below. I believe I'm doing the inheritance correctly (although the docs are quite unclear around some parts), but even if I'm not it probably shouldn't fail with an NPE.

`
openapi: 3.0.0
info:
  version: 1.0.0
  title: reproducer

paths:
  /foo:
    get:
      responses:
        '500':
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralError'

components:
  schemas:
    GeneralError:
      anyOf:
        - $ref: '#/components/schemas/SpecificError'
      discriminator:
        propertyName: code
        mapping:
          SPECIFIC_ERROR: '#/components/schemas/SpecificError'

    SpecificError:
      allOf:
        - $ref: '#/components/schemas/GeneralError'
        - type: object
          properties:
            detail:
              type: string
          required:
            - detail
`

**Comment by doctau** [comment]
If you don't have anyOf/oneOf in General error then it does not fail during generation, but nothing is generated for SpecificError (unless there is another reference to it).
