### ISSUE TITLE
openapi-generator-cli: generate java client api throws NPE

### ISSUE THREAD

**Issue by kireyzambon** [OpenAPITools/openapi-generator#2625]
Hi,

the following command:
`docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json -g java -o /local/out/java
`
throws NullPointerException.

i'm using:
`
openapitools/openapi-generator-cli   latest              928ae4e66974
`

Please can you help me? Thanks a lot

`
[main] INFO  o.o.c.languages.AbstractJavaCodegen - Processing operation com.atlassian.jira.rest.v2.issue.worklog.WorklogResource.getIdsOfWorklogsModifiedSince_get
Exception in thread "main" java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
        at java.util.regex.Matcher.reset(Matcher.java:309)
        at java.util.regex.Matcher.<init>(Matcher.java:229)
        at java.util.regex.Pattern.matcher(Pattern.java:1093)
        at org.openapitools.codegen.utils.URLPathUtils.getServerURL(URLPathUtils.java:59)
        at org.openapitools.codegen.utils.URLPathUtils.getServerURL(URLPathUtils.java:49)
        at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:199)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:891)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:368)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:60)
`

**Comment by kireyzambon** [comment]
thanks:)  i have generated stubs with docker.

I had to fix some compilation error:
> To install the API client library to your local Maven repository, simply execute:

```shell
mvn clean install
```

`ERROR] /C:/project/tmp/out/java/src/main/java/org/openapitools/client/api/ProjectPermissionSchemesApi.java:[39,8] class ProjectpermissionschemesApi is public, should be declared in a file named ProjectpermissionschemesApi.java
`

and then i started to use jar client.
