### ISSUE TITLE
[BUG][CSHARP][PHP] Could not process model 'Dog.Type'

### ISSUE THREAD

**Issue by amiller-ims** [OpenAPITools/openapi-generator#3124]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When types with an `allOf` definition have names with ".Type" or ".Any" suffix, there is an error at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:470)

Actual Output
```
[main] ERROR o.o.codegen.utils.ModelUtils - Failed to obtain schema from null
[main] ERROR o.o.codegen.utils.ModelUtils - Failed to obtain schema from null
Exception in thread "main" java.lang.RuntimeException: Could not process model 'Dog.Any'.Please make sure that your schema is correct!
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:470)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:919)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:396)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:60)
Caused by: java.lang.NullPointerException
        at org.openapitools.codegen.languages.AbstractPhpCodegen.toModelName(AbstractPhpCodegen.java:402)
        at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1755)
        at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1196)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:465)
        ... 3 more
```
Expected Output
- No errors

##### openapi-generator version

4.0.2-SNAPSHOT

##### OpenAPI declaration file content or url

https://gist.github.com/amiller-ims/21f6a4ec6acbb408774f629cdaf8b42c

##### Command line used for generation

Both of these command lines cause similar errors:

- java -jar openapi-generator-cli.jar generate -g php -i petstore.yaml
- java -jar openapi-generator-cli.jar generate -g csharp -i petstore.yaml

##### Steps to reproduce

1. Add ".Type" or ".Any" to the types with `allOf` definitions (maybe any suffix with a period "."). For example, rename "Pet" to "Pet.Type":
```
definitions:
  Dog.Type:
    allOf:
      - $ref: '#/definitions/Pet.Type'
      - type: object
        properties:
          breed:
            type: string
```
##### Related issues/PRs

I searched both Issues and PRs but could not find this problem.

##### Suggest a fix

I think the period (".") is causing the problem. These names did not cause a problem in 4.0.0-beta3. If I discover a fix, I'll update this issue.

**Comment by amiller-ims** [comment]
Using `-D debugOpenAPI` option I see that the model generator is leaving off the schema path.

Actual:
```
      "Dog.Type" : {
        "allOf" : [ {
          "$ref" : "#/components/schemas/Pet.Type"
        }, {
          "$ref" : "Dog.Type_allOf"
        } ]
      },
```

Expected
```
      "Dog.Type" : {
        "allOf" : [ {
          "$ref" : "#/components/schemas/Pet.Type"
        }, {
          "$ref" : "#/components/schemas/Dog.Type_allOf"
        } ]
      },
```

**Comment by amiller-ims** [comment]
If I replace the period (".") with an underscore ("_"), there are no errors. For example,
```
definitions:
  Dog_Type:
    allOf:
      - $ref: '#/definitions/Pet_Type'
      - type: object
        properties:
          breed:
            type: string
  Cat_Type:
    allOf:
      - $ref: '#/definitions/Pet_Type'
      - type: object
        properties:
          declawed:
            type: boolean
  Pet_Type:
    type: object
    discriminator: className
    required:
      - className
    properties:
      className:
        type: string
      color:
        type: string
        default: 'red'
```

**Comment by wing328** [comment]
@amiller-ims thanks for reporting the issue. Do you mind filing an issue with the suggested fix? Let us know if you need help with the PR.
