### ISSUE TITLE
[BUG] Javascript fails when anyOf is used

### ISSUE THREAD

**Issue by tpurcell90** [OpenAPITools/openapi-generator#3144]
#### Bug Report Checklist

- [ x] Have you provided a full/minimal spec to reproduce the issue?
- [ x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ x] What's the version of OpenAPI Generator used?
- [ x] Have you search for related issues/PRs?
- [ x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
For the javascript  API-Client for version 4.0.1 anyOf options give in correct results.

Using the following [openapi.json.gz](https://github.com/OpenAPITools/openapi-generator/files/3281170/openapi.json.gz) you get the following output:
```
Error: Cannot find module './AnyOffloatarray'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/purcell/git/optimade-python-tools/javascript_client_generator/any_of_min_test/any_of/dist/model/TesterResponse.js:24:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
However by removing the anyOf portion of the file like [openapi_no_anyof.json.gz](https://github.com/OpenAPITools/openapi-generator/files/3281171/openapi_no_anyof.json.gz) it runs as expected.

This means that anyOf can not be used.

##### openapi-generator version

4.0.1

##### OpenAPI declaration file content or url

<!-- if it is a bug, a json or yaml that produces it.
If you post the code inline, please wrap it with

Incorrect json
[openapi.json.gz](https://github.com/OpenAPITools/openapi-generator/files/3281170/openapi.json.gz)

Correct json
[openapi_noanyof.json.gz](https://github.com/OpenAPITools/openapi-generator/files/3281171/openapi_no_anyof.json.gz) it runs as expected.

Test script from README
[test_from_readme.js.gz](https://github.com/OpenAPITools/openapi-generator/files/3281199/test_from_readme.js.gz)

##### Command line used for generation
```shell
 openapi-generator generate -i openapi.json -g javascript -o any_of
cd any_of/
npm install
npm link
npm run build
cd ../
node test_from_readme.js
```
##### Steps to reproduce
See above

##### Related issues/PRs
Similar to #2845 

##### Suggest a fix

Likely a bug with how the importing is handled

**Comment by sviatoslavRSV** [comment]
@tpurcell90  simply override method in CodegenConfig.java to get preferable type 
```@Override
    public String toAnyOfName(List<String> names, ComposedSchema composedSchema) {
        return "Object";
    }
```

**Comment by jonasborn** [comment]
Is there any progress? I'm currently in need of oneOf and anyOf and also focusing the issue unsing version 4.3.1.

**Comment by ktunkiewicz** [comment]
A bit old issue, but I found it on google, so other people may find this anwer useful.

Simples way to get around this problem is to make sure that every time `anyOf`, `allOf` or 'oneOf` is used, it has to be the done in a separate **named schema**.

This results in the error:

```json
"TestSchema": {
  "type": "object",
  "properties": {
    "foo": {
      "anyOf": [
        { "type": "string" },
        { "type": "number" },
      ]
    },
    "bar": {
      "anyOf": [
        { "type": "string" },
        { "type": "number" },
      ]
    }
  }
}
```

But it works all fine if you name your schemas, so the generator doesn't have to invent the names on its own, and the problem disappears:

```json
"FooSchema": {
  "anyOf": [
    { "type": "string" },
    { "type": "number" },
  ]
},
"BarSchema": {
  "anyOf": [
    { "type": "number" },
    { "type": "bool" },
  ]
},
"TestSchema": {
  "type": "object",
  "properties": {
    "foo": {
      "$ref": "#/FooSchema"
    },
    "bar": {
      "$ref": "#/BarSchema"
    }
  }
}
```

I hope this helps someone :)

**Comment by SBeyeMHP** [comment]
@ktunkiewicz 

> I hope this helps someone :)

It did 🙏
