### ISSUE TITLE
Unable to generate java client code from a version 2 OpenApi spec

### ISSUE THREAD

**Issue by jeff9finger** [OpenAPITools/openapi-generator#320]
##### Description

I am trying to generate a java client from an Open API version 2 spec. But the generator does not validate the spec.

##### openapi-generator version
3.0.1, 3.0.2-SNAPSHOT

##### OpenAPI declaration file content or url
```
swagger: "2.0"
info:
  version: "2"
  title: "TRACT Billing API"
basePath: "/billing/2"
consumes:
- "application/json"
produces:
- "application/json"
security:
- api_key_header: []
- defined_bearer_token: []
paths:
  /actions:
    get:
      tags:
      - "Action"
      summary: "Get actions"
      operationId: "queryActions"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "query"
        description: "The internal ID of the object."
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Action"
          headers:
            ETag:
              type: "string"
              description: "The standard ETag HTTP header."
            X-total-count:
              type: "integer"
              format: "int64"
              description: "The total results for the particular query. Used to drive\
                \ paging requests."
            X-element-count:
              type: "integer"
              format: "int64"
              description: "The number of elements returned in the current request.\
                \ Used to drive paging requests."
            X-total-pages:
              type: "integer"
              format: "int64"
              description: "The total number of pages that can be requested. Used\
                \ to drive paging requests."
        400:
          description: "Bad request."
          schema:
            $ref: "#/definitions/ApiError"
        default:
          description: "Unknown error."
          schema:
            $ref: "#/definitions/ApiError"
      security:
      - api_key_header: []
      - defined_bearer_token: []
      x-swagger-router-controller: "ActionsController"
definitions:
  Entity:
    type: "object"
    properties:
      id:
        type: "string"
        example: "1438752"
        description: "(unique_key) The ID of the entity."
        readOnly: true
    title: "Entity"
    description: "A base object for all API entities."
  Action:
    title: "Action"
    allOf:
    - $ref: "#/definitions/Entity"
    - type: "object"
      required:
      - "action_type"
      discriminator: "action_type"
      properties:
        name:
          type: "string"
          description: "The name of the action."
          readOnly: true
        enabled:
          type: "boolean"
          description: "Specifies whether the action is enabled."
          readOnly: true
        friendly_name:
          type: "string"
          description: "The optional additional name of the action."
          readOnly: true
        supports_approval:
          type: "boolean"
          description: "Specifies whether the action supports approval."
          readOnly: true
        action_type:
          $ref: "#/definitions/ActionType"
  ActionType:
    type: "string"
    title: "ActionType"
    description: "Indicates the type of action that occurs."
    enum:
    - "agreement"
    - "agreement-service"
    - "bill-cycle-run"
    - "bill-batch-run"
    - "billing-account"
    - "counter"
    - "credit-adjustment"
    - "disbursement"
    - "invoice"
    - "payment"
    - "product-sale"
    - "remote-prepaid-register"
    - "sales-order"
    - "service"
    - "service-cfv"
    - "system-notification"
    - "usage-rule"
    x-swagger-router-model: "ActionTypeDto"
```

##### Steps to reproduce

```
java -jar openapi-generator-cli.jar generate --generator-name java --library jersey2 --input-spec test

.yaml --output src --verbose
```

Output:
```
[main] INFO  o.o.c.config.CodegenConfigurator -
VERBOSE MODE: ON. Additional debug options are injected
 - [debugSwagger] prints the openapi specification as interpreted by the codegen
 - [debugModels] prints models passed to the template engine
 - [debugOperations] prints operations passed to the template engine
 - [debugSupportingFiles] prints additional data passed to the template engine
Exception in thread "main" java.lang.IllegalArgumentException: Cannot construct instance of `io.swagger.v3.oas.models.media.Discriminator` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('action_type')
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.swagger.v3.oas.models.media.ObjectSchema["discriminator"]) (through reference chain: io.swagger.v3.oas.models.media.ComposedSchema["allOf"]->java.util.ArrayList[1])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3738)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3656)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:1062)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:215)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:93)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:19)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:516)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:314)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:58)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Cannot construct instance of `io.swagger.v3.oas.models.media.Discriminator` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('action_type')
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.swagger.v3.oas.models.media.ObjectSchema["discriminator"]) (through reference chain: io.swagger.v3.oas.models.media.ComposedSchema["allOf"]->java.util.ArrayList[1])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:363)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:302)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3733)
	... 8 more
Caused by: java.lang.IllegalArgumentException: Cannot construct instance of `io.swagger.v3.oas.models.media.Discriminator` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('action_type')
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.swagger.v3.oas.models.media.ObjectSchema["discriminator"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3738)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3656)
	at io.swagger.v3.core.util.ModelDeserializer.deserializeObjectSchema(ModelDeserializer.java:106)
	at io.swagger.v3.core.util.ModelDeserializer.deserialize(ModelDeserializer.java:76)
	at io.swagger.v3.core.util.ModelDeserializer.deserialize(ModelDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	... 14 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `io.swagger.v3.oas.models.media.Discriminator` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('action_type')
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.swagger.v3.oas.models.media.ObjectSchema["discriminator"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1031)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1366)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:171)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3733)
	... 19 more
```

**Comment by jmini** [comment]
Are you sure your spec is valid? I get following errors on http://editor.swagger.io/

```
Semantic error at security.0
Security requirements must match a security definition
Jump to line 11
Semantic error at security.1
Security requirements must match a security definition
Jump to line 12
Semantic error at paths./actions.get.responses.400.schema.$ref
$refs must reference a valid location in the document
Jump to line 57
Semantic error at paths./actions.get.responses.default.schema.$ref
$refs must reference a valid location in the document
Jump to line 61
Semantic error at paths./actions.get.security.0
Security requirements must match a security definition
Jump to line 63
Semantic error at paths./actions.get.security.1
Security requirements must match a security definition
Jump to line 64
```

**Comment by jeff9finger** [comment]
When I execute this in swagger-codegen, it works.
```
$ swagger-codegen generate --lang java --library jersey2 --input-spec test.yaml --output src
[main] INFO io.swagger.parser.Swagger20Parser - reading from test.yaml
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting pom.xml as the file already exists in /Users/jeff/tmp/openapi/src//pom.xml
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting README.md as the file already exists in /Users/jeff/tmp/openapi/src//README.md
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting build.gradle as the file already exists in /Users/jeff/tmp/openapi/src//build.gradle
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting build.sbt as the file already exists in /Users/jeff/tmp/openapi/src//build.sbt
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting settings.gradle as the file already exists in /Users/jeff/tmp/openapi/src//settings.gradle
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting gradle.properties as the file already exists in /Users/jeff/tmp/openapi/src//gradle.properties
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting AndroidManifest.xml as the file already exists in /Users/jeff/tmp/openapi/src/src/main/AndroidManifest.xml
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/model/ActionType.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/docs/ActionType.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/model/Entity.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/docs/Entity.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/model/Action.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/docs/Action.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/api/ActionApi.java
[main] INFO io.swagger.codegen.DefaultGenerator - File exists. Skipped overwriting /Users/jeff/tmp/openapi/src/src/test/java/io/swagger/client/api/ActionApiTest.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/docs/ActionApi.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/.travis.yml
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/ApiClient.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/StringUtil.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/auth/HttpBasicAuth.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/auth/OAuth.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/auth/OAuthFlow.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/gradlew
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/gradlew.bat
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/gradle/wrapper/gradle-wrapper.properties
[main] INFO io.swagger.codegen.DefaultGenerator - writing file /Users/jeff/tmp/openapi/src/gradle/wrapper/gradle-wrapper.jar
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/git_push.sh
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/.gitignore
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/ApiException.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/Configuration.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/Pair.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/auth/Authentication.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/JSON.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/RFC3339DateFormat.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/src/main/java/io/swagger/client/CustomInstantDeserializer.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/jeff/tmp/openapi/src/.swagger-codegen/VERSION
```

**Comment by jeff9finger** [comment]
Also
```
$ swagger-codegen validate -i test.yaml
Validating spec file (test.yaml)
```

**Comment by jeff9finger** [comment]
I removed the errors displayed in http://editor.swagger.io/ (though this is a snippet from our current spec that we have in production, so I don't know why these show as errors). Here is the updated spec file. It still has the issues reported. Seems to be around the discriminator.
```
swagger: "2.0"
info:
  version: "2"
  title: "TRACT Billing API"
basePath: "/billing/2"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /actions:
    get:
      tags:
      - "Action"
      summary: "Get actions"
      operationId: "queryActions"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "query"
        description: "The internal ID of the object."
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Action"
          headers:
            ETag:
              type: "string"
              description: "The standard ETag HTTP header."
            X-total-count:
              type: "integer"
              format: "int64"
              description: "The total results for the particular query. Used to drive\
                \ paging requests."
            X-element-count:
              type: "integer"
              format: "int64"
              description: "The number of elements returned in the current request.\
                \ Used to drive paging requests."
            X-total-pages:
              type: "integer"
              format: "int64"
              description: "The total number of pages that can be requested. Used\
                \ to drive paging requests."
        400:
          description: "Bad request."
        default:
          description: "Unknown error."
      x-swagger-router-controller: "ActionsController"
definitions:
  Entity:
    type: "object"
    properties:
      id:
        type: "string"
        example: "1438752"
        description: "(unique_key) The ID of the entity."
        readOnly: true
    title: "Entity"
    description: "A base object for all API entities."
  Action:
    title: "Action"
    allOf:
    - $ref: "#/definitions/Entity"
    - type: "object"
      required:
      - "action_type"
      discriminator: "action_type"
      properties:
        name:
          type: "string"
          description: "The name of the action."
          readOnly: true
        enabled:
          type: "boolean"
          description: "Specifies whether the action is enabled."
          readOnly: true
        friendly_name:
          type: "string"
          description: "The optional additional name of the action."
          readOnly: true
        supports_approval:
          type: "boolean"
          description: "Specifies whether the action supports approval."
          readOnly: true
        action_type:
          $ref: "#/definitions/ActionType"
  ActionType:
    type: "string"
    title: "ActionType"
    description: "Indicates the type of action that occurs."
    enum:
    - "agreement"
    - "agreement-service"
    - "bill-cycle-run"
    - "bill-batch-run"
    - "billing-account"
    - "counter"
    - "credit-adjustment"
    - "disbursement"
    - "invoice"
    - "payment"
    - "product-sale"
    - "remote-prepaid-register"
    - "sales-order"
    - "service"
    - "service-cfv"
    - "system-notification"
    - "usage-rule"
    x-swagger-router-model: "ActionTypeDto"
```

**Comment by jmini** [comment]
I have filed https://github.com/swagger-api/swagger-parser/issues/740 maybe you can add a comment there to explain that it was working with a previous version of `swagger-parser` (used in your version of swagger-codegen).

**Comment by jeff9finger** [comment]
@jmini  Thank you

**Comment by jmini** [comment]
I have opened https://github.com/swagger-api/swagger-parser/issues/780 to ask the Swagger-Parser team for the next release. Feel free to let a comment on this issue.

I hope that we will have a new version of Swagger-Parser with our next `3.2.0` release of OpenAPI-Generator.

**Comment by jmini** [comment]
The issue in Swagger-Parser was fixed, and with PR #696 OpenAPI-Generator was updated to use a version containing the fix. 

This issue reported here, should no longer appear with the newest `3.2.0-SNAPSHOT` version.
@bmordue, @andreevlex, can you check it?

**Comment by jeff9finger** [comment]
Will check this out today.

**Comment by jeff9finger** [comment]
When I execute the same command with the same yaml file, it does seem to execute correctly. Note: This is  without --verbose

```
java -jar openapi-generator-cli.jar generate --generator-name java --library jersey2 --input-spec test.yaml --output src
[main] WARN  o.o.c.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] WARN  o.o.codegen.utils.URLPathUtils - 'host' not defined in the spec (2.0). Default to [http://localhost] for server URL [http://localhost/billing/2]
[main] WARN  o.o.codegen.utils.URLPathUtils - 'host' not defined in the spec (2.0). Default to [http://localhost] for server URL [http://localhost/billing/2]
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/model/Action.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/docs/Action.md
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/model/ActionType.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/docs/ActionType.md
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/model/Entity.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/docs/Entity.md
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/api/ActionApi.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/test/java/org/openapitools/client/api/ActionApiTest.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/docs/ActionApi.md
[main] WARN  o.o.codegen.utils.URLPathUtils - 'host' not defined in the spec (2.0). Default to [http://localhost] for server URL [http://localhost/billing/2]
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/pom.xml
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/README.md
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/build.gradle
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/build.sbt
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/settings.gradle
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/gradle.properties
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/AndroidManifest.xml
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/.travis.yml
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/ApiClient.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/StringUtil.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/auth/HttpBasicAuth.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/auth/ApiKeyAuth.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/auth/OAuth.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/auth/OAuthFlow.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/gradlew
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/gradlew.bat
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/gradle/wrapper/gradle-wrapper.properties
[main] INFO  o.o.codegen.DefaultGenerator - writing file /Users/jeff/tmp/src/gradle/wrapper/gradle-wrapper.jar
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/git_push.sh
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/.gitignore
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/ApiException.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/Configuration.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/Pair.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/auth/Authentication.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/JSON.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/ApiResponse.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/RFC3339DateFormat.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/CustomInstantDeserializer.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/.openapi-generator-ignore
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/.openapi-generator/VERSION
```

However, when I execute the same command with "--verbose", there seem to be some issues that still need to be resolved, though probably not related to the swagger-parser issue.
```
[main] INFO  o.o.c.config.CodegenConfigurator -
VERBOSE MODE: ON. Additional debug options are injected
 - [debugSwagger] prints the openapi specification as interpreted by the codegen
 - [debugModels] prints models passed to the template engine
 - [debugOperations] prints operations passed to the template engine
 - [debugSupportingFiles] prints additional data passed to the template engine
[main] INFO  o.o.codegen.DefaultGenerator - Please use system property 'debugOpenAPI' instead of 'debugSwagger'.
< open-api spec snipped>
[main] INFO  o.o.codegen.DefaultCodegen - Skipped overwriting pom.xml as the file already exists in /Users/jeff/tmp/src//pom.xml
[main] INFO  o.o.codegen.DefaultCodegen - Skipped overwriting README.md as the file already exists in /Users/jeff/tmp/src//README.md
[main] INFO  o.o.codegen.DefaultCodegen - Skipped overwriting build.gradle as the file already exists in /Users/jeff/tmp/src//build.gradle
[main] INFO  o.o.codegen.DefaultCodegen - Skipped overwriting build.sbt as the file already exists in /Users/jeff/tmp/src//build.sbt
[main] INFO  o.o.codegen.DefaultCodegen - Skipped overwriting settings.gradle as the file already exists in /Users/jeff/tmp/src//settings.gradle
[main] INFO  o.o.codegen.DefaultCodegen - Skipped overwriting gradle.properties as the file already exists in /Users/jeff/tmp/src//gradle.properties
[main] INFO  o.o.codegen.DefaultCodegen - Skipped overwriting AndroidManifest.xml as the file already exists in /Users/jeff/tmp/src/src/main/AndroidManifest.xml
[main] WARN  o.o.codegen.utils.URLPathUtils - 'host' not defined in the spec (2.0). Default to [http://localhost] for server URL [http://localhost/billing/2]
[main] WARN  o.o.codegen.utils.URLPathUtils - 'host' not defined in the spec (2.0). Default to [http://localhost] for server URL [http://localhost/billing/2]
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/model/Action.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/docs/Action.md
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/model/ActionType.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/docs/ActionType.md
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/src/main/java/org/openapitools/client/model/Entity.j
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/jeff/tmp/src/docs/Entity.md
[main] INFO  o.o.codegen.DefaultGenerator - ############ Model info ############
com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: org.openapitools.codegen.CodegenModel["children"]->java.util.ArrayList[0]->org.openapitools.codegen.CodegenModel["parentModel"]->org.openapitools.codegen.CodegenModel["children"]->java.util.ArrayList[0]->org.openapitools.codegen.CodegenModel["parentModel"]->org.openapitools.codegen.CodegenModel["children"]->java.util.ArrayList[0]->org.openapitools.codegen.CodegenModel["parentModel"]->org.openapitools.codegen.CodegenModel["children"]->java.util.ArrayList[0]->org.openapitools.codegen.CodegenModel["parentModel"]->org.openapitools.codegen.CodegenModel["children"]->java.util.ArrayList[0]
...
<duplicate recursive errors messages snipped> 
>org.openapitools.codegen.CodegenModel["children"])
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:734)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
<snipped duplicate stack trace lines>
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
Caused by: java.lang.StackOverflowError
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:737)
        ... 1011 more

```

Are these errors an issue? Should we create a separate issue for this?

**Comment by wing328** [comment]
tested with latest v7.0.0 and no longer seeing exceptions generating code.
