### ISSUE TITLE
[BUG] [angular-typescript] angular 7 production build errors with Configuration provider

### ISSUE THREAD

**Issue by wrighting** [OpenAPITools/openapi-generator#3232]
#### Bug Report Checklist

- [ X] Have you provided a full/minimal spec to reproduce the issue?
- [ X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ X] What's the version of OpenAPI Generator used?
- [ X] Have you search for related issues/PRs?
- [ X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Unable to run a production build with angular cli when using injection to provide configuration
```
ng build -c production
```
results in
```
ERROR in : Error: Internal error: unknown identifier undefined
    at Object.importExpr$$1 [as importExpr] (./node_modules/@angular/compiler/bundles/compiler.umd.js:24170:27)
    at tokenExpr (./node_modules/@angular/compiler/bundles/compiler.umd.js:19863:43)
    at providerDef (./node_modules/@angular/compiler/bundles/compiler.umd.js:19789:24)

```
##### openapi-generator version

4.0.2
    "@angular/cli": "^7.3.9",
    "@angular/compiler-cli": "^7.2.15",

##### Command line used for generation

npx openapi-generator generate -g typescript-angular

##### Steps to reproduce

Using a provider for the configuration in order to supply a Bearer token as part of the client request.

This works for a non production build or when using ```ng serve```

```json
export function getConfiguration(authService: MyAuthService): Configuration {
  return authService.getConfiguration();
}

@NgModule({
  providers: [
    MyAuthService,
    {
      provide: Configuration,
      useFactory: getConfiguration,
      deps: [MyAuthService],
      multi: false
    }
  ]
```
##### Suggest a fix

Possibly use an InjectionToken for the Configuration in a similar way to that done for BASE_PATH

I did take a look in the generated README.md but couldn't see anything that helped with using an injected service as an arg to a function for getting the configuration.

**Comment by wrighting** [comment]
Changed the Configuration import and it will now compile

From:
```
import { Configuration } from './typescript-angular-client';
```

To:
```
import { Configuration } from './typescript-angular-client/configuration';
```
