### ISSUE TITLE
[BUG][Elm] Root operation causes StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Elewyth** [OpenAPITools/openapi-generator#3256]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Generating client code for Elm (0.19) from an openapi.yaml specification with a root operation `/` causes a StringIndexOutOfBoundsException:

```
Exception in thread "main" java.lang.RuntimeException: Could not generate api file for 'Default'
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:666)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:922)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:396)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:60)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at org.openapitools.codegen.languages.ElmClientCodegen.lambda$postProcessOperationsWithModels$3(ElmClientCodegen.java:449)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.openapitools.codegen.languages.ElmClientCodegen.postProcessOperationsWithModels(ElmClientCodegen.java:449)
	at org.openapitools.codegen.DefaultGenerator.processOperations(DefaultGenerator.java:1175)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:552)
	... 3 more
```

##### openapi-generator version

@openapitools/openapi-generator-cli@0.0.14-4.0.2 (installed via NPM)

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0

info:
  title: Elm Root Bug
  version: 1.0.0

paths:
  /:
    get:
      summary: Root endpoint that causes generator bug
      responses:
        204:
          description: No response body
```

##### Command line used for generation

```shell
npx openapi-generator generate -i bug.yaml -g elm -o output
```

##### Steps to reproduce

1. Save sample spec as `bug.yaml`
2. `npm install -g openapi-generator-cli`
3. `npx openapi-generator generate -i bug.yaml -g elm -o output`

##### Related issues/PRs

I could not find a related issue, as this seems to be a bug specific to the Elm generator implementation.

##### Suggest a fix

[ElmClientCodegen.java:449](https://github.com/OpenAPITools/openapi-generator/blob/v4.0.2/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java#L449) contains a lambda with `str.charAt(0)` which fails on operations with a path of `/`. This should probably have a fallback on something like `"root"` or even an empty string. The Haskell generator produces an empty string and an operation named `"rootGet"`.

**Comment by Elewyth** [comment]
I just noticed that the Haskell generator does not quite handle this properly, either. It generates a path, where the server will listen for `http://localhost//` instead of `http://localhost/`. Not sure if this is a bug in all/most generators.
