### ISSUE TITLE
[BUG] class NumberSchema cannot be cast to class ArraySchema

### ISSUE THREAD

**Issue by bytenik** [OpenAPITools/openapi-generator#3333]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
3.0.9
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
```
Exception in thread "Thread-1" java.lang.RuntimeException: Could not process model 'body_25'.Please make sure that your schema is correct!
        at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:378)
        at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:756)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:342)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at io.swagger.codegen.v3.generators.util.OpenAPIUtil.getSimpleRef(OpenAPIUtil.java:32)
        at io.swagger.codegen.v3.generators.SchemaHandler.createFromOneOfSchemas(SchemaHandler.java:131)
        at io.swagger.codegen.v3.generators.SchemaHandler.createCodegenModel(SchemaHandler.java:30)
        at io.swagger.codegen.v3.generators.DefaultCodegenConfig.fromProperty(DefaultCodegenConfig.java:1686)
        at io.swagger.codegen.v3.generators.DefaultCodegenConfig.addVars(DefaultCodegenConfig.java:3033)
        at io.swagger.codegen.v3.generators.DefaultCodegenConfig.addVars(DefaultCodegenConfig.java:3003)
        at io.swagger.codegen.v3.generators.DefaultCodegenConfig.addVars(DefaultCodegenConfig.java:2991)
        at io.swagger.codegen.v3.generators.DefaultCodegenConfig.fromModel(DefaultCodegenConfig.java:1402)
        at io.swagger.codegen.v3.generators.dotnet.CSharpClientCodegen.fromModel(CSharpClientCodegen.java:515)
        at io.swagger.codegen.v3.DefaultGenerator.processModels(DefaultGenerator.java:988)
        at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:349)
        ... 3 more
```
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When running the generator, I get an error that it cannot process a model instead of getting generated code. I've tried temporarily removing the offending model but more models then fail. Validators report that the file is valid other than various semantic issues like bodies on DELETE, but that seems unrelated to this issue.

##### openapi-generator version

I'm using 3.0.9

##### OpenAPI declaration file content or url

https://gist.github.com/bytenik/c533d96eeae399a31279bdf6b9ee4efd

##### Command line used for generation

`java -DdebugModels=true -DdebugOperations=true -jar swagger-codegen-cli-3.0.9.jar generate -i .\openapi.json -l csharp -o bitgo -v`

##### Steps to reproduce

Run the command line above.

**Comment by macjohnny** [comment]
please help us narrow down the problem by simplifying your spec as much as possible, i.e. remove all parts that are not absolutely necessary to reproduce the issue.

**Comment by bytenik** [comment]
I'm not entirely sure how to do that; its unfortunately not my spec. I'm
generating from a public API service.

**Comment by macjohnny** [comment]
just copy the spec into a file and remove part by part to see if the error still occurs

**Comment by jonstaff** [comment]
I'm able to reproduce this issue with the following spec:
```
openapi: 3.0.0
servers:
  - url: https://example.com
info:
  description: "This is an example"
  version: "0.1.0"
  title: "Example"
paths:
  /foo:
    get:
      summary: foobar
      operationId: foobar
      responses:
        '200':
          description: OK
components:
  schemas:
    Foo:
      type: object
      properties:
        id:
          type: string
          format: uuid
        bars:
          type: array
          items:
            $ref: '#/components/schemas/Bar'
    Bar:
      type: array
      items:
        type: number
        format: double
        minItems: 2
        maxItems: 2
```

Command:
```
$ openapi-generator generate -g dynamic-html -i example.yaml
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: dynamic-html (documentation)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'dynamic-html' is considered stable.
Exception in thread "main" java.lang.RuntimeException: Could not process model 'Foo'.Please make sure that your schema is correct!
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:470)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:920)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:396)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:60)
Caused by: java.lang.ClassCastException: class io.swagger.v3.oas.models.media.NumberSchema cannot be cast to class io.swagger.v3.oas.models.media.ArraySchema (io.swagger.v3.oas.models.media.NumberSchema and io.swagger.v3.oas.models.media.ArraySchema are in unnamed module of loader 'app')
	at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:2188)
	at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:2194)
	at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:2194)
	at org.openapitools.codegen.DefaultCodegen.addVars(DefaultCodegen.java:3627)
	at org.openapitools.codegen.DefaultCodegen.addVars(DefaultCodegen.java:3575)
	at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1845)
	at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1197)
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:465)
```
This passes validation just fine. It seems related to the `minItems` and `maxItems` properties, because when those are commented out, the command succeeds:
```
$ openapi-generator generate -g dynamic-html -i example.yaml
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: dynamic-html (documentation)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'dynamic-html' is considered stable.
[main] INFO  o.o.codegen.DefaultGenerator - Model Bar not generated since it's an alias to array (without property) and `generateAliasAsModel` is set to false (default)
```

**Comment by macjohnny** [comment]
the spec file is invalid.
you need to place the `minItems`/`maxItems` one level up, i.e. 
```yaml
    Bar:
      type: array
      minItems: 2
      maxItems: 2
      items:
        type: number
        format: double
```
because `minItems`/`maxItems` can only exist on `type: array` elements, but in your example they are part of the `type: number` item.

See 
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object
http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.4.3

**Comment by bytenik** [comment]
Sorry, this sample spec from @jonstaff is not representative of my issue. The spec I attached doesn't have minItems and maxItems.

**Comment by macjohnny** [comment]
@bytenik yes, that's why I reopened the issue. could you try to narrow down the problem with a simplified version of your spec?

**Comment by bytenik** [comment]
Yep, I'm trying to do that now. Its not trivial with so many things referencing each other.

**Comment by bytenik** [comment]
Is there a way to get better information on the failure than just `body_25` without renaming everything in the spec?

**Comment by bytenik** [comment]
Okay, looks like this simplified version still blows up with my original command:
```{
    "openapi": "3.0.0",
    "paths": {
        "/api/v2/{coin}/wallet/{walletId}/tx/build": {
            "post": {
              "tags": [
                "Wallet"
              ],
              "summary": "Build a transaction",
              "operationId": "v2.wallet.tx.build",
              "description": "Build a transaction from the wallet using provided options.\nInstead of this endpoint, you likely want to use [send transaction](https://bitgo.com/api/v2/#operation/express.wallet.sendcoins)\nin the SDK.\n",
              "requestBody": {
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object",
                      "properties": {
                        "recipients": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "amount": {
                                "description": "String representation of the amount to send",
                                "oneOf": [
                                  {
                                    "type": "string",
                                    "pattern": "^-?\\d+$",
                                    "example": "2000000"
                                  },
                                  {
                                    "type": "integer"
                                  }
                                ]
                              },
                              "address": {
                                "description": "The address to send to",
                                "type": "string",
                                "example": "2MvrwRYBAuRtPTiZ5MyKg42Ke55W3fZJfZS",
                                "maxLength": 250
                              }
                            }
                          },
                          "description": "A list of recipient addresses and amounts. Must be present but empty for CPFP transactions."
                        }
                      },
                      "required": [
                        "recipients"
                      ]
                    }
                  }
                }
              }
            }
          }    
    }
  }```

**Comment by macjohnny** [comment]
does the error still occur if you remove `amount` or `address`?

**Comment by bytenik** [comment]
Yes, removing `address` still generates the error.

**Comment by macjohnny** [comment]
and if you just remove `amount` the error does not occur anymore?

**Comment by bytenik** [comment]
Correct.

**Comment by macjohnny** [comment]
and if you remove `pattern: "^-?\\d+$"`?

**Comment by bytenik** [comment]
Looks like its the `oneOf`. Removing it and picking either of the two works, but, with it present everything blows up. Unfortunately this would be difficult to work around as the original spec has these all over.

**Comment by macjohnny** [comment]
hmm, I see. would you like to give it a try and fix the issue? the code line where the null-pointer exception occurs is a good starting point to investigate what is missing at that point

**Comment by bytenik** [comment]
It appears this works okay in 4.0.x.
