### ISSUE TITLE
[BUG][CLI][GENERATOR] NullPointer when not setting outputDir

### ISSUE THREAD

**Issue by Fjolnir-Dvorak** [OpenAPITools/openapi-generator#3439]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The openapi-generator-cli will throw a NullPointerException when the flag `o` is omitted.

##### openapi-generator version

master commit no.  2c4fdd0

##### OpenAPI declaration file content or url

Example Petstore is sufficient

##### Command line used for generation
```bash
openapi-generator generate \
    -g spring \
    --library spring-cloud \
    --additional-properties "java8=true" \
    --additional-properties "dateLibrary=java8" \
    --additional-properties "hideGenerationTimestamp=true" \
    --additional-properties "fullJavaUtil=true" \
    -i petstore-swagger-or-anything-else.json \
    --artifact-id demo \
    --api-package de.mo.demo.api \
    --model-package de.mo.demo.model
```

##### Steps to reproduce

The above statement will throw following NullPointer:
```
Exception in thread "main" java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)
        at org.openapitools.codegen.ignore.CodegenIgnoreProcessor.<init>(CodegenIgnoreProcessor.java:63)
        at org.openapitools.codegen.ignore.CodegenIgnoreProcessor.<init>(CodegenIgnoreProcessor.java:52)
        at org.openapitools.codegen.DefaultGenerator.opts(DefaultGenerator.java:96)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:399)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:60)
Exception in thread "main" java.lang.NullPointerException
```

This Nullpointer will vanish if you add the flag `o` to the command :

```bash
openapi-generator generate \
    -g spring \
    --library spring-cloud \
    --additional-properties "java8=true" \
    --additional-properties "dateLibrary=java8" \
    --additional-properties "hideGenerationTimestamp=true" \
    --additional-properties "fullJavaUtil=true" \
    -i petstore-swagger-or-anything-else.json \
    --artifact-id demo \
    --api-package de.mo.demo.api \
    --model-package de.mo.demo.model \
    -o ./
```

##### Related issues/PRs

Found nothing

##### Suggest a fix

I am looking into it and will hopefully provide a pull request shortly.

**Comment by jmini** [comment]
Isn't `-o` (or `--output`) a mandatory parameter on the CLI ?

What should be the default if omitted ? (I think a proper error indicating that the option is missing could also be ok)

**Comment by Fjolnir-Dvorak** [comment]
na, it is not required. The default is the current directory

**Comment by Locour** [comment]
I just downloaded version 4.1.0 as a npm package and i got the same error.

Using the cli command without `-o` parameter

````
openapi-generator generate -g typescript-angular -i swagger.json
````

results in the following error

````
Exception in thread "main" java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)
        at org.openapitools.codegen.ignore.CodegenIgnoreProcessor.<init>(CodegenIgnoreProcessor.java:63)
        at org.openapitools.codegen.ignore.CodegenIgnoreProcessor.<init>(CodegenIgnoreProcessor.java:52)
        at org.openapitools.codegen.DefaultGenerator.opts(DefaultGenerator.java:96)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:399)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:60)
````

Whereas when specifying the output parameter directly it works without any error:

````
 openapi-generator generate -g typescript-angular -i swagger.json -o .
````

**Comment by Fjolnir-Dvorak** [comment]
merged and working
