### ISSUE TITLE
[BUG][Python] UUID properties with default values trigger ClassCastException

### ISSUE THREAD

**Issue by alexras** [OpenAPITools/openapi-generator#3516]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

If I define a schema that has a UUID property, and that property has a default value, the Python code generator throws a `ClassCastException`.

##### openapi-generator version

4.0.3

##### OpenAPI declaration file content or url

```yaml
---
components:
  schemas:
    MyModel:
      properties:
        id:
          default: "00000000-0000-4000-8000-000000000000"
          format: uuid
          type: string
      title: MyModel
      type: object

info:
  title: 'My API'
  version: 0.1.0dev

openapi: 3.0.2

paths: {}
```

##### Command line used for generation

`docker run --rm -v ${PWD}:/local --env 'PYTHON_POST_PROCESS_FILE="/usr/local/bin/yapf -i"' openapitools/openapi-generator-cli:v4.0.3 generate -i /local/swagger.yml -g python -o /local/build`

##### Steps to reproduce

Run the generator with the above declaration file; it will throw an exception that looks like this:

```
Exception in thread "main" java.lang.RuntimeException: Could not process model 'MyModel'.Please make sure that your schema is correct!
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:470)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:920)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:396)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:60)
Caused by: java.lang.ClassCastException: java.util.UUID cannot be cast to java.lang.String
        at org.openapitools.codegen.languages.PythonClientCodegen.toDefaultValue(PythonClientCodegen.java:643)
        at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:1981)
        at org.openapitools.codegen.DefaultCodegen.addVars(DefaultCodegen.java:3627)
        at org.openapitools.codegen.DefaultCodegen.addVars(DefaultCodegen.java:3575)
        at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1845)
        at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1197)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:465)
        ... 3 more
```

If you remove the default and run the generator again, code generation will succeed.

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/2209 - similar exception, with a different cause.

##### Suggest a fix

Rather than just casting to a string, perhaps just calling `p.getDefault().toString()` would work.

**Comment by Briggybros** [comment]
This is not specific to the python generator. I'm seeing the same problem in java, typescript-fetch, and typescript-axios.

**Comment by black-snow** [comment]
I second this. Trying to generate code for java. Models are being created but then it breaks with

```
Cause: class java.util.UUID cannot be cast to class java.lang.String (java.util.UUID and java.lang.String are in module java.base of loader 'bootstrap')
```

**Comment by ccampanale** [comment]
This is still an issue with `typescript` and `typescript-axios` generators.

**Comment by spacether** [comment]
We welcome a PR to fix this issue if anyone wants to file it
