### ISSUE TITLE
java.lang.NullPointerException when parsing OAuth 2 

### ISSUE THREAD

**Issue by JohannesHoppe** [OpenAPITools/openapi-generator#355]
##### Description

The generator fails with an exception against our swagger.json. It works great with `swagger-codegen-cli.jar` instead.

##### openapi-generator version

v3.0.2

##### OpenAPI declaration file content or url

[swagger.json](https://api.angular.schule/swagger.json)

##### Command line used for generation

```
java -jar openapi-generator-cli.jar generate -i https://api.angular.schule/swagger.json -g typescript-angular

Exception in thread "main" java.lang.NullPointerException
	at io.swagger.v3.parser.converter.SwaggerConverter.convertOauth2SecurityScheme(SwaggerConverter.java:320)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:279)
	at io.swagger.v3.parser.converter.SwaggerConverter.lambda$convert$2(SwaggerConverter.java:222)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:222)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:93)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:19)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:516)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:314)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:58)
`

**Comment by jmini** [comment]
According to http://editor.swagger.io/, you spec is not a valid OAS2. Please fix the issues.

(it is possible that swagger-parser `1.x` was able to deal with them and that swagger-parser `2.0.1` is no longer capable to handle them)

**Comment by JohannesHoppe** [comment]
Thanks for the tipp. I will try to fix that. I think we need a better error message here?! 😄

**Comment by jmini** [comment]
For the error message, feel free to file an issue to https://github.com/swagger-api/swagger-parser

**Comment by jimschubert** [comment]
This was fixed, but I don't recall when (the PR wasn't linked back to this issue). Tried on master, and there are no NPE but the spec does require `--skip-validate-spec`:

```
openapi-generator generate -i https://api.angular.schule/swagger.json -g typescript-angular -o .bak/355 --skip-validate-spec
```

Please open another issue if there are concerns with the spec handling or output.

**Comment by JohannesHoppe** [comment]
@jimschubert I once again googled for a solution, found my own issue and realised that you provided a solution. Thank you very much for that! 👍
