### ISSUE TITLE
[BUG][JAVA] Crash generating Spring server from OpenBanking swagger

### ISSUE THREAD

**Issue by elier** [OpenAPITools/openapi-generator#3770]
#### Description
I'm trying to generate a SpringBoot server using an OpenBanking swagger and I get the following error:

`
java.lang.RuntimeException: Could not process model 'CreditInterest'.Please make sure that your schema is correct!
`
I think the schema is correct, it is just very complex.

##### openapi-generator version
4.1.1

##### OpenAPI declaration file content or url
https://raw.githubusercontent.com/OpenBankingUK/read-write-api-specs/master/dist/account-info-openapi.yaml

##### Command line used for generation
java -jar openapi-generator-cli.jar generate -i account-info-openapi.3.yaml -g spring -o openapi-generator-openbanking3-test

##### Steps to reproduce
Download the swagger file and try to generate a spring server with -g spring

##### Related issues/PRs
N/A

##### Suggest a fix
The CreditInterest object has several nested objects. I'm trying to pinpoint what exactly make the generate fails

**Comment by jmini** [comment]
Stacktrace:

```
ception in thread "main" java.lang.RuntimeException: Could not process model 'CreditInterest'.Please make sure that your schema is correct!
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:471)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:921)
	at fr.jmini.openapi.openapitools.generator.TestOpenapitoolsCodegen3Main.convert(TestOpenapitoolsCodegen3Main.java:192)
	at ...
Caused by: java.lang.ClassCastException: io.swagger.v3.oas.models.media.ObjectSchema cannot be cast to io.swagger.v3.oas.models.media.ArraySchema
	at org.openapitools.codegen.languages.AbstractJavaCodegen.getTypeDeclaration(AbstractJavaCodegen.java:689)
	at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:2231)
	at org.openapitools.codegen.DefaultCodegen.addVars(DefaultCodegen.java:3706)
	at org.openapitools.codegen.DefaultCodegen.addVars(DefaultCodegen.java:3654)
	at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1918)
	at org.openapitools.codegen.languages.AbstractJavaCodegen.fromModel(AbstractJavaCodegen.java:943)
	at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1199)
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:466)
	... 4 more
```

This is really similar to #3761 but at an other place (`AbstractJavaCodegen.getTypeDeclaration(..)` and I just fixed it for `AbstractJavaCodegen.toDefaultValue(..)` in PR #3765).

That said, I am wondering why we get an ObjectSchema instead of an ArraySchema.
The spec at this point looks good:
https://github.com/OpenBankingUK/read-write-api-specs/blob/2b5270a3838cf0de2bd2347d21325fdd6d5713ee/dist/account-info-openapi.yaml#L5693

**Comment by wing328** [comment]
> That said, I am wondering why we get an ObjectSchema instead of an ArraySchema.

Issues with Swagger Parser?

**Comment by jmini** [comment]
@wing328: Yes. I am filling the issue right now.

**Comment by jmini** [comment]
This is due to an error in Swagger-Parser:
https://github.com/swagger-api/swagger-parser/issues/1190

The trigger seems to be `additionalProperties: false` in `array` Schema.

@elier If you have the possibility to remove them, it should fix the issue you have with OpenAPI-Generator.

---

That said we can fix the `ClassCastException` (but I guess the generated code will still be broken, swagger-parser is loosing the array information).

**Comment by jmini** [comment]
PR #3780 is fixing the ugly `ClassCastException`, but to have a correct generated project with the spec described in this project, the solution is to get a fix for the issue in Swagger-Parser.

**Comment by jmini** [comment]
Issue swagger-api/swagger-parser#1190 is fixed and PR #3770 to update to the version containing that fix has been merged. 

You can give version `4.2.0-SNAPSHOT` of OpenAPI-Generator a try?
