### ISSUE TITLE
[BUG] [aspnetcore] File Upload throws exception

### ISSUE THREAD

**Issue by etherealjoy** [OpenAPITools/openapi-generator#3836]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The issue is that ASP.NET runtime throws an error that with the generated code which have this signature 
```
public virtual IActionResult UploadLogsV10([FromForm]System.IO.Stream logfile)
```
because it cannot create this object from the incoming request

##### openapi-generator version

`master`

##### OpenAPI declaration file content or url

```yaml
# Swagger 2.0 API specification
swagger: '2.0'
info:
  title: Logs 
  version: v1.0.0
  description: >-
    API specification 
basePath: /api
schemes:
  - https

tags:
  - name: Logs
    x-displayName: Logs
    description: API for uploading logs.

paths:
  /v1.0/logs:
    post:
      tags:
        - Logs
      summary: Reports logs from the headunit.
      description:  This operation is used to upload logs
      operationId: UploadLogsV1_0
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: formData
          name: logfile
          type: file
          description: >-
            The logfile to upload.
      responses:
        '200':
          description: success
```
##### Command line used for generation

```shell
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i \
/home/dev/api-specs/swagger.yaml  -o /home/dev/gen -g aspnetcore
```
##### Steps to reproduce

Call the api to post the logs and the following error is thrown
```shell
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLPHSGBHSMNG", Request id "0HLPHSGBHSMNG:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Could not create an instance of type 'System.IO.Stream'. Model bound complex types must not be abstract or value types and must have a parameterless constructor. Alternatively, give the 'logfile' parameter a non-null default value.
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinder.CreateModel(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinder.BindModelCoreAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

##### Suggest a fix

Changing the parameter to IFormCollection and iterating over the form fields works but not intuitive.

I have not tried it, but probably IFormFile might also work.

**Comment by frankyjuang** [comment]
might be the same  as https://github.com/OpenAPITools/openapi-generator/issues/2398

**Comment by etherealjoy** [comment]
@frankyjuang 
You are right. I will close this one.
