### ISSUE TITLE
[HTML] Does not accept additionalProperties flag for a schema within requestBody.

### ISSUE THREAD

**Issue by sri3390** [OpenAPITools/openapi-generator#409]
**Description**

Currently the html generation fails for schemas that have the field `additionalProperties` mentioned within `requestBody` schema for openapi v3 with the exception:
```
[main] WARN  o.o.codegen.utils.URLPathUtils - 'host' not defined in the spec (2.0). Default to http://localhost
Exception in thread "main" java.lang.RuntimeException: Could not process model 'body_4'.Please make sure that your schema is correct!
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:398)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:783)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:315)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:58)
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to io.swagger.v3.oas.models.media.Schema
	at org.openapitools.codegen.languages.StaticHtmlGenerator.getTypeDeclaration(StaticHtmlGenerator.java:121)
	at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:1782)
	at org.openapitools.codegen.DefaultCodegen.addParentContainer(DefaultCodegen.java:2970)
	at org.openapitools.codegen.DefaultCodegen.addAdditionPropertiesToCodeGenModel(DefaultCodegen.java:1539)
	at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1523)
	at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1016)
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:393)
	... 3 more
```

**openapi-generator version**

3.0.2, 3.0.3

**OpenAPI declaration file content or url**

```json
https://gist.github.com/sri3390/18907fb14ad3b909eb6dd44c7036d80b
```

**Command line used for generation**
```
java -jar openapi-generator-cli-3.0.3-20180626.073419-19.jar generate -i openapi.json -g html -o /test
```

**Steps to reproduce**
Copy the json file linked and run the above command.

This works fine if we remove the flag defined here: https://gist.github.com/sri3390/18907fb14ad3b909eb6dd44c7036d80b#file-sample-json-file-L38.

This also works fine if `additionalProperties` is present in the response schemas.

**Comment by jmini** [comment]
Thank you for this report.

You are right, the [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#schema-object) section in the OAS3 format spectifaction says:

> The following properties are taken from the JSON Schema definition but their definitions were adjusted to the OpenAPI Specification.
> ...
> * additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema.

So your case is valid.

For the moment we support "Dictionaries, HashMaps and Associative Arrays" and not "Free-Form Objects" (see https://swagger.io/docs/specification/data-models/dictionaries/ ). Something like:

```json
"additionalProperties": {
    "type": "boolean"
}
```

If I read the spec correctly `"additionalProperties": false` is similar to not having it set.

**Comment by jmini** [comment]
PR to solve the ClassCastException: #410

**Comment by sri3390** [comment]
Thank you @jmini . Appreciate the help 👍

**Comment by jmini** [comment]
#410 was merged.

Can you try it with `3.1.0-SNAPSHOT` (or next week when `3.1.0` is out).

Please reopen or comment if your issue is not solved.

**Comment by jmini** [comment]
Support for `additionalProperties: true`:

* issue https://github.com/OpenAPITools/openapi-generator/issues/796 
* PR https://github.com/OpenAPITools/openapi-generator/pull/849
