### ISSUE TITLE
Problems with swagger migration

### ISSUE THREAD

**Issue by karussell** [OpenAPITools/openapi-generator#413]
##### Description

When I try to convert a rather big swagger config to openapi 3 the generator fails.

I used https://mermade.org.uk/openapi-converter for conversion but cannot see what is wrong with the created yaml. Probably just the error message is not descriptive enough.

##### openapi-generator version

3.0.3

##### OpenAPI declaration file content or url

https://gist.github.com/karussell/5361f28647bc17c72daf294e33a10dc9

##### Command line used for generation

```bash
PKG=com.graphhopper.directions.api.client
java -jar openapi-generator-cli-3.0.3.jar generate -i graphhopper-spec.yaml -g java --artifact-version 0.11-SNAPSHOT --api-package $PKG.api --invoker-package $PKG --model-package $PKG.model --artifact-id directions-api-client --group-id com.graphhopper --library okhttp-gson -DhideGenerationTimestamp=true
```

##### Steps to reproduce

execute the command line

##### Error

```
[main] WARN  io.swagger.v3.parser.OpenAPIV3Parser - Exception while reading:
com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while parsing a block mapping
 in 'reader', line 1, column 1:
    openapi: 3.0.0
    ^
expected <block end>, but found Scalar
 in 'reader', line 779, column 2:
     minLon, minLat, maxLon,
     ^

 at [Source: (StringReader); line: 779, column: 2]
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException.from(MarkedYAMLException.java:27) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:351) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:825) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:247) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4044) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2539) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at io.swagger.v3.parser.OpenAPIV3Parser.readWithInfo(OpenAPIV3Parser.java:140) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at io.swagger.v3.parser.OpenAPIV3Parser.readLocation(OpenAPIV3Parser.java:45) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:19) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:516) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:314) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:58) [openapi-generator-cli-3.0.3.jar:3.0.3]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 1, column 1:
    openapi: 3.0.0
    ^
expected <block end>, but found Scalar
 in 'reader', line 779, column 2:
     minLon, minLat, maxLon,
     ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:347) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	... 12 common frames omitted
[main] ERROR i.s.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting ('true', 'false' or 'null')
 at [Source: (StringReader); line: 1, column: 8]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:673) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2835) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1889) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4030) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2539) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:209) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:122) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:93) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:42) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:91) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:19) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:516) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:314) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:58) [openapi-generator-cli-3.0.3.jar:3.0.3]
[main] ERROR i.s.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting ('true', 'false' or 'null')
 at [Source: (StringReader); line: 1, column: 8]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:673) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2835) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1889) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4030) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2539) ~[openapi-generator-cli-3.0.3.jar:3.0.3]
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:209) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:122) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:93) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:42) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:91) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:19) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:516) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:314) [openapi-generator-cli-3.0.3.jar:3.0.3]
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:58) [openapi-generator-cli-3.0.3.jar:3.0.3]
[main] WARN  o.o.c.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
Exception in thread "main" java.lang.RuntimeException: missing OpenAPI input!
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:765)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:315)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:58)
```

As the error message says something with the openapi word I tried a sample for the pet example and this works. So it must be something else.

Finally I reduce the spec to the reduced-spec.yaml (see gist) but I get:

```
Exception in thread "main" java.lang.NullPointerException
	at java.util.ArrayList.<init>(ArrayList.java:178)
	at org.openapitools.codegen.languages.AbstractJavaCodegen.getAccept(AbstractJavaCodegen.java:980)
	at org.openapitools.codegen.languages.AbstractJavaCodegen.preprocessOpenAPI(AbstractJavaCodegen.java:970)
	at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:183)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:772)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:315)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:58)
```

**Comment by jmini** [comment]
Your second gist "reduced-spec.yaml" is missing.

---

Your first gist is also invalid in http://editor.swagger.io/. There the error message is better:

> **Parser error**
> bad indentation of a mapping entry

On this line:
```yaml
        bbox:
          description: >-
            The bounding box of the route, format 
 minLon, minLat, maxLon,
```

---

Why aren't you using the your Swagger v2 specification directly with OpenAPI-Generator. Both formats (OpenAPI version 3 and Swagger version 2) are supported?

**Comment by karussell** [comment]
> Your second gist "reduced-spec.yaml" is missing.

Sorry, it was below the original: https://gist.github.com/karussell/5361f28647bc17c72daf294e33a10dc9#file-reduced-spec-yaml

> Your first gist is also invalid in http://editor.swagger.io/. There the error message is better:

Ok, then probably the converter has some bugs. Will investigate and try to fix this file first.

> Why aren't you using the your Swagger v2 specification directly with OpenAPI-Generator. Both formats (OpenAPI version 3 and Swagger version 2) are supported?

The aim was to migrate to version 3

**Comment by jmini** [comment]
> The aim was to migrate to version 3

I have pretty good results with `Swagger-Parser` (the same tool that this project is using).
See my quick how-to: https://j2r2b.github.io/2018/05/18/from-oas2-to-oas3.html

**Comment by jmini** [comment]
Your `reduced-spec.yaml` is also invalid. I get this error with http://editor.swagger.io/

> **Schema error** at paths['/route'].get
should have required property 'responses'
missingProperty: responses
Jump to line 10

I think you just need to define a response like this:

```yaml
      responses:
        '201':
          description: OK
```

**Comment by wing328** [comment]
@karussell if you still need help with this issue, please let us know.

Closing it for the time being.
