### ISSUE TITLE
[BUG] Large spec results in java/lang/OutOfMemoryError

### ISSUE THREAD

**Issue by mandrean** [OpenAPITools/openapi-generator#4398]
##### Description

When trying to generate a `native`+`jackson` Java client from a large v2 spec (14,000 lines of YAML), the generator crashes with `java/lang/OutOfMemoryError`. I've tried disabling generation of tests & docs, but with the same result.

(Works fine with `swagger-codegen` btw.)

##### openapi-generator version

Standalone _and_ Maven plugin: `4.2.0`

##### OpenAPI declaration file content or url

`swagger.yaml`: https://pastebin.com/raw/jpSf6krv
`swagger.config.json`: https://pastebin.com/raw/EK8Zv5bu

##### Command line used for generation

```
$ openapi-generator generate -i swagger.yaml -c swagger.config.json -g java
```

##### Steps to reproduce

Either just running it standalone (see above), or using the Maven plugin with the following `pom.xml`: https://pastebin.com/raw/NbwHpKdx

##### Related issues/PRs

Maybe https://github.com/OpenAPITools/openapi-generator/issues/2503?

**Comment by mandrean** [comment]
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.StringUTF16.newBytesFor(StringUTF16.java:52)
	at java.base/java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:89)
	at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:112)
	at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:394)
	at com.fasterxml.jackson.core.io.SegmentedStringWriter.getAndClear(SegmentedStringWriter.java:83)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:999)
	at io.swagger.v3.core.util.Json.pretty(Json.java:24)
	at org.openapitools.codegen.examples.ExampleGenerator.generate(ExampleGenerator.java:159)
	at org.openapitools.codegen.examples.ExampleGenerator.generateFromResponseSchema(ExampleGenerator.java:97)
	at org.openapitools.codegen.examples.ExampleGenerator.generateFromResponseSchema(ExampleGenerator.java:59)
	at org.openapitools.codegen.DefaultCodegen.handleMethodResponse(DefaultCodegen.java:2547)
	at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2670)
	at org.openapitools.codegen.languages.AbstractJavaCodegen.fromOperation(AbstractJavaCodegen.java:1155)
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1050)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:972)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:531)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:926)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:416)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:60)
```

**Comment by mandrean** [comment]
Using a custom build of `openapi-generator` where `org.openapitools.codegen.examples.ExampleGenerator.generate()` always returns an empty list, I managed to generate a client for this large spec!

So probably something in `ExampleGenerator` I'm assuming.

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/8731 to workaround the issue for the time being.
