### ISSUE TITLE
[BUG] [python-flask] Trying to run installed module NotADirectory error for yaml file

### ISSUE THREAD

**Issue by batousik** [OpenAPITools/openapi-generator#4433]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Using petstore swagger yaml I have created python-flask server. and then I have created dist and installed it.

```
python setup.py sdist
sudo python3 setup.py install
sudo python3 -m openapi_server
```

Trying to run the module and get the following error

```
sudo python3 -m openapi_server
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/openapi_server-1.0.0-py3.5.egg/openapi_server/__main__.py", line 18, in <module>
  File "/usr/local/lib/python3.5/dist-packages/openapi_server-1.0.0-py3.5.egg/openapi_server/__main__.py", line 13, in main
  File "/usr/local/lib/python3.5/dist-packages/connexion-2.4.0-py3.5.egg/connexion/apps/flask_app.py", line 54, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/connexion-2.4.0-py3.5.egg/connexion/apps/abstract.py", line 155, in add_api
    options=api_options.as_dict())
  File "/usr/local/lib/python3.5/dist-packages/connexion-2.4.0-py3.5.egg/connexion/apis/abstract.py", line 73, in __init__
    self.specification = Specification.load(specification, arguments=arguments)
  File "/usr/local/lib/python3.5/dist-packages/connexion-2.4.0-py3.5.egg/connexion/spec.py", line 151, in load
    return cls.from_file(spec, arguments=arguments)
  File "/usr/local/lib/python3.5/dist-packages/connexion-2.4.0-py3.5.egg/connexion/spec.py", line 107, in from_file
    spec = cls._load_spec_from_file(arguments, specification_path)
  File "/usr/local/lib/python3.5/dist-packages/connexion-2.4.0-py3.5.egg/connexion/spec.py", line 91, in _load_spec_from_file
    with specification.open(mode='rb') as openapi_yaml:
  File "/usr/lib/python3.5/pathlib.py", line 1151, in open
    opener=self._opener)
  File "/usr/lib/python3.5/pathlib.py", line 1005, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib/python3.5/pathlib.py", line 371, in wrapped
    return strfunc(str(pathobj), *args)
NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.5/dist-packages/openapi_server-1.0.0-py3.5.egg/openapi_server/openapi/openapi.yaml'
```

##### openapi-generator version

openapi-generator-cli-4.2.0.jar

##### OpenAPI declaration file content or url

https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore.yaml

##### Command line used for generation

java -jar openapi-generator-cli-4.2.0.jar generate -i ./swagger.yaml -g python-flask -o generated/server/python/flask -c python-config.json

```
{
    "packageName": "openapi_server",
    "controllerPackage": "controllers",
    "defaultController": "default_controller",
    "sortParamsByRequiredFlag": true,
    "ensureUniqueParams": true,
    "allowUnicodeIdentifiers": false,
    "prependFormOrBodyParameters": false,
    "packageVersion": "1.0.0",
    "supportPython2": true,
    "serverPort": 9898
}
```

##### Steps to reproduce

```
python setup.py sdist
sudo python3 setup.py install
sudo python3 -m openapi_server
```

##### Suggest a fix

I am new to python but maybe instead of trying to open yaml file as a file use ziputils to open a file inside an archive?

**Comment by batousik** [comment]
Had to time to look into the issue. As a fast fix for now, I have changed the path of openapi.yaml to a hardcoded full path to a file. And placed the file on a system.

**Comment by kerherve** [comment]
+1
I had a similar issue using openapi-generator-cli version 4.2.2 or 4.3.1. I had to hardcode the path of the openapi.yaml file as well to make my application work.

**Comment by chrisinmtown** [comment]
I can reproduce this error easily in my Python - Flask - Connexion project by running `python3 setup.py install`  and then trying to launch the server.

That install method creates an egg file like `/Users/me/.virtualenvs/py39/lib/python3.9/site-packages/mysrv-0.0.1-py3.9.egg`.  The yaml file is in that zip archive, but the simple method of adding the API file to the connexion app doesn't find it when buried in a zip archive:
```
conn_app = connexion.App(__name__, specification_dir=".")
conn_app.add_api('openapi.yml', arguments={'title': 'My Backend'})
```
If instead I use `pip3 install .` to install the module, the code shown above works fine.  The installer yields a real directory in `/Users/me/.virtualenvs/py39/lib/python3.9/site-packages/mysrv/` and at runtime the YAML file is found & loaded.

Please share the proper way of coding the `app.add_api()` method so both methods work.  Thanks in advance.
