### ISSUE TITLE
[BUG] [GRADLE] Plugin not compatible with gradle 6.0

### ISSUE THREAD

**Issue by anelam** [OpenAPITools/openapi-generator#4496]
##### Description

Using the gradle plugin with gradle version 6.0 throws an axception:

```
An exception occurred applying plugin request [id: 'org.openapi.generator', version: '4.2.0']
> Failed to apply plugin [id 'org.openapi.generator']
   > Could not create an instance of type org.openapitools.generator.gradle.plugin.extensions.OpenApiGeneratorGenerateExtension.
      > Please use the ObjectFactory.mapProperty() method to create a property of type Map<K, V>.
```

##### openapi-generator version

4.2.0

##### build.gradle.kts

```kts
plugins {
    id("org.openapi.generator") version "4.2.0"
}
```

**Comment by roxspring** [comment]
Looks like this is a duplicate of #2613, fixed by #4352, and released in [v4.2.1](https://github.com/OpenAPITools/openapi-generator/releases/tag/v4.2.1).

Please retry with the latest release and close the bug if the problem is resolved.

**Comment by gszyszka** [comment]
I'm also seeing an issue with gradle 6.0 and plugin [v4.2.2](https://github.com/OpenAPITools/openapi-generator/releases/tag/v4.2.2)

* What went wrong:
An exception occurred applying plugin request [id: 'org.openapi.generator']
> Failed to apply plugin [id 'org.openapi.generator']
   > Could not generate a proxy class for class org.openapitools.generator.gradle.plugin.extensions.OpenApiGeneratorGenerateExtension.

* Exception is:
org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'org.openapi.generator']
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.exceptionOccurred(DefaultPluginRequestApplicator.java:247)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:229)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:159)

**Comment by renceabishek** [comment]
hey @roxspring ,
We still have this issue with 6.X version. I tried with 6.6.1 and got below issue. when i turned to 5.X (in my case 5.6.2) It is working

```
> Failed to apply plugin 'org.openapi.generator'.
   > Could not create an instance of type org.openapitools.generator.gradle.plugin.extensions.OpenApiGeneratorGenerateExtension.
      > Please use the ObjectFactory.mapProperty() method to create a property of type Map<K, V>.
```

**Comment by moley** [comment]
Hi, any news on this bug, we'd like to use this plugin with gradle 6, too

**Comment by wing328** [comment]
@moley are you using the latest stable version v5.0.1?

https://plugins.gradle.org/plugin/org.openapi.generator
