### ISSUE TITLE
[BUG] NPE when validating schema with allOf with inline values

### ISSUE THREAD

**Issue by rasmusfaber** [OpenAPITools/openapi-generator#4681]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

Using a schema with an allOf with an inline object, i.e.
```
components:
  schemas:
    allOfInline:
      allOf:
        - type: object
          properties:
            name:
              type: string
```
causes the validator (with recommend, which is default with the Maven job) to fail with a NullPointerException:
```
java.lang.NullPointerException: element cannot be mapped to a null key                                                      at java.util.Objects.requireNonNull (Objects.java:246)                                                                  at java.util.stream.Collectors.lambda$groupingBy$53 (Collectors.java:1127)                                              at java.util.stream.ReduceOps$3ReducingSink.accept (ReduceOps.java:169)                                                 at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:177)                                           at java.util.Iterator.forEachRemaining (Iterator.java:133)                                                              at java.util.Spliterators$IteratorSpliterator.forEachRemaining (Spliterators.java:1801)                                 at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:484)                                               at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:474)                                        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential (ReduceOps.java:913)                                          at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)                                               at java.util.stream.ReferencePipeline.collect (ReferencePipeline.java:578)                                              at org.openapitools.codegen.utils.ModelUtils.getChildrenMap (ModelUtils.java:880)                                       at org.openapitools.codegen.utils.ModelUtils.getUnusedSchemas (ModelUtils.java:120)                                     at org.openapitools.codegen.config.CodegenConfigurator.toContext (CodegenConfigurator.java:462)                         at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput (CodegenConfigurator.java:498)                  at org.openapitools.codegen.plugin.CodeGenMojo.execute (CodeGenMojo.java:705)
```

##### openapi-generator version

4.2.2

##### OpenAPI declaration file content or url

```
openapi: 3.0.1
info:
  version: 1.0.0
  title: Example
  license:
    name: MIT
servers:
  - url: http://api.example.xyz/v1
paths:
  /person:
    get:
      operationId: list
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/allOfInline"
components:
  schemas:
    allOfInline:
      allOf:
        - type: object
          properties:
            name:
              type: string

```

##### Command line used for generation

`java -jar openapi-generator-cli.jar validate -i allOf-inline.yaml --recommend`

(or use Maven)

##### Steps to reproduce

Execute command as above

##### Related issues/PRs

Regression was introduced in 10627ed5cc3f4703b0f02662ea568353e8d26e00 during the fix of #4335 

##### Suggest a fix

PR incoming

**Comment by jimschubert** [comment]
I've tested this against current master and I don't receive an NPE. I was wondering if you could check?

```
openapi-generator validate -i .bak/4681/openapi.yaml --recommend
Validating spec (.bak/4681/openapi.yaml)
No validation issues detected.
```

I verified on 4.2.2 that I did get NPE:

```
➜  openapi-generator git:(master) openapi-generator validate -i .bak/4681/openapi.yaml --recommend
Validating spec (.bak/4681/openapi.yaml)
Exception in thread "main" java.lang.NullPointerException: element cannot be mapped to a null key
	at java.util.Objects.requireNonNull(Objects.java:228)
	at java.util.stream.Collectors.lambda$groupingBy$45(Collectors.java:907)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.openapitools.codegen.utils.ModelUtils.getChildrenMap(ModelUtils.java:880)
	at org.openapitools.codegen.utils.ModelUtils.getUnusedSchemas(ModelUtils.java:120)
	at org.openapitools.codegen.cmd.Validate.run(Validate.java:57)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
➜  openapi-generator git:(master) openapi-generator version
4.2.2
```

I believe I fixed this in #5107
