### ISSUE TITLE
Python (2.x) Flask tests in Travis failed 

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#4823]
```
Using /home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages
Finished processing dependencies for openapi-server==1.0.0
GLOB sdist-make: /home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/setup.py
py27 create: /home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/.tox/py27
py27 installdeps: -r/home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/requirements.txt, -r/home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/test-requirements.txt
py27 inst: /home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/.tox/.tmp/package/1/openapi_server-1.0.0.zip
py27 installed: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.,attrs==19.3.0,certifi==2019.11.28,chardet==3.0.4,Click==7.0,clickclick==1.2.2,configparser==4.0.2,connexion==2.5.0,contextlib2==0.6.0.post1,coverage==5.0,Flask==1.1.1,Flask-Testing==0.6.1,functools32==3.2.3.post2,idna==2.8,importlib-metadata==1.3.0,inflection==0.3.1,itsdangerous==1.1.0,Jinja2==2.10.3,jsonschema==3.2.0,MarkupSafe==1.1.1,more-itertools==5.0.0,nose==1.3.7,openapi-server==1.0.0,openapi-spec-validator==0.2.8,pathlib2==2.3.5,pluggy==0.13.1,py==1.8.0,pyrsistent==0.15.6,python-dateutil==2.8.1,PyYAML==5.2,randomize==0.14,requests==2.22.0,scandir==1.10.0,six==1.13.0,swagger-ui-bundle==0.0.6,typing==3.7.4.1,urllib3==1.25.7,Werkzeug==0.16.0,zipp==0.6.0
py27 run-test-pre: PYTHONHASHSEED='605076116'
py27 run-test: commands[0] | nosetests
E
======================================================================
ERROR: Failure: SyntaxError (invalid syntax (abstract.py, line 32))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/.tox/py27/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/openapi_server/test/__init__.py", line 3, in <module>
    import connexion
  File "/home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/.tox/py27/local/lib/python2.7/site-packages/connexion/__init__.py", line 5, in <module>
    from .apis import AbstractAPI  # NOQA
  File "/home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/.tox/py27/local/lib/python2.7/site-packages/connexion/apis/__init__.py", line 1, in <module>
    from .abstract import AbstractAPI  # NOQA
  File "/home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/.tox/py27/local/lib/python2.7/site-packages/connexion/apis/abstract.py", line 32
    class AbstractAPI(metaclass=AbstractAPIMeta):
                               ^
SyntaxError: invalid syntax

----------------------------------------------------------------------
Ran 1 test in 0.058s

FAILED (errors=1)
ERROR: InvocationError for command /home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/.tox/py27/bin/nosetests (exited with code 1)
py3 create: /home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/.tox/py3
py3 installdeps: -r/home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/requirements.txt, -r/home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/test-requirements.txt
py3 inst: /home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/python-flask-python2/.tox/.tmp/package/1/openapi_server-1.0.0.zip
py3 installed: attrs==19.3.0,certifi==2019.11.28,chardet==3.0.4,Click==7.0,clickclick==1.2.2,connexion==2.5.0,coverage==5.0,Flask==1.1.1,Flask-Testing==0.6.1,idna==2.8,importlib-metadata==1.3.0,inflection==0.3.1,itsdangerous==1.1.0,Jinja2==2.10.3,jsonschema==3.2.0,MarkupSafe==1.1.1,more-itertools==8.0.2,nose==1.3.7,openapi-server==1.0.0,openapi-spec-validator==0.2.8,pluggy==0.13.1,py==1.8.0,pyrsistent==0.15.6,python-dateutil==2.8.1,PyYAML==5.2,randomize==0.14,requests==2.22.0,six==1.13.0,swagger-ui-bundle==0.0.6,typing==3.7.4.1,urllib3==1.25.7,Werkzeug==0.16.0,zipp==0.6.0
py3 run-test-pre: PYTHONHASHSEED='605076116'
py3 run-test: commands[0] | nosetests
S....SSS...SSSS....S
----------------------------------------------------------------------
Ran 20 tests in 5.480s

OK (SKIP=9)
___________________________________ summary ____________________________________
ERROR:   py27: commands failed
  py3: commands succeeded
Makefile:20: recipe for target 'test-all' failed
make: *** [test-all] Error 1
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (nose-test) on project PythonFlaskConnexionTestsPython2: Command execution failed. Process exited with an error: 2 (Exit value: 2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :PythonFlaskConnexionTestsPython2
```

Ref: https://travis-ci.org/OpenAPITools/openapi-generator/builds/625992917

We've commented out the tests in pom.xml for the time being.

**Comment by wing328** [comment]
@aadibajpai can you please take a look when you've time? It could be similar to #3286

**Comment by aadibajpai** [comment]
> @aadibajpai can you please take a look when you've time? It could be similar to #3286

Sorry, I'm totally plagued by other stuff now. No time at all :(

**Comment by wing328** [comment]
No worry. Thanks for the prompt reply.

**Comment by spacether** [comment]
This appears to be caused by the connexion library.
The library was allowing installations on newer versions which didn't support py27. 
This diff https://github.com/OpenAPITools/openapi-generator/pull/4765
Pins the connexion library to working versions for older python versions. @wing328 this may now be working in master. I am away from a computer and unable to test iy right now.
