### ISSUE TITLE
[BUG] oneOf Could not process model

### ISSUE THREAD

**Issue by stevenbrookes** [OpenAPITools/openapi-generator#4989]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

Running openapi-generator-cli via docker on the latest mockserver spec file throws an error 

Exception in thread "main" java.lang.RuntimeException: Could not process model 'Expectations'.Please make sure that your schema is correct!
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:472)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:923)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:416)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
Caused by: java.lang.NullPointerException
        at org.openapitools.codegen.DefaultCodegen.addProperties(DefaultCodegen.java:2003)
        at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1847)
        at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1166)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:467)
        ... 3 more

Section of file causing the error is

       "oneOf" : [ {
          "$ref" : "#/components/schemas/Expectation"
        }, {
          "type" : "array",
          "additionalProperties" : false,
          "items" : {
            "$ref" : "#/components/schemas/Expectation"
          }
        } ]

Removing the oneOf and just leaving for example the array section fixes the issue and file generation completes successfully.

##### openapi-generator version

4.2.2 and 4.2.3-SNAPSHOT run via docker

##### OpenAPI declaration file content or url

https://api.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.8.x

##### Command line used for generation

docker run --rm -v "mockserver:/local" openapitools/openapi-generator-cli:v4.2.2 generate -i https://api.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.8.x -c /local/swagger/config.json -g php -o /local

##### Steps to reproduce

Run docker command above

##### Suggest a fix

Sorry I only do PHP!

**Comment by spacether** [comment]
@stevenbrookes can you please paste in the schema definition for Expectation? That will help us understand how to fix this issue.

**Comment by simllll** [comment]
Experience the same issue, any workaround?
```
Exception in thread "main" java.lang.RuntimeException: Could not process model 'RequiredFieldType'.Please make sure that your schema is correct!
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:496)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:1005)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:426)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
Caused by: java.lang.NullPointerException
        at org.openapitools.codegen.DefaultCodegen.addProperties(DefaultCodegen.java:2389)
        at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:2209)
        at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1289)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:491)
        ... 3 more
```

and the excerpt of the swagger file:
```
            $ref: '#/components/schemas/IRequiredFieldEducationLevel'
        RequiredFieldType:
            oneOf:
                -
                    $ref: '#/components/schemas/SimpleRequiredField'
                -
                    $ref: '#/components/schemas/ComplexRequiredField'
                -
                    type: string
```

**Comment by sebastien-rosset** [comment]
This may not work for you, a workaround is to define the schema outside oneOf and add a reference to that schema under oneOf. That worked for me.
