### ISSUE TITLE
[REQ] Support modelPropertyNaming=original for Python

### ISSUE THREAD

**Issue by jonashaag** [OpenAPITools/openapi-generator#5214]
Add support for `modelPropertyNaming` (or similar) to Python codegen.

If you have definitions like this one:

```
      parameters:
        - name: FooID
          in: query
```

Then the resulting code uses underscore notation:

```
    def myendpoint(self, foo_id, ..., **kwargs):  # noqa: E501
```

It should also be supported to leave the identifiers as-is, so that the code is:

```
    def myendpoint(self, FooID, ..., **kwargs):  # noqa: E501
```

Related tickets:
- https://github.com/OpenAPITools/openapi-generator/issues/3813

**Comment by spacether** [comment]
This is being worked in my draft PR here https://github.com/OpenAPITools/openapi-generator/pull/8325

**Comment by spacether** [comment]
@jonashaag @alessandromarchetti @gbm001 @rm31 @gbvanrenswoude can you try the python-experimental generator?
It uses spec naming for all model properties and endpoint parameters. It was added in: #8325

**Comment by rm3l** [comment]
@spacether Sure. I just tried to quickly run the `python-experimental` generator (which I guess is included in the latest `5.4.0-SNAPSHOT`). Unfortunately, I got the error below. Any ideas why ?
From the exception message,  I guess the wrong templating engine is passed to the `PythonExperimentalClientCodegen` instance, but did not have much time to investigate further.

```
❯ OPENAPI_GENERATOR_VERSION=5.4.0-SNAPSHOT openapi-generator-cli generate -i openapi.yaml -g python-experimental -o python-experimental-client

[INFO] Scanning for projects...                                                                                                                                                                                                           
[INFO]                                                                                                                                                                                                                                    
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------                                                                                                                                                           
[INFO] Building Maven Stub Project (No POM) 1                                                                                                                                                                                             
[INFO] --------------------------------[ pom ]---------------------------------                                                                                                                                                           
[INFO]                                                                                                                                                                                                                                    
[INFO] --- maven-dependency-plugin:2.9:get (default-cli) @ standalone-pom ---                                                                                                                                                             
[INFO] Resolving org.openapitools:openapi-generator-cli:jar:5.4.0-SNAPSHOT                                                                                                                                                                
Downloading from central: https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/5.4.0-SNAPSHOT/maven-metadata.xml                                                                                
Downloaded from central: https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/5.4.0-SNAPSHOT/maven-metadata.xml (2.0 kB at 2.3 kB/s)                                                            
Downloading from central: https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/5.4.0-SNAPSHOT/openapi-generator-cli-5.4.0-20220105.225636-15.jar                                                
Downloaded from central: https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/5.4.0-SNAPSHOT/openapi-generator-cli-5.4.0-20220105.225636-15.jar (25 MB at 1.3 MB/s)                             
[WARNING] destination/dest parameter is deprecated: it will disappear in future version.                                                                                                                                                  
[INFO] Copying /home/asoro/.m2/repository/org/openapitools/openapi-generator-cli/5.4.0-SNAPSHOT/openapi-generator-cli-5.4.0-SNAPSHOT.jar to /home/asoro/.local/bin/openapi-generator-cli-5.4.0-SNAPSHOT.jar                               
[INFO] ------------------------------------------------------------------------                                                                                                                                                           
[INFO] BUILD SUCCESS                                                                                                                                                                                                                      
[INFO] ------------------------------------------------------------------------                                                                                                                                                           
[INFO] Total time:  22.250 s                                                                                                                                                                                                              
[INFO] Finished at: 2022-01-06T16:44:34+01:00                                                                                                                                                                                             
[INFO] ------------------------------------------------------------------------
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - Output directory (/home/asoro/Work/tmp/openapi-gen-python/python-experimental-client) does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: python-experimental (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'python-experimental' is considered experimental.
[main] INFO  o.o.c.l.AbstractPythonCodegen - Environment variable PYTHON_POST_PROCESS_FILE not defined so the Python code may not be properly formatted. To define it, try 'export PYTHON_POST_PROCESS_FILE="/usr/local/bin/yapf -i"' (Linux/Mac)
[main] INFO  o.o.c.l.AbstractPythonCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
Exception in thread "main" java.lang.RuntimeException: Only the HandlebarsEngineAdapter is supported for this generator
        at org.openapitools.codegen.languages.PythonExperimentalClientCodegen.processOpts(PythonExperimentalClientCodegen.java:219)
        at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:251)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:894)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

**Comment by spacether** [comment]
Thanks for letting me know. It looks like our code is defaulting to mustache templates and the generator is erroring. You should be able to get past it by passing in the -e templating engine handlebars

**Comment by spacether** [comment]
I have a PR posted to fix it and I am waiting on a review from the core team:
https://github.com/OpenAPITools/openapi-generator/pull/11245
In the meantime pass in `-e handlebars ` to using python-experimental to specify the needed handlebars templating engine.

**Comment by rm3l** [comment]
Thanks. The generator command worked with `-e handlebars`.

**Comment by rm3l** [comment]
I'm not a Python expert, but after quickly taking a look at the code generated, this looks good to me, at least for the names of endpoint parameters and model properties.
Is it also planned to have method names respect the operation ID set in the OpenAPI definition? (This is perhaps related to #3813)
Anyways, thanks again for your work in #8325 on this generator.

**Comment by spacether** [comment]
Doing that is possible. If you want it please thumbs up vote it in the issue that I have created here:
https://github.com/OpenAPITools/openapi-generator/issues/11253

**Comment by spacether** [comment]
Can this issue be closed now that model property naming is consistent with original naming in python-experimental?

**Comment by rm3l** [comment]
> Can this issue be closed now that model property naming is consistent with spec naming in python-experimental?

Looks good to me with `python-experimental`.
@jonashaag Maybe you have additional feedback, since you initially reported this issue.

**Comment by spacether** [comment]
Closing this issue because we now have the [python-experimental](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/python-experimental.md#metadata) generator which uses spec case for model properties and endpoint parameters.
- For example [Pet.photoUrls keeps its case here](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python-experimental/petstore_api/model/pet.py#L85)
- And query, header, path, and cookie params use the original spec case [here](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python-experimental/petstore_api/api/fake_api_endpoints/parameter_collisions.py#L324)
