### ISSUE TITLE
[BUG][JAVA][MAVEN] java.time.OffsetDateTime cannot be cast to java.lang.String 

### ISSUE THREAD

**Issue by FloKaemmerer** [OpenAPITools/openapi-generator#5256]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Generation of client classes fails with class cast Exception while generation using maven Plugin.
Running `mvn clean compile` fails with 
```
[ERROR] 
java.lang.RuntimeException: Could not process operation:
  Tag: class Tag {
    name: Process
    description: REST-Services.
    externalDocs: null
}
  Operation: getProcessUsingGET
  Resource: get /api/prozesse
  Schemas: {}
  Exception: java.time.OffsetDateTime cannot be cast to java.lang.String
```

##### openapi-generator version

4.2.3
(Happens also in earlier Versions of 4.x.x)

##### OpenAPI declaration file content or url
The Spec used: (its valid according to https://apitools.dev/swagger-parser/online/ and https://editor.swagger.io/ )

```yaml
swagger: '2.0'
info:
  description: 'REST service'
  version: '2.1.9'
  title: REST
host: localhost
basePath: /
tags:
  - name: Process
    description: REST-Services.
paths:
  /api/prozesse:
    get:
      tags:
        - Process
      summary: Return a list of Process
      description: |
        Max response time MAX_RESPONSE_TIME_MS=20
      operationId: getProcessUsingGET
      produces:
        - application/json;charset=utf-8
      parameters:
        - name: dateFrom
          in: query
          description: Filters out Transactions before this date
          required: true
          type: string
          default: '2000-01-01T00:00:00.001Z'
          format: date-time
          allowEmptyValue: false
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - bearer: []
      deprecated: false
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
```

Used pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<artifactId>failing-with-class-cast-exception</artifactId>
	<name>failing-with-class-cast-exception</name>
	<groupId>com.example</groupId>
	<version>0.0.1-SNAPSHOT</version>
	<build>
		<plugins>
			<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>4.2.3</version>
				<executions>
					<execution>
						<id>kto-privatkunde</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>process.yml</inputSpec>
							<generatorName>java</generatorName>
							<generateApiTests>false</generateApiTests>
							<generateModelTests>false</generateModelTests>
							<configOptions>
								<library>jersey2</library>
								<hideGenerationTimestamp>true</hideGenerationTimestamp>
								<delegatePattern>true</delegatePattern>
								<java8>java8</java8>
								<dateLibrary>java8</dateLibrary>
							</configOptions>
							<additionalProperties>failOnEmptyBeans=false</additionalProperties>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
```
##### Command line used for generation

`mvn clean compile`

##### Steps to reproduce

Setup maven project and run `mvn clean compile`

**Comment by cljk** [comment]
I have a similar issue - generator 4.3.0 - java client resteasy with dateLibrary `java8`.

The model is generated correctly with OffsetDateTime - but when consuming my service I´m getting an exception:

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.time.OffsetDateTime` (no Creators, like default construct, exist): no String-argument constructor/factory method to deserialize from String value ('2020-03-11T16:09:56.000+0000')
 at [Source: (org.jboss.resteasy.specimpl.AbstractBuiltResponse$InputStreamWrapper); line: 1, column: 30] (through reference chain: java.util.ArrayList[0]->org.vgb.userconfiguration.restclient.model.UserConfiguration["createdAtDate"])
        at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
        at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1452)
        at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1028)
        at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
        at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323)
        at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1373)
        at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:171)
        at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
        at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
        at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1574)
        at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:965)
        at org.jboss.resteasy.resteasy-jackson2-provider@3.9.1.Final//org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.readFrom(ResteasyJackson2Provider.java:181)
        at org.jboss.resteasy.resteasy-jaxrs@3.9.1.Final//org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:66)
```

Interestingly when parsing the Json string returned by the service manually with using the  `ObjectMapper`  of the generated `JSON` class it´s working. 
The following is working: 

```

 ApiClient apiClient = new ApiClient();
    JSON json= apiClient.getJSON();

ObjectMapper mapper = json.getContext(UserConfiguration.class);
        ObjectReader objectReader = mapper.readerFor(UserConfiguration.class);

        UserConfiguration us = objectReader.<UserConfiguration>readValue(is);
```
`UserConfiguration` is my model class and `is` is my json String - below:

```
{
    "id": 10000,
    "createdAtDate": "2019-12-09T10:32:42.000+0000",
    "lastModifiedAtDate": "2019-12-09T10:32:42.000+0000",
    "configKey": "ACKNOWLEDGED_WORKING_RULES",
    "configValue": "1",
    "userUid": "d742efb7-2191-477e-9fec-9e7eea9afc02"
  }
```

**Comment by cljk** [comment]
I just wanted to add: in MY case my problem only existed in using the generated resteasy client in an app running in Wildfly 18 (Keycloak to be precise).

Using the generated client in a standalone app worked... why ever.
I switched to `jersey2` as library - this works in my context.

Perhaps the whole `java8` date library implementation is buggy.
I would suggest try to switch to another date lib or update to generator `4.3.0` - im my case it creates artifacts without compile issues.
Also I would suggest inserting the maven compiler plugin in the build section with configuring it to Java 8 - like

```
<plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.8.0</version>
                    <configuration>
                        <release>11</release>
                        <useIncrementalCompilation>yes</useIncrementalCompilation>
                    </configuration>
                </plugin>
```

**Comment by Allezxandre** [comment]
I'm also stumbling on this issue using a Python OpenAPI definition. My date-times are in the RFC3339 format with 6 digit, like so: `2020-07-20T17:00:00.123000+00:00`. 

But the Swift5 generator is crashing for me (on versions `4.3.1` and `5.0.0beta1`).

<details>
  <summary>(Disclose the full error)</summary>

```
Exception in thread "main" java.lang.RuntimeException: Could not process model 'Model'.Please make sure that your schema is correct!
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:475)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:850)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:432)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.ClassCastException: class java.time.OffsetDateTime cannot be cast to class java.lang.String (java.time.OffsetDateTime and java.lang.String are in module java.base of loader 'bootstrap')
	at org.openapitools.codegen.languages.Swift5ClientCodegen.toDefaultValue(Swift5ClientCodegen.java:629)
	at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:2982)
	at org.openapitools.codegen.DefaultCodegen.addVars(DefaultCodegen.java:4732)
	at org.openapitools.codegen.DefaultCodegen.addVars(DefaultCodegen.java:4680)
	at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:2480)
	at org.openapitools.codegen.languages.Swift5ClientCodegen.fromModel(Swift5ClientCodegen.java:753)
	at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1127)
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:470)
	... 4 more
make: *** [generate-beta] Error 1
```
</details>

**Comment by wing328** [comment]
@Allezxandre thanks for the PR. We'll review and merge accordingly if no question from us.

@cljk @FloKaemmerer please give the latest master a try as I could no longer repeat the issue.

**Comment by cljk** [comment]
@wing328 
I´ve lost this issue out of focus - and checking it again is not easy for me since I switched more or less completely to `retrofit2` - which has a different API. 
Sorry that I´ve no proof / test case.
