### ISSUE TITLE
[BUG][Elm] nullable Elm schema is not allowed to contain `null`

### ISSUE THREAD

**Issue by domenkozar** [OpenAPITools/openapi-generator#5615]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used? 5.0.0
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

Elm generator crashes if nullable enum schema to contains null value.

This is allowed by jsonschema and thus openapi spec.

##### openapi-generator version

5.0.0 branch, 4th Feb 2020

##### OpenAPI declaration file content or url

```yaml
rating:
      type: string
      nullable: true
      enum:
        - null 
        - Gibberish
```

##### Command line used for generation

```
openapi-generator-cli  generate --input-spec openapi.yaml --enable-post-process-file --generator-name elm --config openapi-generator.yml  --output openapi-client
```

##### Steps to reproduce

There's an error:

```
Exception in thread "main" java.lang.RuntimeException: Could not process model 'rating'.Please make sure that your schema is correct!
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:473)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:938)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:423)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
Caused by: java.lang.NullPointerException
        at org.openapitools.codegen.DefaultCodegen.postProcessModelsEnum(DefaultCodegen.java:490)
        at org.openapitools.codegen.languages.ElmClientCodegen.postProcessModels(ElmClientCodegen.java:321)
        at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1214)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:468)
        ... 3 more
```

**Comment by domenkozar** [comment]
cc @eriktim

**Comment by eriktim** [comment]
Thanks for opening this issue @domenkozar.
The error seems to be misleading. I think the issue is you're using `null` as an enum value here which seems to be unsupported. I'm not sure what you're trying to achieve here, but I think there are two options for now:

1. You want `null` to be one of the values of the enum. In that case you should write `"null"` in the yaml instead, or

2. You want the enum to be nullable. In that case I would recommend providing the non-nullable enum as a type and whereever you use it you can use nullable/[not-]required. For example:
```
optionA:
  required:
    - rating
  properties:
    rating:
      $ref: '#/components/schemas/rating'
      nullable: true
optionB:
  properties:
    rating:
      $ref: '#/components/schemas/rating'
rating:
      type: string
      enum:
        - Gibberish
```

@wing328 can you clarify what the desired behavior is here?

**Comment by domenkozar** [comment]
OpenAPI specification says schemas respect jsonschema, which does allow my example.

See https://github.com/OAI/OpenAPI-Specification/issues/1900#issuecomment-552945475

**Comment by eriktim** [comment]
Yes I've seen that one but it seems the OpenAPI generator does not support this (yet?). It's not the Elm generator breaking here.

**Comment by domenkozar** [comment]
Thanks - I've updated issue title to reflect that.

**Comment by zupo** [comment]
Hey @eriktim, where should I report this so that it gets fixed in the "OpenAPI generator", so that I can then help getting it fixed for Elm?

**Comment by eriktim** [comment]
@zupo this should be the right location. I was actually hoping for @wing328 to give some clarity on this issue.
