### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by Warxcell** [OpenAPITools/openapi-generator#5899]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Hello, I use API Platform as API server and I use OpenAPI Generator to generate client for it from OpenAPI 3 Specs. API-Platform uses : as logical divider in Schema names and OpenAPI Generator does not like it.

-attribute components.schemas.Schema name CategoryProductTypeResource:jsonld doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$

##### openapi-generator version

3.1.0

##### OpenAPI declaration file content or url

https://pastebin.com/NHKAFep8

##### Command line used for generation

openapi-generator generate -i openapi.json -g javascript -o client --additional-properties usePromises=true,useES6=true

##### Steps to reproduce

1. Use provided  OpenAPI declaration file content and command line for generation.

##### Related issues/PRs

Didn't found anything related

##### Suggest a fix

Maybe add option to provide some kind of rename mapping:
{
"Category:jsonld-category_logo": "CategoryCategoryLogo"
}

**Comment by senaria** [comment]
👋 Any news about that problem?

**Comment by yakobe** [comment]
As a follow up, jsonld generates property names like `@id` and `@context` which are then changed to just `id` and `context` as the model property name. 
This can cause duplicates in typescript models if there is another property without the `@`. E.g. `id` or `context`.

Is there a way to generate the model property names and keep them `@id`? I tried the `allowUnicodeIdentifiers` [option](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-fetch.md).

**Comment by davidrojo** [comment]
Same issue here. Have you found any workaround?

**Comment by hosseinsalemi** [comment]
Same problem.

**Comment by kevinoid** [comment]
For reference, it sounds like the OpenAPI files generated by API Platform don't comply with the Schema name restrictions specified in OpenAPI 3.  See OAI/OpenAPI-Specification#634 and OAI/OpenAPI-Specification#1387 for spec discussion, api-platform/api-platform#1493 for API Platform discussion.

**Comment by Richard87** [comment]
Hi! I have the same problem as @yakobe above, with API-Platform and JsonLD including properties as `@id`, `@type` and `@context` and more... 
https://json-ld.org/

It would be amazing if openapi-generator could generate valid code and work with that standard at the same time. I have tried a bunch of arguments, but with the same results, a bunch of duplicate `id` properties...

I am running this command: 
```
../pwa/node_modules/.bin/openapi-generator-cli generate -i openapi.json -o ../pwa/components/openapi -g typescript-fetch --additional-properties=supportsES6=true,npmVersion=6.9.0,typescriptThreePlus=true,allowUnicodeIdentifiers=true,disallowAdditionalPropertiesIfNotPresent=false,paramNaming=original,modelPropertyNaming=original,enumPropertyNaming=original
```
 without any luck...

OpenApi.json with Json-LD content:
https://pastebin.com/HKYE2993

And the generated typescript model:
```typescript
/* tslint:disable */
/* eslint-disable */
/**
 * Hello API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserJsonldContext } from './UserJsonldContext';
import {
    UserJsonldContextFromJSON,
    UserJsonldContextFromJSONTyped,
    UserJsonldContextToJSON,
} from './UserJsonldContext';

/**
 * 
 * @export
 * @interface UserJsonld
 */
export interface UserJsonld {
    /**
     * 
     * @type {UserJsonldContext}
     * @memberof UserJsonld
     */
    context?: UserJsonldContext;
    /**
     * 
     * @type {string}
     * @memberof UserJsonld
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonld
     */
    readonly type?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonld
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonld
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJsonld
     */
    email?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserJsonld
     */
    readonly roles?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UserJsonld
     */
    readonly userIdentifier?: string;
}

/**
 * Check if a given object implements the UserJsonld interface.
 */
export function instanceOfUserJsonld(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserJsonldFromJSON(json: any): UserJsonld {
    return UserJsonldFromJSONTyped(json, false);
}

export function UserJsonldFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJsonld {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'context': !exists(json, '@context') ? undefined : UserJsonldContextFromJSON(json['@context']),
        'id': !exists(json, '@id') ? undefined : json['@id'],
        'type': !exists(json, '@type') ? undefined : json['@type'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'roles': !exists(json, 'roles') ? undefined : json['roles'],
        'userIdentifier': !exists(json, 'userIdentifier') ? undefined : json['userIdentifier'],
    };
}

export function UserJsonldToJSON(value?: UserJsonld | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '@context': UserJsonldContextToJSON(value.context),
        'name': value.name,
        'email': value.email,
    };
}
```

**Comment by arulselvan** [comment]
+1  same kind error while generate aspnetcore 👇 

D:\project\cis\practice\layout-designer> npx @openapitools/openapi-generator-cli generate -i layout-designer.yaml -g aspnetcore -o ./api --additional-properties=operationResultTask=true,packageAuthors=InstaCCTX,packageName=TX.LayoutApi,packageTitle=LayoutAPI,useNewtonsoft=false
Did set selected version to 7.0.1
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 6, Warning count: 3
Errors:
        -**components.schemas.Schema name LayoutApiResponse[String] doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.schemas.Schema name LayoutApiResponse[InstaCCWidget] doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.schemas.Schema name LayoutApiResponse[List[InstaCCWidget]] doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.schemas.Schema name LayoutApiResponse[List[String]] doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.schemas.Schema name LayoutApiResponse[Boolean] doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.schemas.Schema name LayoutApiResponse[List[Layout]] doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
Warnings:
        -components.schemas.Schema name LayoutApiResponse[String] doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.schemas.Schema name LayoutApiResponse[InstaCCWidget] doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.schemas.Schema name LayoutApiResponse[List[InstaCCWidget]] doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.schemas.Schema name LayoutApiResponse[List[String]] doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.schemas.Schema name LayoutApiResponse[Boolean] doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
        -components.schemas.Schema name LayoutApiResponse[List[Layout]] doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+**$

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:668)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:695)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:503)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

**Comment by arulselvan** [comment]
> +1 same kind error while generate aspnetcore 👇
> 
> npx @openapitools/openapi-generator-cli generate -i layout-designer.yaml -g aspnetcore -o ./api --additional-properties=operationResultTask=true,packageAuthors=InstaCCTX,packageName=TX.LayoutApi,packageTitle=LayoutAPI,useNewtonsoft=false Did set selected version to 7.0.1 Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI). | Error count: 6, Warning count: 3 Errors: -**components.schemas.Schema name LayoutApiResponse[String] doesn't adhere to regular expression ^[a-zA-Z0-9.-_]+$ -components.schemas.Schema name LayoutApiResponse[InstaCCWidget] doesn't adhere to regular expression ^[a-zA-Z0-9.-_]+$ -components.schemas.Schema name LayoutApiResponse[List[InstaCCWidget]] doesn't adhere to regular expression ^[a-zA-Z0-9.-_]+$ -components.schemas.Schema name LayoutApiResponse[List[String]] doesn't adhere to regular expression ^[a-zA-Z0-9.-_]+$ -components.schemas.Schema name LayoutApiResponse[Boolean] doesn't adhere to regular expression ^[a-zA-Z0-9.-_]+$ -components.schemas.Schema name LayoutApiResponse[List[Layout]] doesn't adhere to regular expression ^[a-zA-Z0-9.-_]+$ Warnings: -components.schemas.Schema name LayoutApiResponse[String] doesn't adhere to regular expression ^[a-zA-Z0-9.-_]+$ -components.schemas.Schema name LayoutApiResponse[InstaCCWidget] doesn't adhere to regular expression ^[a-zA-Z0-9.-_]+$ -components.schemas.Schema name LayoutApiResponse[List[InstaCCWidget]] doesn't adhere to regular expression ^[a-zA-Z0-9.-_]+$ -components.schemas.Schema name LayoutApiResponse[List[String]] doesn't adhere to regular expression ^[a-zA-Z0-9.-_]+$ -components.schemas.Schema name LayoutApiResponse[Boolean] doesn't adhere to regular expression ^[a-zA-Z0-9.-_]+$ -components.schemas.Schema name LayoutApiResponse[List[Layout]] doesn't adhere to regular expression ^[a-zA-Z0-9.-_]+**$
> 
> ```
>     at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:668)
>     at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:695)
>     at org.openapitools.codegen.cmd.Generate.execute(Generate.java:503)
>     at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
>     at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
> ```



My case stemmed from the use of Swashbuckle.AspNetCore in a .NET Core project. I was able to identify the solution through the following discussion thread. Initially, I had configured my project with the FriendlyId option, but after removing it, the Generic List types were generated as separate schemas. Consequently, I could successfully employ openapi-generator-cli to generate clients for various programming languages

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1803

But I'm thinking whether using generics is advisable in the context of OpenAPI 3 specifications. Is it generally recommended, or are there potential drawbacks?
