### ISSUE TITLE
[BUG][JAVA] Generated model combining properties and additionalProperties can't be deserialized

### ISSUE THREAD

**Issue by s0b** [OpenAPITools/openapi-generator#6146]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When using `properties` and `additionalProperties` at the same time, the generated model extends HashMap and contains the plain properties as private members of the class. This generated class cannot be deserialized by Jackson or Gson. 

##### openapi-generator version

4.3.0. Is the latest version released of the `openapi-generator-maven-plugin`.

##### Example of JSON object

```json
{
  "total": 3709,
  "version": 4,
  "201fe2a0": [
    "codeDynamicItem1",
    293,
    63700,
    19,
    "nameDynamicItem1",
    "",
    "",
    "",
    0,
    -64
  ],
  "18147a62": [
    "codeDynamicItem2",
    237,
    40000,
    478,
    "nameDynamicItem2",
    "string1",
    "string2",
    "string3",
    0,
    0
  ],
  "1cbd607e": [
    "codeDynamicItem3",
    347,
    63100,
    9,
    "nameDynamicItem3",
    "string1",
    "string2",
    "string3",
    0,
    0
  ],
  "statistics": {
    "available": {
      "type1": 3305,
      "type2": 76,
      "type3": 71
    },
    "unavailable": {
      "type1": 1283,
      "type2": 15,
      "type3": 20
    }
  }
}

```

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.2
info:
  version: 1.0.0
  title: Mock data
servers:
  - url: "http://localhost:8080/"
tags:
  - name: Mock
paths:
  /mock:
    get:
      tags:
        - Mock
      operationId: getMockData
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MockResponse'
components:
  schemas:
    MockResponse:
      type: object
      properties:
        total:
          type: integer
          example: 12721
        version:
          type: integer
          example: 4
        statistics:
          type: object
          properties:
            available:
              type: object
              properties:
                type1:
                  type: number
                type2:
                  type: number
                type3:
                  type: number
            unavailable:
              type: object
              properties:
                type1:
                  type: number
                type2:
                  type: number
                type3:
                  type: number
      additionalProperties:
        type: array
        items:
          oneOf:
            - type: string
              nullable: true
            - type: integer

```

##### Command line used for generation

```xml
<plugin>
  <groupId>org.openapitools</groupId>
  <artifactId>openapi-generator-maven-plugin</artifactId>
  <version>4.3.0</version>
  <executions>
    <execution>
      <goals>
        <goal>generate</goal>
      </goals>
      <configuration>
        <inputSpec>${project.basedir}/src/main/resources/static/openapi.yml</inputSpec>
        <output>${project.build.directory}/generated-sources</output>
  
        <generatorName>java</generatorName>
        <modelNameSuffix>Dto</modelNameSuffix>
        <!--<library>okhttp-gson</library>-->
        <library>native</library>
  
        <generateApiDocumentation>false</generateApiDocumentation>
        <generateApiTests>false</generateApiTests>
        <generateModelDocumentation>false</generateModelDocumentation>
        <generateModelTests>false</generateModelTests>
  
        <apiPackage>${project.groupId}.mock.api</apiPackage>
        <modelPackage>${project.groupId}.mock.model</modelPackage>
        <invokerPackage>${project.groupId}.mock.client</invokerPackage>
  
        <configOptions>
          <serializableModel>true</serializableModel>
          <useBeanValidation>true</useBeanValidation>
          <hideGenerationTimestamp>true</hideGenerationTimestamp>
        </configOptions>
      </configuration>
    </execution>
  </executions>
</plugin>
```

##### Actual output vs Expected output

The actual output is when using Jackson is an error:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<java.lang.Object>` out of VALUE_NUMBER_INT token
 at [Source: (jdk.internal.net.http.ResponseSubscribers$HttpResponseInputStream); line: 1, column: 10] (through reference chain: com.example.mock.model.MockResponseDto["total"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.10.3.jar:2.10.3]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1445) ~[jackson-databind-2.10.3.jar:2.10.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1219) ~[jackson-databind-2.10.3.jar:2.10.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1171) ~[jackson-databind-2.10.3.jar:2.10.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:332) ~[jackson-databind-2.10.3.jar:2.10.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:265) ~[jackson-databind-2.10.3.jar:2.10.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[jackson-databind-2.10.3.jar:2.10.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[jackson-databind-2.10.3.jar:2.10.3]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527) ~[jackson-databind-2.10.3.jar:2.10.3]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364) ~[jackson-databind-2.10.3.jar:2.10.3]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29) ~[jackson-databind-2.10.3.jar:2.10.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218) ~[jackson-databind-2.10.3.jar:2.10.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3259) ~[jackson-databind-2.10.3.jar:2.10.3]
	at com.example.mock.api.MockApi.getMockData(MockApi.java:98) ~[classes/:na]
[...]
```

The actual output when using Gson is an error:

```
java.lang.IllegalStateException: Expected BEGIN_ARRAY but was NUMBER at line 1 column 14 path $.
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350) ~[gson-2.8.5.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80) ~[gson-2.8.5.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.5.jar:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.5.jar:na]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[gson-2.8.5.jar:na]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.5.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:927) ~[gson-2.8.5.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:892) ~[gson-2.8.5.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:841) ~[gson-2.8.5.jar:na]
	at com.example.mock.client.JSON.deserialize(JSON.java:138) ~[classes/:na]
	at com.example.mock.client.ApiClient.deserialize(ApiClient.java:775) ~[classes/:na]
[...]
```

The expected output is a Java object that can be deserialized

##### Steps to reproduce

I have created an [example project](https://github.com/s0b/additional-properties-demo) with the information provided above to reproduce the issue.

Just launch the server:

```
mvn clean generate-sources spring-boot:run
```

And execute the following cURL request which is going to trigger the issue:

```
curl http://localhost:8080/load
```

##### Related issues/PRs

Haven't found any on this project.

##### Suggest a fix

Above configuration is going to generate a model which starts like this:

```java
public class MockResponseDto extends HashMap<String, List> implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Integer total;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private Integer version;

  public static final String SERIALIZED_NAME_STATISTICS = "statistics";
  @SerializedName(SERIALIZED_NAME_STATISTICS)
  private MockResponseStatisticsDto statistics;

  public MockResponseDto total(Integer total) {
    this.total = total;
    return this;
  }
```

Instead of extending a HashMap this could be fixed by adding the additional properties as a new porperty in the model, something like this:

```java
public class MockResponseDto implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Integer total;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private Integer version;

  public static final String SERIALIZED_NAME_STATISTICS = "statistics";
  @SerializedName(SERIALIZED_NAME_STATISTICS)
  private MockResponseStatisticsDto statistics;

  public static final String SERIALIZED_NAME_ADDITIONALPROPERTIES = "additionalProperties";
  @SerializedName(SERIALIZED_NAME_ADDITIONALPROPERTIES)
  protected Map<String,String> additionalProperties = new HashMap<String,String>();

  public MockResponseDto total(Integer total) {
    this.total = total;
    return this;
  }

  @JsonAnyGetter
  public Map<String, String> any() {
   return this.additionalProperties;
  }

  @JsonAnySetter
  public void set(String name, String value) {
   this.additionalProperties.put(name, value);
  }
```

This change could potentially break current usages of the additionalProperties so maybe this change should be a configuration that needs to be enabled.

Also the actual name of the new suggested `additionalProperties` variable should be configurable as it's a probable name in an actual JSON.

**Comment by harel-e** [comment]
I'm running into a similar issue. When I try to serialize an generated object that extends HashMap (using Jackson), I get an empty json {}. 

+1 to the suggested solution, delegation vs inheritance. I suspect it would also simplify generating class inheritance.
fyi, delegation of additional properties is the solution in the project jsonschema2pojo, and it works quite well.
