### ISSUE TITLE
[BUG][Java] Error when path contains comma - java generator

### ISSUE THREAD

**Issue by speedlog** [OpenAPITools/openapi-generator#6380]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

Error during generate java code, when path contains comma.

##### openapi-generator version
```
openapi-generator-cli 4.3.1
  commit : 003165c
  built  : 2020-05-06T09:38:39Z
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/
```

##### OpenAPI declaration file content or url

[contract.yaml](https://gist.githubusercontent.com/speedlog/ad93c07b7d5802b659a8b2cbffd5ab5c/raw/8376ab9d158e6a9b2f0f5db46038e0e7314195c6/contract.yaml)
```yaml
openapi: 3.0.0
info:
  title: test
  version: '1.0'
  description: Test
servers:
  - url: 'http://localhost:3000'
paths:
  '/pet/{from},{to}':
    parameters:
      - schema:
          type: string
        name: from
        in: path
        required: true
      - schema:
          type: string
        name: to
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: getPet
components:
  schemas: {}
```

##### Command line used for generation

`openapi-generator generate -i contract.yaml -g java -o /tmp/test`

##### Steps to reproduce

Run above command.
Error:
```
[main] ERROR i.s.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"openapi: 3.0.0
info:
  title: test
  version: '1.0'
  description: Test
servers:
  - url: 'http://localhost:3000'
paths:
  '/pet/{from},{to}':
    parameters:
      - schema:
          type: string
        name: from
        in: path
        required: true
      - schema:
          type: string
        name: to
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: getPet
compon"[truncated 20 chars]; line: 1, column: 8]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:722)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2868)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1914)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:773)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:210)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
	at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:94)
	at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:42)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:89)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:461)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:507)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:423)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)

```

**Comment by ernestomar** [comment]
The error happens when you use path variables and don't provide documentation.

The following:

```
openapi: "3.0.0"
info:
  title: Foo specification
  version: 1.0.0
paths:
  /payment/{id}:
    get:
      operationId: fooGet
      summary: Foo GET
      responses:
        '200':
          description: Desc
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
components:
  schemas:
    Response:
      title: Foo response
      type: object
      properties:
        statusCode:
          type: string
          description: |-
            Código de respuesta con el siguiente formato: XXXX-#### donde los primeros cuatro caracteres identifican
            al microservicio que envia la respuesta y los ultimos cuatro numero el código de respuesta, si la
            invocación es exitosa debe retornar 0000.
      required:
        - statusCode 
```

Throws:

```
Validating spec (openapi.yaml)
[main] ERROR i.s.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"openapi: "3.0.0"
info:
  title: Foo specification
  version: 1.0.0
paths:
  /payment/{id}:
    get:
      operationId: fooGet
      summary: Foo GET
      responses:
        '200':
          description: Desc
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
components:
  schemas:
    Response:
      title: Foo response
      type: object
      properties:
        statusCode:
          type: string
          description: "[truncated 329 chars]; line: 1, column: 8]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:722)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2868)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1914)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:773)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:210)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
        at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:94)
        at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:42)
        at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:89)
        at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
        at org.openapitools.codegen.cmd.Validate.execute(Validate.java:52)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
[main] ERROR i.s.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"openapi: "3.0.0"
info:
  title: Foo specification
  version: 1.0.0
paths:
  /payment/{id}:
    get:
      operationId: fooGet
      summary: Foo GET
      responses:
        '200':
          description: Desc
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
components:
  schemas:
    Response:
      title: Foo response
      type: object
      properties:
        statusCode:
          type: string
          description: "[truncated 329 chars]; line: 1, column: 8]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:722)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2868)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1914)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:773)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:210)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
        at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:94)
        at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:42)
        at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:89)
        at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
        at org.openapitools.codegen.cmd.Validate.execute(Validate.java:52)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.HashSet.<init>(HashSet.java:119)
        at org.openapitools.codegen.cmd.Validate.execute(Validate.java:54)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
```

But if you provide specification for path variables:

```
openapi: "3.0.0"
info:
  title: Foo specification
  version: 1.0.0
paths:
  /payment/{id}:
    get:
      operationId: fooGet
      summary: Foo GET
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Foo ID
      responses:
        '200':
          description: Desc
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
components:
  schemas:
    Response:
      title: Foo response
      type: object
      properties:
        statusCode:
          type: string
          description: |-
            Código de respuesta con el siguiente formato: XXXX-#### donde los primeros cuatro caracteres identifican
            al microservicio que envia la respuesta y los ultimos cuatro numero el código de respuesta, si la
            invocación es exitosa debe retornar 0000.
      required:
        - statusCode        
```

It works well.
