### ISSUE TITLE
[Java][jersey2] Enable OAuth2 debug stream

### ISSUE THREAD

**Issue by sebastien-rosset** [OpenAPITools/openapi-generator#6461]
In the Jersey2 Java client, it would be useful to conditionally enable the OAuth2 debug stream when debug is enabled for the client.

For example, with client credentials, the following exception is raised:

```
java.lang.IllegalArgumentException: Response body is incorrect. Can't extract a token from an empty string
	at com.github.scribejava.core.utils.Preconditions.check(Preconditions.java:49)
	at com.github.scribejava.core.utils.Preconditions.checkEmptyString(Preconditions.java:31)
	at com.github.scribejava.core.extractors.OAuth2AccessTokenJsonExtractor.extract(OAuth2AccessTokenJsonExtractor.java:37)
	at com.github.scribejava.core.extractors.OAuth2AccessTokenJsonExtractor.extract(OAuth2AccessTokenJsonExtractor.java:18)
	at com.github.scribejava.core.oauth.OAuth20Service.sendAccessTokenRequestSync(OAuth20Service.java:53)
	at com.github.scribejava.core.oauth.OAuth20Service.getAccessTokenClientCredentialsGrant(OAuth20Service.java:295)
	at ....client.auth.OAuth.obtainAccessToken(OAuth.java:161)
	at .....auth.OAuth.applyToParams(OAuth.java:112)
	at ....ApiClient.updateParamsForAuth(ApiClient.java:1231)
	at ....ApiClient.invokeAPI(ApiClient.java:1048)
	...
```

My suggestion is that at this [line](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/jersey2/auth/OAuth.mustache#L145):

```java
    service = new ServiceBuilder(clientId)
        .apiSecret(clientSecret)
        .build(authApi);
```

We conditionally add a call to `debug()`:
```java
    service = new ServiceBuilder(clientId)
        .apiSecret(clientSecret).debug()
        .build(authApi);
```

This would make it possible to troubleshoot OAuth2 without running a debugger or changing the library. Since the data may be sensitive, we should have a specific debug flag.

**Comment by naude-r** [comment]
it would be useful for the OkHttp based client as well.
