### ISSUE TITLE
[BUG][Java] Empty looking object is generated for anyOf type

### ISSUE THREAD

**Issue by H21lab** [OpenAPITools/openapi-generator#6485]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

While generating the [TS29573_N32_Handshake.yaml](https://github.com/jdegre/5GC_APIs/blob/master/TS29573_N32_Handshake.yaml) to create java client, the java class SecurityCapability is generated with no relevant methods and it looks empty (there are no method to be able to passing values inside). However in yaml file the object is defined in the following way:
```
    SecurityCapability:
      anyOf:
        - type: string
          enum:
            - TLS
            - PRINS
        - type: string
```

##### openapi-generator version

5.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

https://github.com/jdegre/5GC_APIs/blob/master/TS29573_N32_Handshake.yaml

##### Command line used for generation

Generated by openapi-generator-maven-plugin by using following options:

```
	<plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>5.0.0-SNAPSHOT</version>
                
                <configuration>
                    <generatorName>java</generatorName>
                    <output>${project.build.directory}/generated-sources</output>
                    <configOptions>
                    </configOptions>
               </configuration>
               
               <executions>
                   <execution>
                        <id>65</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>                      
                            <inputSpec>${project.basedir}/src/main/resources/TS29573_N32_Handshake.yaml</inputSpec>
                            <modelPackage>com.h21lab.TS29573_N32_Handshake.handler</modelPackage>
                            <apiPackage>com.h21lab.TS29573_N32_Handshake.model</apiPackage>
                            <invokerPackage>com.h21lab.TS29573_N32_Handshake.handler</invokerPackage>
                        </configuration>
                    </execution>
           	</executions>
            </plugin>
    	<plugins>
```

##### Steps to reproduce

Generator will produce the following class with no relevant methods or variables:
```
/*
 * N32 Handshake API
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.0.alpha-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.h21lab.TS29573_N32_Handshake.handler;

import java.util.Objects;
import java.util.Arrays;

/**
 * SecurityCapability
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-05-29T11:08:32.406367+02:00[Europe/Vienna]")
public class SecurityCapability {

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return Objects.hash();
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecurityCapability {\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}


```

**Comment by wing328** [comment]
Please use the `jersey2` library, which has better support for oneOf, anyOf.

**Comment by H21lab** [comment]
I have tested it by using 
```
<generatorName>java</generatorName>
<library>jersey2</library>
```
After it was not possible to compile the project and I have to modify AbstractOpenApiSchema.java:
```
//package com.h21lab.TS29573_N32_Handshake.handler.model;
package com.h21lab.TS29573_N32_Handshake.handler;
```
And also the ApiClient.java:
```
//import com.h21lab.TS29573_N32_Handshake.handler.model.AbstractOpenApiSchema;
import com.h21lab.TS29573_N32_Handshake.handler.AbstractOpenApiSchema;
```
Then the client worked. (with jersey2, the difference is, there are no async method).
Now there  was method generated from anyOf type and possible to set value by `securityCapability.setActualInstance("some string");`

However after receiving the response from the server, there was raised additional error in the client:
```
Exception in thread "main" javax.ws.rs.ProcessingException: Error reading entity from input stream.
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:897)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:842)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:340)
	at org.glassfish.jersey.client.InboundJaxrsResponse$2.call(InboundJaxrsResponse.java:102)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:365)
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:240)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:99)
	at com.h21lab.TS29573_N32_Handshake.handler.ApiClient.deserialize(ApiClient.java:777)
	at com.h21lab.TS29573_N32_Handshake.handler.ApiClient.invokeAPI(ApiClient.java:947)
	at com.h21lab.TS29573_N32_Handshake.model.SecurityCapabilityNegotiationApi.postExchangeCapabilityWithHttpInfo(SecurityCapabilityNegotiationApi.java:129)
	at com.h21lab.TS29573_N32_Handshake.model.SecurityCapabilityNegotiationApi.postExchangeCapability(SecurityCapabilityNegotiationApi.java:71)
	at com.h21lab.main.Client.main(Client.java:75)
Caused by: java.io.IOException: Failed deserialization for SecurityCapability: no match found
	at com.h21lab.TS29573_N32_Handshake.handler.SecurityCapability$SecurityCapabilityDeserializer.deserialize(SecurityCapability.java:61)
	at com.h21lab.TS29573_N32_Handshake.handler.SecurityCapability$SecurityCapabilityDeserializer.deserialize(SecurityCapability.java:37)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1682)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:977)
	at org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:837)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:882)
	... 14 more
```

**Comment by black-snow** [comment]
My issue might be related.

My schema has:

```yaml
        fields:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/CircularField'
              - $ref: '#/components/schemas/Field'
```

And I both `Field` and `CircularField` get generated (`java` and `resttemplate` lib). But `CircularField` tries to import `AnyOfCircularFieldField` - but there is no such class.

Will https://github.com/OpenAPITools/openapi-generator/pull/7263 fix this?

**Comment by oscar-besga-panel** [comment]
I hate to report that this behaviour is also found in version7.9.0

I generate with
```
java -jar openapi-generator-cli-7.7.0.jar \
    generate \
    --input-spec TS29510_Nnrf_NFDiscovery.yaml \
    --generator-name jaxrs-jersey \
    --output temp/java \
    --config TS29510_Nnrf_NFDiscovery.json
```
With these options in the json file
```
{
    "apiPackage": "com.telefonica.iot.nrf.service.openapi.rel17.discovery.api",
    "modelPackage": "com.telefonica.iot.nrf.service.openapi.rel17.discovery.model",
    "dateLibrary":  "java8",
    "generateBuilders": true,
    "generateConstructorWithAllArgs": true
}
```

And this data definition in the specs
```
 NFType:
      description: NF types known to NRF
      anyOf:
        - type: string
          enum:
            - NRF
            - UDM
[...]
            - SMS_ROUTER
        - type: string
```

It generates a class without properties/internal_variables [like this](https://gist.github.com/oscar-besga-panel/6f8407e1387da315c6d9d13c0b3e9197) 

The server launch an error if I try to run it
```
org.glassfish.jersey.server.model.ModelValidationException: Validation of the application resource model has failed during application initialization.
[[FATAL] No injection source found for a parameter of type public javax.ws.rs.core.Response com.telefonica.iot.nrf.service.openapi.rel17.management.api.NfInstancesApi.getNFInstances(com.telefonica.iot.nrf.service.openapi.rel17.management.model.NFType,java.lang.Integer
```
