### ISSUE TITLE
[BUG] Any isSomething field is serialized incorrectly in Kotlin generator

### ISSUE THREAD

**Issue by mishin** [OpenAPITools/openapi-generator#6616]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?

- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
openapi: 3.0.1
- [x] Have you search for related issues/PRs?
yes
- [x] What's the actual output vs expected output?
expected - it will generate correct API
actual output  is
```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 1
Errors: 
        -attribute paths.'/v1/{uuid}'.[['unknown']].in is missing
Warnings: 
        -attribute paths.'/v1/{uuid}'.[['unknown']].in is missing

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:480)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:507)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:423)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
```
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### openapi-generator version

openapi: 3.0.1
##### OpenAPI declaration file content or url

https://gist.github.com/mishin/31fc9ae2b0d4acd79fc668fded257c41

##### Command line used for generation
```
./gradlew  'generate all'
```

```
openapi-generator-cli generate -g kotlin -i /src/main/resources/openapi/api.yaml -o /var/tmp/kotlin3/
```

return 
```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 1
Errors: 
        -attribute paths.'/v1/{uuid}'.[['unknown']].in is missing
Warnings: 
        -attribute paths.'/v1/{uuid}'.[['unknown']].in is missing

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:480)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:507)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:423)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
```

**Comment by mishin** [comment]
https://hceris.com/painless-json-with-kotlin-and-jackson/

**Comment by mishin** [comment]
I found the same issue https://github.com/FasterXML/jackson-module-kotlin/issues/80

**Comment by mishin** [comment]
https://www.baeldung.com/jackson-exception

**Comment by mishin** [comment]
```
package online.oboz.notificator.message_processing.listener

import com.fasterxml.jackson.annotation.JsonAutoDetect
import com.fasterxml.jackson.annotation.PropertyAccessor
import com.fasterxml.jackson.module.kotlin.KotlinModule
import org.junit.Assert
import org.junit.jupiter.api.Test
import org.slf4j.Logger
import org.slf4j.LoggerFactory


class ListenerRegistryTestOpenApi : AIntegrationTest() {
    companion object {
        private val log: Logger = LoggerFactory.getLogger(this::class.java)
    }

    @Test
    fun SerializationTest() {
        mapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);
        mapper.registerModule(KotlinModule())

        val example = IsBoolExample(true)
        val json = mapper.writeValueAsString(example)
        // json contains: {"trueOrFalse":true}

        val deserialized = mapper.readValue(json, IsBoolExample::class.java)
        log.warn("deserialized :" + deserialized.isTrueOrFalse)
        log.warn("example :" + example.isTrueOrFalse)
        Assert.assertEquals(example.isTrueOrFalse, deserialized.isTrueOrFalse)

    }

    class IsBoolExample(val isTrueOrFalse: Boolean)

}

```

**Comment by mishin** [comment]
close because fixed https://github.com/FasterXML/jackson-module-kotlin/issues/346
