### ISSUE TITLE
[QUESTION] How to get parameters in different groups in openapi-generator

### ISSUE THREAD

**Issue by RezaRahmati** [OpenAPITools/openapi-generator#6683]
I am new to openapi-generator. 

Part of my yaml file is like below. in the generator (in the moustache file) I am able to get all parameters by using `allParams` and it will return 
```
ChannelTimezoneNameHeader,
LanguageHeader,

goalId,
customerId
```
My question is how can I get first category of parameters and second category separately, not combined together?

```
/accounts/customer/{customerId}/goals/{goalId}/transactions:
      x-swagger-router-controller: "GoalsController"
      parameters:
        -
          $ref: "#/parameters/ChannelTimezoneNameHeader"
        -
          $ref: "#/parameters/LanguageHeader"
      get:
        tags:
          - "goals"
        summary: "get goal transactions for a customer account"
        description: ""
        operationId: "getGoalTransactions"
        security:
          -
            AuthorizationHeader: []
            XIdTokenHeader: []
        parameters:
          -
            name: "goalId"
            in: "path"
            description: "goalId"
            required: true
            type: "string"
          -
            name: "customerId"
            in: "path"
            description: "customerId"
            required: true
            type: "string"
        responses:
          200:
            description: "successful operation"
            schema:
              $ref: "#/definitions/TransactionListGoal"
          400:
            description: "Bad Request"
            schema:
              $ref: "#/definitions/ChannelApiError"
          500:
            description: "Server error"
            schema:
              $ref: "#/definitions/ChannelApiError"
```
I already asked this question in [stackoverflow](https://stackoverflow.com/questions/62396475/how-to-get-parameters-in-different-groups-in-openapi-generator) hoping getting help, but no answers , this is why I am posting in github as well

**Comment by wing328** [comment]
I think you're looking for the following
```
{{#queryParams}} ... {{/queryParams}}

{{#formParams}} ... {{/formParams}}

{{#headerParams}} ... {{/headerParams}}.

{{#pathParams}} ... {{/pathParams}}

{{#bodyParamas}} ... {/bodyParamas}}
```

**Comment by RezaRahmati** [comment]
Thank you for response, let me change my mustache file to see which one is which

**Comment by wing328** [comment]
OK. Closing this for the time being.

**Comment by RezaRahmati** [comment]
@wing328 thanks it works, except for `{{#bodyParamas}}` that I get below exception 
(since there was a typo I tried with both bodyParamas and bodyParams)

`Exception in thread "main" java.lang.RuntimeException: Could not generate api file for 'AccountManagement'
        at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:667)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:923)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:396)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:60)
Caused by: com.samskivert.mustache.MustacheParseException: Section close tag with mismatched open tag 'operation' != 'bodyParams' @ line 372
        at com.samskivert.mustache.Mustache$Accumulator.requireSameName(Mustache.java:680)
        at com.samskivert.mustache.Mustache$Accumulator$1.addCloseSectionSegment(Mustache.java:612)
        at com.samskivert.mustache.Mustache$Accumulator.addTagSegment(Mustache.java:638)
        at com.samskivert.mustache.Mustache$Parser.parseChar(Mustache.java:498)
        at com.samskivert.mustache.Mustache$Parser.parse(Mustache.java:396)
        at com.samskivert.mustache.Mustache.compile(Mustache.java:314)
        at com.samskivert.mustache.Mustache$Compiler.compile(Mustache.java:87)
        at com.samskivert.mustache.Mustache$Compiler.compile(Mustache.java:82)
        at org.openapitools.codegen.templating.MustacheEngineAdapter.compileTemplate(MustacheEngineAdapter.java:51)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:957)
        at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:618)`

**Comment by RezaRahmati** [comment]
@wing328 thank you it works, just there are few typos in the last line, if you edit your answer would be great in case somebody else copy pasting

`{{#bodyParamas}} ... {/bodyParamas}}` to `{{#bodyParams}} ... {{/bodyParams}}`

**Comment by wing328** [comment]
Sorry for the typo. Just fixed it.

**Comment by RezaRahmati** [comment]
> Sorry for the typo. Just fixed it.

and one open brace is missing too ;)
