### ISSUE TITLE
[BUG][python] ClassCastException: class java.util.Date cannot be cast to class java.lang.String

### ISSUE THREAD

**Issue by orenyomtov** [OpenAPITools/openapi-generator#6694]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used? 4.3.1
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The following property generates an error when trying to generate a python client
```json
"properties": {
                    "dueDate": {
                        "format": "date",
                        "default": "2016-01-30",
                        "type": "string"
                    }
                }
```
```
Exception in thread "main" java.lang.RuntimeException: Could not process model 'mySchema'.Please make sure that your schema is correct!
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:496)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:1005)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:431)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
Caused by: java.lang.ClassCastException: class java.util.Date cannot be cast to class java.lang.String (java.util.Date and java.lang.String are in module java.base of loader 'bootstrap')
	at org.openapitools.codegen.languages.PythonClientCodegen.toExampleValueRecursive(PythonClientCodegen.java:724)
	at org.openapitools.codegen.languages.PythonClientCodegen.toExampleValue(PythonClientCodegen.java:703)
	at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:2846)
	at org.openapitools.codegen.DefaultCodegen.addVars(DefaultCodegen.java:4534)
	at org.openapitools.codegen.DefaultCodegen.addVars(DefaultCodegen.java:4482)
	at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:2378)
	at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1289)
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:491)
	... 4 more
```
##### openapi-generator version

4.3.1

##### OpenAPI declaration file content or url

```json
{
    "openapi": "3.0.0",
    "info": {
        "version": "1.0.0",
        "title": "Issue Reproduction",
        "license": {
            "name": "MIT"
        }
    },
    "paths": {},
    "components": {
        "schemas": {
            "mySchema": {
                "type": "object",
                "properties": {
                    "dueDate": {
                        "format": "date",
                        "default": "2016-01-30",
                        "type": "string"
                    }
                }
            }
        }
    }
}
```

##### Command line used for generation

`openapi-generator generate -g python -o /tmp/error/ -i ./error.json`

##### Steps to reproduce

Save the above json file as error.json, and run the command line

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/1312
https://github.com/OpenAPITools/openapi-generator/issues/2907

##### Suggest a fix

🤷🏻‍♂️

**Comment by wing328** [comment]
I think the issue has been resolved in the latest master. Can you please give it a try?

**Comment by orenyomtov** [comment]
Thanks, yes it had been solved!

Works great on the `:latest` docker image.
