### ISSUE TITLE
[BUG] Failure to parse --auth command line option

### ISSUE THREAD

**Issue by johnthagen** [OpenAPITools/openapi-generator#6745]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Unable to properly pass `--auth` header from the command line.

##### openapi-generator version

Running on macOS 10.15.5

```bash
% openapi-generator version
4.3.1
```

##### Command line used for generation

```bash
% openapi-generator generate --input-spec https://mydomain/rest/swagger.json --generator-name python --output out --auth "Authorization: Basic dXNlcjp1c2Vy"
[error] Found unexpected parameters: [Basic, dXNlcjp1c2Vy=]

See 'openapi-generator-cli help' for usage.
```

##### Expected

I would expect the `--auth` parameter to be parsed correctly. Also, there don't seem to be any documentation examples on using this parameter to compare to.

**Comment by johnthagen** [comment]
Potentially related: https://stackoverflow.com/questions/42119616/using-swagger-codegen-with-username-and-password-basic-auth/42137322#comment110328552_42137322

**Comment by johnthagen** [comment]
So it appears this needs to be URL encoded (spaces need to be converted to `%20` and `=` need to be converted to `%3D` at a minimum).

Something in the docs about this would be very helpful because currently it doesn't seem to be documented how this is supposed to work.

**Comment by johnthagen** [comment]
This worked (and if your base64 ends in `=` replace with `%3D`:

```
% openapi-generator generate --input-spec https://mydomain/rest/swagger.json --generator-name python --output out --auth "Authorization:Basic%20dXNlcjp1c2Vy"
```

**Comment by butler1233** [comment]
Just to add, this issue appears to occur on multiple cli options, but not all. 

On some where it does work though, it's not properly. 

For example, if I try to pass `generate -o "../Folder Name/"`, then it won't complain about the extra parameters, but instead it will complain with an exception:

```
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <"> at index 25: ../Folder Name/" -t Api\oag_template -p netCoreProjectFile=true,optionalAssemblyInfo=true,optionalProjectFile=true,signKey=../../../ORDERS~1/Snek.snk,packageAuthors=WhiteHinge,targetFramework=net472,testTargetFramework=net472,packageCopyright=2016-2020_White_Hinge_Limited 
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at org.openapitools.codegen.config.WorkflowSettings$Builder.withOutputDir(WorkflowSettings.java:325)
	at org.openapitools.codegen.config.CodegenConfigurator.setOutputDir(CodegenConfigurator.java:407)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:309)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

**Comment by AlvaroL** [comment]
Thanks @johnthagen this was making me crazy, it is not documented anywhere
