### ISSUE TITLE
Cannot define multiple resource in request body of json.

### ISSUE THREAD

**Issue by mitsuru793** [OpenAPITools/openapi-generator#6967]
##### Description

I want to the following generated code.

```
export interface CreatePostRequest {
    post?: Post;
    tag?: Tag;
}
```

----------

I create the yaml.

```yaml
openapi: 3.0.0
info:
  title: Sample API
  description: 'Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.'
  version: 0.0.1
servers:
  - url: 'http://api.myapp.net/v1'
    description: 'Optional server description, e.g. Main (production) server'
paths:
  /posts:
    post:
      summary: ''
      operationId: create-post
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              post:
                $ref: '#/components/schemas/Post'
              tag:
                $ref: '#/components/schemas/Tag'
components:
  schemas:
    Post:
      title: Post
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
    Tag:
      title: Tag
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
```

`openapi-generator generate -i ./index.yml -o ./generated/ -g typescript-fetch --additional-properties=typescriptThreePlus=true`

openapi-generator command outputs the following.

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 2, Warning count: 2
Errors:
        -attribute paths.'/posts'(post).requestBody.content.'application/json'.schema.tag is unexpected
        -attribute paths.'/posts'(post).requestBody.content.'application/json'.schema.post is unexpected
Warnings:
        -attribute paths.'/posts'(post).requestBody.content.'application/json'.schema.tag is unexpected
        -attribute paths.'/posts'(post).requestBody.content.'application/json'.schema.post is unexpected

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:480)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:507)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:423)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
```

----------

When I use application/x-www-form-urlencoded and properties, it generates ideal code.

```yaml
requestBody:
  content:
    application/x-www-form-urlencoded:
      schema:
        properties:
          post:
            $ref: '#/components/schemas/Post'
          tag:
            $ref: '#/components/schemas/Tag'
```

```typescript
export interface CreatePostRequest {
    post?: Post;
    tag?: Tag;
}
```

-----------

When I use application/json and properties, it generates a broken code.

```yaml
requestBody:
  content:
    application/json:
      schema:
        properties:
          post:
            $ref: '#/components/schemas/Post'
          tag:
            $ref: '#/components/schemas/Tag'
```

```typescript
import * as runtime from '../runtime';
import {
    UNKNOWN_BASE_TYPE,
    UNKNOWN_BASE_TYPEFromJSON,
    UNKNOWN_BASE_TYPEToJSON,
} from '../models';

export interface CreatePostRequest {
    uNKNOWNBASETYPE?: UNKNOWN_BASE_TYPE;
}
```

##### openapi-generator version

```
> openapi-generator --version
openapi-generator-cli 4.3.1
  commit : 003165c
  built  : 2020-05-06T09:38:39Z
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/
```

**Comment by wing328** [comment]
```
requestBody:
  content:
    application/json:
      schema:
        properties:
          post:
            $ref: '#/components/schemas/Post'
          tag:
            $ref: '#/components/schemas/Tag'
```

I don't think that's valid as reported by openapi-generator:
```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 2, Warning count: 2
Errors:
        -attribute paths.'/posts'(post).requestBody.content.'application/json'.schema.tag is unexpected
        -attribute paths.'/posts'(post).requestBody.content.'application/json'.schema.post is unexpected
Warnings:
        -attribute paths.'/posts'(post).requestBody.content.'application/json'.schema.tag is unexpected
        -attribute paths.'/posts'(post).requestBody.content.'application/json'.schema.post is unexpected
```
