### ISSUE TITLE
[BUG][TypeScript] Description

### ISSUE THREAD

**Issue by LeKwisatz** [OpenAPITools/openapi-generator#7044]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

My webservice can return 'text/csv' in case of success or 'application/problem+json' in case of failure. The generated http request only keeps the json Accept header so that the response cannot be interpreted when csvc is returned in case of success. 
Therefore the requests results in a "SyntaxError: Unexpected token T in JSON at position 0 at JSON.parse (<anonymous>)" since it is not JSON. 
As a workaround, I will wrap my csv in a json.

##### openapi-generator version

4.3.1
not tested on previous versions

##### OpenAPI declaration file content or url

```yaml
    responses:
        "200":
          content:
            text/csv:
              schema:
                type: string
        '404':
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
```

##### Command line used for generation

openapi-generator generate -i ./src/apis/contracts/swagger_0.4.yaml -g typescript-angular -o ./src/apis/name --api-package api --model-package model --additional-properties=\"ngVersion=7.2.11\" --additional-properties=\"withInterfaces=true\"

##### Steps to reproduce

- creates a WS that can return both csv or json 
- call the service so it returns csv

##### Related issues/PRs

not found

##### Suggest a fix

I guess there is a reason why, but in the generated code, only the json accept header is selected by this.configuration.selectHeaderAccept(httpHeaderAccepts) instead of both :

```js
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'text/csv',
                'application/problem+json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }
```

**Comment by LeKwisatz** [comment]
here is the full stacktrace

```
SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.onLoad (http://localhost:4200/vendor.js:8491:51)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:3772:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.js:64370:33)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:3771:60)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:4200/polyfills.js:3544:47)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (http://localhost:4200/polyfills.js:3847:34)
    at invokeTask (http://localhost:4200/polyfills.js:5042:14)
    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:4200/polyfills.js:5079:21)
```
