### ISSUE TITLE
[BUG] [General] Problem with inheritance when subclass has no property

### ISSUE THREAD

**Issue by MarcMil** [OpenAPITools/openapi-generator#7045]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used? - 5.0.0-beta
- [x] Have you search for related issues/PRs?

##### Description

The problem occurs when reading a schema with subclasses, when the subclasses do not specify properties of their own, but only inherit all properties from their parent (e.g. in order to be futureproof, one might first specify the inheritance hierarchy and later on add specific properties for some subclasses).
The schema is valid according to https://editor.swagger.io/ and https://apitools.dev/swagger-parser/online/
When I try to run the code generator says "Invalid inline schema defined in allOf in 'Cat'. Per the OpenApi spec, for this case when a composed schema defines a discriminator, the allOf schemas must use $ref. Change this inline definition to a $ref definition"

Link to the stack trace (when run via Maven):
https://gist.github.com/MarcMil/557bee99da5dc4af38086c1f6088c6d2

##### openapi-generator version

5.0.0 Beta
##### OpenAPI declaration file content or url
Here the OpenAPI schema which _does not work_:
https://gist.github.com/MarcMil/4a78e766e755be073018111a67abae0f

This _works_, because there is a field "foo" in each subclass:
https://gist.github.com/MarcMil/707bc45824a8ee69daf93d6af0dc091d

##### Command line used for generation

java -jar openapi-generator-cli.jar  generate -g java -i "OpenAPI.json" 

Leads to:
```
Exception in thread "main" java.lang.RuntimeException: Could not process model 'Animal'.Please make sure that your schema is correct!
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:475)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:850)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:432)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.RuntimeException: Invalid inline schema defined in allOf in 'Cat'. Per the OpenApi spec, for this case when a composed schema defines a discriminator, the allOf schemas must use $ref. Change this inline definition to a $ref definition
	at org.openapitools.codegen.DefaultCodegen.getAllOfDescendants(DefaultCodegen.java:2794)
	at org.openapitools.codegen.DefaultCodegen.createDiscriminator(DefaultCodegen.java:2851)
	at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:2229)
	at org.openapitools.codegen.languages.AbstractJavaCodegen.fromModel(AbstractJavaCodegen.java:1017)
	at org.openapitools.codegen.languages.JavaClientCodegen.fromModel(JavaClientCodegen.java:723)
	at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1127)
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:470)
	... 4 more
```

##### Steps to reproduce
Try to read in the OpenAPI declaration file already breaks. Interestingly, validate works: "No validation issues detected."

##### Related issues/PRs

Unknown

##### Suggest a fix

Link to the stack trace:
https://gist.github.com/MarcMil/557bee99da5dc4af38086c1f6088c6d2

**Comment by ArtyMaury** [comment]
I'm having the same issue with version 4.3.1.

Have you found a fix that doesn't mean adding a false property to the subclasses ?

**Comment by bmiddleb** [comment]
This has been a bug for over a year. Why hasn't it been fixed?

**Comment by ArtyMaury** [comment]
sadly, after several unresolved issues on the "official" openapi generator I've turned to [oazapfts](https://github.com/cellular/oazapfts) which is very fast, well maintained and doesn't need a jvm.

**Comment by amakhrov** [comment]
Isn't it a duplicate of https://github.com/OpenAPITools/openapi-generator/issues/7262 ? If so, it has been fixed in v5
