### ISSUE TITLE
[BUG] generator cannot handle cross referenced schema $ref 

### ISSUE THREAD

**Issue by dynofu** [OpenAPITools/openapi-generator#7254]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?

- [ ] What's the actual output vs expected output?
there should be no warning/error like this 
```
o.o.codegen.utils.ModelUtils - Failed to get the schema name: ./schemas/Pet.yaml#/Pet

Exception in thread "main" java.lang.RuntimeException: Could not process model 'Pet'.Please make sure that your schema is correct!
```
see more detail below.

- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

the repro is in the https://github.com/dyno/openapi-ref-issue

cross referenced schema reports error in code generator, (`make generate-client`)
but shows no problem in swagger-ui-watcher.

##### openapi-generator version

```
docker run openapitools/openapi-generator-cli        --version
openapi-generator-cli 5.0.0-SNAPSHOT
  commit : 0cb4c43
  built  : 2020-08-04T04:27:51Z
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/
```

##### OpenAPI declaration file content or url

https://github.com/dyno/openapi-ref-issue

https://github.com/dyno/openapi-ref-issue/blob/master/openapi.yaml
```
openapi.yaml
schemas/
├── Cat.yaml
├── Dog.yaml
└── Pet.yaml
```

##### Generation Details

make generate-client

##### Steps to reproduce

as above.

```
[main] INFO  o.o.c.languages.AbstractJavaCodegen - Invoker Package Name, originally not set, is now derived from api package name: openapi.internal
[main] INFO  o.o.c.languages.AbstractJavaCodegen - Processing operation null
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: ./schemas/Pet.yaml#/Pet
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: ./schemas/Pet.yaml#/Pet
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: ./schemas/Pet.yaml#/Pet
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: ./schemas/Pet.yaml#/Pet
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: ./schemas/Pet.yaml#/Pet
Exception in thread "main" java.lang.RuntimeException: Could not process model 'Pet'.Please make sure that your schema is correct!
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:475)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:850)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:432)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException
        at org.openapitools.codegen.DefaultCodegen.getAllOfDescendants(DefaultCodegen.java:2817)
        at org.openapitools.codegen.DefaultCodegen.createDiscriminator(DefaultCodegen.java:2871)
        at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:2232)
        at org.openapitools.codegen.languages.AbstractJavaCodegen.fromModel(AbstractJavaCodegen.java:1018)
        at org.openapitools.codegen.languages.JavaClientCodegen.fromModel(JavaClientCodegen.java:717)
        at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1127)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:470)
        ... 4 more
```

**Comment by dyno** [comment]
swagger-cli also think it's valid

```
swagger-cli validate openapi.yaml
openapi.yaml is valid
```
