### ISSUE TITLE
[BUG] Failed to generate bin/configs/python-blueplanet.yaml

### ISSUE THREAD

**Issue by jirikuncar** [OpenAPITools/openapi-generator#7283]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] ~Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?~
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Running `./bin/generate-samples.sh bin/configs/python-blueplanet.yaml` is failing with:

```
[pool-1-thread-4] Generation failed for python-blueplanet: (RuntimeException) Could not generate model 'ApiResponse'
java.lang.RuntimeException: Could not generate model 'ApiResponse'
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:520)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:852)
        at org.openapitools.codegen.cmd.GenerateBatch$GenerationRunner.run(GenerateBatch.java:212)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.nio.file.NoSuchFileException: ~/src/OpenAPITools/openapi-generator/samples/server/petstore/python-blueplanet/model-definitions/types/tosca/openapi_server/ApiResponse_ResourceType.tosca
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
        at java.base/java.nio.file.Files.write(Files.java:3491)
        at org.openapitools.codegen.TemplateManager.writeToFileRaw(TemplateManager.java:227)
        at org.openapitools.codegen.TemplateManager.writeToFile(TemplateManager.java:209)
        at org.openapitools.codegen.TemplateManager.writeToFile(TemplateManager.java:171)
        at org.openapitools.codegen.TemplateManager.write(TemplateManager.java:149)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:916)
        at org.openapitools.codegen.DefaultGenerator.generateModelDocumentation(DefaultGenerator.java:358)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:517)
        ... 5 more
```

##### openapi-generator version

`openapi-generator-project 5.0.0-SNAPSHOT`

##### OpenAPI declaration file content or url

```
generatorName: python-blueplanet
outputDir: samples/server/petstore/python-blueplanet
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/python-blueplanet
```

##### Steps to reproduce

```console
$  mvn -DskipTests clean package
$ ./bin/generate-samples.sh bin/configs/python-blueplanet.yaml
```

##### Suggest a fix

```console
$ git rm -f bin/configs/python-blueplanet.yaml
```

**Comment by wing328** [comment]
it's working fine for me:
```
$ ./bin/generate-samples.sh ./bin/configs/python-blueplanet.yaml 
# START SCRIPT: ./bin/generate-samples.sh
This script generates all configs under bin/configs by default.
You may generate a targeted script or set of scripts using glob patterns.

For example:
    ./bin/generate-samples.sh bin/configs/java-*

You may generate a single config with additional options if you use -- to
separate the single config file from the generator arguments.

For example:
    ./bin/generate-samples.sh bin/configs/java-vertx.yaml -- --global-property debugModels=true


[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: python-blueplanet (server)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'python-blueplanet' is considered stable.
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] INFO  o.o.c.l.AbstractPythonConnexionServerCodegen - Environment variable PYTHON_POST_PROCESS_FILE not defined so the Python code may not be properly formatted. To define it, try 'export PYTHON_POST_PROCESS_FILE="/usr/local/bin/yapf -i"' (Linux/Mac)
[main] INFO  o.o.c.l.AbstractPythonConnexionServerCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] WARN  o.o.c.l.AbstractPythonConnexionServerCodegen - Path '/pet/{petId}' is not consistant with Python variable names. It will be replaced by '/pet/{pet_id}'
[main] WARN  o.o.c.l.AbstractPythonConnexionServerCodegen - Parameter name 'petId' is not consistant with Python variable names. It will be replaced by 'pet_id'
[main] WARN  o.o.c.l.AbstractPythonConnexionServerCodegen - Parameter name 'petId' is not consistant with Python variable names. It will be replaced by 'pet_id'
[main] WARN  o.o.c.l.AbstractPythonConnexionServerCodegen - Parameter name 'petId' is not consistant with Python variable names. It will be replaced by 'pet_id'
[main] WARN  o.o.c.l.AbstractPythonConnexionServerCodegen - Path '/pet/{petId}/uploadImage' is not consistant with Python variable names. It will be replaced by '/pet/{pet_id}/uploadImage'
[main] WARN  o.o.c.l.AbstractPythonConnexionServerCodegen - Parameter name 'petId' is not consistant with Python variable names. It will be replaced by 'pet_id'
[main] WARN  o.o.c.l.AbstractPythonConnexionServerCodegen - Path '/store/order/{orderId}' is not consistant with Python variable names. It will be replaced by '/store/order/{order_id}'
[main] WARN  o.o.c.l.AbstractPythonConnexionServerCodegen - Parameter name 'orderId' is not consistant with Python variable names. It will be replaced by 'order_id'
[main] WARN  o.o.c.l.AbstractPythonConnexionServerCodegen - Parameter name 'orderId' is not consistant with Python variable names. It will be replaced by 'order_id'
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/models/api_response.py
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.ApiResponse/low.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.ApiResponse/create.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.ApiResponse/high.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/model-definitions/types/tosca/openapi_server/ApiResponse_ResourceType.tosca
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/models/category.py
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.Category/low.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.Category/create.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.Category/high.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/model-definitions/types/tosca/openapi_server/Category_ResourceType.tosca
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/models/order.py
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.Order/low.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.Order/create.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.Order/high.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/model-definitions/types/tosca/openapi_server/Order_ResourceType.tosca
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/models/pet.py
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.Pet/low.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.Pet/create.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.Pet/high.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/model-definitions/types/tosca/openapi_server/Pet_ResourceType.tosca
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/models/tag.py
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.Tag/low.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.Tag/create.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.Tag/high.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/model-definitions/types/tosca/openapi_server/Tag_ResourceType.tosca
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/models/user.py
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.User/low.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.User/create.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/model-definitions/types/ddui-views/openapi_server.resourceTypes.User/high.json (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/model-definitions/types/tosca/openapi_server/User_ResourceType.tosca
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.DefaultCodegen - Multiple MediaTypes found, using only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/controllers/pet_controller.py
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/app/openapi_server/test/test_pet_controller.py (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/controllers/store_controller.py
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/app/openapi_server/test/test_store_controller.py (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/controllers/user_controller.py
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/app/openapi_server/test/test_user_controller.py (Test files never overwrite an existing file of the same name.)
[main] INFO  o.o.c.l.AbstractPythonConnexionServerCodegen - Path '/pet/{pet_id}' is not consistant with the original OpenAPI definition. It will be replaced back by '/pet/{petId}'
[main] INFO  o.o.c.l.AbstractPythonConnexionServerCodegen - Reverting name of parameter 'pet_id' of operation 'get_pet_by_id' back to 'petId'
[main] INFO  o.o.c.l.AbstractPythonConnexionServerCodegen - Reverting name of parameter 'pet_id' of operation 'update_pet_with_form' back to 'petId'
[main] INFO  o.o.c.l.AbstractPythonConnexionServerCodegen - Reverting name of parameter 'pet_id' of operation 'delete_pet' back to 'petId'
[main] INFO  o.o.c.l.AbstractPythonConnexionServerCodegen - Path '/pet/{pet_id}/uploadImage' is not consistant with the original OpenAPI definition. It will be replaced back by '/pet/{petId}/uploadImage'
[main] INFO  o.o.c.l.AbstractPythonConnexionServerCodegen - Reverting name of parameter 'pet_id' of operation 'upload_file' back to 'petId'
[main] INFO  o.o.c.l.AbstractPythonConnexionServerCodegen - Path '/store/order/{order_id}' is not consistant with the original OpenAPI definition. It will be replaced back by '/store/order/{orderId}'
[main] INFO  o.o.c.l.AbstractPythonConnexionServerCodegen - Reverting name of parameter 'order_id' of operation 'get_order_by_id' back to 'orderId'
[main] INFO  o.o.c.l.AbstractPythonConnexionServerCodegen - Reverting name of parameter 'order_id' of operation 'delete_order' back to 'orderId'
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/Makefile
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/README.md
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/requirements.txt
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/Dockerfile
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/.dockerignore
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/.gitignore
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/README.md
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/requirements.txt
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/setup.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/tox.ini
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/test-requirements.txt
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/__init__.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/__main__.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/encoder.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/util.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/typing_utils.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/controllers/__init__.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/models/__init__.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/models/base_model_.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/test/__init__.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/swagger/swagger.yaml
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/solution/fig.yml
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/Makefile
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/README.md
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/requirements.txt
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/Dockerfile
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/.dockerignore
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/.gitignore
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/README.md
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/requirements.txt
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/setup.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/tox.ini
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/test-requirements.txt
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/__init__.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/__main__.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/encoder.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/util.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/typing_utils.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/controllers/__init__.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/models/__init__.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/models/base_model_.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/test/__init__.py
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/app/openapi_server/swagger/swagger.yaml
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/solution/fig.yml
[main] INFO  o.o.codegen.TemplateManager - Skipped samples/server/petstore/python-blueplanet/.openapi-generator-ignore (Skipped by supportingFiles options supplied by user.)
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/.openapi-generator/VERSION
[main] INFO  o.o.codegen.TemplateManager - writing file samples/server/petstore/python-blueplanet/.openapi-generator/FILES
```

**Comment by wing328** [comment]
Let us know if you still need help on this.

**Comment by jirikuncar** [comment]
@wing328 I have few updates. It works now if I run the `./bin/generate-samples.sh bin/configs/python-blueplanet.yaml` but it fails for `./bin/generate-samples.sh bin/configs/python-*.yaml`

```
[pool-1-thread-4] Generation failed for python-blueplanet: (RuntimeException) Could not generate model 'ApiResponse'
java.lang.RuntimeException: Could not generate model 'ApiResponse'
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:520)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:852)
        at org.openapitools.codegen.cmd.GenerateBatch$GenerationRunner.run(GenerateBatch.java:212)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.nio.file.NoSuchFileException: ~/src/OpenAPITools/openapi-generator/samples/server/petstore/python-blueplanet/model-definitions/types/tosca/openapi_server/ApiResponse_ResourceType.tosca
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
        at java.base/java.nio.file.Files.write(Files.java:3491)
        at org.openapitools.codegen.TemplateManager.writeToFileRaw(TemplateManager.java:227)
        at org.openapitools.codegen.TemplateManager.writeToFile(TemplateManager.java:209)
        at org.openapitools.codegen.TemplateManager.writeToFile(TemplateManager.java:171)
        at org.openapitools.codegen.TemplateManager.write(TemplateManager.java:149)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:916)
        at org.openapitools.codegen.DefaultGenerator.generateModelDocumentation(DefaultGenerator.java:358)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:517)
        ... 5 more
```

**Comment by wing328** [comment]
No luck repeating the issue.

Can you try recloning the repo (https://github.com/OpenAPITools/openapi-generator) or try it in another machine?

**Comment by jirikuncar** [comment]
I have a workaround:

```console
$ docker build -t og .
$  docker run -it --rm -v $(pwd):/opt/openapi-generator og ./bin/generate-samples.sh bin/configs/python-*.yaml
```
but still no success on macOS directly with 
```
openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
```
