### ISSUE TITLE
[Slim] Security samples script fails

### ISSUE THREAD

**Issue by ybelenko** [OpenAPITools/openapi-generator#734]
##### Description

Following instruction for every PR I've noticed that I cannot generate security samples anymore.

##### openapi-generator version

3.2.0-SNAPSHOT

##### OpenAPI declaration file content or url

[petstore-security-test.yaml](../blob/master/modules/openapi-generator/src/test/resources/2_0/petstore-security-test.yaml)

##### Command line used for generation

```shell
$ bin/security/php-slim-server-petstore.sh
```

##### Steps to reproduce
```shell
$ bin/security/php-slim-server-petstore.sh
# START SCRIPT: bin/security/php-slim-server-petstore.sh
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with 
the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec 
(CLI).
 | Error count: 1, Warning count: 1
Errors:
        -attribute paths.'/fake'(put).descriptions is unexpected
Warnings:
        -Unused model: Return

        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:541)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:323)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:59)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
```

**Comment by wing328** [comment]
@ybelenko thanks for reporting the issue. I've filed @739 to fix it.
