### ISSUE TITLE
[BUG][CLI] crash when evaluating definitions without parameters

### ISSUE THREAD

**Issue by codymikol** [OpenAPITools/openapi-generator#7453]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When you provide openapi-generator an openapi definition that includes a url with path variables, but no defined parameters, it will throw a null pointer exception. 

```
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.HashSet.<init>(HashSet.java:120)
        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:464)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:507)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:423)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
```

##### openapi-generator version

5.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

https://github.com/codymikol/openapi-generator-kotlin-bug-demo/blob/master/generated-openapi-spec.json

##### Generation Details

This seems to happen regardless of generator-name, and the only other CLI options I am providing are the input-spec and output.

##### Steps to reproduce

I have created a minimal repro repository over [here](https://github.com/codymikol/openapi-generator-kotlin-bug-demo)
this includes a shell script with all of the exact steps that I took. The generated openapi spec is hardcoded in the repo, but I have also included a minimal Spring project that generates the spec via springfox 3 if you'd like to generate that yourself.

Note that the script uses the latest published openapi-generator and will need some tweaking to point at your own build. I have tested with both and they have the same result

##### Related issues/PRs

I did a search, but found nothing similar.

##### Suggest a fix

I plan on looking into this myself, this is mostly to help document the issue in case I end up not having enough time. Any suggestions would be great.

**Comment by codymikol** [comment]
I'll leave this for my findings while digging into this

It looks like when this is evaluated, the result.messages property is null and this is what causes the NPE.

```java
SwaggerParseResult result = new OpenAPIParser().readLocation(inputSpec, authorizationValues, options);
```

**Comment by codymikol** [comment]
The root cause of this issue seems to come from swagger-parser. It will return null for messages and throw a NPE. I think what we can do is add some decent error handling for when this kind of error does occur.

**Comment by codymikol** [comment]
I have added a PR that will not fix this, but will make it much more obvious what has gone wrong.
