### ISSUE TITLE
OpenAPI file wrongly interpreted as json

### ISSUE THREAD

**Issue by aarondl** [OpenAPITools/openapi-generator#7488]
##### Description

I was writing an openapi schema in yaml and when I tried to use path templating suddenly it was giving me json parsing errors. It's worth noting that I get two of the exact same error consecutively for a single run of the `generate` command.

```
[main] ERROR i.s.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"openapi: '3.0.0'
info:
  version: 0.0.1
  title: API

servers:
  - url: http://localhost:3000/api/v1

paths:
  /projects/{id}:
    get:
      operationId: projectList
      tags: [projects]
      responses:
        '200':
          description: OK
"; line: 1, column: 8]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:722)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2868)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1914)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:773)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:210)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
	at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:94)
	at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:42)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:89)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:510)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:560)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:424)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

##### openapi-generator version

Present in both 4.3.1 and 5.0.0-beta2 docker images.

##### OpenAPI declaration file content or url

```yaml
openapi: '3.0.0'
info:
  version: 0.0.1
  title: API

servers:
  - url: http://localhost:3000/api/v1

paths:
  /projects/{id}:
    get:
      operationId: projectList
      tags: [projects]
      responses:
        '200':
          description: OK
```

##### Command line used for generation

Note: There are some docker paths in there, but they're correct because if I remove path templating I can generate files.

```bash
      generate \
        --global-property color=true \
        --additional-properties typescriptThreePlus=true \
        --additional-properties supportsES6=true \
        --generator-name typescript-fetch \
        --input-spec /gen/openapi.yaml \
        --output /gen/ts
```

##### Steps to reproduce

1. Run 5.0.0-beta2 docker image with the above command line options and openapi.yaml file.
2. Remove the `/{id}` from the `/projects` path to see that it generates fine without it.

##### Related issues/PRs

I looked but couldn't find anything. I also looked for a flag to force json or yaml, and that doesn't appear either.

##### Suggest a fix/enhancement

I think there should be a flag that can force a filetype if the generator is going to rely on some sort of regexp/heuristic to determine a filetype

**Comment by wing328** [comment]
Also adding a proper path parameter `id` fixes the issue as well.

```
openapi: 3.0.0
info:
  version: 0.0.1
  title: API
servers:
  - url: http://localhost:3000/api/v1
paths:
  '/projects/{id}':
    get:
      parameters:
        - name: id
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      operationId: projectList
      tags:
       - projects
      responses:
        '200':
          description: OK
```

**Comment by aarondl** [comment]
@wing328 this is actually true. I can't believe it given the error I was receiving but not having the parameters defined was the problem. For anyone else looking at this issue the other changes that wing made to the yaml file (quotes around the path, tags as a bulleted list vs inline array etc) are not a factor.

**Comment by aarondl** [comment]
Oh and thanks wing! This unblocks my entire side project :D
