### ISSUE TITLE
Unable to get local issuer exception

### ISSUE THREAD

**Issue by deeptowncitizen** [OpenAPITools/openapi-generator#7629]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

I'm using `@openapitools/openapi-generator-cli@2.0.3` to generate the code from the openapi spec.
Originally, my code worked with `1.0.18-4.3.1` and I was using the command line e.g.
```
yarn run openapi-generator generate -i /app/schema.json -g typescript-fetch -o /app/output -t /app/templates
```

After the migration to 2.x I had to modify the command line to
```
yarn run openapi-generator-cli generate -i /app/schema.json -g typescript-fetch -o /app/output -t /app/templates
```
and the output for this call is:
```
(node:48032) UnhandledPromiseRejectionWarning: Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
(node:48032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:48032) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm behind the corporate firewall and I did not expect to have any calls made by the openapi generator. What are they for and can I turn them off?

##### openapi-generator version
2.0.3

**Comment by sluglit** [comment]
I am experiencing the same problem with a slight difference.
Our build servers have no internet access and we rely on a local NPM repository which serves dependencies.

**Comment by wetgi** [comment]
I have the same problem and already tested version 2.1.10 and 2.1.5.

```
Unable to query repository, because of: "connect ECONNREFUSED 54.164.121.222:443"

Response:
(node:28513) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'headers' of undefined
    at VersionManagerService.printResponseError (/usr/local/lib/node_modules/@openapitools/openapi-generator-cli/main.js:884:43)
    at CatchSubscriber.httpService.get.pipe.Object [as selector] (/usr/local/lib/node_modules/@openapitools/openapi-generator-cli/main.js:797:18)
    at CatchSubscriber.error (/usr/local/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/internal/operators/catchError.js:46:31)
    at MapSubscriber.Subscriber._error (/usr/local/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/usr/local/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/usr/local/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/usr/local/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/usr/local/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/usr/local/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/internal/Subscriber.js:72:18)
    at axios.then.catch.err (/usr/local/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/@nestjs/common/http/http.service.js:51:28)
(node:28513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:28513) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by BarthaBRW** [comment]
Is there a solution for this issue?

**Comment by dolanmiu** [comment]
Also having this issue

**Comment by rihabibi** [comment]
I have the same issue, any solutions ?

**Comment by TheRealAstoo** [comment]
Hello guys, I had this issue running tests with `Jest` and a generated client with `typescript-axios`. 

What I found : 

You need to give your jest config (can be in a `jest.config.js` or directly in your `package.json` per exemple) this key value : 

`"testEnvironment": "node"`

I hope it can help some people like it helped me 🤗

**Comment by Yop-Yop** [comment]
Same problem for me here, i am behind a proxy.

**Comment by rdelhommer** [comment]
It might be best to open an issue on https://github.com/OpenAPITools/openapi-generator-cli as this appears to be an issue with the npm wrapper around openapi-generator.

Anyways, I found a workaround for this.  I was able to bypass the issue by manually setting the version in my openapitools.json file. The issue is happening when the npm wrapper tries to query the lastest available version of openapi-generator from maven.  If you've set your version in openapitools.json, it wont run the query and will just download the jar file  corresponding to the version you've chosen

Example
```
"version": "5.2.1"
```

**Comment by tapan-p** [comment]
May be little late but please take a look at my approach below. Not a fix but just a work around while the actual issue gets fixed.
[https://github.com/OpenAPITools/openapi-generator-cli/issues/390#issuecomment-999811893](https://github.com/OpenAPITools/openapi-generator-cli/issues/390#issuecomment-999811893)

**Comment by shayneoneill** [comment]
Does anyone know a solution for this with the python code. I have *no* idea how to debug why its telling me this error because it just doesnt seem to be documented.
