### ISSUE TITLE
[BUG][python-flask] actual operation argument not passed to implementation function

### ISSUE THREAD

**Issue by SteveHespelt** [OpenAPITools/openapi-generator#8168]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists? - NO - I've been using the online code generator at api.openapi-generator.tech/api/gen/servers to create the python-flask server code.
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output? - I would expect the 'additionalMetadata' request body property to be passed as a kwargs argument to the operation's implementation function.
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

While the file property of the request body payload (in the below OpenAPI specification yaml snippet) is properly conveyed from the api client, the additionalMetadata property is not passed as an argument to the operation's implementation function. Stepping through the Connexion code in a debugging session shows me that the actual argument is received from the client and all is good up until the connexion.decorators.parameter.py (lines 101..121) code that builds up the kwargs dictionary that is eventually unpacked as part of the invocation of the operation's implementation function at line 121 (at that point, kwargs is missing the 'additionalMetadata' key that is found within the request_body dictionary that's passed to operation.get_arguments() at line 102.

What I suspect the issue is (& I don't yet know why):  has_kwargs is false, causing connexion.operations.abstract.py's _get_body_arguments() to 
not populate the resulting dictionary with the contents of the body dictionary argument.

Or it's more likely that I'm not doing something correctly as I'm quite new to using the entire openapi-generator ecosystem.
Perhaps my specification is incomplete, thus causing the has_kwargs to be false?

MTIA for any feedback on what I'm doing wrong.

##### openapi-generator version

Using the online generator - downloaded .openapi-generator/VERSION => 5.0.0-beta3

##### OpenAPI declaration file content or url
__most of my OpenAPI yaml is excluded for brevity's sake__
```yaml
     # the POST's 
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/uploadFile'

components:
  schemas: 
    uploadFile:
      type: object
      properties:
        additionalMetadata:
          description: Additional data to pass to server
          type: string
        file:
          description: file to upload
          format: binary
          type: string
```

##### Generation Details

I'm using the online generator at api.openapi-generator.tech, providing the ```"options": { "packageName": "swagger_client", "library": "urllib3" }``` 
^^^ using swagger_client to preserve the naming used when I initially started using Swagger codegen generated code prior to switching to openapi-generator.tech and using the /api/gen/servers/python-flask endpoint.

##### Suggest a fix

I have to assume it's something I've managed to do wrong as this seems like a pretty simple use case and the connexion.operations.openapi.py  OpenAPIOperation._get_body_argument() must be pretty thoroughly verified for such a use case.

**Comment by SteveHespelt** [comment]
additional info: in connexion.py inspect_function_arguments(function):
 The OrderedDict (parameters) has the 'additionalMetadata' named parameter per the spec's requestBody schema, but the arguments to the any() function are missing any instance of p such that p.kind == p.VAR_KEYWORD
```has_kwargs = any(p.kind == p.VAR_KEYWORD for p in parameters.values())```

Is if fair for me to assume that per https://docs.python.org/3/library/inspect.html, the VAR_KEYWORD value for p.kind is a pure python feature & the server stubs should 'play nice' as the generated stubs have named parameters rather than use the **kwargs mechanism?

Or is this a specialized case where a property whose format == binary  AND type == string implies that only 1 File property can be used in a requestBody ?

**Comment by SteveHespelt** [comment]
sorry - a follow-up question:
RE the above uploadFile type, I followed the current Petstore example at [https://github.com/OpenAPITools/openapi-generator/tree/master/samples/openapi3/server/petstore/python-flask/openapi_server/openapi/openapi.yaml](https://github.com/OpenAPITools/openapi-generator/tree/master/samples/openapi3/server/petstore/python-flask/openapi_server/openapi/openapi.yaml), following how the UploadForm is defined.

My question is:  Why does the current online 5.0.0beta3 generator for python-flask create a controller stub that does NOT use the UploadForm type while the sample here [https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/server/petstore/python-flask/openapi_server/controllers/pet_controller.py](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/server/petstore/python-flask/openapi_server/controllers/pet_controller.py) has this form (pun?):
```
def upload_file(pet_id, upload_form=None):  # noqa: E501
    """uploads an image
     # noqa: E501
    :param pet_id: ID of pet to update
    :type pet_id: int
    :param upload_form: 
    :type upload_form: dict | bytes
"""
```
Generated earlier this afternoon using the api.openapi-generator.tech service:
```
def add_ontology_to_repository_new(repo_id, ontology_id, additional_metadata=None, file=None):  # noqa: E501
    """add_ontology_to_repository_new

     # noqa: E501

    :param repo_id: Repository Id - valid format is...
    :type repo_id: str
    :param ontology_id: 
    :type ontology_id: str
    :param additional_metadata: Additional data to pass to server
    :type additional_metadata: str
    :param file: file to upload
    :type file: str

    :rtype: None
    """
    return 'do some magic!'

```
Downloaded at the same time is this openapi.yaml snippet for the above function:
```
  /repo/{repoId}/ontology/{ontologyId}/add:
    post:
      operationId: add_ontology_to_repository_new
      parameters:
      - description: Repository Id - valid format is...
        explode: false
        in: path
        name: repoId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: ontologyId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/uploadFile'
        required: true
```
The uploadFile type defined via:
```
    uploadFile:
      properties:
        additionalMetadata:
          description: Additional data to pass to server
          type: string
        file:
          description: file to upload
          format: binary
          type: string
      type: object

```
removing the required: true property from the requestBody doesn't change the stub's signature.  
Nor does adding the require: [ 'file' ] to the uploadFile: { ... } block. I know, from stepping through with a debugger, that the internals will enforce the required: true status but my comment regards only the stub function's signature being impacted.  
Thanks for taking the time to read this post.

**Comment by SteveHespelt** [comment]
Sometimes going back to square 1 is a good thing to try. Having used the Petstore samples as a guide, decided to go back again. Because I observed that the generated code in my repository_api.py had params_map dictionaries in which the UploadFile type wasn't used but each property (file, additionalMetadata) was a distict param in the map. While the Petstore pet_api.py has params_map with upload_form and root_map['openapi_types'] has the UploadForm type per the spec's YAML. 
Note: I generated the Petstore sample code using the same api.openapi-generator.tech service as I've been doing for my spec.
So my focus is drawn to the obvious physical difference between my spec YAML and that of the Petstore is the structure of the requestBody element - snippets from each specification are below.  Both sets of code generated via a POST to /api/gen/clients/python. I'm using [yaml2json 0.4.0](https://github.com/wakeful/yaml2json) to provide the JSON this POST requires.

Using host api.openapi-generator.tech (most recent stable: 5.0.0-beta3) -> PetApi uses the UploadForm type. Same for api-latest-master host.

But not this site's master branch - its pet_api.py doesn't make use of the UploadForm type. check the Endpoint assigned to the PetApi's upload_file attr.

So changing my spec to use the same pattern ($ref at the content block level) I now get the repository_api.py using the UploadFile type rather than each property in the requestBody.

But when using the generated repository_api.py method that uses the same multipart/form-data content-type for the requestBody, I get a ApiValueError exception raised when the **ApiClient.sanitize_for_serialization** is passed the BufferedReader instance for the UploadFile.file property. I don't see any code in that method to handle a file_type as the Petstore spec & my spec use via the type: string, format: binary properties.
Despite model/upload_form.py showing that UploadForm's file property is of type file_type:
```
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'file': (file_type,),  # noqa: E501
            'additional_metadata': (str,),  # noqa: E501
        }
```
I'm a bit confused.  My next step will be to build, test the Petstore sample app by adding a UploadForm object to the test/test_pet_api.py's test_upload_file function to see what happens...
And then create a minimal spec to reproduce the ApiValueException so I can post that test case here.

My immediate workaround will be to base64 encode the file content's, change the request body to use a str (for the file as a base64 string) rather than a file, not use the multipart mechanism but just straight JSON with 2 properties...
-steve

my app's specification has this snippet:
```
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/uploadFile'
...
 schemas:
    uploadFile:
      type: object
      required:
      - file
      properties:
        additionalMetadata:
          description: Additional data to pass to server
          type: string
        file:
          description: file to upload
          format: binary
          type: string
```
While the Petstore sample (master:openapi/openapi.yaml) has this snippet for the /pet/{petId}/uploadImage POST operation:
```
      requestBody:
        $ref: '#/components/requestBodies/UploadForm'
...
requestBodies:
  UploadForm:
      content:
        multipart/form-data:
          example:
            additionalMetadata: additional metadata example
            file: c29tZSB0ZXN0IGRhdGEK
          schema:
            $ref: '#/components/schemas/UploadForm'
...
schemas:
    UploadForm:
      description: A form for attaching files to a pet
      properties:
        additionalMetadata:
          description: Additional data to pass to server
          type: string
        file:
          description: file to upload
          format: binary
          type: string
      required:
      - file
      title: An upload form
      type: object
```

**Comment by SteveHespelt** [comment]
Using today's Petstore sample [openapi.yaml](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/server/petstore/python-flask/openapi_server/openapi/openapi.yaml), and the api-latest-master.openapi-generator.tech service, using this code in the test/test_pet_api.py (>90% is 'borrowed' from the generated docs/PetApi.md )
```
    def test_upload_file(self):
        """Test case for upload_file

        uploads an image  # noqa: E501
        """
        # Enter a context with an instance of the API client
        with swagger_client.ApiClient(self.configuration) as api_client:
            # Create an instance of the API class
            api_instance = PetApi(api_client)
            pet_id = 1 # int | ID of pet to update
            try:
                upload_form = UploadForm( additional_metadata="additional_metadata_example",
                                          file=open('./capability.owl', 'rb'),   ) # UploadForm |  (optional)
                response = api_instance.upload_file( pet_id, upload_form=upload_form )
            except swagger_client.ApiException as e:
                print("Exception when calling PetApi->upload_file: %s\n" % e)

```
results in this traceback as mentioned earlier
```
======================================================================
ERROR: test_upload_file (__main__.TestPetApi)
Test case for upload_file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_pet_api.py", line 105, in test_upload_file
    response = api_instance.upload_file( pet_id, upload_form=upload_form )
  File "/home/steve/PycharmProjects/test-Petstore/swagger_client/api_client.py", line 763, in __call__
    return self.callable(self, *args, **kwargs)
  File "/home/steve/PycharmProjects/test-Petstore/swagger_client/api/pet_api.py", line 1084, in __upload_file
    return self.call_with_http_info(**kwargs)
  File "/home/steve/PycharmProjects/test-Petstore/swagger_client/api_client.py", line 841, in call_with_http_info
    collection_formats=params['collection_format'])
  File "/home/steve/PycharmProjects/test-Petstore/swagger_client/api_client.py", line 411, in call_api
    _check_type)
  File "/home/steve/PycharmProjects/test-Petstore/swagger_client/api_client.py", line 180, in __call_api
    body = self.sanitize_for_serialization(body)
  File "/home/steve/PycharmProjects/test-Petstore/swagger_client/api_client.py", line 272, in sanitize_for_serialization
    key: cls.sanitize_for_serialization(val) for key, val in model_to_dict(obj, serialize=True).items()
  File "/home/steve/PycharmProjects/test-Petstore/swagger_client/api_client.py", line 272, in <dictcomp>
    key: cls.sanitize_for_serialization(val) for key, val in model_to_dict(obj, serialize=True).items()
  File "/home/steve/PycharmProjects/test-Petstore/swagger_client/api_client.py", line 284, in sanitize_for_serialization
    raise ApiValueError('Unable to prepare type {} for serialization'.format(obj.__class__.__name__))
swagger_client.exceptions.ApiValueError: Unable to prepare type BufferedReader for serialization
```
