### ISSUE TITLE
[BUG] Upgrading to 5.0 beta3 (from beta2) introduced the following error with csharp-netcore generation (net50 not in supported versions)

### ISSUE THREAD

**Issue by HeshamMeneisi** [OpenAPITools/openapi-generator#8207]
```
openapi-generator-cli generate -i $SWAGGER_FILE -g csharp-netcore -o $output -c $configFile --git-repo-id=$GIT_REPO --git-user-id=$GIT_USER \
--additional-properties=packageVersion=$VERSION,packageName=$packageName
```

```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid .NET framework version: net5.0. List of supported versions: netstandard1.3, netstandard1.4, netstandard1.5, netstandard1.6, netstandard2.0, netstandard2.1, netcoreapp2.0, netcoreapp2.1, netcoreapp3.0, netcoreapp3.1, net47
        at org.openapitools.codegen.languages.CSharpNetCoreClientCodegen.processOpts(CSharpNetCoreClientCodegen.java:579)
        at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:250)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:862)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:432)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

```

**Comment by wing328** [comment]
Previously the value is not validated (showing a warning only) and it will default to netstandard2.0 if i'm not mistaken.

**Comment by HeshamMeneisi** [comment]
> Previously the value is not validated (showing a warning only) and it will default to netstandard2.0 if i'm not mistaken.

I figured that it's a new validation added. There's no  "netcoreapp50", "net5.0" and "netstandard3.0" btw the two new entries are "net5.0" and "net5.0-windows".

> NET 5 and .NET Standard
.NET 5 is the implementation of .NET that Microsoft is actively developing. It's a single product with a uniform set of capabilities and APIs that can be used for Windows desktop apps and cross-platform console apps, cloud services, and websites. The .NET 5.0 TFMs reflect this broad range of scenarios:
net5.0
This TFM is for code that runs everywhere. With a few exceptions, it includes only technologies that work cross-platform. For .NET 5 code, net5.0 replaces both netcoreapp and netstandard TFMs.
net5.0-windows
This is an example of OS-specific TFMs that add OS-specific functionality to everything that net5.0 refers to.


And it's required to target net50 for C# 9 features:

> For existing code that targets netstandard, there's no need to change the TFM to net5.0. .NET 5.0 implements .NET Standard 2.1 and earlier. The only reason to retarget from .NET Standard to .NET 5.0 would be to gain access to more runtime features, language features, or APIs. For example, in order to use C# 9, you need to target .NET 5.0. You can multitarget .NET 5.0 and .NET Standard to get access to newer features and still have your library available to other .NET implementations.


Source: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by HeshamMeneisi** [comment]
I can help implement this if you point me to the right bit of code.

**Comment by wing328** [comment]
I think https://github.com/OpenAPITools/openapi-generator/blob/61777b4a7c0987ff923d02e7f1250bb6695e76dd/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java#L889-L911 is a good starting point.

**Comment by HeshamMeneisi** [comment]
> it will default to netstandard2.0 if i'm not mistaken.

I just checked a package generated by beta2 and it had correctly set `<TargetFramework>net5.0</TargetFramework>` on the csproj file and the built Nuget package.

**Comment by HeshamMeneisi** [comment]
> I think
> 
> https://github.com/OpenAPITools/openapi-generator/blob/61777b4a7c0987ff923d02e7f1250bb6695e76dd/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java#L889-L911
> 
> is a good starting point.

Ok, will give it a shot soon.

**Comment by wing328** [comment]
PM via Slack if you need help: https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM
