### ISSUE TITLE
[BUG] openapi-generator-maven-plugin version 5.0.0 does not work for OpenApi 3.0 yml-files

### ISSUE THREAD

**Issue by frochi42** [OpenAPITools/openapi-generator#8260]
##### Description
I have a perfect OpenApi 3.0.1 yml-file. openapi-generator-maven-plugin v4.3.1 generates perfect code.
When changing the plugin version from 4.3.1 to 5.0.0 I get a syntax error. No other changes.

[INFO]
[INFO] --- openapi-generator-maven-plugin:5.0.0:generate (api) @ core-automation ---
[ERROR] failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (StringReader); line: 1, column: 8]

##### openapi-generator version

5.0.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: my Title
  description: Documentation of my REST APIs.
  ...
```

##### Generation Details

mvn install

##### Steps to reproduce

mvn install

##### Related issues/PRs

N/A

##### Suggest a fix

???

**Comment by skalinkin** [comment]
I have the same issue. 
the test project is here 
https://github.com/skalinkin/openapi-generator-maven-plugin-test

**Comment by paulmchugh777** [comment]
I have the same problem.

The YAML file works fine with versions 4.3.1 and 5.0.0-beta3 but gives the following exception when using the released 5.0.0 version.

com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')

YAML file starts as shown below:

openapi: 3.0.0
info:
  title: Administration Configuration API
  description: This is the Administration Configuration API
  version: 0.0.1

**Comment by selliera** [comment]
I have the exact same problem with openapi-generator-cli 5.0.0:
A command that worked with 4.3.1:
`java -jar openapi-generator-cli-4.3.1.jar  generate -g openapi -o dir -i my.yaml -c my_config.json`
Now, with:
`java -jar openapi-generator-cli-5.0.0.jar  generate -g openapi -o dir -i my.yaml -c my_config.json`
it fails with the error show above: it looks like it tries to parse the yaml as json.

Looks like an issue with swagger-parser:
`    Due to the too"[truncated 18719 chars]; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1917)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:773)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:210)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
	at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:94)
	at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:42)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:89)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:518)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:568)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:424)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
`

**Comment by selliera** [comment]
Oh, it looks like this issue is related to #8266
At least it is the case for me: I do have relative urls in "server", and using full urls lets the build work.

**Comment by frochi42** [comment]
I can confirm that the relative url in "servers" is also the root cause for my problem. Giving it an absolute URL works.
However, we need relative URL's....
#8266 is also still open...

**Comment by wing328** [comment]
I tested the latest master with https://raw.githubusercontent.com/skalinkin/openapi-generator-maven-plugin-test/main/src/main/resources/api.yaml provided by @skalinkin  in https://github.com/skalinkin/openapi-generator-maven-plugin-test.

Please give it another try with the latest master and share the spec that can still reproduce the issue.

**Comment by stephanpelikan** [comment]
We had the same issue with the URL

> /api/admin/v1

It worked for builds on a Linux machine but failed for builds on a Windows machine.

We changed the URL to 

> http://localhost/api/admin/v1

and now it works.

Two major questions:

1. Why there is no proper error message instead of **Unrecognized token 'openapi'**?
2. Can the documentation be updated since there is no hint that "absolute URL" is different for Linux and Windows.

From the documentation:
> url 	string 	REQUIRED. A URL to the target host. This URL supports Server Variables and MAY be relative, to indicate that the host location is relative to the location where the OpenAPI document is being served. Variable substitutions will be made when a variable is named in {brackets}.

**Comment by maarten-daalder-isaac** [comment]
Hi @stephanpelikan, regarding 1, the code assumes that if there is an error that it isn't a YAML file and then tries the JSON variant. Which fails due to `openapi` not being `{` or other valid JSON token.

Regarding 2, once the upstream library is fixed and the plugin is updated the problem should go away. See also the comment by @wing328 above yours.

**Comment by Mikhail2048** [comment]
@wing328 I have used the very recent version available on maven central, which is 2.4.29, [see here](https://repo.maven.apache.org/maven2/io/swagger/swagger-codegen-maven-plugin/), and the problem still exists. It is clearly a bug, why would plugin try to parse yaml as a json file in case of an error. 

It is strange, because at very least the extension of the file (such as yaml or yml) can give the plugin a relatively clear view that this file should not be treated as json, but as YAML file
