### ISSUE TITLE
[BUG] [Java Resttemplate] Incorrect handling of free form query parameters

### ISSUE THREAD

**Issue by gspatace** [OpenAPITools/openapi-generator#8352]
**Description:**
Currently, when using free form query parameters, the URI is not built correctly.

**Steps to reproduce:**
_Input spec file:_
```
openapi: 3.0.0
info:
  title: test
  version: 0.0.1
servers: 
  - url: "http://localhost"
paths:
  /some/endpoint: 
    get: 
      parameters: 
        - in: "query"
          name: "fixed"
          schema: 
            type: "string"
        - in: "query"
          name: "free-form"
          schema:
            type: "object"
          style: "form"
      responses: 
        200:
          description: "test"
```
_Command to generate client files:_
`java -jar modules\openapi-generator-cli\target\openapi-generator-cli.jar generate -i spec.yml -o work -g java --library resttemplate
`

_Client code ( usage of generated API ):_
```
        ApiClient apiClient = new ApiClient();
        DefaultApi defaultApi = new DefaultApi(apiClient);
        Map<String, Object> freeFormQueryParams = new HashMap<>();
        freeFormQueryParams.put("this", "first");
        freeFormQueryParams.put("that", "second");
        freeFormQueryParams.put("other", "third");
        defaultApi.someEndpointGet("fixedValue", freeFormQueryParams);
```

**Expected result of URI built for the endpoint:**
http://localhost/some/endpoint?fixed=fixedValue&this=first&that=second&other=third

**Actual result:**
http://localhost/some/endpoint?fixed=fixedValue&free-form=%7Bthat%3Dsecond%2C+other%3Dthird%2C+this%3Dfirst%7D

Tested with master as of today.

I've added a patch that addresses this, I'll open a PR soon, too.

[free-form-params.txt](https://github.com/OpenAPITools/openapi-generator/files/5775958/free-form-params.txt)

**Comment by RomainPruvostMHH** [comment]
Hello,
I get exactly the same problem with the generator "webclient". With the same fix purposed by @gspatace in the mustache file https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache, it works well.

To explain my problem a little :
I have a openapi v3 definition :
```json
"/documents/search": {
			"get": {
				"operationId": "searchByParameters",
				"parameters": [
					{
						"name": "family",
						"in": "query",
						"required": true,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "metadata",
						"in": "query",
						"schema": {
							"type": "object",
							"additionalProperties": {
								"type": "string"
							}
						},
						"style": "form",
						"explode": true
					}
				]
```

The generated java code is : 
```
Flux<Document> searchByParameters(String family, Map<String, String> metadata)
```

And when I test my code with a unit test :
```java
        @Test
	void testSearchByParameters() throws Exception {
		final Map<String, String> params = new HashMap<>();
		params.put("id", "400824298");
		params.put("label", "Description");

		StepVerifier.create(documentsApi.searchByParameters("myFamily", params))
				.expectNextMatches(result -> result instanceof Document && result.getMetaData()
						.equals(params))
				.verifyComplete();
	}
```

I get the error below :
`
        java.lang.IllegalArgumentException: Map has no value for 'id=400824298, label=Description'
	at org.springframework.web.util.UriComponents$MapTemplateVariables.getValue(UriComponents.java:345)
	at org.springframework.web.util.HierarchicalUriComponents$QueryUriTemplateVariables.getValue(HierarchicalUriComponents.java:1058)
	at org.springframework.web.util.UriComponents.expandUriComponent(UriComponents.java:262)
	at org.springframework.web.util.HierarchicalUriComponents.lambda$expandQueryParams$5(HierarchicalUriComponents.java:450)
	at java.base/java.util.Map.forEach(Map.java:661)
	at org.springframework.web.util.HierarchicalUriComponents.expandQueryParams(HierarchicalUriComponents.java:446)
	at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:435)
	at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:52)
	at org.springframework.web.util.UriComponents.expand(UriComponents.java:161)
	at org.springframework.web.util.DefaultUriBuilderFactory$DefaultUriBuilder.build(DefaultUriBuilderFactory.java:384)
	at org.springframework.web.util.DefaultUriBuilderFactory.expand(DefaultUriBuilderFactory.java:148)
	at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.uri(DefaultWebClient.java:182)
	at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.uri(DefaultWebClient.java:151)
	at fr.si2m.pulse.api.client.document.util.ApiClient.prepareRequest(ApiClient.java:543)
`

And with the fix, the call is done perfectly with my list of exploded query params :
GET /documents/search?family=myFamily&id=400824298&label=Description

Hope this help you to fix it.
Kind regards,

**Comment by wing328** [comment]
Thanks for the fix by @RomainPruvostMHH 

@gspatace, can you please give it a try with the latest master?

**Comment by gspatace** [comment]
@wing328 Yes, sure, I'll test this on latest master, but by looking at the changes - it should work -  they are exactly what I suggested initially in https://github.com/OpenAPITools/openapi-generator/pull/8353 . I'll decline that PR once I've confirmed.

**Comment by gspatace** [comment]
@wing328 it works as expected.
