### ISSUE TITLE
[BUG][Python] Adding custom model template with Python generator throws exception

### ISSUE THREAD

**Issue by phemmer** [OpenAPITools/openapi-generator#8420]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When adding a custom model template with the Python generator, an exception is thrown.

##### openapi-generator version

5.0.0

##### OpenAPI declaration file content or url

```yaml
# api.yaml
openapi: 3.0.3
info:
  title: API
  description: API
  version: 1.0.0
servers:
  - url: 'https://localhost:80'
paths: {}
components:
  schemas:
    Test:
      type: object
```

##### Generation Details

Following the instructions from https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md:

```yaml
# config.yaml
templateDir: templates
files:
  model-stub.mustache:
    templateType: Model
    destinationFilename: .pyi
```
```
$ java -jar openapi-generator-cli-5.0.0.jar generate -g python -c config.yaml -i api.yaml -o gen/
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] WARN  o.o.c.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: python (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'python' is considered experimental.
[main] INFO  o.o.c.l.PythonLegacyClientCodegen - Environment variable PYTHON_POST_PROCESS_FILE not defined so the Python code may not be properly formatted. To define it, try 'export PYTHON_POST_PROCESS_FILE="/usr/local/bin/yapf -i"' (Linux/Mac)
[main] INFO  o.o.c.l.PythonLegacyClientCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.c.languages.PythonClientCodegen - generateAliasAsModel is hard coded to true in this generator. Alias models will only be generated if they contain validations or enums
Exception in thread "main" java.lang.IllegalStateException: Duplicate key SupportingFile[templateFile='__init__model.mustache', folder='openapi_client/models', destinationFilename='__init__.py', canOverwrite=true]
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1254)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.openapitools.codegen.DefaultGenerator.processUserDefinedTemplates(DefaultGenerator.java:941)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:869)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:432)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

##### Steps to reproduce

1. Create the above `api.yaml`.
2. Create the above `config.yaml`.
3. Create an empty `templates` directory.
4. Run the above `generate` command.

##### Expected result

Should create a `gen/openapi_client/model/test.pyi` file according to `templates/model-stub.mustache`.

##### Suggest a fix

It would appear that the use of `templateType: model` is causing the generator to add `__init__model.mustache` to the file list multiple times. There does not appear to be a way to prevent this.  
As I am not redefining or providing a template for `__init__model.mustache`, it should not be trying to add it again.

**Comment by spacether** [comment]
So I am also unable to get this working:
Spec file (ensures the model is written)
```
# api.yaml
openapi: 3.0.3
info:
  title: API
  description: API
  version: 1.0.0
servers:
  - url: 'https://localhost:80'
paths:
  /pathA:
    post:
      operationId: pathA
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Test'
        required: true
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
components:
  schemas:
    Test:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      # Both properties are required
      required:
        - id
        - name
```
Config file:
```
templateDir: templates_python
files:
    model_new.mustache:
    templateType: Model
    destinationFilename: Model.py
```
This did not work for python or Java

**Comment by DavideFarina96** [comment]
Version: `openapi-generator-cli 5.0.1-SNAPSHOT` (using the provided docker container)

I am facing the same issue. The code gets generated correctly with the default configurations, but it throws an error when using the following config file:
```
templateDir: /local/generated_code/openapi_server
files:
  controller.mustache:
    templateType: API
    destinationFilename: .py
```

Error:
```
[main] WARN  o.o.codegen.DefaultCodegen - Empty operationId found for path: PUT /_node-configs/{ncgroup}/{ncid}/_udata. Renamed to auto-generated operationId: _node_configsNcgroupNcidUdataPUT
Exception in thread "main" java.lang.IllegalStateException: Duplicate key SupportingFile[templateFile='__init__.mustache', folder='openapi_server/controllers', destinationFilename='__init__.py', canOverwrite=true]
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
        at java.util.HashMap.merge(HashMap.java:1253)
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.openapitools.codegen.DefaultGenerator.processUserDefinedTemplates(DefaultGenerator.java:942)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:870)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:432)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

**Comment by DavideFarina96** [comment]
One workaround to use the templates is the following:
- Get the default template files you want to use
- Modify them to suit your needs
- Put these templates (only the modified ones is enough) in a `templates` folder (any name will work)
- When generating the code, instead of passing the configuration defining the `templateDir`, pass the path to the directory with the `-t` parameter. For example, in my case (using the docker container), this looks like this:
```
docker-entrypoint.sh generate \
-i /local/GitLab_repos/SnapshotDatabase/snapshot-api/fs_api.yaml \
-g python-flask \
-t /local/templates/ \
-o /local/fs_api_gen
```

This workaround lets you use the templates you want, bypassing the issue which arises when using the config file to define where to get the templates from

**Comment by phemmer** [comment]
Note that only works when you want to modify/replace the existing template. The use case I had that triggered this issue was generating a separate file.
