### ISSUE TITLE
[PYTHON-FLASK] Problem posting with x-www-form-urlencoded

### ISSUE THREAD

**Issue by MartinDelille** [OpenAPITools/openapi-generator#8571]
##### Description

My python flask server is crashing when posting url encoded post parameter.

##### openapi-generator version

5.0.0

##### OpenAPI declaration file content or url

```yaml
---
openapi: 3.0.3
servers:
  - url: 'https://my.api.com'
info:
  version: 1.0
  title: A test API
paths:
  /login:
    post:
      operationId: login
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
                $ref: '#/components/schemas/LogInInfo'
      responses:
        '200':
          description: Login successfull
components:
  schemas:
    LogInInfo:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
```

##### Command line used for generation

```
openapi-generator generate -g python-flask -i api.yaml
```

##### Steps to reproduce

1. Generate the flask server
2. Run it with `python -m openapi_server`
3. Make a post request on the path `/login`
4. See the crash log:

```
$ python -m openapi_server
The swagger_ui directory could not be found.
    Please install connexion with extra install: pip install connexion[swagger-ui]
    or provide the path to your local installation by passing swagger_path=<your path>

The swagger_ui directory could not be found.
    Please install connexion with extra install: pip install connexion[swagger-ui]
    or provide the path to your local installation by passing swagger_path=<your path>

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
[2021-01-28 20:05:12,933] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/validation.py", line 184, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
TypeError: login() missing 2 required positional arguments: 'email' and 'password'
127.0.0.1 - - [28/Jan/2021 20:05:12] "POST /login HTTP/1.1" 500 -
```

##### Related issues/PRs

Not that I know.

##### Suggest a fix/enhancement

I manage to fix it by replacing the `openapi_server/controllers/default_controller.py` code:

```python
import connexion
import six

from openapi_server import util


def login(email, password):  # noqa: E501
    """login

     # noqa: E501

    :param email: 
    :type email: str
    :param password: 
    :type password: str

    :rtype: None
    """
    return
```

With:

```python
import connexion
import six

from openapi_server import util


def login(**kwargs):  # noqa: E501
    email = kwargs["body"]["email"]
    password = kwargs["body"]["password"]
    """login

     # noqa: E501

    :param email: 
    :type email: str
    :param password: 
    :type password: str

    :rtype: None
    """
    return
```

Any idea what is going wrong ?

**Comment by MartinDelille** [comment]
Maybe the python technical comitee can explain me what I'm doing wrong her? cc @taxpon @frol @mbohlool @cbornet @kenjones-cisco @tomplus @Jyhess @arun-nalla @spacether

**Comment by demonday** [comment]
Just ran into this issue myself, so looks like its still around.
