### ISSUE TITLE
[BUG] Error generating python client from OpenAPI spec

### ISSUE THREAD

**Issue by rpgoldman** [OpenAPITools/openapi-generator#8663]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Trying to generate a Python client from an OpenAPI spec (which, unfortunately, I cannot share), I get this error stacktrace:

```
  Exception: Cannot invoke "io.swagger.v3.oas.models.media.Schema.getType()" because "schema" is null
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1145)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1036)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:561)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:878)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:432)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException: Cannot invoke "io.swagger.v3.oas.models.media.Schema.getType()" because "schema" is null
	at org.openapitools.codegen.utils.ModelUtils.isObjectSchema(ModelUtils.java:437)
	at org.openapitools.codegen.languages.PythonClientCodegen.getObjectExample(PythonClientCodegen.java:845)
	at org.openapitools.codegen.languages.PythonClientCodegen.setParameterExampleValue(PythonClientCodegen.java:1212)
	at org.openapitools.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:4438)
	at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:3847)
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1113)
	... 6 more
```

When I look at the output directory, it contains only three subdirectories, `docs` `registry_client` and `test` and no files at all.  The `registry_client` contains only the `model` subdirectory, so presumably the error happened before the code for invoking the API could be generated.

I am willing to work to get a MWE, but I need some help figuring out how to focus on the relevant part of my spec.

Note that this same specification is processed successfully (well, with some minor hiccups from `anyOf` processing) with the `python-legacy` generator).

Tested with swagger editor and it passed, with 3 warnings, which seem irrelevant:

1. Use of `Accept` header, which will be ignored.
2. Two schemas that are never referenced.

##### Notes of possible interest

In the transcript I see:

```
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
```

I'm afraid without a line number reference, I couldn't decipher the above.

There are many lines like this:

```
[main] WARN  o.o.c.l.PythonLegacyClientCodegen - Type null not handled properly in toExampleValue
```

There's this, which I'm afraid I also don't understand:

```
[main] WARN  o.o.codegen.DefaultCodegen - More than one inline schema specified in allOf:. Only the first one is recognized. All others are ignored.
```

The last several lines, presumably the ones leading up to the error are these:
```
[main] WARN  o.o.c.languages.PythonClientCodegen - #/components/parameters/offset is not defined
[main] WARN  o.o.c.languages.PythonClientCodegen - #/components/parameters/offset is not defined
[main] WARN  o.o.c.languages.PythonClientCodegen - #/components/parameters/offset is not defined
[main] WARN  o.o.c.languages.PythonClientCodegen - #/components/parameters/offset is not defined
[main] WARN  o.o.c.languages.PythonClientCodegen - #/components/parameters/offset is not defined
[main] WARN  o.o.c.languages.PythonClientCodegen - #/components/parameters/offset is not defined
```

##### openapi-generator version

```
openapi-generator-cli 5.0.0
  commit : d7d5e53
  built  : 2020-12-21T05:39:41Z
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/
```

##### Generation Details

```
openapi-generator generate -vv --generator-name python --package-name registry_client -o /tmp/registry-client --input-spec squid-registry-v4-openapi.yaml > /tmp/openapi-generator-transcript.txt
```

##### Related issues/PRs

None obviously jumped out at me.

**Comment by wing328** [comment]
Can you try openapi-generator 5.0.1? I saw a fix or two related to how examples are handled in the python client generator.

**Comment by rpgoldman** [comment]
@wing328 I just tried 5.0.1, and I'm afraid I got the same error -- 

```
Exception: Cannot invoke "io.swagger.v3.oas.models.media.Schema.getType()" because "schema" is null
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1146)
```

It would be lovely if the code generator was to try to print some information about where it is in processing the input specification when this happens.

I will see if I can somehow bisect this big and proprietary API spec and find where it's going awry to generate an MWE.

**Comment by qlan2** [comment]
The error message looks slightly different for us.
` Exception: Cannot invoke "io.swagger.v3.oas.models.media.Schema.getType()" because "schema" is null
        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1146)
        at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1037)
        at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:561)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:879)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:432)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException: Cannot invoke "io.swagger.v3.oas.models.media.Schema.getType()" because "schema" is null
        at org.openapitools.codegen.utils.ModelUtils.isBinarySchema(ModelUtils.java:647)
        at org.openapitools.codegen.utils.ModelUtils.isFileSchema(ModelUtils.java:659)
        at org.openapitools.codegen.languages.AbstractTypeScriptClientCodegen.getTypeDeclaration(AbstractTypeScriptClientCodegen.java:423)
        at org.openapitools.codegen.languages.TypeScriptAxiosClientCodegen.addAdditionPropertiesToCodeGenModel(TypeScriptAxiosClientCodegen.java:176)
        at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:2530)
        at org.openapitools.codegen.DefaultCodegen.handleMethodResponse(DefaultCodegen.java:3569)
        at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:3693)
        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1114)
        ... 6 more
`
The same OpenAPI definition works fine when generating Java client, but failed for typescript-fetch and typescript-axios.

**Comment by spacether** [comment]
Hi there, can you provide a sample spec for this issue? We won't be able to fix it without a way to reproduce it. Thank  you for the report!

**Comment by bancsdani** [comment]
Hi @spacether,
with this yaml you can reproduce the issue:
https://github.com/alpacahq/bkdocs/blob/master/assets/openapi.yaml

**Comment by bancsdani** [comment]
Hi @spacether,
When the Python generator is generating examples, sometimes it returns null for schemas, I added checks for null in PythonClientCodegen.java(in getObjectExample() and in exampleFromStringOrArraySchema()):
`if (schema == null) {
            return null;
        }`
but this is just a workaround probably.

**Comment by rtician** [comment]
Hi @spacether, were you able to reproduce the problem? Or a possible solution?

**Comment by allanlewis** [comment]
I can reproduce this with v5.3.1 and this schema: https://smartcat.com/api/methods/v1/swagger.json
I've attached the specific schema at time of writing in case it changes: [swagger.txt](https://github.com/OpenAPITools/openapi-generator/files/7906091/swagger.txt)
(I used a `.txt` extension because Github doesn't allow uploading `.json` files for some reason.)

**Comment by spacether** [comment]
@bancsdani I just tried this out with v5.3.1 master branch commit 8b3cad0692b6c58f827c0a9b35f1ad733547504b 
And the samples were able to be generated with your spec:
`
generate -i modules/openapi-generator/src/test/resources/3_0/spec_breaks_gen.yaml -g python -o samples/openapi3/client/petstore/python_spec_breaks_gen --additional-properties packageName=petstore_api,recursionLimit=1234
`

**Comment by spacether** [comment]
@allanlewis for your spec I am seeing these errors:
```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 6, Warning count: 11
Errors: 
	-attribute components.schemas.Schema name NetRateModel+TMRangeRateModel doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
	-attribute components.schemas.Schema name IAsyncEnumerable<ProjectModel> doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
	-attribute components.schemas.Schema name ModelWithFiles<IReadOnlyList`1> doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
	-attribute components.schemas.Schema name AssignExecutivesRequestModel+Executive doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
	-attribute components.schemas.Schema name ModelWithFiles<CreateProjectModel> doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
	-attribute components.schemas.Schema name ModelWithFiles<UploadDocumentPropertiesModel> doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
Warnings: 
	-attribute components.schemas.Schema name NetRateModel+TMRangeRateModel doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
	-attribute components.schemas.Schema name IAsyncEnumerable<ProjectModel> doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
	-attribute components.schemas.Schema name ModelWithFiles<IReadOnlyList`1> doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
	-attribute components.schemas.Schema name AssignExecutivesRequestModel+Executive doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
	-attribute components.schemas.Schema name ModelWithFiles<CreateProjectModel> doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$
	-attribute components.schemas.Schema name ModelWithFiles<UploadDocumentPropertiesModel> doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:556)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:583)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:433)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```
When I pass in `--skip-validate-spec` I get many errors centered around example generation including:
```
[main] ERROR o.o.codegen.DefaultCodegen - Error in generating `example` for the property SchemaForRequestBodyApplicationJsonPatchjson. Default to ERROR_TO_EXAMPLE_VALUE. Enable debugging for more info.
[main] ERROR o.o.codegen.DefaultCodegen - Error in generating `example` for the property SchemaForRequestBodyApplicationJsonPatchjson. Default to ERROR_TO_EXAMPLE_VALUE. Enable debugging for more info.
[main] ERROR o.o.codegen.DefaultCodegen - Error in generating `example` for the property SchemaForRequestBodyApplicationJson. Default to ERROR_TO_EXAMPLE_VALUE. Enable debugging for more info.
[main] ERROR o.o.codegen.DefaultCodegen - Error in generating `example` for the property SchemaForRequestBodyApplicationJson. Default to ERROR_TO_EXAMPLE_VALUE. Enable debugging for more info.
[main] ERROR o.o.codegen.DefaultCodegen - Error in generating `example` for the property SchemaForRequestBodyTextJson. Default to ERROR_TO_EXAMPLE_VALUE. Enable debugging for more info.
[main] ERROR o.o.codegen.DefaultCodegen - Error in generating `example` for the property SchemaForRequestBodyTextJson. Default to ERROR_TO_EXAMPLE_VALUE. Enable debugging for more info.
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: class Tag {
    name: Document
    description: null
    externalDocs: null
}
  Operation: null
  Resource: post /api/integration/v1/document/assign
...
  Exception: null
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1159)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1053)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:549)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:891)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException
	at org.openapitools.codegen.utils.ModelUtils.isObjectSchema(ModelUtils.java:452)
	at org.openapitools.codegen.languages.PythonClientCodegen.getObjectExample(PythonClientCodegen.java:968)
	at org.openapitools.codegen.languages.PythonClientCodegen.exampleFromStringOrArraySchema(PythonClientCodegen.java:1385)
	at org.openapitools.codegen.languages.PythonClientCodegen.exampleForObjectModel(PythonClientCodegen.java:1359)
	at org.openapitools.codegen.languages.PythonClientCodegen.toExampleValueRecursive(PythonClientCodegen.java:1291)
	at org.openapitools.codegen.languages.PythonClientCodegen.toExampleValueRecursive(PythonClientCodegen.java:1117)
	at org.openapitools.codegen.languages.PythonClientCodegen.toExampleValue(PythonClientCodegen.java:1012)
	at org.openapitools.codegen.languages.PythonClientCodegen.setParameterExampleValue(PythonClientCodegen.java:1462)
	at org.openapitools.codegen.DefaultCodegen.fromRequestBody(DefaultCodegen.java:6850)
	at org.openapitools.codegen.languages.PythonClientCodegen.fromRequestBody(PythonClientCodegen.java:504)
	at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:4092)
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1127)
	... 6 more
```

**Comment by spacether** [comment]
@allanlewis your bug is happening because you have a + in your reference `#/components/schemas/AssignExecutivesRequestModel+Executive` and ModelUtils.getSimpleRef returns `AssignExecutivesRequestModel Executive`
this is a problem that will probably happen for all generators when given your input spec because getSimpleRef is widely used in our code base.
This line in getSimpleRef `ref = URLDecoder.decode(ref, "UTF-8")` changes the + to a space
And it was added in this PR: https://github.com/OpenAPITools/openapi-generator/pull/7191/files

**Comment by allanlewis** [comment]
Thanks for looking into this, @spacether 🙏 

I'll pass on your feedback to the maintainers of that spec.

**Comment by spacether** [comment]
No longer applies. If it does, please re open it with a sample spec
