### ISSUE TITLE
[BUG] openapi-generator for k6 fails to generate a k6 client when OpenAPI 4XX, 5XX error statuses are present in a response

### ISSUE THREAD

**Issue by cdimascio** [OpenAPITools/openapi-generator#9045]
##### Description

When generating a k6 client from ann OpenAPI spec. If a response schema includes e.g. `4XX` the generator fails

Expected: The generator properly handles `4XX`, `5XX`, etc and properly genrates a client 

To reproduce:

Run the k6 generator
```shell
openapi-generator-cli generate --generator-name k6 --input-spec /path/to/myapi.yml --output generated --skip-validate-spec
```

Ensure the response includes e.g. `4XX` in the response schema e.g.

```yaml
        4XX:
          description: client
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
```

The k6 client code gen fails

```shell
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - Output directory (/Users/cdimasci/amazongit/PharmacyPricingPePrServiceLoadTestK6/generated) does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: k6 (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'k6' is considered beta.
[main] WARN  o.o.codegen.DefaultCodegen - The value (generator's option) must be either boolean or string. Default to `false`.
Exception in thread "main" java.lang.NumberFormatException: For input string: "4XX"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at org.openapitools.codegen.languages.K6ClientCodegen.preprocessOpenAPI(K6ClientCodegen.java:322)
        at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:251)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:864)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:440)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

##### openapi-generator version

```
> openapi-generator-cli version
5.1.0
```

##### OpenAPI declaration file content or url

<!-- if it is a bug, a json or yaml that produces it.
The generator is unable to handle `4XX` and `5XX` statuses

```yaml
        4XX:
          description: client
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

##### Generation Details
see above

##### Steps to reproduce

see above

**Comment by wing328** [comment]
@cdimascio thanks for reporting the issue.

cc @mostafa

**Comment by simskij** [comment]
@wing328, mostafa has since moved on to other projects, so feel free to set me as the code owner for the k6 code generator. 👍🏼  I'll have a look as soon as time allows. Thank you @cdimascio for making us aware of the issue!

**Comment by yndo97** [comment]
@simskij hey! any updates on this?

**Comment by mostafa** [comment]
@yndo97 

@simskij moved to another company and I'd be happy to see and review contributions, as I won't be able to fix it. I'll notify k6 people about this, though.
