### ISSUE TITLE
[BUG][ruby] required properties referencing a oneOf schema break generation

### ISSUE THREAD

**Issue by jfeltesse-mdsol** [OpenAPITools/openapi-generator#9191]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

It looks like https://github.com/OpenAPITools/openapi-generator/pull/8040 broke the ruby client generator when required properties point to a oneOf schema.

##### openapi-generator version

master @ acedd1cfba

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: oneOf repro
  version: v1
paths:
  '/hello':
    post:
      operationId: hello.post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [greeting]
              properties:
                greeting:
                  $ref: '#/components/schemas/Greeting'
      responses:
        '204':
          description: returns a greeting

components:
  schemas:
    Greeting:
      oneOf:
        - type: string
        - type: object
```

##### Generation Details

```
openapi-generator generate -i oneof_broken.yaml -g ruby --library faraday -o out/ruby_oneof
```

##### Steps to reproduce

1. run the command above by passing the openapi file yet above
2. generation fails with
   ```
   Exception in thread "main" java.lang.RuntimeException: Could not generate api file for 'Default'
   	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:675)
   	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:878)
   	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:440)
   	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
   	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
   Caused by: java.lang.NullPointerException
   	at org.openapitools.codegen.languages.RubyClientCodegen.constructExampleCode(RubyClientCodegen.java:736)
   	at org.openapitools.codegen.languages.RubyClientCodegen.constructExampleCode(RubyClientCodegen.java:751)
   	at org.openapitools.codegen.languages.RubyClientCodegen.constructExampleCode(RubyClientCodegen.java:726)
   	at org.openapitools.codegen.languages.RubyClientCodegen.constructExampleCode(RubyClientCodegen.java:759)
   	at org.openapitools.codegen.languages.RubyClientCodegen.constructExampleCode(RubyClientCodegen.java:664)
   	at org.openapitools.codegen.languages.RubyClientCodegen.postProcessOperationsWithModels(RubyClientCodegen.java:588)
   	at org.openapitools.codegen.DefaultGenerator.processOperations(DefaultGenerator.java:1194)
   	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:580)
   ```
3. comment out the `required: [greeting]` line
4. generation works

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/8040

##### Suggest a fix

unsure, sorry.

@zippolyte @jirikuncar @wing328

**Comment by jirikuncar** [comment]
It looks like it is related to the fact that the oneOf models do not have a type alias with a name.
