### ISSUE TITLE
[BUG] Error while generating code for any language on specification using $ref to other local files

### ISSUE THREAD

**Issue by emilianozublena** [OpenAPITools/openapi-generator#9298]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I'm working on a specification for a given service. As some of the schemas & paths could be re-used elsewhere, i've defined them on separate yaml files and referenced everything through the usage of $refs.
So far the EDITOR is working, i'm seeing the generated docs from the spec just fine, but whenever i try to generate code from any given language i get the same error.
```
[main] WARN  io.swagger.v3.parser.OpenAPIV3Parser - Exception while resolving:
java.lang.NullPointerException: Cannot invoke "io.swagger.v3.parser.util.OpenAPIDeserializer$ParseResult.missing(String, String)" because "result" is null
	at io.swagger.v3.parser.util.OpenAPIDeserializer.getSchema(OpenAPIDeserializer.java:2324)
	at io.swagger.v3.parser.util.OpenAPIDeserializer.getSchema(OpenAPIDeserializer.java:2349)
	at io.swagger.v3.parser.ResolverCache.loadRef(ResolverCache.java:152)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefToExternalSchema(ExternalRefProcessor.java:75)
	at io.swagger.v3.parser.processors.SchemaProcessor.processReferenceSchema(SchemaProcessor.java:214)
	at io.swagger.v3.parser.processors.SchemaProcessor.processSchema(SchemaProcessor.java:37)
	at io.swagger.v3.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:52)
	at io.swagger.v3.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:67)
	at io.swagger.v3.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:84)
	at io.swagger.v3.parser.OpenAPIResolver.resolve(OpenAPIResolver.java:49)
	at io.swagger.v3.parser.OpenAPIV3Parser.resolve(OpenAPIV3Parser.java:175)
	at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:154)
	at io.swagger.v3.parser.OpenAPIV3Parser.readLocation(OpenAPIV3Parser.java:89)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:518)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:568)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:424)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: ./Schemas/Responses.yaml#/components/schemas/BaseResponse
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: ./Schemas/Responses.yaml#/components/schemas/BaseResponse
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: ./Schemas/Errors.yaml#/components/schemas/UnauthorizedException
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: ./Schemas/Errors.yaml#/components/schemas/UnauthorizedException
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 0
Errors: 
	-Cannot invoke "io.swagger.v3.parser.util.OpenAPIDeserializer$ParseResult.missing(String, String)" because "result" is null

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:541)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:568)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:424)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```
If i remove all the references and place everything under 1 single file, then it works as expected

##### openapi-generator version

5.0.1

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: Integrations Service API
  description: >-
    Integrations Service API
  contact: {}
  version: '1.0'
servers:
- url: http://localhost:5000/api/v1
  variables: {}
paths:
  /onboarding/orders-guides/manual:
    $ref: './Paths/Onboarding/OrdersGuidesManual.yaml'
  /onboarding/invoices/manual:
    $ref: './Paths/Onboarding/InvoicesManual.yaml'
  /onboarding/operators/manual:
    $ref: './Paths/Onboarding/OperatorsManual.yaml'
  /onboarding/catalog/manual:
    $ref: './Paths/Onboarding/CatalogManual.yaml'
  /onboarding/{onboardingID}:
    $ref: './Paths/Onboarding/OnboardingById.yaml'
  /orders/{orderID}/send/email:
    $ref: './Paths/Onboarding/OrdersSendActions.yaml'

```

##### Generation Details

openapi-generator generate -i IntegrationsAPI.yaml -g php -o ./src

**Comment by enekonieto** [comment]
I had problems too using subfolders. Try putting all YAML files in the same folder.

**Comment by emilianozublena** [comment]
We solved it, it was another thing (don't remember from the top of my head) but we didn't need to place everything under same folder.
Error's thrown by generators are kinda useless, you gotta dig through the spec, change, generate, change, generate, until you find something meaningful to fix.
Thx though!
