### ISSUE TITLE
[BUG] Running openapi-generator-cli under NPM gets following error: 'Unable to query repository, because of: "getaddrinfo ENOTFOUND 8080"'

### ISSUE THREAD

**Issue by ThomasSL** [OpenAPITools/openapi-generator#9343]
After installing openapi-generator-cli on NPM we get the following error when trying to run it:
'Unable to query repository, because of: "getaddrinfo ENOTFOUND 8080"'

Version: @openapitools/openapi-generator-cli@2.2.6

Full stack-trace:
Unable to query repository, because of: "getaddrinfo ENOTFOUND 8080"

Response:
C:\Users\oebothst\AppData\Roaming\npm\node_modules\@openapitools\openapi-generator-cli\main.js:912
            Object.entries(error.response.headers).forEach(a => this.logger.log(...a));
                                          ^

TypeError: Cannot read property 'headers' of undefined
    at VersionManagerService.printResponseError (C:\Users\oebothst\AppData\Roaming\npm\node_modules\@openapitools\openapi-generator-cli\main.js:912:43)
    at CatchSubscriber.selector (C:\Users\oebothst\AppData\Roaming\npm\node_modules\@openapitools\openapi-generator-cli\main.js:820:18)
    at CatchSubscriber.error (C:\Users\oebothst\AppData\Roaming\npm\node_modules\@openapitools\openapi-generator-cli\node_modules\rxjs\internal\operators\catchError.js:46:31)
    at MapSubscriber.Subscriber._error (C:\Users\oebothst\AppData\Roaming\npm\node_modules\@openapitools\openapi-generator-cli\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (C:\Users\oebothst\AppData\Roaming\npm\node_modules\@openapitools\openapi-generator-cli\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (C:\Users\oebothst\AppData\Roaming\npm\node_modules\@openapitools\openapi-generator-cli\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (C:\Users\oebothst\AppData\Roaming\npm\node_modules\@openapitools\openapi-generator-cli\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (C:\Users\oebothst\AppData\Roaming\npm\node_modules\@openapitools\openapi-generator-cli\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (C:\Users\oebothst\AppData\Roaming\npm\node_modules\@openapitools\openapi-generator-cli\node_modules\rxjs\internal\Subscriber.js:72:18)
    at C:\Users\oebothst\AppData\Roaming\npm\node_modules\@openapitools\openapi-generator-cli\node_modules\@nestjs\common\http\http.service.js:51:28

**Comment by ThomasSL** [comment]
We found the reason for the error now.

Our environment variables for HTTPS_PROXY did not start with the protocol (eg. "https://"). Fixing this made the openapi-generator-cli run as expected.
