### ISSUE TITLE
[BUG] 504 error downloading openapi-generator-cli

### ISSUE THREAD

**Issue by robertmassaioli** [OpenAPITools/openapi-generator#9349]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I get the following output from my builds and running locally:

``` bash
$ yarn gen-fetch
yarn run v1.22.10
$ openapi-generator-cli generate -i ../openapi.yaml -g typescript-fetch -o src/reminders-client
Unable to query repository, because of: "Request failed with status code 504"

Response:
server awselb/2.0
date Tue, 27 Apr 2021 04:27:08 GMT
content-type text/html
content-length 132
connection close

(node:19114) UnhandledPromiseRejectionWarning: TypeError: error.response.data.on is not a function
    at VersionManagerService.printResponseError (/Users/rmassaioli/Code/my-reminders/frontend/node_modules/@openapitools/openapi-generator-cli/main.js:914:33)
    at CatchSubscriber.selector (/Users/rmassaioli/Code/my-reminders/frontend/node_modules/@openapitools/openapi-generator-cli/main.js:820:18)
    at CatchSubscriber.error (/Users/rmassaioli/Code/my-reminders/frontend/node_modules/rxjs/internal/operators/catchError.js:46:31)
    at MapSubscriber.Subscriber._error (/Users/rmassaioli/Code/my-reminders/frontend/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/Users/rmassaioli/Code/my-reminders/frontend/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/Users/rmassaioli/Code/my-reminders/frontend/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/Users/rmassaioli/Code/my-reminders/frontend/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/Users/rmassaioli/Code/my-reminders/frontend/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/Users/rmassaioli/Code/my-reminders/frontend/node_modules/rxjs/internal/Subscriber.js:72:18)
    at /Users/rmassaioli/Code/my-reminders/frontend/node_modules/@nestjs/common/http/http.service.js:51:28
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:19114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 62.60s.
$
```

##### openapi-generator version

According to my yarn.lock:

```
"@openapitools/openapi-generator-cli@^2.0.0":
  version "2.2.5"
  resolved "https://registry.yarnpkg.com/@openapitools/openapi-generator-cli/-/openapi-generator-cli-2.2.5.tgz#363611ae37d21fabf15ed297dfd5fe82a013faba"
  integrity sha512-8eTiw9U5PWYZx41RDIrJ6iZ4XCteD6ljupbJS6/ichZEUwa1Pv78y14QSLVfky+1KpJsq/RlqrgjnPm6yMHo6g==
  dependencies:
    "@nestjs/common" "7.6.15"
    "@nestjs/core" "7.6.15"
    "@nuxtjs/opencollective" "0.3.2"
    chalk "4.1.0"
    commander "6.2.1"
    compare-versions "3.6.0"
    concurrently "5.3.0"
    console.table "0.10.0"
    fs-extra "9.1.0"
    glob "7.1.6"
    inquirer "7.3.3"
    lodash "4.17.21"
    reflect-metadata "0.1.13"
    rxjs "6.6.7"
    tslib "1.13.0"
```

##### Generation Details

You should be able to run a similar command to the one to reproduce it.

##### Steps to reproduce

You should be able to run a similar command to the one to reproduce it.

##### Related issues/PRs

I could not find any similar issues. It was not happening yesterday. The last time that I modified this yarn.lock file according to my git history was the 6th of Apr:

```
commit 47635fe72671eccfeb0e36c44506adc2c734ddd6
Author: Renovate Bot <renovate@whitesourcesoftware.com>
Date:   Tue Apr 6 10:35:11 2021 +0000

    Update dependency @openapitools/openapi-generator-cli to v2

:100644 100644 7eb2ccf d4068f3 M        frontend/package.json
:100644 100644 5c6f0b5 a327f47 M        frontend/yarn.lock
```

##### Suggest a fix

Looks like something is wrong in AWS land.

**Comment by robertmassaioli** [comment]
This issue may have resolved itself without me doing anything:

```
$ yarn gen-fetch  
yarn run v1.22.10
$ openapi-generator-cli generate -i ../openapi.yaml -g typescript-fetch -o src/reminders-client
Download 5.1.0 ...
Downloaded 5.1.0
Did set selected version to 5.1.0
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: typescript-fetch (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'typescript-fetch' is considered stable.
[main] INFO  o.o.c.l.AbstractTypeScriptClientCodegen - Hint: Environment variable 'TS_POST_PROCESS_FILE' (optional) not defined. E.g. to format the source code, please try 'export TS_POST_PROCESS_FILE="/usr/local/bin/prettier --write"' (Linux/Mac)
[main] INFO  o.o.c.l.AbstractTypeScriptClientCodegen - Note: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.codegen.DefaultGenerator - Model ReminderResponseList not generated since it's an alias to array (without property) and `generateAliasAsModel` is set to false (default)
[main] INFO  o.o.codegen.TemplateManager - writing file /Users/rmassaioli/Code/my-reminders/frontend/src/reminders-client/models/ErrorResponse.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /Users/rmassaioli/Code/my-reminders/frontend/src/reminders-client/models/IssueDetails.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /Users/rmassaioli/Code/my-reminders/frontend/src/reminders-client/models/ReminderIdList.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /Users/rmassaioli/Code/my-reminders/frontend/src/reminders-client/models/ReminderRequest.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /Users/rmassaioli/Code/my-reminders/frontend/src/reminders-client/models/ReminderResponse.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /Users/rmassaioli/Code/my-reminders/frontend/src/reminders-client/apis/IndividualReminderApi.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /Users/rmassaioli/Code/my-reminders/frontend/src/reminders-client/apis/IssueRemindersApi.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /Users/rmassaioli/Code/my-reminders/frontend/src/reminders-client/apis/UserRemindersApi.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /Users/rmassaioli/Code/my-reminders/frontend/src/reminders-client/index.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /Users/rmassaioli/Code/my-reminders/frontend/src/reminders-client/runtime.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /Users/rmassaioli/Code/my-reminders/frontend/src/reminders-client/apis/index.ts
[main] INFO  o.o.codegen.TemplateManager - writing file /Users/rmassaioli/Code/my-reminders/frontend/src/reminders-client/models/index.ts
[main] INFO  o.o.codegen.TemplateManager - Skipped /Users/rmassaioli/Code/my-reminders/frontend/src/reminders-client/.openapi-generator-ignore (Skipped by supportingFiles options supplied by user.)
[main] INFO  o.o.codegen.TemplateManager - writing file /Users/rmassaioli/Code/my-reminders/frontend/src/reminders-client/.openapi-generator/VERSION
[main] INFO  o.o.codegen.TemplateManager - writing file /Users/rmassaioli/Code/my-reminders/frontend/src/reminders-client/.openapi-generator/FILES
################################################################################
# Thanks for using OpenAPI Generator.                                          #
# Please consider donation to help us maintain this project 🙏                 #
# https://opencollective.com/openapi_generator/donate                          #
################################################################################
✨  Done in 13.87s.
$ 
```

**Comment by michelmattos** [comment]
I'm having this same issue right now.

**Comment by robertmassaioli** [comment]
This issue seems to have fixed itself and I have not seen it since.

**Comment by dougkeen** [comment]
This issue still exists due to coupling to `search.maven.org`, and the above issues correlated to outages of that service. 
https://github.com/OpenAPITools/openapi-generator-cli/issues/680
