### ISSUE TITLE
[BUG] Async syntax error

### ISSUE THREAD

**Issue by brunolorente** [OpenAPITools/openapi-generator#9399]
I'm using openapi-generator-cli v3.0.x, code generation process is ok, but in the moment of use the api, i've the following issue:
`blorente@drama-laptop:~/Documentos/repos/openapi/test$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import openapi_client
  File "/home/blorente/Documentos/repos/openapi/test/openapi_client/__init__.py", line 18, in <module>
    from openapi_client.api.default_api import DefaultApi
  File "/home/blorente/Documentos/repos/openapi/test/openapi_client/api/__init__.py", line 6, in <module>
    from openapi_client.api.default_api import DefaultApi
  File "/home/blorente/Documentos/repos/openapi/test/openapi_client/api/default_api.py", line 124
    async=params.get('async'),
    ^
SyntaxError: invalid syntax`

**To Reproduce**
1. Install openapi-generator-cli 3.0.0
2. Make an whatever.yaml file with using openpi:3.0.0
3. Run openapi-generator-cli genrate -i whatever.yaml -g python -o test (also tried with --aadditional-properties=library=asyncio)
4. pip3 install -r requirements.txt
5. pip3 install -e openapi_client
6. Runing a custom and simple script importing the library
7. Run the custom script test.py (not autogenerated) 
8. Crashing
`blorente@drama-laptop:~/Documentos/repos/openapi/test$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import openapi_client
  File "/home/blorente/Documentos/repos/openapi/test/openapi_client/__init__.py", line 18, in <module>
    from openapi_client.api.default_api import DefaultApi
  File "/home/blorente/Documentos/repos/openapi/test/openapi_client/api/__init__.py", line 6, in <module>
    from openapi_client.api.default_api import DefaultApi
  File "/home/blorente/Documentos/repos/openapi/test/openapi_client/api/default_api.py", line 124
    async=params.get('async'),
    ^
SyntaxError: invalid syntax`

**Expected behavior**
I expect to test the generated client api

**OpenAPI Spec File**
https://pastebin.com/D2amPb8P

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version: 3.8
 - openapi-generator-cli version 3.0.0

**Additional context**
I'm learning by myself with openapi generators, so please, be nice :).

**Comment by wing328** [comment]
Which `openapi-generator` version (not CLI) are you using? we just released v5.1.1 so please give it a try.

**Comment by tnielens** [comment]
I confirm v5.1.1 solved the issue for me.
