### ISSUE TITLE
[BUG][typescript][axios] Getting java.lang.OutOfMemoryError when generating apis

### ISSUE THREAD

**Issue by sirmyron** [OpenAPITools/openapi-generator#9432]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I made some minor changes to the schema of my OpenAPI specification and since that I've been getting out of memory error when generating the client code. Here's the error I'm getting:
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOfRange(Arrays.java:3821)
	at java.base/java.lang.StringLatin1.newString(StringLatin1.java:764)
	at java.base/java.lang.StringBuilder.toString(StringBuilder.java:447)
	at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:426)
	at com.fasterxml.jackson.core.io.SegmentedStringWriter.getAndClear(SegmentedStringWriter.java:83)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1011)
	at io.swagger.v3.core.util.Json.pretty(Json.java:24)
	at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:2296)
	at org.openapitools.codegen.DefaultCodegen.handleMethodResponse(DefaultCodegen.java:3623)
	at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:3747)
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1113)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1038)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:561)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:878)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:440)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

Using verbose mode, I see output for a number of my operations then it eventually throws the error above.

I also tried using the CLI jar and specified a high -Xms which made no difference.

##### openapi-generator version

5.1.0 (Mac) and 5.1.1 (CLI jar)

##### OpenAPI declaration file content or url

Swagger generated OpenAPI spec:
https://gist.githubusercontent.com/sirmyron/4d6c961f5d5418e122aa14658ed64634/raw/4b37b1ff6b9fe76696e3a325ccdd0c2ce0fb9b14/api.json

##### Generation Details

I've tried the following commands, using both flat file and url pointing to the swagger specification:

```
openapi-generator generate -g typescript-axios -i http://localhost:8060/core/v3/api-docs -o /app/src/core/api/core --skip-validate-spec --additional-properties=enumPropertyNaming=UPPERCASE,enumNameSuffix=,legacyDiscriminatorBehavior=false,withSeparateModelsAndApi=true,apiPackage=endpoints,modelPackage=models,supportsES6=true
```
```
java -jar -Xms4096M ./openapi-generator-cli.jar generate -i http://localhost:8060/core/v3/api-docs -g typescript-axios --skip-validate-spec --additional-properties enumPropertyNaming=UPPERCASE,enumNameSuffix=,legacyDiscriminatorBehavior=false,withSeparateModelsAndApi=true,apiPackage=endpoints,modelPackage=models,supportsES6=true -o /app/src/core/api/core
```

##### Steps to reproduce

You can try executing any one of the commands above using the open api json file above.

**Comment by wing328** [comment]
@sirmyron thanks for reporting the issue. Have you tried generators other than typescript-axios (e.g. csharp-netcore, java, etc) to see if the issue happens with typescript-axios only?

**Comment by sirmyron** [comment]
@wing328 I did not, however, it turns out that there is a bug in swagger.core that significantly bloated the number of models in our schema. Noticed this after upgrading to spring boot 2.1.3... doesn't happen in 2.1.2. Need to complete investigations to post this bug.

Also, I was able to get this to work by setting -Xmx20G when using the jar. Now that we no longer have the bloated schema, we can run generation as normal.

Is there a way to specify memory heap size when using the cli too installed by Homebrew?

**Comment by ovirta** [comment]
We are also running in to the same out of memory error using [this ](https://gist.github.com/ovirta/456812dfe1542b5c6f9207821ab6f03d) api.json.

Same issue with plain typescript and aspnetcore generators. 

Please have a look at the command and result below.
```
java -jar ./openapi-generator-cli-5.2.1.jar generate -i api.json -g typescript-axios -o ./output --skip-validate-spec
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - Output directory (C:\work\sesu-frontend\apiClientGenerators\sykeWaterData\.\output) does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: typescript-axios (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'typescript-axios' is considered stable.
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] INFO  o.o.c.l.AbstractTypeScriptClientCodegen - Hint: Environment variable 'TS_POST_PROCESS_FILE' (optional) not defined. E.g. to format the source code, please try 'export TS_POST_PROCESS_FILE="/usr/local/bin/prettier --write"' (Linux/Mac)
[main] INFO  o.o.c.l.AbstractTypeScriptClientCodegen - Note: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.lang.AbstractStringBuilder.<init>(Unknown Source)
        at java.lang.StringBuilder.<init>(Unknown Source)
        at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:416)
        at com.fasterxml.jackson.core.io.SegmentedStringWriter.getAndClear(SegmentedStringWriter.java:83)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1011)
        at io.swagger.v3.core.util.Json.pretty(Json.java:24)
        at org.openapitools.codegen.examples.ExampleGenerator.generate(ExampleGenerator.java:159)
        at org.openapitools.codegen.examples.ExampleGenerator.generateFromResponseSchema(ExampleGenerator.java:97)
        at org.openapitools.codegen.examples.ExampleGenerator.generateFromResponseSchema(ExampleGenerator.java:59)
        at org.openapitools.codegen.DefaultCodegen.handleMethodResponse(DefaultCodegen.java:3757)
        at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:3901)
        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1137)
        at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1060)
        at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:561)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:902)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

Appreciate it if there is some insight how to prevent this issue without restructuring  (too much) the original api.json.

**Comment by sirmyron** [comment]
@ovirta you can try specifying how much memory you want used when running the command. Assuming you have 20GB of memory available, you could try the following:

```
java -Xmx20G -jar ./openapi-generator-cli-5.2.1.jar generate -i api.json -g typescript-axios -o ./output --skip-validate-spec
```

**Comment by ovirta** [comment]
> ```
> java -Xmx20G -jar ./openapi-generator-cli-5.2.1.jar generate -i api.json -g typescript-axios -o ./output --skip-validate-spec
> ```

That did indeed the trick. Appreciate the heads up @sirmyron .

**Comment by xseman** [comment]
I'm experiencing same problem, even with `-Xmx30G` (v5.3.0), weirdly it fail at 14GB utilization.

```
Exception in thread "main" java.lang.OutOfMemoryError: UTF16 String size is 1184549945, should be less than 1073741823
    at java.base/java.lang.StringUTF16.newBytesFor(StringUTF16.java:49)
    at java.base/java.lang.AbstractStringBuilder.inflate(AbstractStringBuilder.java:228)
    at java.base/java.lang.AbstractStringBuilder.appendChars(AbstractStringBuilder.java:1680)
    at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:687)
    at java.base/java.lang.StringBuilder.append(StringBuilder.java:228)
    at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:421)
    at com.fasterxml.jackson.core.io.SegmentedStringWriter.getAndClear(SegmentedStringWriter.java:83)
    at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1011)
    at io.swagger.v3.core.util.Json.pretty(Json.java:24)
    at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:2663)
    at org.openapitools.codegen.languages.TypeScriptFetchClientCodegen.fromModel(TypeScriptFetchClientCodegen.java:449)
    at org.openapitools.codegen.languages.TypeScriptFetchClientCodegen.fromModel(TypeScriptFetchClientCodegen.java:37)
    at org.openapitools.codegen.DefaultCodegen.handleMethodResponse(DefaultCodegen.java:3855)
    at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:3986)
    at org.openapitools.codegen.languages.TypeScriptFetchClientCodegen.fromOperation(TypeScriptFetchClientCodegen.java:455)
    at org.openapitools.codegen.languages.TypeScriptFetchClientCodegen.fromOperation(TypeScriptFetchClientCodegen.java:37)
    at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1139)
    at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1062)
    at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:562)
    at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:903)
    at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
    at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
    at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```
