### ISSUE TITLE
 Unrecognized token openapi

### ISSUE THREAD

**Issue by atigm** [OpenAPITools/openapi-generator#9520]
##### Description

I have problem with 3.1.x but 3.0.x works fine.

swagger.yaml
```
openapi: 3.1.0
info:
  description: test API
  title: test
  version: 1.0
servers:
  - url: /
tags:
  - name: examples-rest
    description: API examples
paths:
  /examples:
    get:
      tags:
        - examples-rest
      responses:
        '200':
          description: examples
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/example'
components:
  schemas:
    example:
      type: object
      properties:
        reference:
          type: string
          maxLength: 18
        designation:
          type: string
          maxLength: 69
```

build.gradle
```
...
plugins {
    id 'org.springframework.boot' version '2.3.7.RELEASE'
    id 'io.spring.dependency-management' version '1.0.9.RELEASE'
    id 'java'
    id 'org.openapi.generator' version '5.1.1'
............
}

openApiGenerate {
    generatorName = "java"
    inputSpec = new File("$rootDir/swagger.yaml").toString()
    outputDir = new File("$buildDir/generated/openapi").toString()
    apiPackage = "com.example.controller"
    invokerPackage = "com.example"
    modelPackage = "com.example.model"
    modelNamePrefix = "Api"
    generateApiTests = false
    configOptions = [
            library            : "resttemplate",
            dateLibrary        : "java8-localdatetime",
            booleanGetterPrefix: "is",
            interfaceOnly      : "true"
    ]
}

sourceSets.main.java.srcDirs += "$buildDir/generated/openapi/src/main/java"

compileJava.dependsOn tasks.openApiGenerate

....
wrapper {
    gradleVersion = '6.4.1'
}
```

I have this error when I run 

```
failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"openapi: 3.1.0
info:
  description: test API
  title: test
  version: 1.0
servers:
  - url: /
tags:
  - name: examples-rest
    description: API examples
paths:
  /example:
    get:
      tags:
        - example-rest
      responses:
 "[truncated 4489 chars]; line: 1, column: 8]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:717)
```

```
There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
   | Error count: 2, Warning count: 0
  Errors:
        -attribute openapi is unexpected
        -attribute paths.'/example'(get).responses.200.content is unexpected

```

**Comment by iliuta** [comment]
Hi, I have the same issue since I migrated to 5.x.x version. 
Previously I used the 4.3.1 version.

Now, what I have noticed:
- on Mac and Docker linux it works just fine
- on Windows machines I have the same error. I suspected some encoding problems and tried to play with the file (adding quotes to strings, removing fields, etc) but the error moves in the file ("truncated XXX chars") but nothing to do.
- 4.3.1 works fine on any platform.

**Comment by julianladisch** [comment]
Duplicate of #8260
Duplicate of #8266

**Comment by Stokestack** [comment]
Just encountered this. It's disheartening to see it still present over a year later.
