### ISSUE TITLE
[BUG][Python] deepObject parameter style creates invalid code on 5.0.1 and raises exception on 5.1.1

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [OpenAPITools/openapi-generator#9603]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description
when having a spec with deep objects, the python codegen creates invalid code on generator 5.0.x and fails alltogether on generator 5.1.x

##### openapi-generator version
5.1.1 and 5.0.1

##### OpenAPI declaration file content or url

https://gist.github.com/RonnyPfannschmidt/db157171fa1b99ce90e7c3fb23d3a3cc#file-api-yaml

##### Generation Details/ steps to reproduce
https://gist.github.com/RonnyPfannschmidt/db157171fa1b99ce90e7c3fb23d3a3cc#file-run-with-codegen-5-0-1-log
https://gist.github.com/RonnyPfannschmidt/db157171fa1b99ce90e7c3fb23d3a3cc#file-run-with-codegen-5-1-1-log

##### Suggest a fix

my current workaround is to use 5.1.x templates , the 5.0.x codegen and to post-process the generated files dropping the bad lines
it would be nice if there was a configuration option to set a `deep_object_hook` so users can provide a own serialization/de-serialization for deep_objects

**Comment by spacether** [comment]
How about instead implementing proper serialization/deserialization for deepobject?
Sadly, I don't think that our python generator has kept up with the openpapi options for parameter serialization.

**Comment by RonnyPfannschmidt** [comment]
@spacether it's on the mid term agenda for me, as a starting point I want don't crash at gen time and a option to configure the serializer

We also need the sercer/connexion side at some point

**Comment by spacether** [comment]
Doesn't openapi define what deepobject should do? Do you have a use case where you need to customize how it behaves?

**Comment by RonnyPfannschmidt** [comment]
@spacether deepObject is an utterly painful "standard" left for implementations, there are some non-formal ones for php/ruby, but there is no implementation for python that's standardized, so is not something i will start soon as it will need a good setup to be sane

also i don't want to just put a parser hack into openapi-codegen sincei ts jsut going to be a mess then

**Comment by kevinkirkup** [comment]
Any update on this?

**Comment by spacether** [comment]
No one has written this feature yet. If you want it, please consider writing a PR adding it in
[QueryParameter.__serialize_deep_object](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python-experimental/api_client.handlebars#L483)

**Comment by kevinkirkup** [comment]
I don't mind updating the template, but I don't have an environment to fix the exception being thrown:

```
1  Exception: null
2        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1159)
3        at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1050)
4        at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:549)
5        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:891)
6        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
7        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
8        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
9  Caused by: java.lang.NullPointerException
10        at org.openapitools.codegen.languages.PythonClientCodegen.fromProperty(PythonClientCodegen.java:440)
11        at org.openapitools.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:4752)
12        at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:4113)
13        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1127)
```

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java#L440

**Comment by kevinkirkup** [comment]
May also be related to #11234

**Comment by spacether** [comment]
@kevinkirkup my PR will fix the NPE issue but does not add the deep object serialization

**Comment by bplevin36** [comment]
it's understandable that the generator can't handle `deepObject` serialization, but it should at least provide an escape hatch where the caller can construct the query string themselves
