### ISSUE TITLE
[WebClient not supported in Blazor WebAssembly] System.Net.Requests is not supported on this platform. System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by AhmedKhalil777** [OpenAPITools/openapi-generator#9660]
## Try to support Blazor WASM with generators
- The Restsharp uses the webclient, WebClient cannot be used on the Browser (client-side Blazor) simply because it is relatively old technology, and there is no reason to adapt it to use on the browser.

System.Net.Requests is not supported on this platform.
System.PlatformNotSupportedException
System.Net.Requests is not supported on this platform.
   at System.Net.WebRequest.get_DefaultWebProxy()
   at RestSharp.RestClient.ConfigureHttp(IRestRequest request)
   at RestSharp.RestClient.ExecuteAsync(IRestRequest request, Action`2 callback, String httpMethod, Func`4 getWebRequest)
   at RestSharp.RestClient.ExecuteAsync(IRestRequest request, Action`2 callback, Method httpMethod)
   at RestSharp.RestClient.ExecuteAsync(IRestRequest request, Action`2 callback)
   at RestSharp.RestClient.ExecuteAsync[CourseDTOPaginatedList](IRestRequest request, Action`2 callback)
   at RestSharp.RestClient.ExecuteAsync[CourseDTOPaginatedList](IRestRequest request, CancellationToken cancellationToken)
--- End of stack trace from previous location ---

**Comment by devhl-labs** [comment]
Try the library option for httpclient. Post here if it doesnt work. Ive been trying to rewrite the http client but i need my nrt pull request merged first.

**Comment by AhmedKhalil777** [comment]
I tried to use it but same error,, 

```
npx @openapitools/openapi-generator-cli generate -i {{url}} -g csharp-netcore -o {{OutPut path}} --additional-properties=library=httpclient
```

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: System.Net.Requests is not supported on this platform.
System.PlatformNotSupportedException: System.Net.Requests is not supported on this platform.
   at System.Net.WebRequest.get_DefaultWebProxy()
   at RestSharp.RestClient.ConfigureHttp(IRestRequest request)
   at RestSharp.RestClient.ExecuteAsync(IRestRequest request, Action`2 callback, String httpMethod, Func`4 getWebRequest)
   at RestSharp.RestClient.ExecuteAsync(IRestRequest request, Action`2 callback, Method httpMethod)
   at RestSharp.RestClient.ExecuteAsync(IRestRequest request, Action`2 callback)
   at RestSharp.RestClient.ExecuteAsync[CourseDTOPaginatedList](IRestRequest request, Action`2 callback)
   at RestSharp.R

**Comment by devhl-labs** [comment]
I dont think youre passing in the library ootion for httpclie t.
