### ISSUE TITLE
[BUG] Build failure with OpenJDK 16

### ISSUE THREAD

**Issue by anmlnath** [OpenAPITools/openapi-generator#9817]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I would like to contribute to openapi-generator's language support, but I'm not that familiar with Java, and the build is failing on my system.

```
❯ mvn clean install -e

[INFO] Running TestSuite
Configuring TestNG with: TestNG60Configurator
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.instrument.IllegalClassFormatException: Error while instrumenting sun/util/resources/provider/NonBaseLocaleDataMetaInfo.
	at org.jacoco.agent.rt.internal_43f5073.CoverageTransformer.transform(CoverageTransformer.java:94)
...

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.0:jar (attach-javadocs) on project openapi-generator-core: MavenReportException: Error while generating Javadoc: Project contains Javadoc Warnings -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.0:jar (attach-javadocs) on project openapi-generator-core: MavenReportException: Error while generating Javadoc: Project contains Javadoc Warnings
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
```

##### openapi-generator version

master (2e85ccdec8c3304e42c3434ef6da54a637a13e1a)

##### Steps to reproduce

* clone https://github.com/OpenAPITools/openapi-generator.git
* `mvn clean install -e`

```
❯ java --version
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)
```

```
❯ mvn --version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /usr/local/Cellar/maven/3.8.1/libexec
Java version: 16.0.1, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/16.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_CA, platform encoding: UTF-8
OS name: "mac os x", version: "11.4", arch: "x86_64", family: "mac"
```

##### Related issues/PRs

#9804 a different build error

**Comment by anmlnath** [comment]
`./run-in-docker.sh mvn package` does work

**Comment by wing328** [comment]
@anmlnath thanks for reporting the issue. Can you please try the following to skip javadoc as a workaround?
```
mvn clean package -Dmaven.javadoc.skip=true
```

**Comment by anmlnath** [comment]
Thanks for the response.

Running `mvn clean package -Dmaven.javadoc.skip=true` reports a tonne of errors in the form:

```
java.lang.instrument.IllegalClassFormatException: Error while instrumenting org/openapitools/codegen/languages/PythonClientCodegen$MockitoMock$1700579199$auxiliary$BQ4PxCPc.
	at org.jacoco.agent.rt.internal_43f5073.CoverageTransformer.transform(CoverageTransformer.java:94)
```

Since the Docker package works, I assume this is something with my environment, like the Java JDK version?

**Comment by wing328** [comment]
Right, we've not yet tested this project with JDK 16. Please use `./run-in-docker.sh mvn package` for the time being.

**Comment by Stokestack** [comment]
Same experience here. java -version yields this:
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)
