### ISSUE TITLE
[BUG] [R] Circular references break R generator with StackOverflowError

### ISSUE THREAD

**Issue by kkliebersbach** [OpenAPITools/openapi-generator#9821]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using a swagger.json file with circular references RClientCodegen.java throws the following exception:

```
Exception in thread "main" java.lang.StackOverflowError
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at org.openapitools.codegen.languages.RClientCodegen.constructExampleCode(RClientCodegen.java:762)
	at org.openapitools.codegen.languages.RClientCodegen.constructExampleCode(RClientCodegen.java:752)
	at org.openapitools.codegen.languages.RClientCodegen.constructExampleCode(RClientCodegen.java:771)
	at org.openapitools.codegen.languages.RClientCodegen.constructExampleCode(RClientCodegen.java:752)
	at org.openapitools.codegen.languages.RClientCodegen.constructExampleCode(RClientCodegen.java:771)
	at org.openapitools.codegen.languages.RClientCodegen.constructExampleCode(RClientCodegen.java:752)
	at org.openapitools.codegen.languages.RClientCodegen.constructExampleCode(RClientCodegen.java:728)
	at org.openapitools.codegen.languages.RClientCodegen.constructExampleCode(RClientCodegen.java:771)
	at org.openapitools.codegen.languages.RClientCodegen.constructExampleCode(RClientCodegen.java:752)
	at org.openapitools.codegen.languages.RClientCodegen.constructExampleCode(RClientCodegen.java:771)
	at org.openapitools.codegen.languages.RClientCodegen.constructExampleCode(RClientCodegen.java:752)
	at org.openapitools.codegen.languages.RClientCodegen.constructExampleCode(RClientCodegen.java:728)
	at org.openapitools.codegen.languages.RClientCodegen.constructExampleCode(RClientCodegen.java:771)
	at org.openapitools.codegen.languages.RClientCodegen.constructExampleCode(RClientCodegen.java:752)
        ...
```

##### openapi-generator version

5.2.0 (master)

##### OpenAPI declaration file content or url

https://api.splashback.io/data/swagger/v1/swagger.json

##### Generation Details

Simply clone master and build locally as instructed in README.md.

Java version 1.8.0 (OpenJDK), Maven version 3.6.3.

##### Steps to reproduce

Run `openapi-generator-cli` with the following arguments:

```bash
$ java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i swagger.json -g r -o /var/tmp/r_api_client
```

##### Related issues/PRs

No related issues could be found.

##### Suggest a fix

Working on a fix now. Will post if any issues arise!

**Comment by kkliebersbach** [comment]
@Ramanth @saigiridhar21 I have submitted PR #9822 which fixes this issue.
